### ISSUE TITLE
Allow term_meta show_on_level to indicate more than one level or only on last level of a heirarchy

### ISSUE THREAD

**Issue by bignall** [htmlburger/carbon-fields#100]
I have a need to show a term_meta container only on the last level in a heirarchy.  So perhaps something like show_on_leaf_level. 

I can imagine use cases for needing to show it on multiple levels as well so perhaps an array of levels with a way to indicate all levels greater than x level. Or something similar to show_on_level like not_show_on_level which can take an array of levels not to show on.

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which allows you to achieve this using the new conditionals system:
More info here: https://carbonfields.net/docs/containers-conditional-display/?crb_version=2-0-0
