### ISSUE TITLE
Composer and Carbon Fields

### ISSUE THREAD

**Issue by duncanarrow** [htmlburger/carbon-fields#1009]
## Version

  - Carbon Fields: 3.0
  - WordPress: 5.7
  - PHP: 7.4

Just trying to get my head around using Composer with Carbon Fields. I’m running MAMP with the latest version of Composer.

Two questions:

1) Where should Composer be installed on my MAMP install in relation to the WP directory structure (or does it even matter?)
2) If I compile Carbon Fields locally on my Mac, can I then just drag the compiled files online? Does it even work like that? Or when you build it, does it create sym links that are specific to that install?

The problem I have is that many webhosts don’t support Composer and I very rarely use Github. So whilst I appreciate the plugin version of CF, I’d also like to consider building it using Composer.

Thanks.

**Comment by jorostoyanov** [comment]
Hi @duncanarrow,

1) Where should Composer be installed on my MAMP install in relation to the WP directory structure (or does it even matter?)

Composer can be installed globally with this guide -- https://getcomposer.org/download/ -- or per project by placing a `composer.phar` in the project and later calling it with `php composer.phar ..`

2) If I compile Carbon Fields locally on my Mac, can I then just drag the compiled files online? Does it even work like that? Or when you build it, does it create sym links that are specific to that install?

Yes, you can build it locally and then upload directly the `vendor` folder. There aren't any symlinks or other dependencies
