### ISSUE TITLE
Fatal error for use limit_options() in Set

### ISSUE THREAD

**Issue by Grafs** [htmlburger/carbon-fields#1011]
## Version

  - Carbon Fields: 3.3
  - WordPress: 5.7.2
  - PHP: 8

## Expected Behavior
limit_options( $count ) for Field::make( 'set', 'crb_product_features', 'Features' )

## Actual Behavior
Fatal error: Uncaught Error: Call to undefined method Carbon_Fields\Field\Set_Field::limit_options()

## Container definition
```php
Container::make( 'post_meta', __('Options blocks') )
			->where( 'post_id', '=', '57241')
				->add_fields( array(
					Field::make( 'set', 'regions_reg', __('Region') )
				        ->limit_options( 3 )
						-> add_options( array(
							'global' => __('Global'),
							'eu' => __('EU'),
							'austria' => __('Austria'),
							'belgium' => __('Belgium'),
							'czech republic' => __('Czech Republic'),
							'denmark' => __('Denmark'),
						) )
		 ) );
```

**Comment by HTMLBurger-NG** [comment]
Hi @Grafs ,

We're going to address this in a future release.

**Comment by HTMLBurger-NG** [comment]
Just to clarify: this has been fixed in `development` branch.
