### ISSUE TITLE
Update without composer

### ISSUE THREAD

**Issue by derogit** [htmlburger/carbon-fields#1015]
## Version

  - Carbon Fields: 3.3.0
  - WordPress: 5.7
  - PHP: 7.2

## Question
Can i install v.3.3.2 without composer?

**Comment by jorostoyanov** [comment]
Hi @derogit 

You can download all releases as a plugin from here -- https://carbonfields.net/release-archive/

**Comment by derogit** [comment]
But v3.3.2 doesn't exist there

**Comment by jorostoyanov** [comment]
Please check again. I have added the latest v3.3.1 and v3.3.2 to the list.

Thanks for pointing this out!
