### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function carbon_set_post_meta() 

### ISSUE THREAD

**Issue by Somonator** [htmlburger/carbon-fields#1022]
How to use carbon_set_post_meta() function? I created a function to add a new post, but I get an error.

```
require_once get_stylesheet_directory() . '/libs/carbon-fields/carbon-fields-plugin.php';

function ___add_order($paytm_id, $user_data, $date) {
    $post_data = [
        'post_type' => 'video',	
        'post_title' => 'Test',
		'post_status' => 'publish'
    ];
    
    $post_id = wp_insert_post($post_data, true);

    if (!is_wp_error($post_id)) {
        carbon_set_post_meta($post_id, '__vg_video_id', $paytm_id);
        carbon_set_post_meta($post_id, '__vg_user_data', $user_data);
        carbon_set_post_meta($post_id, '__vg_date', $date);
    }
}
```

> Fatal error: Uncaught Error: Call to undefined function carbon_set_post_meta()

**Comment by jorostoyanov** [comment]
Hi @Somonator 

On which hook are you using the `__add_order` function?

**Comment by Somonator** [comment]
> Hi @Somonator 
> 
> On which hook are you using the `__add_order` function?

I call the function without hooks.  I plan to use ajax query inside.

**Comment by jorostoyanov** [comment]
All functions of Carbon Fields should be used after initialisation.

The initialisation should happen on `after_setup_theme`

Please, make sure you are using the `___add_order ` function after that
