### ISSUE TITLE
Bug: meta_query with 'NOT EXISTS' comparison returns all

### ISSUE THREAD

**Issue by ChrissiQ** [htmlburger/carbon-fields#1025]
## Version

  - Carbon Fields: v3.3.2
  - WordPress: 5.7.1
  - PHP: 7.2

## Expected Behavior
In the `pre_get_posts` wordpress filter, setting a`meta_query` for a meta key with `'compare' => 'NOT EXISTS'` should return only those posts where the key has not been set.  In other words, only posts without this meta should be returned.

## Actual Behavior
All posts, whether the meta key has been set or not, are returned instead.  Posts with the meta set have not been excluded.

## Container definition
No container is required to reproduce this problem - it occurs as long as carbon fields has been initialized.  Vanilla wordpress without CF does not exhibit this - you can disable CF or start a vanilla WP install without CF to show this.

This filter should exclude all posts where the meta key `_expiry` has been set:

```php
add_action('pre_get_posts', function($query) {
    $query->set('meta_query', [
        [
            'key' => '_expiry',
            'compare' => 'NOT EXISTS',
        ]
    ]);
});
```

## Steps to Reproduce the Problem

On a vanilla wordpress install with carbon fields initialized:

  1. Add the code for the filter.
  1. Set the `_expiry` meta key with any value on a post, through any means (you could use CF, or set it directly in the admin with the Custom Fields panel.
  1. Reload `/wp-admin/edit.php`.  The post with `_expiry` meta key wasn't excluded.
  1. Remove carbon fields from the project (don't initialize) and reload `/wp-admin/edit.php` - you will find the post excluded.

## Comments
This is just the minimal reproducible code for the problem - what I'm really trying to do is exclude "expired" posts from the front-end, on a project with CF enabled, but I'm finding that the query I want to use is NOT working.  It took me a bit to disable CF and find that it works fine with CF disabled.

**Comment by Panchev** [comment]
Hello, @igorhrcek.

Please check if the generated SQL of your WP query contains something like this:

`wp_postmeta.meta_key = 'carbon_fields:_expiry' `

If that's the case you can add the following code to resolve the issue.

`add_filter( 'get_meta_sql', 'remove_string_carbon_fields_from_query', 20, 1 );
function remove_string_carbon_fields_from_query( $sql ){
	if ( strpos( $sql['join'], 'carbon_fields:' ) !== false ) {
		$sql['join'] = str_replace( 'carbon_fields:', '', $sql['join'] );
	}
	return $sql;
}`

**Comment by igorhrcek** [comment]
Hey @Panchev, thanks for the reply.

This resolves the issue.
