### ISSUE TITLE
Make `_model` available again in complex field header templates

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#103]
I think that there is a regression introduced by commit c9e6c744.

When `set_header_template` was added to complex fields one of the use cases was something like: `$complex->set_header_template('<img src="{{ _models.image.get("url") }}" height="120">');`

It's not optimal since it loads the full size image but is better than nothing. I've used this in past projects for a complex `gallery` field which has images…

![cf-complex-model](https://cloud.githubusercontent.com/assets/188612/19165371/cffd8828-8c03-11e6-87a9-ee737ab814dd.png)

**Comment by doup** [comment]
Another option would be to pass the image url or the model instead of the image ID…

```javascript
_.each(this.fieldsCollection.models, function(fieldModel) {
    var fieldName = fieldModel.get('base_name');

    switch (fieldModel.get('type')) {
        case 'Image':
            var fieldValue = fieldModel.get('thumb_url');
            break;
        default:
            var fieldValue = fieldModel.get('value');
            break;
    }

    templateVariables[ fieldName ] = fieldValue;
});
```

**Comment by doup** [comment]
What would be the best approach for this? Expose again the `_model` variable or make something different? It looks like the easiest path would be to revert the change. Maybe changing the name from `_models` to `models` (is the visibility hint `_` necessary for a complex field header template?)

**Comment by m1r0** [comment]
I think that just exposing the `model` is sufficient (no need for additional logic for each field type). About the `_` prefix, it's a good practice, imagine if you have a field with the name `model`, then there will be a naming conflict.
