### ISSUE TITLE
[Question] Use Association Field to update taxonomy

### ISSUE THREAD

**Issue by Romaixn** [htmlburger/carbon-fields#1032]
## Version

  - Carbon Fields: 3.3
  - WordPress: 5.8

## Question
Hello, is it possible to use an Association Field in an Post Meta container to update taxonomy ? 

Like having custom field to display list of category, and on save update the real taxonomy "category" (just to custom UI, like restrict to 1 max, etc..)

I see there is 'carbon_fields_post_meta_container_saved' hook but no idea how it works (parameters ?)

Thanks for your help !

**Comment by jorostoyanov** [comment]
Hi @Romaixn 

The `carbon_fields_post_meta_container_saved`  accepts two parameters: `$post_id` and `$post_meta_container` object. The action is called here - https://github.com/htmlburger/carbon-fields/blob/46e9b60c30061e869fca66227e50dfc009afe194/core/Container/Post_Meta_Container.php#L116

What kind of data you need to update on the taxonomy after udpate?

**Comment by Romaixn** [comment]
Hi @jorostoyanov, I think I understand now thanks !

I need to update the taxonomy of post according to taxonomy selected in carbon Field. (carbon field = taxonomy like that).

I think I can debug with some dump now :) Thanks a lot

**Comment by jorostoyanov** [comment]
Great! I am closing the issue.

Feel free to re-open it in case any questions appear :-)
