### ISSUE TITLE
Block deprecated since version 5.8.0! Use block_categories_all instead.

### ISSUE THREAD

**Issue by codeies** [htmlburger/carbon-fields#1044]
## Version

  - Carbon Fields: 3.3.2
  - WordPress: 5.8
  - PHP: 8

block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead.

**Comment by jorostoyanov** [comment]
Hi @codeies 

This has been fixed here - https://github.com/htmlburger/carbon-fields/pull/1024/ - and will be available in the next release!

**Comment by tomkeysers** [comment]
Any idea when this release will get out, more or less?
