### ISSUE TITLE
Theme options adding my own settings page using add_submenu_page()

### ISSUE THREAD

**Issue by edwardhew** [htmlburger/carbon-fields#105]
Hi guys,

I'm developing a custom settings page that displays DB rows, it's not a big thing, I wanted to add it as a submenu to the Theme Options top level menu created with Carbon Fields but could not without my submenu slug overwriting the parent's slug. Here is an example.

```PHP
// Copied from CF documentation
Container::make('theme_options', 'Basic Options')
    ->add_fields(array(
        Field::make('header_scripts', 'crb_header_script'),
        Field::make('footer_scripts', 'crb_footer_script'),
));

// Add second options page under 'Basic Options'
Container::make('theme_options', 'Social Links')
    ->set_page_parent('Basic Options')  // title of a top level Theme Options page
    ->add_fields(array(
        Field::make('text', 'crb_facebook_link'),
        Field::make('text', 'crb_twitter_link')
));

function test_options_page_html() {
    // check user capabilities
    if (!current_user_can('manage_options')) {
        return;
    }
    require (plugin_dir_path(__FILE__) . 'admin/settings-view.php');
}
// My custom submenu
function test_options_page() {
    add_submenu_page(
        'crbn-basic-options.php',
        'Test Options',
        'Test1 Options',
        'manage_options',
        'settings-custom' ,
        'test_options_page_html'
    );
}
add_action('admin_menu', 'test_options_page');

/**
 * // WP API
 * add_submenu_page(
 *     string $parent_slug,
 *     string $page_title,
 *     string $menu_title,
 *     string $capability,
 *     string $menu_slug,
 *     callable $function = ''
 * )
 */
```

When I run this, `Basic Options` menu links to my `settings-custom`, which is the child's slug overwriting the parent's slug. When I remove my `add_submenu_page()`, `Basic Options` links correctly.'

I did test by creating my own top level many with `add_menu_page()`, and not inserting into menu created by Carbon Fields, no problems, everything works.

Thanks in advance.

**Comment by pkostadinov-2create** [comment]
Just a thought - if you are trying to display HTML, why don't you try the `html` field type, with `set_html` method accepting callback function `test_options_page_html`:

```
Container::make( 'theme_options', __( 'Test Options', 'crb' ) )
	->set_page_parent( 'Basic Options' )
	->add_fields( array(
		Field::make( 'html', 'crb_html', __( 'Html', 'crb' ) )
			->set_html( 'test_options_page_html' ),
	) );
```

**Comment by edwardhew** [comment]
That is very good to know, thank you!

I could always just make a top level admin menu for what I want to do, I was just thinking to slip my own settings menu link into one created with this plugin.

**Comment by pkostadinov-2create** [comment]
For your specific issue - there is a custom hook available for attaching custom subpages. Check `\carbon-fields\core\Container\Theme_Options_Container.php` - `Line 117`

For example your code:
```
add_action('admin_menu', 'test_options_page');
```

Will become:

```
add_action('load-toplevel_page_crbn-basic-options', 'test_options_page');
```

**Comment by edwardhew** [comment]
Thanks so much, tried it, nothing happens.

I see that it is from these lines:
$page_hook = get_plugin_page_hookname( $this->settings['file'], '' );
add_action( 'load-' . $page_hook, array( $this, '_save' ) );

**Comment by pkostadinov-2create** [comment]
Sorry for the delay - after testing your initial code, I found out that it works - all you need is to modify the Action priority:

```
add_action('admin_menu', 'test_options_page', 11);
```

**Comment by edwardhew** [comment]
Sorry was busy with something else past few days, still haven't have the chance to test this out, but I'll take your word for it. Thank you for your help!

**Comment by m1r0** [comment]
@edwardhew, please re-open the ticket if you are still having problems with this.

**Comment by edwardhew** [comment]
Tested this, absolutely works. Thank you very much @pkostadinov-2create
