### ISSUE TITLE
Styling Issues with complex field in term meta

### ISSUE THREAD

**Issue by fabianpimminger** [htmlburger/carbon-fields#1053]
## Version

  - Carbon Fields: 3.3.2
  - WordPress: 5.8
  - PHP: 7

## Expected Behavior
Add Entry should display a styled dropdown list of the components. 

## Actual Behavior
Dropdown List is not styled

<img width="448" alt="Bildschirmfoto 2021-11-01 um 15 47 38" src="https://user-images.githubusercontent.com/45733/139691565-7d1e49b7-28ce-4e16-8dcd-d15435c8c5f6.png">

**Comment by HTMLBurger-NG** [comment]
Hi @fabianpimminger ,

We're going to address this in a future release.
