### ISSUE TITLE
Can fields be used as solo inputs?

### ISSUE THREAD

**Issue by wolfiesites** [htmlburger/carbon-fields#1054]
Hello,

I just wonder if I can use Fields as styled, solo inputs?

Without container and saving values. 
Just styled inputs like:
- text input
- image input
- dropdowns
- radio buttons
etc..

Just to render input fields and pass some arguments to fill inputs with default data?

And if not maybe u know some awesome libraries?

Awesome work! I appreciate it a ton.
Thanks in advance!

**Comment by jorostoyanov** [comment]
Hi @wolfiesites 

Do you want to use it on the front-end? If so -- no Carbon Fields are Administration oriented library.

**Comment by wolfiesites** [comment]
@jorostoyanov ok. Thanks for clarification!
