### ISSUE TITLE
Is it possible to get the current post ID inside set_render_callback()?

### ISSUE THREAD

**Issue by oobi** [htmlburger/carbon-fields#1059]
## Version

  - Carbon Fields: 3.2
  - WordPress: 5.8.2
  - PHP: 7.4

## Container definition
```php
Block::make(__('child-pages', $this->text_domain))
        ...
	->set_render_callback(function ($fields, $attributes, $inner_blocks) {
		// Do something with $post->ID
	});
}
```

## Comments
I'm trying to find a way to access the current post's ID within the render callback but so far a solution eludes me.  I've tried the usual suspects (global $post etc) but short of modifying Carbon so I can pass it in, I can't see a way to get access to the $post object. 

Any clues are gratefully received!

**Comment by jorostoyanov** [comment]
Hi @oobi 

Try using `$_GET['post']`

**Comment by oobi** [comment]
Yeah I tried that and $_POST and $_REQUEST. The trouble I had is it's going through the Wordpress REST process (in the editor) and that stuff doesn't appear to exist in that context.

/wp-json/carbon-fields/v1/block-renderer?_locale=user

**Comment by jorostoyanov** [comment]
I see, I will check that and will let you know

**Comment by SAYri-ua** [comment]
Has anyone managed to solve this problem?

**Comment by oobi** [comment]
Sadly I found no way to do this without hacking carbon fields itself. An extra param in the set_render_callback would be amazing.

**Comment by HTMLBurger-NG** [comment]
Hi @oobi ,

We're going to address this in a future release.
We will add an additional 4th parameter In the callback function, which would be the `post_id`.

**Comment by oobi** [comment]
That would be amazing - thanks for considering it!

**Comment by oobi** [comment]
That works a treat - thanks a bunch!

**Comment by oobi** [comment]
I spoke too soon. This works in the editor (preview the block) but not on the front end. What I'm hoping for is access to the post_id for the purpose of running query to access (for example) child pages or post metadata.

Example:
```
->set_render_callback(function ($fields, $attributes, $inner_blocks, $post_id) {
	echo 'Post ID is ' . $post_id;
});
```

In the editor (preview):

<img width="251" alt="image" src="https://user-images.githubusercontent.com/503084/222611561-6354fd8d-5bcd-424d-a542-a53cd07e3d34.png">

On the front end:

<img width="164" alt="image" src="https://user-images.githubusercontent.com/503084/222611655-aa4fc765-2d9b-432e-a4e7-54c78936b624.png">

Having a little dig into the code for Block_Container, the get_post_id method seems to rely on the post ID being present in the request or admin URL, which is not the case for the front end. 

admin:
/wp-admin/post.php?post=5&action=edit

frontend: 
/path/to/post

**Comment by oobi** [comment]
Actually here's a little patch for that method that allows it to work in both places: 

```
public function get_post_id()
	{
		$post_id = isset($_GET['post']) && (int) $_GET['post'] > 0 ? (int) $_GET['post'] : null;
		if (!empty($post_id)) {
			return $post_id;
		}

		$admin_url = $_SERVER['HTTP_REFERER'];
		if (!empty($admin_url)) {
			$parsed_url = parse_url($admin_url);
			if (isset($parsed_url['query']) && !empty($parsed_url['query'])) {
				$params = explode('&', $parsed_url['query']);
				foreach ($params as $param) {
					$param = explode('=', $param);
					if ($param[0] === 'post') {
						$post_id = $param[1];
					}
				}
			}
		}

                // grab post_id on front end render
		if (empty($post_id)) {
			$post_id = get_the_ID();
		}

		return $post_id;
	}
```

**Comment by HTMLBurger-NG** [comment]
Hi @oobi,

Thank you for your patch, we would apply it on our next release.

**Comment by oobi** [comment]
No problem -- another quick change: 

```
$admin_url = $_SERVER['HTTP_REFERER'] ?? '';
```

Referrer isn't guaranteed to be set. I bumped into this using webpack.

**Comment by HTMLBurger-NG** [comment]
Thank you again, we've already fixed this issue in the `development` branch.
