### ISSUE TITLE
composer.json incorrect PHP version definition

### ISSUE THREAD

**Issue by dhalucario** [htmlburger/carbon-fields#1062]
## Version

  - Carbon Fields: development branch
  - WordPress: -
  - PHP: 7.4.25

## Expected Behavior
When trying to install composer dependencies using composer install I should not be told that I cannot use PHP 7.4.25

## Actual Behavior
When trying to install dependencies using composer I should be able to install dependencies using PHP 7.4.25.

## Container definition
---

## Steps to Reproduce the Problem

  1. Clone carbon-fields into a new wordpress instance.
  2. Try to run composer install in the root of the project directory

## Comments
The documentation states that caron-fields supports "Supports PHP5.3 or higher".
The composer.json should reflect that.

**Comment by dhalucario** [comment]
Im also pretty sure we had a discussion in a different issue that 5.3 isn't supported by Wordpress anymore, so the README is also wrong. I will commit a pull request in a second to fix that.

**Comment by jorostoyanov** [comment]
Fixed here: https://github.com/htmlburger/carbon-fields/commit/27c032156e21a1a3fc16036ac46537da66aa1ce3

Thanks for the contribution!
