### ISSUE TITLE
Yoast SEO settings prevent user meta fields from appearing

### ISSUE THREAD

**Issue by timpoole** [htmlburger/carbon-fields#1070]
## Version

  - Carbon Fields: 3.3.2
  - WordPress: 5.8.3
  - Yoast SEO: 17.9
  - PHP: 7.4.5

## Expected Behavior
Carbon Fields was used to add user meta fields to user profiles. With Yoast deactivated, the fields appear on the user profile page as expected.

## Actual Behavior
With Yoast activated the fields are replaced by 'Yoast SEO settings'.

## Container definition
```php
Container::make( 'user_meta', 'Address' )
   ->add_fields( array(
       Field::make( 'text', 'crb_city_and_post', 'City and post code' ),
       Field::make( 'text', 'crb_street', 'Street Name' ),
   ) );
```

## Steps to Reproduce the Problem

  1. Install and activate the Yoast SEO plugin.
  2. Add the above user meta container and fields.
  3. Whilst logged in as an administrator, check if the fields appear on a user profile page - with and without Yoast enabled.

## Comments
Help to resolve this would be much appreciated - thank you for your time.

**Comment by HTMLBurger-NG** [comment]
We couldn't reproduce the issue on the newest version (v3.5.0).
Please update WordPress core and Carbon Fields to the newest version and let us know if the issues still exist.
