### ISSUE TITLE
Not able to create a page with Gutenberg

### ISSUE THREAD

**Issue by mabffahad** [htmlburger/carbon-fields#1071]
I have used the latest version of carbon fields where I have been facing issues. When I try to create a new page from the dashboard, it is showing me blank page and saying **Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataset')** in the console in the file of metabox.min.js

**Comment by HTMLBurger-NG** [comment]
Hi, @mabffahad 

We couldn't reproduce the issue on the newest version (v3.5.0).
Please update WordPress core and Carbon Fields to the newest version and let us know if the issues still exist.
