### ISSUE TITLE
Certain image uploads don't have metadata sizes causing wp_list_pluck to fail/warn on non array value

### ISSUE THREAD

**Issue by luukvr** [htmlburger/carbon-fields#1098]
https://github.com/htmlburger/carbon-fields/blob/46e9b60c30061e869fca66227e50dfc009afe194/core/Helper/Helper.php#L534

PHP message: PHP Warning:  Invalid argument supplied for foreach() in wp-includes/class-wp-list-util.php on line 165

Check if metadata 'sizes' exist before doing the pluck

**Comment by HTMLBurger-NG** [comment]
Hi @luukvr ,

Thank you for your feedback and your PR.
We're going to address this in a future release.
