### ISSUE TITLE
the icon of a file-fieldtype with set_value_type("url") reverts to default after uploading a file and pressing "update"

### ISSUE THREAD

**Issue by bigmistqke** [htmlburger/carbon-fields#1101]
## Version

  - Carbon Fields: 3.3.4
  - WordPress: 5.9.3
  - PHP: 7.3.21

## Expected Behavior
After uploading a file with the file-fieldtype and set_value_type( "url" ) the file-icon should remain 
![image](https://user-images.githubusercontent.com/10504064/169604966-e64fcd2f-60e1-451c-a3d0-6aa46f7f9d32.png)
after pressing "update" 

## Actual Behavior
but instead it returns to its default state 
![image](https://user-images.githubusercontent.com/10504064/169605001-db1bd56a-85d5-4fae-942a-cba53cad688d.png)

## Container definition
```php
Container::make( 'post_meta', 'files' )
  ->add_fields( array(
    Field::make( 'file', 'crb_files', 'files' )
    ->set_visible_in_rest_api( true )
    ->set_width( 10 )
    ->set_value_type( "url" )
  ));
```

## Steps to Reproduce the Problem

  1. make the container definition
  2. upload the file
  3. press update

## Comments
![image](https://user-images.githubusercontent.com/10504064/169604909-7af7afc2-e27c-4299-8b9d-e463b4398ce4.png)
the data does show up via the REST-api, so it's purely a cosmetical bug in the wordpress-editor. 
The bug does not occur when set_value_type is not set.

at the moment it only seems to happen with pdf-files, although a bit earlier i had the same bug happening with images too.

**Comment by faganer** [comment]
Like mine, version 3.3.4, Filed image, file will not return images, the problem is the same as yours. Only Media Gallery is available.

**Comment by HTMLBurger-NG** [comment]
We couldn't reproduce the issue on the newest version (v3.5.0).
Please update WordPress core and Carbon Fields to the newest version and let us know if the issues still exist.
