### ISSUE TITLE
Custom fields do not load

### ISSUE THREAD

**Issue by Andjar2** [htmlburger/carbon-fields#1103]
## Version

  - Carbon Fields: 3.3.0
  - WordPress: 6.0
  - PHP: 7.4

## Expected Behavior
Show custom fields in a given CPT.

## Actual Behavior
It does not show the custom fields, it will only appear after "saving" --- https://prnt.sc/d1543UVAKH53

```
Could not find DOM element for container "carbon_fields_container_forecast".
s @ metaboxes.min.js?ver=3.3.0:1
```

Any recommendation to fix this?

**Comment by HTMLBurger-NG** [comment]
We couldn't reproduce the issue on the newest version (v3.5.0).
Please update WordPress core and Carbon Fields to the newest version and let us know if the issues still exist.
