### ISSUE TITLE
Selected terms are not associated with a post

### ISSUE THREAD

**Issue by electroae4** [htmlburger/carbon-fields#1107]
## Version

  - Carbon Fields: 3.3.4
  - WordPress: 6.0.1
  - PHP: 8.0

## Steps to Reproduce the Problem

 I'm starting to use Carbon Fields (with Wordpress) and I'm having a problem.

1. I installed Wordpress v.6.0.1 on localhost (Windows 10, OpenServer, PHP 8.0, MySQl 8.0);
2. Then I installed Carbon Fields using composer.
3. I created several categories and one post.
4. I created an association field using Carbon Fields to select post categories from the field

```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

add_action( 'carbon_fields_register_fields', 'crb_attach_post_fields' );
function crb_attach_post_fields() {
  
  Container::make( 'post_meta', 'Post settings' )
      ->where( 'post_type', '=', 'post' )
      ->add_fields( array(
          Field::make( 'association', 'crb_category', 'Category' )              
              ->set_types( array(
                  array(
                      'type'      => 'term',
                      'taxonomy'  => 'category',
                  )
              ) )
      ));
}

add_action( 'after_setup_theme', 'crb_load' );
function crb_load() {
    require_once( 'vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();
}
```
![1](https://user-images.githubusercontent.com/109409726/179345593-dbf97def-2251-4496-b85b-c09bef2fb01e.png)

5. After selecting category 1 and saving the post, this category is not associated with the post.

![2](https://user-images.githubusercontent.com/109409726/179345616-2c79f3e4-cbe0-405f-a75c-63b96cd60489.png)

![3](https://user-images.githubusercontent.com/109409726/179345617-600b0b4d-e280-429e-aeef-71deb624e003.png)

6. If I select a category in the sidebar it works fine.
![4](https://user-images.githubusercontent.com/109409726/179345645-68adf2c6-c348-4f08-ab28-6dc2060ced10.png)

What is the problem? How to fix it?

**Comment by jorostoyanov** [comment]
Hi @electroae4 

Association field is just a meta field for the post. It is not supposed to associate the post with the selected category.

You should be using the sidebar settings to relate posts and taxonomy terms

**Comment by electroae4** [comment]
@jorostoyanov Thanks for your reply!

I really liked the Carbon Fields plugin. Much more than ACF.
ACF has this option - "Connect selected terms to the post".
This is a very, very useful option. 
I don't want to use the sidebar. I like custom fields Carbon Fields.

Whether it is possible to make as in ACF?
