### ISSUE TITLE
Ability to filter/translate Complex Field labels texts

### ISSUE THREAD

**Issue by tamara-m** [htmlburger/carbon-fields#1114]
## Version

  - Carbon Fields: 3.3.4
  - WordPress: 6.0.1
  - PHP: 7.4

## Expected Behavior

I would expect to be able to filter / translate all texts used throughout the library.

## Actual Behavior

Some texts have been hard-coded in and are impossible to filter/translate, such as the Complex Field labels in htmlburger\carbon-fields\core\Field\Complex_Field.php copied below:

```
/**
* Entry labels
* These are translated in init()
*
* @var array
*/
public $labels = array(
   'singular_name' => 'Entry',
    'plural_name' => 'Entries',
);
```

## Container definition
N/A

## Steps to Reproduce the Problem

  1. Add any Complex field

## Comments

The perfect solution would be to be able to both filter and translate these labels, would you accept a PR that updates the function above to this other version?:

```
/**
* Entry labels
* These are translated in init()
*
* @var array
*/
public $labels = apply_filters('carbon_fields_complex_field_labels', array(
   'singular_name' => __('Entry', 'carbon-fields' ),
    'plural_name' => __('Entries', 'carbon-fields' ), 
) );
```

Thank you for your consideration and for Carbon Fields in general, I love to use this library in my WP projects :)

**Comment by HTMLBurger-NG** [comment]
Hi @tamara-m ,

Currently, there is a method that would allow you to change the labels of a complex field called `setup_labels`.

Here is an example of usage:
```
Field::make( 'complex', 'home_slider', __( 'Slider', 'crb' ) )
		->setup_labels( array(
			'singular_name' => __( 'Slide', 'crb' ),
			'plural_name'   => __( 'Slides', 'crb' )
		) )
```
