### ISSUE TITLE
Theme options page, long slug, any way to customise?

### ISSUE THREAD

**Issue by mrdigitalau** [htmlburger/carbon-fields#1116]
## Version

  - Carbon Fields: 3.3
  - WordPress: 6.02
  - PHP: 7.4

## Expected Behavior
Ideally I want the slug to be http://demo.test/wp-admin/admin.php?page=theme_options.php

## Actual Behavior
Slug is currently http://demo.test/wp-admin/admin.php?page=crb_carbon_fields_container_theme_options.php

## Container definition
```
Container::make('theme_options', __('Theme Options', 'crb'))
            ->add_fields(array(
                  Field::make('text', 'crb_phone', 'Phone')->set_attribute('type', 'tel')->set_attribute('placeholder', 'Eg. (02) 9123 4567'),
                  Field::make('text', 'crb_email', 'Email')->set_attribute('type', 'email')->set_attribute('placeholder', 'Eg. you@yourbusiness.com.au'),
            ));
```

## Steps to Reproduce the Problem

  1. Install Carbon fields into theme
  2. Create container
  3. Theme options page displays with slug prefix of ?page=crb_carbon_fields_container_XXXX

## Comments
Not a bug per se, but I am unable to find any docs or help on making this work.
Is it at all possible to customise the theme options page slug? I do not want to show ?page=crb_carbon_fields_container_ in the slug.

Thank you for your awesome package

**Comment by HTMLBurger-NG** [comment]
Hi @mrdigitalau,
Currently, you could use the `set_page_file` method like this:
```
Container::make( 'theme_options', __( 'Theme Options', 'crb' ) )
    ->set_page_file('theme_options.php')
```

This would achieve the following link: http://demo.test/wp-admin/admin.php?page=theme_options.php
