### ISSUE TITLE
select fields setting the first option as a default value

### ISSUE THREAD

**Issue by MohammedFaragallah** [htmlburger/carbon-fields#1117]
## Version

  - Carbon Fields: 3.3.4
  - WordPress: 6.0.2
  - PHP: 7.4

## Expected Behavior
_Please enter the expected behavior here_

## Actual Behavior
_Please enter the actual, unexpected behavior here_

## Container definition
```php
// Please add your entire container definition here so issues
// are easy to reproduce
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Comments
_Please add any other comments here_
how to prevent the select field from adding the first option as a default value?

**Comment by HTMLBurger-NG** [comment]
Hi @MohammedFaragallah,

In order to add a placeholder for the select field you could use an empty value with a label.

Example of usage:
```
Field::make( 'select', 'my_select', __( 'Choose Options' ) )
    ->set_options( array(
        '' => "Please choose ...",
        '1' => 1,
        '2' => 2,
        '3' => 3,
        '4' => 4,
        '5' => 5,
    ) )
    ->set_required(true),
```
