### ISSUE TITLE
Carbon fields as part of child theme

### ISSUE THREAD

**Issue by pageartcz** [htmlburger/carbon-fields#1119]
Hello, I need to say first that I'm not developer and just starting with Carbon Fields. I know it should be used as plugin but can Carbon fields be used as part of child theme so I only install child theme and it will also install Carbon Fields and use it based on my functions? If this is possible what can I do to include it in child theme? Thank you.

**Comment by HTMLBurger-NG** [comment]
Hi @pageartcz ,

You could easily use the Carbon Fields within a child theme with the help of Composer.

Please read our documentation https://docs.carbonfields.net/quickstart.html
