### ISSUE TITLE
Complex Field Dynamic Tabs

### ISSUE THREAD

**Issue by Jpwaldstein** [htmlburger/carbon-fields#112]
Hi wandering if its possible to make tabs within complex fields. For example:

https://gist.github.com/Jpwaldstein/b665f8d0185b6b5d8fdaa9984a0f0d14

Wandering how to separate the columns selected, I would want each column to have its own tab.

**Comment by Santana1053** [comment]
You can use `set_layout($layout)`
- `tabbed-horizontal` – groups are displayed as horizontal tabs
- `tabbed-vertical` – groups are displayed as vertical tabs

https://carbonfields.net/docs/complex-field-setup-methods/

**Comment by Jpwaldstein** [comment]
set_layout($layout) is not working for me at all.  I have tried in simple situations and more complex like the gist above with no luck.  Also @georgeHtmlBurger is tabbed layout supposed to work within complex fields?
