### ISSUE TITLE
Filter block_categories deprecated warnings

### ISSUE THREAD

**Issue by tambaqui** [htmlburger/carbon-fields#1122]
## Version

  - Carbon Fields:  3.3.4
  - WordPress: 6.0.2
  - PHP: 7.4

## Expected Behavior
Deprecated warnings are not displayed when creating a new post or page.

## Actual Behavior
With carbon fields enabled WordPress displays 2 deprecated warnings when creating a new post or page:

```php
Deprecated: block_categories is deprecated since version 5.8.0! Use block_categories_all instead. in /wp-includes/functions.php on line 5465

Deprecated: block_categories is deprecated since version 5.8.0! Use block_categories_all instead. in /wp-includes/functions.php on line 5465
```

## Comments
The attach() method of the Block_Container class needs to be updated.

**Comment by HTMLBurger-NG** [comment]
This issue was fixed in the current release (v3.5.0).
Please update the WordPress core and Carbon Fields to the newest version and let us know if the issues still exist.
