### ISSUE TITLE
Allow `inputmode` attribute

### ISSUE THREAD

**Issue by robsonsobral** [htmlburger/carbon-fields#1123]
## Version

  - Carbon Fields: "^3.3.2"
  - WordPress: 5.9.1
  - PHP: 7.4.30

## Expected Behavior

Allow the use of the [`inputmode`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) attribute.

## Actual Behavior

Get the following error:

> Fatal error: Uncaught Carbon_Fields\Exception\Incorrect_Syntax_Exception: Only the following attributes are allowed: list, max, maxLength, min, pattern, placeholder, readOnly, step, type, is, data-*

## Container definition
```php
// Please add your entire container defintion here so issues
// are easy to reproduce
```

## Steps to Reproduce the Problem

The following code sample:

```php
        Field::make('text', 'az_big_number_value', __('Valor'))
            ->set_attribute('type', 'text')
            ->set_attribute('inputmode', 'numeric')
            ->set_attribute('pattern', '[+-]?\d+[B,K,M,T]?')
            ->set_context('normal')
```

**Comment by HTMLBurger-NG** [comment]
Hi @robsonsobral ,

We've allowed this attribute in our next release.
