### ISSUE TITLE
Fetch images links from a carbon field gallery

### ISSUE THREAD

**Issue by Prains** [htmlburger/carbon-fields#1139]
## Version

  - Carbon Fields: newest
  - WordPress: newest
  - PHP: newest

## Expected Behavior
Trying to fetch gallery with rest api in order to get links

## Actual Behavior
fetching gallery with rest api and returns id of an images

please help how to get url of an images instead of a id

**Comment by HTMLBurger-NG** [comment]
Hi @Prains ,

We've added a filter that would allow you to retrieve the URLs instead of IDs in our next release.

The filter is called `carbon_fields_rest_api_return_attachments_as_urls`.

Example usage in which we exclude the File Field.
```
add_action( 'init', function() {
	add_filter('carbon_fields_rest_api_return_attachments_as_urls', function( $return, $value, $field, $object_id ) {
		if ( get_class( $field ) === 'Carbon_Fields\Field\File_Field' ) {
			return false;
		}

		return true;
	}, 10, 4);
} );
```
