### ISSUE TITLE
RICH_TEXT field: can't edit in Visual tab, it's empty after save

### ISSUE THREAD

**Issue by andreistez** [htmlburger/carbon-fields#1148]
## Version

  - Carbon Fields: 3.3.2
  - WordPress: 6.1.1
  - PHP: 7.4

## Expected Behavior
Publish new page, which has post_meta where( 'post_type', '=', 'page' ) with complex field. This complex field contains several sections (add_fields), some of them have rich_text field. After publishing content in rich_text fields is visible and editable using "Visual" tab of the editor. All editors have normal height like before publishing page.

## Actual Behavior
Publish new page, which has post_meta where( 'post_type', '=', 'page' ) with complex field. This complex field contains several sections (add_fields), some of them have rich_text field. After publishing content in rich_text fields is NOT visible and sure NOT editable using "Visual" tab of the editor. All editors are collapsed.

## Container definition
```php
Container::make( 'post_meta', __( 'Поля контента' ) )
	->where( 'post_type', '=', 'page' )
	->add_fields( [
		Field::make( 'complex', 'page_sections', __( 'Секции страницы' ) )
			->set_layout( 'tabbed-horizontal' )

			// Hero section.
			->add_fields( 'hero_section', __( 'Основная' ), [
				Field::make( 'text', 'title', __( 'Заголовок' ) )
					->set_width( 34 ),
				Field::make( 'text', 'desc', __( 'Описание' ) )
					->set_width( 33 ),
				Field::make( 'image', 'bg_image', __( 'Фоновое изображение' ) )
				     ->set_width( 33 ),
				Field::make( 'date', 'date', __( 'Дата окончания акции' ) )
					->set_storage_format( 'd:m:Y' )
					->set_width( 50 ),
				Field::make( 'text', 'button_label', __( 'Текст на кнопке' ) )
					->set_width( 50 )
			] )

			// Info section.
			->add_fields( 'info_section', __( 'Информация' ), [
				Field::make( 'complex', 'info', __( 'Информация' ) )
					->set_layout( 'tabbed-horizontal' )
					->set_max( 3 )
					->add_fields( [
						Field::make( 'image', 'image', __( 'Изображение' ) )
							->set_width( 34 ),
						Field::make( 'text', 'title', __( 'Заголовок' ) )
							->set_width( 33 ),
						Field::make( 'text', 'desc', __( 'Описание' ) )
							->set_width( 33 )
					] )
			] )

			// About Us section.
			->add_fields( 'about_section', __( 'О нас' ), [
				Field::make( 'rich_text', 'text', __( 'Текст' ) )
			] )

			// Products section.
			->add_fields( 'products_section', __( 'Продукция' ), [
				Field::make( 'text', 'title', __( 'Заголовок' ) )
					->set_width( 50 ),
				Field::make( 'text', 'button_label', __( 'Текст на кнопке' ) )
					->set_width( 50 ),
				Field::make( 'complex', 'products', __( 'Товары' ) )
					->set_layout( 'tabbed-horizontal' )
					->add_fields( [
						Field::make( 'image', 'image', __( 'Изображение' ) )
							->set_width( 34 ),
						Field::make( 'text', 'title', __( 'Название' ) )
							->set_width( 33 ),
						Field::make( 'text', 'desc', __( 'Описание' ) )
							->set_width( 33 )
					] )
			] )

			// Icon & text repeater section.
			->add_fields( 'steps_section', __( 'Шаги' ), [
				Field::make( 'text', 'title', __( 'Заголовок' ) ),
				Field::make( 'complex', 'steps', __( 'Шаги' ) )
					->set_layout( 'tabbed-horizontal' )
					->add_fields( [
						Field::make( 'image', 'image', __( 'Изображение' ) )
							->set_width( 34 ),
						Field::make( 'text', 'title', __( 'Заголовок' ) )
							->set_width( 33 ),
						Field::make( 'rich_text', 'desc', __( 'Описание' ) )
							->set_width( 33 )
					] )
			] )

			// Certificates section.
			->add_fields( 'certificates_section', __( 'Сертификаты' ), [
				Field::make( 'text', 'title', __( 'Заголовок' ) ),
				Field::make( 'complex', 'certificates', __( 'Сертификаты' ) )
					->set_layout( 'tabbed-horizontal' )
					->add_fields( [
						Field::make( 'image', 'certificate', __( 'Изображение' ) )
					] )
			] )

			// Testimonials section.
			->add_fields( 'testimonials_section', __( 'Отзывы' ), [
				Field::make( 'text', 'title', __( 'Заголовок' ) ),
				Field::make( 'complex', 'testimonials', __( 'Отзывы' ) )
					->set_layout( 'tabbed-horizontal' )
					->add_fields( [
						Field::make( 'image', 'image', __( 'Изображение' ) ),
						Field::make( 'image', 'avatar', __( 'Фото автора' ) )
							->set_width( 25 ),
						Field::make( 'text', 'name', __( 'Имя' ) )
							->set_width( 25 ),
						Field::make( 'text', 'position', __( 'Должность' ) )
							->set_width( 25 ),
						Field::make( 'text', 'text', __( 'Текст' ) )
							->set_width( 25 )
					] )
			] )

			// Latest news section.
			->add_fields( 'news_section', __( 'Новости' ), [
				Field::make( 'text', 'title', __( 'Заголовок' ) )
			] )
	] );
```

## Steps to Reproduce the Problem

  1. Add new page.
  2. Start adding complex field's entries, at least one of them has rich_text field.
  3. Publish/Save page and reload - rich_text fields will be collapsed and empty and not editable through Visual tab.

## Comments
In some cases field could look OK, but I had this issue many times, just maybe try different sections order, fill them with content and so on.
For example, if I add only About Us section - all could be fine. But when I add Hero, About and Products filled with content, save & reload - an issue appears.

**Comment by HTMLBurger-NG** [comment]
Hi @andreistez ,

We couldn't reproduce the issue on the newest version (v3.5.0).
Please update WordPress core and Carbon Fields to the newest version and let us know if the issues still exist.

**Comment by andreistez** [comment]
@HTMLBurger-NG , thanks, I've downloaded v3.5.0 and nothing changed for me.
![image](https://user-images.githubusercontent.com/24782391/220086011-25e8075b-2211-4130-9376-94a23f519cea.png)
![image](https://user-images.githubusercontent.com/24782391/220086153-1cffc4df-5801-4b3c-a1e1-77133e15045f.png)
![image](https://user-images.githubusercontent.com/24782391/220086203-18e55202-2238-45e9-b384-dd384ede1bcc.png)

**Comment by HTMLBurger-NG** [comment]
Hi @andreistez ,

We've fixed some issues with the non-ASCII symbols in the containers' titles in the last release 3.5.1.

Please upgrade to it, and let us know if the issue is still existing.

**Comment by andreistez** [comment]
@HTMLBurger-NG , hi! Thank you.
I've uploaded this website live and seems there are no such issue (if I'm not mistaken, even in previous version).
But locally situation is still the same - I've updated plugin and all titles in container to Latin letters, but still see collapsed editor...

**Comment by KDanil1906** [comment]
I have the same problem. 
Carbon Fields 3.5.2
php 7.4
WP 6.1.1

All I've managed to find is that the problem is nested rich_text - inside the complex field.

If I remove rich_text from complex fields then other rixh_text fields on the page will behave as they should. 
But if there are rich_texts inside the complex in that case the visual tab stops displaying text and it is impossible to enter any new text into it, while the text tab works

**Comment by KDanil1906** [comment]
I was able to solve the problem by disabling Gutenberg

`if( 'disable_gutenberg' ){
	remove_theme_support( 'core-block-patterns' ); // WP 5.5

	add_filter( 'use_block_editor_for_post_type', '__return_false', 100 );

	// отключим подключение базовых css стилей для блоков
	// ВАЖНО! когда выйдут виджеты на блоках или что-то еще, эту строку нужно будет комментировать
	remove_action( 'wp_enqueue_scripts', 'wp_common_block_scripts_and_styles' );

	// Move the Privacy Policy help notice back under the title field.
	add_action( 'admin_init', function(){
		remove_action( 'admin_notices', [ 'WP_Privacy_Policy_Content', 'notice' ] );
		add_action( 'edit_form_after_title', [ 'WP_Privacy_Policy_Content', 'notice' ] );
	} );
}`
