### ISSUE TITLE
Add support for custom field types as an option on "text" fields

### ISSUE THREAD

**Issue by JacobDB** [htmlburger/carbon-fields#1154]
I've been using Carbon Fields in a couple of custom plugins that tie in to third party APIs. These APIs have a "public" key and a "secret" key. I'd like to be able to set the "secret" key field to the "password" field type (i.e. `<input type="password" />`, just to visually obscure the data. The value itself can continue to be plain text.

I think this would be best implemented as an option on the "text" field to specify the "type" attribute, as there are many text-like field types, such as `text`, `password`, `date`, `tel`, `email`, `search`, etc. Being able to specify one of these field types would help with accessibility and design.

**Comment by HTMLBurger-NG** [comment]
Hi @JacobDB,
Thank you for contacting us.

In the library, there is already a method `set_attribute`, that would allow you to override the text field type.

Example usage:
```
Field::make( 'text', 'my_password_field', __( 'Password Field' ) )
    ->set_attribute( 'type', 'password' ),
```

**Comment by JacobDB** [comment]
Aha! I suspected it was possible, but couldn't find anything in the documentation, thanks!
