### ISSUE TITLE
Gutenberg crashes with white screen and 'Uncaught TypeError' error due to Carbon Fields metabox.js

### ISSUE THREAD

**Issue by nemo369** [htmlburger/carbon-fields#1161]
## Version

  - Carbon Fields: ^5.3
  - WordPress: 6.2
  - PHP: 7.3

## Expected Behavior
Edit a page in Gutenberg will work and I wont get a blank white screen.

## Actual Behavior
when entering Gutenberg page/post to edit the page is crashing and the user get a white blank screen. Opening the devtools show the error 'Uncaught TypeError: a._reactRootContainer.unmount is not a function' from metabox.js

## Container definition
```php
<?php
defined('ABSPATH') || die();

use Carbon_Fields\Container;
use Carbon_Fields\Field;

// !! Field Name Patterns : most have uniqe prefix
// https://docs.carbonfields.net/#/advanced-topics/field-name-patterns?id=field-name-patterns


add_action('carbon_fields_register_fields', 'crb_attach_post_options');
function crb_attach_post_options()
{
    $post_type = 'post';
    $prefix = 'post_';
    $metaBox = Container::make('post_meta', 'General Settings');
    $metaBox->where('post_type', '=', $post_type);
  $metaBox = Container::make('post_meta', 'General Settings');
    $metaBox->where('post_type', '=', $post_type);
    $metaBox->add_fields(
        array(
            Field::make('image',  'firstimage', 'Optional: Main Photo at the top of the page {width:1180px,height:600px}'),
            Field::make('text', $prefix . 'name', 'Project name, will be used in loby pages'),
            // Field::make('text', 'subtitle', 'Subtitle (client name)'),

        )
    );

```

## Steps to Reproduce the Problem

  1. Edit a post/page in Gutenberg editor with metabox (WordPress version 6.2)
  1. Observe the blank white screen and the error message in the console: 'Uncaught TypeError: a._reactRootContainer.unmount is not a function'

## Comments
When attempting to edit a page or post in WordPress 6.2 using Gutenberg editor with Carbon Fields version 5.3 installed, users are experiencing a blank white screen and an error message in the browser console: 'Uncaught TypeError: a._reactRootContainer.unmount is not a function' from metabox.js.

**Comment by HTMLBurger-NG** [comment]
Hi @nemo369,

We've recently pushed a new release v3.6.0 where we've fixed the issues with WordPress 6.2.

**Comment by 0jordanmiller** [comment]
Still running into this

**Comment by xgschwi** [comment]
I am also running into problems with this on a project with maintenance @HTMLBurger-NG. I updated carbon fields with `composer update`, and see that I now have v3.6. Upon trying to edit a WordPress page again, or adding a page I am seeing the same console error attributed to carbon fields.
![image](https://github.com/htmlburger/carbon-fields/assets/61365241/f010ed26-180d-4d98-b631-312cc9423e6f)
![image](https://github.com/htmlburger/carbon-fields/assets/61365241/82bae8cf-c301-4e25-b42a-101c65018856)
![image](https://github.com/htmlburger/carbon-fields/assets/61365241/efd54d9e-e7a7-4c98-9415-fe6ba54b0025)

**Comment by enoonan** [comment]
Has this ever been addressed? I have inherited a site that is running into this issue.
