### ISSUE TITLE
Multiselect error when removing only option: `Uncaught TypeError: Cannot read properties of null (reading 'map')`

### ISSUE THREAD

**Issue by justlevine** [htmlburger/carbon-fields#1182]
## Version

  - Carbon Fields: 3.6.0
  - WordPress: 5.9.7
  - PHP: 7.4

## Expected Behavior
_Please enter the expected behavior here_

I should be able to remove the last selected option from a multiselect form.

## Actual Behavior
_Please enter the actual, unexpected behavior here_

Instead of the option getting removed, nothing happens, and I get a console error: `Uncaught TypeError: Cannot read properties of null (reading 'map')`

![image](https://github.com/htmlburger/carbon-fields/assets/29322304/a8902163-2567-402a-99f3-03a58278c69e)

This seems to be caused by the use of `selected.map()` instead of `selected?.map()` in [`handleChange`](https://github.com/htmlburger/carbon-fields/blob/47f1538cca6cd2860d1b37a040a42c59eb798d76/packages/core/fields/multiselect/index.js#L26) means the value is not an array. (not sure if this is a change in behavior in react-select@v3 https://github.com/htmlburger/carbon-fields/commit/2de3fbe44d5e063dece9bd40900e54dc7ff4addd
## Container definition
```php
// Please add your entire container defintion here so issues
// are easy to reproduce
Container::make( 'theme_options', 'Harness Settings' )
  ->set_page_parent( 'options-general.php' )
  ->add_fields(
    Field::make( 'multiselect', self::MODULE_HIDE_LIST, __( 'Modules to disable on the frontend.', 'harness' ) )->set_options(
      [
        'certifications'     => 'Certifications',
        'corrective-actions' => 'Corrective Actions',
        'documents'          => 'Documents',
        'equipment'          => 'Equipment',
        'notifications'      => 'Notifications',
      ]
    )
    ->set_help_text( 'Selected modules / features will be hidden / disabled on the frontend.' )
  )
```

## Steps to Reproduce the Problem

  1. Select an item or several in the Multiselect field.
  2. Try to remove all selected items from the Multiselect field.
  3. When attempting to remove the last item, note it does _note_ get removed. See console log.

## Comments
_Please add any other comments here_

**Comment by justlevine** [comment]
`values.map` in [Multiselect's `filterValues`](https://github.com/htmlburger/carbon-fields/blob/47f1538cca6cd2860d1b37a040a42c59eb798d76/packages/core/fields/multiselect/index.js#L38) also needs to be made nullable. 

I tried making a PR, but I cannot get the build script to run correctly using either NPM or Yarn 😕

**Comment by mrksdiehl** [comment]
Same issue here.

**Comment by MattOndo** [comment]
Bumping, same issue here

**Comment by amirnaderi** [comment]
Any updates about this issue!?

**Comment by laurensdacosta** [comment]
Also need an update on this issue!

**Comment by nestle49** [comment]
@vvasilev- @atanas-dev @jorostoyanov anybody else?

**Comment by atanas-vasilev-dev** [comment]
Fixed and coming in next release, see here:
https://github.com/htmlburger/carbon-fields/issues/1205

**Comment by atanas-vasilev-dev** [comment]
The fix for this issue is now released in https://github.com/htmlburger/carbon-fields/releases/tag/v3.6.5
