### ISSUE TITLE
Adding class to the field input

### ISSUE THREAD

**Issue by wp-src** [htmlburger/carbon-fields#119]
Hi. First of all thanks for this powerful framework!.
I am using carbon fields in my theme and i want to add a css class to one of my text fields input.
When i use the add_class method it adds the class to the parent element. Please make it possible to add an class to the input.
Also please let me know if it is possible to override the template for a specific field.
Thanks.

**Comment by m1r0** [comment]
Hi @wp-src,

Glad that you like the plugin! We are not planing to add the ability for custom classes for inputs, but there are multiple ways you can approach this:
You can use the [carbon-field-template](https://github.com/htmlburger/carbon-field-template) and extend the text field.
Another way to do it is by adding a custom class to the holder using the add_class method and use JavaScript to add the additional classes on the input that you need.

**Comment by wp-src** [comment]
@m1r0 Thanks for your response.
I think using another project behind the main project makes my project dirty!
It was very good to let user override the field template while creating it.
Anyway i think second approach is better for me.
