### ISSUE TITLE
Carbon field doesn't work anymore after Wordpress update

### ISSUE THREAD

**Issue by iamalessiopaoletti** [htmlburger/carbon-fields#1198]
Hi, carbon fields doesn't work anymore after the last update of wordpress, in the page the content are hidden, the blocks tell that missing the support for block and in the console I have these errors:

![Screenshot 2023-11-08 165237-2222](https://github.com/htmlburger/carbon-fields/assets/41924220/abe4073e-cf83-44ca-93af-defde17373ff)

**Comment by greabs** [comment]
Same here. Seems to be an issue with upgrading to the latest WP version 6.4  ..

**Comment by greabs** [comment]
Followup; the issue is caused by WP 6.4 scratching the Lodash lib. https://github.com/WordPress/gutenberg/pull/52571 
Can an update be expected for Carbon Fields to fix the dependency on Lodash?

**Comment by iamalessiopaoletti** [comment]
I have another site updated but work well, why?

**Comment by iamalessiopaoletti** [comment]
I solved it like this in function.php:

`
function load_lodash() {
  // Il codice CDN del file lodash.js
  $lodash_url = 'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js';

  // Carica il codice CDN
  wp_enqueue_script('lodash', $lodash_url, array(), null, false);
}
add_action('admin_enqueue_scripts', 'load_lodash');
`


It is worrying that there is no assistance though.

**Comment by greabs** [comment]
Yeah but that's not really a solution. Lodash has been dropped by the wp-core guys because it not needed anymore and increases the load. Either it should be included in a new release of Carbon Fields (also not great) or Carbon Fields simply isn't compatible anymore with WP v6.4+   ..

**Comment by jorostoyanov** [comment]
Hey Guys!

I have just released v3.6.1 of Carbon Fields which adds support for WordPress v6.4.

Please, update to the latest version on your instances and if any issue re-appears feel free to open a new issue :)

**Comment by gardiner** [comment]
Hi guys, thanks for your quick reaction and all your efforts!

👍
