### ISSUE TITLE
Term Meta Styling Issue

### ISSUE THREAD

**Issue by alpanayotov** [htmlburger/carbon-fields#12]
There is a CSS issue on the "Add New Term" page, when we have a complex field with groups. The default styling prevents the dropdown from showing. Image attached.
![carbon-bug_03](https://cloud.githubusercontent.com/assets/6815161/14041412/4392c7fa-f279-11e5-9a44-4d2daa7a2b0b.jpg)

Solution: #13

**Comment by tyxla** [comment]
Merged: https://github.com/htmlburger/carbon-fields/pull/13
