### ISSUE TITLE
Possible bug in `show_on_page()`

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#120]
Hi there, I was trying to show a form for just a page but nothing was working, so after digging into the code I think that I've found a bug.

I've seen that [`core/Container/Post_Meta_Container.php::show_on_page`](https://github.com/htmlburger/carbon-fields/blob/master/core/Container/Post_Meta_Container.php#L418) string path calls `get_page_by_path`; I've checked with my string that this returns an actual post… It works. :-/

So there is something wrong on the first `if ( absint( $page ) == $page ) {`. I've checked what `absint` does and I've reproduced the bug in the php console (`$ php -a`):

```
php > var_dump(abs(intval("qui-som/equip")) == "qui-som/equip");
bool(true)
php > var_dump(abs(intval("qui-som/equip")));
int(0)
php > var_dump(0 == "qui-som/equip");
bool(true)
```

As you can see when a string is compared to zero it returns true (!?). The easy fix is to just use `===` operator in the if. Tested in booth PHP 5.4 and 7.0. [More info: http://php.net/manual](http://php.net/manual/en/types.comparisons.php#49327).

---

What I don't get is that earlier I'm quite sure that the same code worked…

**Comment by m1r0** [comment]
This is a bug alright, thanks for the report.

**Comment by m1r0** [comment]
This is fixed in https://github.com/htmlburger/carbon-fields/commit/51c08deefa4a1b219796c84ed129cc150630e134.
