### ISSUE TITLE
Preview blocks in Wordpress 6.4.1 not supported

### ISSUE THREAD

**Issue by Floris-devries** [htmlburger/carbon-fields#1200]
## Version

  - Carbon Fields: 3.6.1
  - WordPress: 6.4.1
  - PHP:  8.1

## Expected Behavior
When viewing the gutenberg block in the theme editor, it should show me the result of the data I filled in.

## Actual Behavior
The block is not customizable anymore, and I get the following error: "This block has encountered an error and cannot be previewed."

The console gives me the following error:
"TypeError: Illegal invocation"

## Container definition
add_action( 'carbon_fields_register_fields', function () {
    Block::make( __( 'Banner' ) )
    ->add_fields( array(
        Field::make( 'text', 'title', __( 'Banner Title' ) ),
        Field::make( 'text', 'subtitle', __( 'Sub Title' ) ),
        Field::make( 'rich_text', 'content', __( 'Banner text' ) ),
        Field::make( 'text', 'btn_text', __( 'Banner button text' ) ),
        Field::make( 'text', 'btn_url', __( 'Banner button url' ) )->set_attribute( 'type', 'url' ),
        Field::make( 'image', 'image', __( 'Banner image' ) )->set_value_type( 'url' ),
        Field::make( 'color', 'bg_color', __( 'Background color' ) ),
    ) )
    ->set_category( 'online-origins-category', __( 'Online Origins Category' ), 'smiley' )
    ->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {
        $fields['block'] = $attributes;
	    echo \Roots\view('blocks.banner', ['fields' => $fields])->render();
	} );
});

## Steps to Reproduce the Problem

  1. Go to the theme editor of a page.
  2. Add a block. 
  1. Preview the block.

## Comments
Carbon fields block are working on my other websites where the version is still lower than 6.4. Maybe others have the same issue and try to find a solution.

**Comment by Floris-devries** [comment]
Where it goes wrong:

{
  key: "componentWillUnmount",
  value: function() {
      clearTimeout(this.timer),
      void 0 !== this.cancelObserver && this.cancelObserver(),
      this.destroyEditor()
  }
}

**Comment by jorostoyanov** [comment]
Hi @Floris-devries 

Thank you for submitting the issue!

I have just released v3.6.2 which fixes it :)
