### ISSUE TITLE
Multiple plugins can't be activated if use Carbon Fields to develop them.

### ISSUE THREAD

**Issue by shaonsina** [htmlburger/carbon-fields#1209]
## Version

  - Carbon Fields: 3.6.3
  - WordPress: 6.4.2
  - PHP: 8.2.12

If I use Carbon Fields to build the plugins **A** and **B** to create **options pages** and **metaboxes**, then only one of them can be activated (like: plugin A or plugin B). If I activate both of them, then a **fatal error** raises while activating plugin B.

https://prnt.sc/wrDhQD0b3Znj

**Comment by owaisahmed5300** [comment]
You should use tool such as php scoper

**Comment by phycticio** [comment]
Namespacing should solve this issue.
