### ISSUE TITLE
Add more hide_on_* methods

### ISSUE THREAD

**Issue by m1r0** [htmlburger/carbon-fields#122]
Maybe the most useful ones will be:

```
->hide_on_page()
->hide_on_page_children()
->hide_on_category()
->hide_on_taxonomy_term()
->hide_on_user_role()
->hide_on_level()
```

More suggestions are welcomed.

**Comment by pkostadinov-2create** [comment]
Some code refactor may be needed - all of the logic could be separated into methods like:

```
->is_page()
->is_page_children()
->is_category()
->is_taxonomy_term()
->is_user_role()
->is_level()
```

And the methods `show_on_` and `hide_on_` would call those methods.

**Comment by georgeHtmlBurger** [comment]
Maybe having a filter that would return either `true` or `false` on whether the panel should be visible or not respectively, so people can add any custom logic.

**Comment by pkostadinov-2create** [comment]
Related ticket: #148

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which allows you to achieve this using the new conditionals system:
More info here: https://carbonfields.net/docs/containers-conditional-display/?crb_version=2-0-0
