### ISSUE TITLE
No TinyMCE appears in gutenberg block but appears in sidebar edition

### ISSUE THREAD

**Issue by Foorinto** [htmlburger/carbon-fields#1231]
## Version

  - Carbon Fields: 3.6
  - WordPress: 6.5.2
  - PHP: 8.3

## Expected Behavior
TinyMCE displayed in the gutenberg block

## Actual Behavior
TinyMCE is not displaying in the gutenberg block, I get no error, neither conflict but this warning in the console:
```
carbon-fields-core-css was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe.
<link rel="stylesheet" id="carbon-fields-core-css" href="[pathToTheme]/vendor/htmlburger/carbon-fields/build/gutenberg/core.min.css?ver=3.6.3" media="all">
```

But it works in the sidebar when you visualize the block (eye icon)

![tinymce-2](https://github.com/htmlburger/carbon-fields/assets/54845120/7e9243a5-824f-479e-84ba-0cfc90fa3392)
![tinymce-1](https://github.com/htmlburger/carbon-fields/assets/54845120/fb97a9e0-a380-4b84-81ff-d0bc75f78187)

## Container definition
```php
add_action('carbon_fields_register_fields', 'crb_attach_gutenberg_options');
function crb_attach_gutenberg_options() {
    Block::make( __( 'My Shiny Gutenberg Block' ) )
	->add_fields( array(
		Field::make( 'text', 'heading', __( 'Block Heading' ) ),
		Field::make( 'image', 'image', __( 'Block Image' ) ),
		Field::make( 'rich_text', 'content', __( 'Block Content' ) ),
	) )
	->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {
		?>
		<div class="block">
			<div class="block__heading">
				<h1><?php echo esc_html( $fields['heading'] ); ?></h1>
			</div><!-- /.block__heading -->

			<div class="block__image">
				<?php echo wp_get_attachment_image( $fields['image'], 'full' ); ?>
			</div><!-- /.block__image -->

			<div class="block__content">
				<?php echo apply_filters( 'the_content', $fields['content'] ); ?>
			</div><!-- /.block__content -->
		</div><!-- /.block -->
		<?php
	} );
}
```

## Steps to Reproduce the Problem

  1. Intall carbon fields (composer require htmlburger/carbon-fields)
  2. Use rich_text in functions.php

## Comments
Hello,
Maybe I'm missing something, but I can't find it. Can anyone help me ?

I also get the same issue than this threand on the forum: 
[https://community.carbonfields.net/t/adding-a-cf-block-to-a-core-group-block-removed-the-preview-button-from-toolbar/2140](url)

Thanks in advance.

**Comment by atanas-vasilev-dev** [comment]
@Foorinto
I'm not able to reproduce this issue.

Are you on the latest version of `3.6`? If you're not, could you update to `3.6.3` and let us know if your problem persists?

It would also be helpful to know that the problem is not any incompatibility with any plugins so could you turn off all plugins before testing?

**Comment by Foorinto** [comment]
Hello,

I was already in version 3.6.3, but I tried again, the editor does appear now.
I don't know what causes this issue, but it's working well now.

Thanks for your help.
