### ISSUE TITLE
UI Translations not working

### ISSUE THREAD

**Issue by MaxGruson** [htmlburger/carbon-fields#1235]
## Version

  - Carbon Fields: 3.6.3
  - WordPress: 6.5.4
  - PHP: 8.0.13

## Expected Behavior
Carbon Fields UI gets translated according to currently set language.

## Actual Behavior
Carbon Fields UI falls back to English. All fields don't seem to use carbon-fields-ui-[language domain].mo

## Steps to Reproduce the Problem

1. Set WordPress language to anything but English. 
2. Add a field.

## Comments
Translation only seems to fail of strings defined in Carbon Fields's Javascript files, like `carbon-fields/packages/core/fields/complex/group.js`. A function like `__( 'Duplicate', 'carbon-fields-ui' )` doesn't return a translated string. If I however use the same function in a random PHP file, the translation works fine. Might this have something to do with the absence of [JSON translation files](https://developer.wordpress.org/cli/commands/i18n/make-json/)?

**Comment by jayddaniels** [comment]
@MaxGruson  Not sure, if this is the actual problem, but its solvable if you go to core/Loader/Loader.php->get_ui_translations() and change filling of the $locale to something like this:
foreach ( $translations->entries as $msgid => $entry ) {
			$locale[ $msgid ] = $entry->translations;
			if($entry->is_plural){
				$locale[ $entry->plural ]=$entry->translations;
			}else{
				$locale[ $entry->singular ]=$entry->translations;
			}
		}

**Comment by MaxGruson** [comment]
@jayddaniels  Hey, you're right, that did solve it in my case, thanks!

Should probably be merged @atanas-vasilev-dev ?

**Comment by remotedots** [comment]
I've run into a similar issue:

UI strings translated with `__('string', 'domain')` were only showing the untranslated strings in the backend. Using the function anywhere in the code would return the right translation.

It seems that `__(..)` was called before the translation functions are fully initialized.

Calling `load_theme_textdomain()` after the theme setup and not on init would fix this:

```
add_action('after_setup_theme', function() {
    load_theme_textdomain('domain', get_template_directory() . '/languages');
});
```

**Comment by techno-trump** [comment]
> [@MaxGruson](https://github.com/MaxGruson) Not sure, if this is the actual problem, but its solvable(just testing for now, so maybe just partially but ..) if you go to core/Loader/Loader.php->get_ui_translations() and change filling of the $locale to something like this: foreach ( $translations->entries as $msgid => $entry ) { $locale[ $msgid ] = $entry->translations; if($entry->is_plural){ $locale[ $entry->plural ]=$entry->translations; }else{ $locale[ $entry->singular ]=$entry->translations; } }

This helped in my case
