### ISSUE TITLE
Carbon Fields Not Supported in WordPress 6.6 Update

### ISSUE THREAD

**Issue by tanjilahmed7** [htmlburger/carbon-fields#1240]
## Version

  - Carbon Fields:
  - WordPress: 6.6
  - PHP: 8.3

## Plugins List

- Add WPGraphQL SEO
- Add WPGraphQL SEO
- Carbon Fields
- graphql crb
- WP GraphQL Gutenberg
- WPGraphQL
- WPGraphQL Tax Query
- Yoast SEO

When I updated to WordPress version 6.6, an error occurred with the Carbon Fields blocks. I have attached an image for better understanding. When i downgrade the wordpress (6.4.5) version that moment it works. 

![image](https://github.com/user-attachments/assets/bbc7701f-0407-44ce-90da-bd2b7e2c6e69)

**Comment by mrdarrengriffin** [comment]
Yeah, having the same issue. This is what I get for theme options

![Screenshot 2024-07-17 at 11 47 06](https://github.com/user-attachments/assets/da0744c4-1d95-4a74-afe7-f20d3ee5978a)

**Comment by beavis82** [comment]
We're experiencing the same issue on numerous sites using Carbon Fields (an older version - 3.3.4). As a quick fix, enqueueing  regenerator runtime seems to be working for us so far. Add this code to your theme or a plugin: 

if (!function_exists('enqueue_regenerator_runtime_admin')) {
    function enqueue_regenerator_runtime_admin() {
        // Check if regenerator-runtime has already been enqueued
        if (!wp_script_is('regenerator-runtime', 'enqueued')) {
            wp_enqueue_script('regenerator-runtime');
        }
    }

    add_action('admin_enqueue_scripts', 'enqueue_regenerator_runtime_admin');
}

Hope this helps until an official fix is released.

**Comment by atanas-vasilev-dev** [comment]
After some testing I figured out that this problem occurs on CF versions below 3.5. Anyone having this issue should try and update to the latest version.

**Comment by michelmany** [comment]
Updating CF to version 3.5 solved the issue for me.

`composer require htmlburger/carbon-fields`

**Comment by wrafaelb** [comment]
- The problem was solved when I updated to the latest version of the plugin. I'm usgin 3.6 version
