### ISSUE TITLE
Using the 'Click here' link to add new entry in empty complex field triggers twice when using tabbed layout.

### ISSUE THREAD

**Issue by yuliyan** [htmlburger/carbon-fields#128]
When you click the "Click here" link inside empty complex field it adds two new entries instead of one.

![image](https://cloud.githubusercontent.com/assets/2722412/20380061/4f8ba9d4-aca8-11e6-935f-79d91103c6cb.png)

Issue occurs on both horizontal and vertical tabbed layouts.

**Comment by htmlburger-git** [comment]
Fixed in https://github.com/htmlburger/carbon-fields/commit/dd6becdd7832901b3f4b917ac0eb931433ec432f (`development`)

**Comment by atanas-angelov-dev** [comment]
Fixed in https://github.com/htmlburger/carbon-fields/commit/dd6becdd7832901b3f4b917ac0eb931433ec432f (`development`)
