### ISSUE TITLE
How to correctly use `carbon_after_save_theme_options`

### ISSUE THREAD

**Issue by wadtech** [htmlburger/carbon-fields#134]
I would like to process some theme options after they are saved, but can't find a sensible way to do it.

I found `carbon_after_save_theme_options` in the Theme Options container save method but it is only ever called with an empty string.

How do I receive my saved options?

**Comment by jorostoyanov** [comment]
@wadtech 

Can you share the code that you're using, so I can have a look and try to reproduce it?

**Comment by wadtech** [comment]
Hi @jorostoyanov 

Thanks for your quick reply, here is an example gist: https://gist.github.com/wadtech/e41bbed0e12d936d1c59ca96e2dcdae3

That's the entire contents of the functions.php file for the theme in this example, saving correctly calls the action because I get the var_dump/die output.

Thanks

**Comment by Santana1053** [comment]
`carbon_after_save_theme_options` does not receive the fields that were changed, as it does not actually modify what was being saved. An example for using this hook would be if you wanted to modify a specific option to be stored in a different way, such as storing a unix timestamp of a time/datetime field in the database.

```
add_action( 'carbon_after_save_theme_options', function () {
    $meta = carbon_get_theme_option( 'my_time_option' );
    if ( $meta ) {
        $time = strtotime( $meta );
        update_option( 'my_time_option_timestamp', $time );
    }
} );
```

And then to get this value you would use carbon_get_theme_option( 'my_time_option_timestamp' )

**Comment by wadtech** [comment]
@Santana1053 I see. For my use-case I would like to notify an external piece of code of the change to the theme options.

Would hooks before/after save with the changed fields be something you'd be open to accepting a pull request for?

**Comment by jaredrethman** [comment]
I have managed to achieve this by grabbing the $_POST superglobal within the callback. for my use case I wanted to store all theme options in a single db entry.

**Comment by Santana1053** [comment]
For that you could have also done
```add_action( 'carbon_after_save_theme_options', function () {
    $meta = carbon_get_theme_option( 'my_time_option' );
    if ( !empty( $meta ) {
        $options = json_encode( $meta );
        update_option( 'my_theme_options', $options);
    }
} );```
