### ISSUE TITLE
Hidden Fields, still not in Carbon Fields?

### ISSUE THREAD

**Issue by AlexBa** [htmlburger/carbon-fields#145]
Hey there,
I know that this topic has been discussed this year, but I think that Hidden fields are very important for a form library like Carbon Fields. At this moment, I'm using a lot of those fields.

So what about creating a simple and official Hidden field for the next version?

Best regards,
Alexander Barton

**Comment by Santana1053** [comment]
Try using this https://github.com/pkostadinov-2create/carbon-field-hidden

**Comment by atanas-angelov-dev** [comment]
We're revisiting this functionality now and wanted to get some feedback on use cases that you need a hidden field for - let us know.

A few clarifications:
- In 2.0, complex field entries are saved even if they do not have any value-holding fields so there is no need for a workaround with a hidden field, for example
- Any other use cases we have had internally were solved by using the html field (left blank or not)

**Comment by AlexBa** [comment]
Okey, let me explain:

I have an project called Affilicious, which is basically a "WooCommerce for Affiliates". Thats means there exists some products with variants. Every product is just a regular post type in Wordpress, but the product variants are one or more complex fields, which internally map to one or more posts with custom types for the variants. 

The mapping is based on the post ID, which is stored in a hidden field in the complex field. See:
https://github.com/affilicious-theme/affilicious/blob/master/src/product/setup/product-setup.php#L247. It need to be persisted somehow, but shouldn't be visible for the user ;)

Additionally there are some other hidden fields for other purposes. My opinion is that if Carbon Fields is used heavily in a (complex) project, there will be more and more situations where hidden fields are just suitable.

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which introduces a Hidden_Field which you can interact with using the new JavaScript API.
More info here: https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-0-0
