### ISSUE TITLE
If I remove the default WP editor, CF won't save at all

### ISSUE THREAD

**Issue by edwardhew** [htmlburger/carbon-fields#154]
If I do this in functions.php to remove the default WP editor
```php
remove_post_type_support('page', 'editor');
```

Below this is how I remove the core WP editor, it works, the editor is removed based on what template path passed into `uses_template` shown below, the carbon fields show up correctly, but when I hit save, carbon fields will not save, no rows created in wp_postmeta at all.

When I tried keeping the WP core editor, where carbon fields appear below the default WP editor, carbon fields will then save correctly.

This is how I did it with CMB2 on some pages, remove core editor, just rely on the postmeta, that saved correctly. Not sure if I'm missing something here or that's how it is.
```php
/**
 * Does current page being edited use a particular template?
 */
function uses_template($template) {
    if (get_post_meta((int)$_GET['post'], '_wp_page_template', true) == $template) {
        return true;
    }
    return false;
}

/**
 * Remove core editor
 */
function remove_editor() {
    remove_post_type_support('page', 'editor');
}

// Homepage custom fields
add_action('carbon_register_fields', 'crb_register_homepage_fields');
function crb_register_homepage_fields() {
    $template_path = 'templates/page-home.php';
    if ( uses_template($template_path) ) {
        include_once(dirname(__FILE__) . '/custom-fields/field-home.php');
        add_action('admin_head', 'remove_editor');
    }
}
```

**Comment by pkostadinov-2create** [comment]
Assuming that you define Carbon Fields container conditionally, behind your custom logic, the `$_GET['post']` is not present during the actual saving of the post (default for WordPress). This is a separate POST request, which you can monitor in your browser network tab. There is a POST request containing `$_POST['post_ID']`, which you should also include in your custom logic:

```
function uses_template($template) {
	$post_ID = 0;
	if ( !empty( $_GET['post'] ) ) {
		$post_ID = (int)$_GET['post']
	} elseif ( !empty( $_POST['post_ID'] ) ) {
		$post_ID = (int)$_POST['post_ID'];
	} else {
		return false;
	}

	if ( get_post_meta( $post_ID, '_wp_page_template', true ) == $template ) {
		return true;
	}
	
	return false;
}
```

I can recommend simply using the Carbon Fields methods `show_on_post_type` and `show_on_template`:

https://carbonfields.net/docs/containers-post-meta/

**Comment by edwardhew** [comment]
Thank you again, you solved my last question too :)

Yes, I am using `show_on_template`, but here I wanted to also hide the WP editor, at the same time bypass this particular call to CRB if user is not working with this template ... but I can see the problem with my logic now, I should really just bypass the whole block altogether if that is the case.

1++
