### ISSUE TITLE
fields-set ->set_default_value doesn't work

### ISSUE THREAD

**Issue by dameer** [htmlburger/carbon-fields#155]
Case scenario:

```
Field::make( 'set', 'set-id', __( 'SetLabel' ) )
->add_options( array(
	'option-one' => 'First', 
	'option-two' => 'Second', 
	'option-three' => 'Third', 
	'option-four' => 'Fourth',
) )
->set_default_value( array( 'option-one', 'option-two', 'option-three', 'option-four' ) )
```

I suppose default values for "set" field type should be of type array since multiple checkboxes are in the game. It won't work as seen above nor it works with single default value (string) provided.
Is it a bug or just myself not getting the point?

**Comment by m1r0** [comment]
This is fixed and will be available in the next release version (which will be really soon).

Thanks for the report @dameer!

**Comment by pablo-sg-pacheco** [comment]
I couldn't make it work. Is it really working?
