### ISSUE TITLE
show_on_page does not work with wordpress 4.7

### ISSUE THREAD

**Issue by eenagy** [htmlburger/carbon-fields#157]
As of this writing tried to use 

```php
    ->show_on_page('jobs' )
```
which was not working on jobs pages. The following is working:

```php
    ->show_on_page(get_page_by_path( 'jobs' )->ID)
```

I'm new to carbonfields(latest carbonfields), but this seems like a bug to me.

**Comment by m1r0** [comment]
Hi @eenagy, thanks for the report.
This is a known bug in version 1.4 and will be fixed in the next release. Checkout https://github.com/htmlburger/carbon-fields/issues/121 for more info.
