### ISSUE TITLE
complex field pre-populate option

### ISSUE THREAD

**Issue by eenagy** [htmlburger/carbon-fields#158]
I was searching the documentation and the php code for setting default value of complex fields.
**Is there a way to pre-populate complex fields with some default settings?**

I want that the wordpress user see what the specific page looks like on complex content scenarios.

I'm thinking _something like this_: 
```php
Field::make('complex', 'gallery')
->add_fields(array(
      Field::make('text', 'crb_title', 'Title')->set_default_value('Default image'),
      Field::make("image", "crb_employee_photo", "Photo")->set_default_value('url_to_image'),	
))->set_default_value(array(
      array('crb_title' => 'image title 1', 'crb_employee_photo' => 'first image')),
      array('crb_title' => 'image title 2', 'crb_employee_photo' => 'second image'))
))
```

This would be really helpful for creating default content, especially for nested complex content.

**Comment by Santana1053** [comment]
+1 for this

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which allows you to use `->set_default_value()` on complex fields thus achieving prefilled groups.
An example is available here: https://carbonfields.net/docs/guides-predefined-complex-groups/?crb_version=2-0-0
