### ISSUE TITLE
1.5 release, complex field no longer appear

### ISSUE THREAD

**Issue by edwardhew** [htmlburger/carbon-fields#160]
No error output, just doesn't appear. 1.4 was fine, updated to 1.5, complex field gone.

**Comment by m1r0** [comment]
@edwardhew, can you please try refreshing the page with CTRL+F5 (clearing the browser cache) and share the results?

The issue might be that the plugin is missing cache busting (https://github.com/htmlburger/carbon-fields/issues/161).

**Comment by edwardhew** [comment]
No luck, still missing.

What I tried:
- Cleared cache, cookies etc
- Used a different browser that never loaded this project

**Comment by m1r0** [comment]
Can you please provide the following:

 * Your WP version
 * The fields definition code for the whole carbon container
 * A list of all other activated plugins

Some more question that might help:

 * Is the problem related to the complex field only, or other fields are also not appearing?
 * Can you please check the browser console for any JavaScript related errors?
 * Can you please try disabling all other plugins and share the result?

**Comment by edwardhew** [comment]
First, thanks for your help m1r0!

Ok, I think maybe found the reason, when I have this, all fields will not show:
`->show_on_template(get_theme_file_path('templates/page-home.php'))`

That is correct path, I've checked, also tried the template's name. Before problem, I only did this, it worked
`->show_on_template('templates/page-home.php')`

This works for complex and regular fields (that I have)
`->show_on_post_type( 'page' )`

- WP 4.7
- please see below
- The post edit page does not use any other plugin, and deactivated all other plugin
- turns out problem is with all field that use `show_on_template()`
- No JS console errors
- Have deactivated all plugins except Carbon Fields

Minimized my code to just this for testing
```php
Container::make('post_meta','Homepage slider')
    ->show_on_template(get_theme_file_path('templates/page-home.php'))
    ->add_fields(array(
        Field::make('complex', 'crb_homepage_slider', 'Slides content')
            ->add_fields(array(
                Field::make('textarea', 'title')
                    ->add_class('short-textarea')
                ))
            ));
```

**Comment by m1r0** [comment]
No problem @edwardhew, glad to help! 

I think that I found the problem - in 1.4, `show_on_template` automatically was setting the post type to `page`, but in 1.5 it's not. This is because WP 4.7 now allows templates on all post types, so automatic post type selection is not making sense anymore. To fix your problem you need to set the post type to `page`. Here is the pull request related to this change: https://github.com/htmlburger/carbon-fields/pull/146.

About the usage of `get_theme_file_path`, you only need the template path relative to the theme, for example `templates/page-home.php`.

**Comment by edwardhew** [comment]
Ah ok, thanks again, now it all works, much relief!

```php
Container::make('post_meta','Homepage slider')
    ->show_on_post_type( 'page' )
    ->show_on_template('templates/page-home.php')
    ->add_fields(array(
        ....
    ));
```
