### ISSUE TITLE
1.5 carbon_register_fields action

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#162]
Prior to 1.5, Calling the add_action 'carbon_register_fields' inside of the wordpress 'init' action worked perfectly fine. Now it would seem that this action only functions when added directly from the main function file.

**Comment by m1r0** [comment]
Yes, this is true, you need to use an action that is earlier than `init`, I suggest `after_setup_theme`.

**Comment by m1r0** [comment]
@Santana1053 did you manage to solve the problem?

**Comment by Santana1053** [comment]
I suppose. I'll just have to go through all of my custom sites and make sure that it isn't called inside init .-.

**Comment by m1r0** [comment]
Really sorry for the inconvenience @Santana1053, but we wouldn't have done it if it wasn't necessary. We try to move the plugin forward and it's difficult to account for all possible use cases.
