### ISSUE TITLE
Packagist CB1.5

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#163]
With the release of CB1.5, updating to this package on composer installs it into the \wp-contents\my_theme\wp-content\plugins\carbon-fields directory instead of installing into the composer vendors folder.

Edit: It does appear that composer is still autoloading it even though its in a different directory, but what reason would there be to not have it in the vendors folder?

**Comment by m1r0** [comment]
We changed the composer package type to `wordpress-plugin` and now the package acts differently. To get the old behavior, you can add the following code to your composer.json:

```
"extra": {
    "installer-paths": {
        "vendor/{$vendor}/{$name}/": ["type:wordpress-plugin"]
    }
}
```

Related: https://github.com/htmlburger/carbon-fields/pull/137, https://github.com/htmlburger/carbon-fields/issues/31

**Comment by Santana1053** [comment]
Why change the package type to wordpress-plugin when you can use https://wpackagist.org/ to accomplish this?

**Comment by m1r0** [comment]
@Santana1053 it seems that people prefer it that way and most of the bigger plugins use it. Also if you think about it, it's kinda logical for plugins to be a separate composer type, they are not really a `library` which is the default type.

**Comment by Santana1053** [comment]
@m1r0 I understand. Thanks for the help in keeping them in the vendors folder. I have multiple themes developed by htmlburger that use the composer package as a library inside of the theme.
