### ISSUE TITLE
1.5 Update - breaks extended containers

### ISSUE THREAD

**Issue by jaredrethman** [htmlburger/carbon-fields#165]
Beautiful plugin - thanks a million CF!

For anyone who extends Carbon Fields containers, and who just ran the 1.5 update, remember to change how your containers are initialized. 

Found that after_theme_setup is a better hook (I previously used init) as the latest update now initializes on init and and not wp_loaded as it was in previous versions.

**Comment by m1r0** [comment]
Thanks @jaredrethman, glad to hear that you like the plugin and thanks for info, many people might find it useful.

Changing the hook was necessary to fix some widgets initialization problem.

About extending the library, I suggest first referring to the [carbon-field-template](https://github.com/htmlburger/carbon-field-template). There the initialization is done on `after_setup_theme`.

We will try not to forget to add an update notice next time we make changes to the hooks. :-)

Related: https://github.com/htmlburger/carbon-fields/issues/162, https://wordpress.org/support/topic/register-my-fields-with-the-carbon_register_fields-hook/
