### ISSUE TITLE
White screen of death when Carbon Fields is activated

### ISSUE THREAD

**Issue by radiocontrolled** [htmlburger/carbon-fields#170]
I've got the most recent version of Carbon Fields installed as well as Wordpress 4.7. Since updating to 4.7, when Carbon Fields is activated, I get the white screen of death at the wp-admin screen where I would normally be able to log in. Via disabling all plugins and turning them on one by one, I've determined this issue happens when Carbon Fields is active but not when it is inactive. Initially I thought it was a conflict with the plugin W3 Total Cache but that is totally uninstalled so it is not the problem and have managed to isolate it to Carbon Fields. I've turned PHP debugging on and I'm not getting error messages at wp-admin. Do you have any suggestions for what the issue might be? Thanks!

**Comment by m1r0** [comment]
Thanks for the report @radiocontrolled.

Could you please answer the following questions and I will try my best to help you:

 * Did the problem occur after updating WP or after updating the plugin?
 * Did you try enabling WP_DEBUG? It would be really helpful to know the error.
 * What is the page response code? 500 or 200?
 * Do you have access to the web server logs? This is another place from where you can get the error.

**Comment by radiocontrolled** [comment]
Hi @m1r0 thank you for the response. 

Did the problem occur after updating WP or after updating the plugin?
- after updating

Did you try enabling WP_DEBUG? It would be really helpful to know the error.
- Yes, I've set WP_DEBUG to true in wp-config.php but I get no errors. 

What is the page response code? 500 or 200?
- 200 if I type in site.com/wp-admin

- if I go to site.com, then go to site.com/wp-admin, I get:
wp-admin	GET	301	text/html	Other	(from disk cache)	7 ms	
wp-admin/	GET	301	text/html	http://www.site.com/wp-admin	(from disk cache)	15 ms	
wp-admin/	GET	200	document	http://site.com/wp-admin/	294 B	409 ms	

Do you have access to the web server logs? This is another place from where you can get the error.
- I do. For privacy would you mind if I emailed them to you?

**Comment by radiocontrolled** [comment]
Hey @m1r0, 

I got also this error message in the installation on my development machine: 

`Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/mysite/wp-content/themes/myTheme/includes/post-meta.php:51) in /Applications/MAMP/htdocs/mysite/wp-includes/pluggable.php on line 1179`

I believe I resolved this by removing the closing `?>` from post-meta.php in my theme. 

Does that make sense to you?

**Comment by m1r0** [comment]
Sometimes when you have a space (` `) or new line after the closing php tag you can get this error. Not sure if this could cause a white screen of death. Should we mark this as resolved?

**Comment by m1r0** [comment]
Please re-open this issue if you are having further problems.

**Comment by radiocontrolled** [comment]
Thanks @m1r0
