### ISSUE TITLE
show_on_template with post templates (introduced with WP 4.7) ?

### ISSUE THREAD

**Issue by MatRouault** [htmlburger/carbon-fields#171]
Hello !
WordPress 4.7 introduces <a href="https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/">post type templates</a>.
With Carbon Fields, containers may be assigned to pages using specific template. Is it possible to do the same with post template ? I've tried, with no success.
Thanks !

**Comment by m1r0** [comment]
Hi @MatRouault, we added this feature in Carbon Fields 1.5. Just combine the `show_on_post_type` and `show_on_template` methods. For example:

```
Container::make('post_meta','Slider')
    ->show_on_post_type('post')
    ->show_on_template('templates/post-slider.php')
    ->add_fields(array(...
```

If you still can't figure it out, please provide the container code that you are using. Cheers!

**Comment by MatRouault** [comment]
It perfectly works, thanks a lot @m1r0 !

**Comment by m1r0** [comment]
No problem @MatRouault, glad to help!
