### ISSUE TITLE
Visual bug with color picker

### ISSUE THREAD

**Issue by avasilev2create** [htmlburger/carbon-fields#172]
As you can see the button below appears above the color picker when it's active.
![capture](https://cloud.githubusercontent.com/assets/24589439/21343797/177cdd48-c6a1-11e6-9a5c-40acb555a014.PNG)
![capture1](https://cloud.githubusercontent.com/assets/24589439/21343798/177d319e-c6a1-11e6-96ec-de89c6bd3b3d.PNG)

**Comment by Santana1053** [comment]
Have you tried clearing your cache?

**Comment by yuliyan** [comment]
@avasilev2create thanks for the report! It's fixed in 6696f0e
