### ISSUE TITLE
wp_editor settings rich text field

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#175]
Currently there is no way to example disable media buttons in rich text field, because settings passed to wp_editor can't be modified.

**Comment by atanas-angelov-dev** [comment]
Hi @timiwahalahti,

Right now the Rich_Text_Field does not support wp_editor settings but we will be revisiting this somewhere down the line.

**Comment by timiwahalahti** [comment]
I think this issue should not be marked as closed, if you are revisiting this at some point.

**Comment by m1r0** [comment]
Make sense, we will keep feature requests open from now on.

**Comment by samikeijonen** [comment]
Would like to see this as well.

**Comment by nebulousGirl** [comment]
Still no progress on that? Seems pretty simple to implement with a filter though.

**Comment by Fritze1602** [comment]
Progress would be great. I wonder if there is a workaround? I fear I will try to do smthing with admin js... meanwhile.

**Comment by davejtoews** [comment]
I needed a fix for this myself and quickly spun up a fork of this field without a media button. In case anyone else finds it useful it's here: https://packagist.org/packages/evanshunt/carbon-fields-rich-text-no-media

install with `composer require evanshunt/carbon-fields-rich-text-no-media:dev-master` or specify a commit.

It's rough and untested, but it seems to meet my needs for the time being.

**Comment by jorostoyanov** [comment]
The Rich_Text_Field supports the `->set_settings()` method, which accepts the same settings like the second argument here -- https://developer.wordpress.org/reference/classes/_wp_editors/parse_settings/
