### ISSUE TITLE
carbon_register_fields breaking change in v1.5

### ISSUE THREAD

**Issue by tschortsch** [htmlburger/carbon-fields#177]
I just to update Carbon Fields from `v1.3` to `v1.5` and all my custom post type fields don't work anymore. After debugging the field registration I found out that the the `carbon_register_fields` action is added to the WP `init` action with a priority of `0` (!).

I always try to encapsulate my custom post types in classes like the following:

```
class MySite_MyPostType {
	public function __construct() {
		register_post_type( 'myposttype', ... );
		add_action( 'carbon_register_fields', array( $this, 'register_fields' ) );
	}

        public function register_fields() {
		// register all custom fields with carbon fields
        }
}
``` 

To initialize the custom post type I do the following in my `functions.php`
```
function mysite_register_post_types() {
	new MySite_MyPostType();
}
// register post types in init action like WP recommends (https://codex.wordpress.org/Function_Reference/register_post_type)
add_action( 'init', 'mysite_register_post_types' );
```

Since the change of the action which is used to register custom carbon fields (https://github.com/htmlburger/carbon-fields/commit/b5c945488e207ec7c02b7843e96f6f2d2ac01571) this doesn't work anymore (As I add my `carbon_register_fields` action too late now). Is there a possibility to keep my object driven approach working (without rebuilding everything)?

Thanks a lot!

**Comment by m1r0** [comment]
Hi @tschortsch and sorry for the inconvenience, this was a necessary change because it fixes some bugs related to the widgets initialization.

I suggest making your class responsible only for post types related things like registration and create another class that should be hooked on `after_setup_theme` for carbon fields initialization. Hope this helps.

Please also check these related issues: https://github.com/htmlburger/carbon-fields/issues/165, https://github.com/htmlburger/carbon-fields/issues/162

**Comment by tschortsch** [comment]
Thanks for your quick answer! I can try to hook `after_setup_theme` to initialize my classes and add the `init` action to register my post type in the constructor which should work.

But this then means you have to register custom fields for a specific post type before the post type itself gets registered. Can't this lead to other problems?

And I think adding an action with the priority `0` should be the really last option to use (like !important in css). Isn't it possible to use a number lower than the default (10)?

**Comment by tschortsch** [comment]
Ah I see maybe this was the problem? 😉 
`add_action( 'init', 'wp_widgets_init', 1 );`

**Comment by m1r0** [comment]
@tschortsch yep, that's the real reason for priority 0 :-)

It shouldn't be a problem for initializing the fields before registering the post types, CF uses the post types in a later state.

**Comment by tschortsch** [comment]
perfect! thanks for the great work!

**Comment by m1r0** [comment]
You are welcome 👍
