### ISSUE TITLE
Header Template PHP Logic

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#179]
I don't know much about how Underscores work, but I was wondering if I could access a wordpress function inside of the `set_header_template` function. For example, I have the following code
`<# if ({$field}) { #>{$prefix}{{ {$field} }}{$suffix}<# } #>`
This will echo the Field if the field isn't empty, along with a prefix or suffix I define elsewhere. What I would like to do is check to see if the Field is an integer, and if so, wrap it inside wordpress `get_the_title( $id )` function, for example to get the name of an image in an image field.

**Comment by atanas-angelov-dev** [comment]
This is currently not supported.
The underscore templates work entirely on the client-side with the field's JavaScript model so PHP cannot be used.
