### ISSUE TITLE
New field type - Image Gallery

### ISSUE THREAD

**Issue by tyxla** [htmlburger/carbon-fields#18]

**Comment by fgilio** [comment]
Hi!
I want to use Carbon Fields in the main project I work on, and this is the one thing that's stopping me today.

IMO it would be awesome to have it work similar to how ACF Gallery does, regarding the admin UI of the field. I have a Pro license of AFC and love it, but I don't like how it clutters the db... plus I'd like to be able to declare all fields in plain PHP.

Please let me know if I can help!

**Comment by atanas-angelov-dev** [comment]
Closing this in favor of #232
