### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#182]
Do y'all have a slack channel or something. I feel like we can get this cooking with fire, but it needs some discussion. I'm willing to contribute in any way that I can.

**Comment by m1r0** [comment]
Hi @dmhendricks,

We are not planning to do a slack channel at the moment, but there is a blog in the works, so stay tuned!

About the discussion - you can share your ideas in here as tickets, so all the community can see them and respond.

**Comment by emohamed** [comment]
We discussed the need to live chat communication and decided to open a gitter channel for Carbon Fields. 

Please sign in here: https://gitter.im/carbon-fields
