### ISSUE TITLE
show_on_post_type and show_on_page not working together always

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#183]
Following setting for meta box isn't working because when using `show_on_page` the post type is forced to page. It should check if there's some post type already set and if not, only then force to page.

```
->show_on_post_type( 'wplf-form' )
->show_on_page( 2048 )
```

Through changing the order makes meta box to work as wanted, I think this should work in either order.

**Comment by m1r0** [comment]
Hi @timiwahalahti,

The `show_on_page` method is intended to work on the `page` post type only, but it's a good idea to maybe implement a `show_on_post` method that can work for all post types.

This discussion can continue in https://github.com/htmlburger/carbon-fields/issues/148.
