### ISSUE TITLE
Error/bug: crbl10n in not defined

### ISSUE THREAD

**Issue by dameer** [htmlburger/carbon-fields#189]
There's some strange error in `/plugins/carbon-fields/assets/js/sidebar-ui.js file ( line 10, col 3 )` causing other widgets not working properly.

For instance, I'm about to use SiteOrigin's Layout Builder widget in footer and it doesn't work because crbl10n in not defined.

![crbl10n_undefined](https://cloud.githubusercontent.com/assets/1826261/21762759/c9a9f74e-d65a-11e6-930c-ac257beab960.png)

**Comment by m1r0** [comment]
Hey @dameer, thanks for reporting this.

It seems that this occurs when you don't have a registered CF Widget.

We are working on a solution at the moment, so stay tuned.

**Comment by atanas-angelov-dev** [comment]
@dameer,

The fix for this is in the latest commit in master (no numbered release, yet)

**Comment by Santana1053** [comment]
For those wanting to see the changes 9031cd82274631db8db33255d1302d8ec598bf8a

**Comment by SmashBrando** [comment]
This bug also happens when using the Sidebar field. Based on the docs, when you've added a sidebar you should be able to delete that sidebar on the widgets page. On a vanilla install of WordPress with just the sidebar field, I get the same error. To resolve this I created a dummy CF widget and the error went away. 

In the context of the custom sidebar, the error prevents the trash icon from appearing.

**Comment by erikjoling** [comment]
First of all I am new to this plugin. It seems like a very useful, developer friendly plugin! Thanks for sharing it. 

I am seeing the same error (master branch) as the topic starter: `ReferenceError: crbl10n is not defined  sidebar-ui.js:10:3`. 

In my case it prevents the Black Studio TinyMCE Widget being added to the widgets overview. 

Will the fix will be included in the next release?

**Comment by atanas-angelov-dev** [comment]
@erikjoling ,

The fix will be included in 2.0 - in the mean time there's a dirty work-around that @SmashBrando mentioned:
> To resolve this I created a dummy CF widget and the error went away.

(IIRC the widget does not need to be registered - it only needs to be defined)

**Comment by erikjoling** [comment]
Ok, thanks :)
