### ISSUE TITLE
Empty row when checkbox is not checked

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#192]
When checkbox is not checked, it should not be saved to database. This is because right now you can't make meta query like below, for getting posts with checked checkbox.

```
'meta_query'  => array(
  array(
    'key'   => '_pool_upsell',
  )
),
```

Instead your forced to do query checking against value, which generates way more expensive database query. `meta_key` is indexed and because of that query against it is much faster.

**Comment by timiwahalahti** [comment]
Actually this comes to bigger question: should empty fields be saved?

I think not, because get_meta returns false if there's no meta with queried key and everyone should check if field is false or empty before trying to use it.

**Comment by atanas-angelov-dev** [comment]
This is very tricky as you can have situations that call for different behaviors. For example, if you have a complex field with a single checkbox left unchecked it will not be saved and then the whole complex entry will disappear as no value is stored ( #47 somewhat related ).

We will be discussing whether adding a flag/value for every complex entry that signifies that an entry exists (so it works even if no values are stored for it) is a viable solution internally (which may open this up  for potential implementation). This also ties in with how getter functions behave as they have no knowledge of the actual field instances and configuration which is another issue that needs to be addressed.

As a dirty work-around for now you can just write an action that removes specific meta/options keys when their values are empty.

**Comment by timiwahalahti** [comment]
Yeah, thanks!

If somebody else needs this quite dirty work-around, here you go. It affects to performance only in admin panel, so it's not that bad when talking about improving performance on client side.

```
function timiwahalahti_no_empty_post_meta_rows( $meta_id, $object_id, $meta_key, $meta_value ) {
  if( !empty( $meta_value ) )
    return;

  $fields_not_to_save = array(
    '_pool_upsell'        => true
  );

  if( isset( $fields_not_to_save[ $meta_key ] ) )
    delete_post_meta( $object_id, $meta_key, $meta_value );
}
add_filter( 'updated_post_meta', 'timiwahalahti_no_empty_post_meta_rows', 50, 4 );
add_filter( 'added_post_meta', 'timiwahalahti_no_empty_post_meta_rows', 50, 4 );
```

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which always stored entry information even if the entry itself is empty or fields inside it have no values.
Also new filters have been added allowing you to control if "empty" values in such cases should be saved to the database at all.

More info here: https://carbonfields.net/docs/advanced-topics-hooks/?crb_version=2-0-0
