### ISSUE TITLE
repeatable fields on widgets

### ISSUE THREAD

**Issue by chrismccoy** [htmlburger/carbon-fields#195]
this would be a cool feature, or is this already possible?

**Comment by elvishp2006** [comment]
Yes, this is already possible: D

**Comment by chrismccoy** [comment]
do you happen to have a gist or example i can see?

**Comment by elvishp2006** [comment]
Yes, follow example links:
https://carbonfields.net/docs/containers-widgets/
https://carbonfields.net/docs/complex-field-usage/

If you can not, I can make a functional example.

**Comment by chrismccoy** [comment]
mind sharing a functional example?

**Comment by elvishp2006** [comment]
```php
<?php
use Carbon_Fields\Widget;
use Carbon_Fields\Field;

class Featured extends Widget;
{
	public function __construct()
	{
		$this->setup(
			'Deugame - Featured',
			esc_html__( 'Display featured posts', 'slug' ),
			array(
				Field::make( 'complex', 'title', esc_html__( 'Title', 'slug' ) )
					->add_fields(
						array(
							Field::make( 'image', esc_html__( 'Title', 'slug' ) ),
						)
					)
			)
		);
	}

	public function front_end( $args, $instance )
	{
              //Your markup
	}
}
```

**Comment by chrismccoy** [comment]
thanks that was helpful

**Comment by chrismccoy** [comment]
is it possible to make one appear, then click to add one more, right now the repeatable shows none, and to click to add one, anyway to make the first one visible, then to add more ?

**Comment by elvishp2006** [comment]
Has a feature request for this: https://github.com/htmlburger/carbon-fields/issues/158

**Comment by atanas-angelov-dev** [comment]
Closing in favor of #158
