### ISSUE TITLE
PHP v7.0.14 support

### ISSUE THREAD

**Issue by DeLuccaBeauty** [htmlburger/carbon-fields#196]
I just upgraded to PHP v7.0.14 and found out that there was in issue with the carbon fields plugin. I had to disable it to allow the website to function.

I am running WP 4.7.1, PHP 7.0.14, and mySQL v 5.6.34.

My VPS hosting provider gave me the following information from the log:
[23-Jan-2017 22:07:57 UTC] PHP Fatal error: Uncaught Error: Call to undefined function Carbon_Fields\Field\mb_strtolower() in /home/delucca/public_html/wp-content/plugins/carbon-fields/core/Field/Field.php:391
Stack trace:
#0 /home/delucca/public_html/wp-content/plugins/carbon-fields/core/Field/Field.php(201): Carbon_Fields\Field\Field->set_name('gruppo_bot_resp...')
#1 /home/delucca/public_html/wp-content/plugins/carbon-fields/core/Field/Field.php(180): Carbon_Fields\Field\Field->__construct('gruppo_bot_resp...', 'Response Method')
#2 /home/delucca/public_html/wp-content/plugins/carbon-fields/core/Field.php(18): Carbon_Fields\Field\Field::factory('Radio', 'gruppo_bot_resp...', 'Response Method')
#3 /home/delucca/public_html/wp-content/plugins/carbon-fields/core/Field.php(27): Carbon_Fields\Field::factory('radio', 'gruppo_bot_resp...', 'Response Method')
#4 /home/delucca/public_html/wp-content/plugins/wp-messenger-bot/includes/fields.php(23): Carbon_Fields\Field::make('radio', 'gruppo_bot_resp...', 'Response Method')
#5 /home/delucca/public_html/wp-inc in /home/delucca/public_html/wp-content/plugins/carbon-fields/core/Field/Field.php on line 391

**Comment by atanas-angelov-dev** [comment]
Hi @DeLuccaBeauty ,

You will need to enable the php_mbstring extension in your `php.ini`. PHP 7 ships with it but it probably is disabled by default.
