### ISSUE TITLE
Storing fields in an array to use in multiple containers

### ISSUE THREAD

**Issue by schrapel** [htmlburger/carbon-fields#197]
I have fields in a complex field that are used in multiple containers. Basically individual modules in a module container and depending on the post type or page has access to different modules. When I register fields outside of add_fields and reference the array value inside add_fields when I save the field it will not save any values.

Has anyone experienced this?

**Comment by atanas-angelov-dev** [comment]
This is a known limitation right now where you cannot have the same field instances referenced in multiple containers.

An easy work-around is to put all your shared field generation code in a function and pass the result of it to `add_fields()` like this:
```
function get_shared_fields() {
	return array(
		Field::make( 'text', 'my_text_field', 'My Text Field' ),
	);
}

Container::make( 'post_meta', __( 'Post Options', 'crb' ) )
	->add_fields( get_shared_fields() );
```
This way the function returns new instances every time you call it.
