### ISSUE TITLE
custom post types not yet registered on carbon_register_fields

### ISSUE THREAD

**Issue by mrksdiehl** [htmlburger/carbon-fields#198]
In a plugin I let the user decide for which post types he wants to enable the custom meta boxes. For that I use `get_post_types` and use it to populate the options of the set field.
In previous versions of carbon fields this worked without problems. Now, with the new implementation of `carbon_register_fields` action, my custom post types are not registered yet and obviously do not show up as an option.
When manually changing the priority in the constructor of Helper and playing with the priority number, the post types show up.

    add_action( 'init', array( $this, 'trigger_fields_register' ), 20 );

I see no possibility to manually change the priority without changing it in the plugin core.

Did I do something wrong? Can I use another action hook?

**Comment by atanas-angelov-dev** [comment]
When loading options for use into fields such as Select, Set etc. it is always a good idea to pass a callable instead of the final array. This way the options are only loaded when they are needed and not on every page load. The additional benefit in your case will be that they are not loaded when you register the fields but when they are prepared for output (much later than the `init` action).

Here's an example:
```
function get_select_options() {
	$options = ...
	return $options;
}

...

Field::make( 'select', 'select_field' )
	->add_options( 'get_select_options' )
```

**Comment by mrksdiehl** [comment]
Thank you very much for the tip. Indeed that solves my problem. I really appreciate your help on this one. Thanks!

**Comment by pablo-sg-pacheco** [comment]
This is gold, thanks :)

**Comment by pablo-sg-pacheco** [comment]
But I found a problem. If you save the post_types in a 'multiselect' field, you can't get it later with the `carbon_fields_register_fields()`. Even if you use the proper hook `carbon_fields_register_fields` to create the fields.

Actually, you can get it, but only the first result is returned. However, as I'm using a multiselect I need all of them.
