### ISSUE TITLE
Custom validation/Getting the Backbone model

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [htmlburger/carbon-fields#199]
I'm new to Carbon Fields. I'm writing about an issue that has bothered me to no end and even caused me to ditch Carbon Fields in favor of Piklist for a while. Piklist has support for custom validation and error messages, but it does not support repeatable fields with a length of zero. Because I need repeatable fields with a length of zero, I am back to Carbon Fields.

That being said, I still need custom validation and error messages. I understand that all validation is done with JavaScript. That does not stop me. I am even more versed in JavaScript than I am in PHP. I also understand that the data binding in JavaScript is done through Backbone, a model-view-controller framework similar to AngularJS. My question is: How do I get to a Backbone model that stores not only field values, but error messages and error states as well?

**Comment by atanas-angelov-dev** [comment]
Hi @ssimo3lsuhsc ,

Can you share more details about what kind of validation you need:
1. A new custom field type which extends an already existing one but adds a custom validation rule?
2. Allow any type of field to have a validation callback (or similar solution) for custom validation?
3. Something else completely?

**Comment by ssimo3lsuhsc** [comment]
Either a new custom field type that extends an existing one OR allowing any field type to have custom validation would make it work. The validation would return the error message to display, or else the Boolean value “true.” You can specify whether the validation should be done in Javascript or PHP as long as it is documented how to access other Carbon Fields post meta within the function.

Stuart Simon
Graphics Specialist
LSU Human Development Center
411 S Prieur St
New Orleans, LA  70112
http://www.hdc.lsuhsc.edu/

**Comment by pkostadinov-2create** [comment]
Hi @ssimo3lsuhsc ,

If you need to create a custom field with custom validation, you can check the next 2 resources:

1. You can follow the template for new Carbon Field from this repo:
   https://github.com/htmlburger/carbon-field-template
2. You can check how the Carbon Fields JS handles validation from the following pull request:
   https://github.com/htmlburger/carbon-fields/pull/77/files

However, please note that there is under development a full JavaScript rewrite with react, which will deprecate your code in some time.

It might be helpful for your case to check the #167 pull request which introduces similar functionality.

**Comment by ssimo3lsuhsc** [comment]
I think I understand. I thought React wasn’t MVC and so did not go well with the mental image I had given the fact that the PHP of Carbon Fields relies heavily on nested associative arrays. I’m hoping that the React implementation of Carbon Fields can expose documentation about the elements placed in the DOM and how to use JQuery to access them. And please be sure to document how to get the number of items in a complex field.

Stuart Simon
Graphics Specialist
LSU Human Development Center
411 S Prieur St
New Orleans, LA  70112
http://www.hdc.lsuhsc.edu/

**Comment by ssimo3lsuhsc** [comment]
I’m willing to share at this point what I’m trying to accomplish. If my e-mail server will let me, I will attach a PHP file that contains the code for my Carbon Fields meta boxes and the validation that I need. I understand the mechanics of validating fields by relating them to fixed values. What I need is to expose the mechanics of how to validate fields against other related fields, whether those fields be children, parents, siblings, uncle and nephew, or cousins in the DOM.


Stuart Simon
Graphics Specialist
LSU Human Development Center
411 S Prieur St
New Orleans, LA  70112
http://www.hdc.lsuhsc.edu/

From: Simon, Stuart A.
Sent: Tuesday, January 31, 2017 11:00 AM
To: 'htmlburger/carbon-fields' <reply@reply.github.com>
Subject: RE: [htmlburger/carbon-fields] Custom validation/Getting the Backbone model (#199)

I think I understand. I thought React wasn’t MVC and so did not go well with the mental image I had given the fact that the PHP of Carbon Fields relies heavily on nested associative arrays. I’m hoping that the React implementation of Carbon Fields can expose documentation about the elements placed in the DOM and how to use JQuery to access them. And please be sure to document how to get the number of items in a complex field.

Stuart Simon
Graphics Specialist
LSU Human Development Center
411 S Prieur St
New Orleans, LA  70112
http://www.hdc.lsuhsc.edu/

**Comment by AlexBa** [comment]
Custom validation for existing fields would be great. Unfortunately, the users in my project get stucked without proper validation. 

For instance: In my project there is a part where the user can create custom taxonomies with the help of complex fields. The internal taxonomy name is only allowed to contain lower cases characters, _ and some more special characters. - is not allowed, but that's what they often enter...

<img width="799" alt="screenshot 2017-05-17 21 21 06" src="https://cloud.githubusercontent.com/assets/7062807/26171870/c834598a-3b46-11e7-9fae-e1d6fd418513.png">

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which allows you to hook into forms' submit event (normal jQuery usage) and add your own client-side validation by utilizing the new JavaScript API to get/set field values, for example.
More info here: https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-0-0

**Comment by ssimo3lsuhsc** [comment]
I have seen and read both the pages about Custom Validation and the JavaScript API, and can only conclude that you have not tested it using the behavior of an end user. The MOST IMPORTANT THING TO ENSURE in custom validation from a user's point of view is that they can see error messages with their own eyes. You have already done this with built-in validation. In order for custom validation to be user-friendly, your API needs to expose the methods that add, remove, show, and hide error messages on particular fields.

**Comment by ssimo3lsuhsc** [comment]
I am going to see if after I type this and click the "Comment" button, I can reopen the issue. At some point I expect to see .addError(field, msg) and .removeError(field, msg) or something similar.
