### ISSUE TITLE
What is the best way to contribute a new translation?

### ISSUE THREAD

**Issue by metaodi** [htmlburger/carbon-fields#2]
I would like to use carbon fields for a German project. Therefore I'd like to add a German translation.

Of course I could simply download the pot file and contribute the new translation. I just wanted to ask if you considered to use a service like [Transifex](https://www.transifex.com/)? I really like the interface they provide, plus it enables the community to update and contribute translations with minimal effort.

**Comment by htmlburger-git** [comment]
Hi @metaodi,

Thanks for your interest! We're short in translations, so we could really use some.

At this time we're not using any additional translation service. Carbon Fields is a free, open-source plugin and therefore using the traditional translation methods.

The best way to contribute a translation right now is:

1. Fork the repository in GitHub.
2. Use the `.pot` file and create your own `.po` and `.mo` files in the language you're translating to.
3. Commit the new `.po` and `.mo` files in your fork repo.
4. Submit a Pull Request with your contributions.

We'll review your contributions, and if everything is fine, we'll merge it into the plugin core.

In one of the next versions, we'll make the plugin community-translation-friendly, so it will be easy to translate here: https://translate.wordpress.org/projects/wp-plugins/carbon-fields

Thanks in advance. We really appreciate any contributions.
