### ISSUE TITLE
Conditional field inside Complex field

### ISSUE THREAD

**Issue by daviddcarr** [htmlburger/carbon-fields#200]
I'm trying to create a container with nested complex fields with conditional logic throughout. In the first layer the user has the option to select a module / layout. After trial and error I've found that conditional logic within the second (nested) complex field doesn't seem to work if it references something one level above. 

Here's an example of part of my code: 

```
Container::make('post_meta', 'Page Modules')
  ->add_fields(array(
    Field::make('complex', 'crb_modules')
      ->add_fields(array(
        Field::make("select", "crb_module", "Select Content Module")
          ->add_options(array(
            'a' => 'Module A',
            'b' => 'Module B'
          )),
        Field::make('text', 'header', 'Main Header'),
        Field::make('rich_text', 'content', 'Main Content')
          ->set_conditional_logic(array(
              array(
                'field' => 'crb_module',
                'value' => 'b',
                'compare' => '=',
              )
          )),
        Field::make('complex', 'upper_list', 'List Content')
          ->add_fields(array(
            Field::make('text', 'list_header', 'Main Header'),
            Field::make('rich_text', 'list_content', 'Main Content')
              ->set_conditional_logic(array(
                  array(
                    'field' => 'crb_module',
                    'value' => 'b',
                    'compare' => '=',
                  )
              ))
          )),
        )),
  ));
```

When I remove the `set_conditional_logic()` from list_content the nested complex field works fine so I'm assuming it has to do with the 'crb_module' reference.  

I'm not sure if there's a way around this issue without creating multiple complex fields instead. If someone can explain how to make this work I'd greatly appreciate it. 

Edit: I didn't mention this, but when `set_conditional_logic()` is applied, and the user clicks 'Add Entry' on the nested complex field, it adds a container as expected, but only the labels are displayed (for all fields within that container, including the ones without conditional logic.)

Thanks!

**Comment by atanas-angelov-dev** [comment]
hi @daviddcarr ,

At this time, conditional logic is limited to the current level only (i.e. to sibling fields).

An alternative solution would be to take advantage of complex groups like this:
```php
Container::make('post_meta', 'Page Modules')
  ->add_fields(array(
    Field::make('complex', 'crb_modules')
      ->add_fields( 'module_a', 'Module A', array(
        Field::make('text', 'header', 'Main Header'),
        Field::make('complex', 'upper_list', 'List Content')
          ->add_fields(array(
            Field::make('text', 'list_header', 'Main Header'),
          )),
      ))
      ->add_fields( 'module_b', 'Module B', array(
        Field::make('text', 'header', 'Main Header'),
        Field::make('rich_text', 'content', 'Main Content'),
        Field::make('complex', 'upper_list', 'List Content')
          ->add_fields(array(
            Field::make('text', 'list_header', 'Main Header'),
            Field::make('rich_text', 'list_content', 'Main Content'),
          )),
      )),
  ));
```

**Comment by daviddcarr** [comment]
This works perfectly, thanks for taking the time to reply!
