### ISSUE TITLE
Multiple inputs in field

### ISSUE THREAD

**Issue by schrapel** [htmlburger/carbon-fields#202]
I've created a new field and I want the field to have multiple inputs. How do I get a different id, name, value for each input? And presumably pull through an array with get_post_meta.

Is this possible?

----

Sorry for posting it as an issue but couldn't find anything in the documentation

**Comment by atanas-angelov-dev** [comment]
If you are looking to have a fixed number of fields you can just register them separately like so:
```php
...
Field::make( 'text', 'crb_text_1', 'Text 1' ),
Field::make( 'text', 'crb_text_2', 'Text 2' ),
Field::make( 'text', 'crb_text_3', 'Text 3' ),
...
```
Here you'll have to use `carbon_get_post_meta()` (or just `get_post_meta()`) for every field.

If you want the user to have unlimited number of text fields with an "Add more" button you can use a complex field like so:
```php
...
Field::make( 'complex', 'crb_text_fields', 'Text Fields' )
	->add_fields( array(
		Field::make( 'text', 'text', 'Text' ),
	) ),
...
```
Here you can use `carbon_get_post_meta( $post_id, 'crb_text_fields', 'complex' )` to pull all values.

You can read more on Complex_Field [here](https://carbonfields.net/docs/complex-field-usage/) (including limiting min and max number of entries etc.).

**Comment by schrapel** [comment]
@atanas-angelov-dev Sorry, I must have worded that badly.

I have created a new field type. I want that field type to have multiple inputs. The field template uses {{id}}, {{name}}, {{value}}, etc.

So I'd want to have {{id-field1}}, {{id-field2}} etc

**Comment by pkostadinov-2create** [comment]
Hi @schrapel ,

Essentially you can have 1 hidden field, which holds the serialized string, and use JS to build everithing else.

You could also experiment with json data, which would be easier to handle in JS.

If you need a carbon fields core example, You can take a closer look into our "Map" field, which does simmilar thing - we store "lat", "lng", "address", "zoom". The values are stored as suffixed entries to the main field key.

**Comment by schrapel** [comment]
@pkostadinov-2create Thanks. I'll check that out
