### ISSUE TITLE
Won't work with page builder

### ISSUE THREAD

**Issue by estudiooka** [htmlburger/carbon-fields#204]
Widgets won't show on the page builder panel, probably because is not loading the script.

**Comment by atanas-angelov-dev** [comment]
Hi @estudiooka ,

We haven't looked into adding Page Builder support specifically, yet.
I'll update this ticket if/when support gets added in.

**Comment by jorostoyanov** [comment]
This ticket is now outdated.

If you need support for specific page builder, open a new issue, so we can discuss there :-)
