### ISSUE TITLE
Disable visual editor is not respected by rich text fields

### ISSUE THREAD

**Issue by halvardos** [htmlburger/carbon-fields#207]
If a user has set the " Disable the visual editor when writing" option I would expect that to also apply to carbon-fields rich text fields.

Super annoying when the editor removes whitespace and changes your input for all fields in a complex field when you save.

**Comment by atanas-angelov-dev** [comment]
Hi @Jeger ,

Thanks for the report! Hopefully this will make it into 2.0.

**Comment by Jeger** [comment]
Cool! Thanks again for creating an awesome plugin :)

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which now respects the setting in question.
