### ISSUE TITLE
The Text Field™

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#209]
Given that this is free as in beer and speech, I love it. That said...

Why is such a basic field like Text so... terrible? Obviously, it would be nice to be able to specify a type, but at the very least, ->add_class() and ->set_required(). I submitted a pull request for that, but was rejected (so my branch is now ancient; whatev). That doesn't bother me (really - I'm not the best developer by far... I just want stuff to work) - I don't understand why I can't do anything with such an essential field. (?)

As it is, if I want to manipulate the field, I have to do some jQuery wizardry. Can we not at least have the ->add_class() so that it is easier to make swell? At least then I can do a .bind() (more easily) and mess it up in whatever way that I want...

(And yes, I can fix it myself. However, when I write a custom plugin for someone, I prefer to reference official releases of libs that I use. Nobody lives forever.)

As I said, I enjoy using CF, better than CMB2 (which is ok, but it's not my style). ACF Pro is king, but there are licensing issues. Your product is our best hope!

By the way: thank you for your work. I *really* do think that you are on the only logical direction.

EDIT: Also, CF is easy to load via Composer. Yes, I can load ACF via Composer, but it is atypical.

**Comment by atanas-angelov-dev** [comment]
Hi @dmhendricks ,

I just checked and `master` has `Field::add_class()` and `Field::set_required()` methods which do exactly what you need them to (and all fields inherit these methods).

Let me know if I'm missing anything or if they are not working for you.
