### ISSUE TITLE
User Meta Container shows only for "administrator" role

### ISSUE THREAD

**Issue by stsdc** [htmlburger/carbon-fields#21]
In my installation I have 3 roles: `administrator`, `member` and `ex_member`.
Some fields I want to show for all of them, and some only for `administrator` role.
Tried to `->show_on_user_role('member')`, but It doesn't show for user with `member` role.

**Comment by tyxla** [comment]
Hi @stsdc,

There is usually a slight confusion of what `show_on_user_role()` does. 

It basically determines whether to show the custom fields based on the current user that you're editing. And some people expect it to check the role of the currently logged in user (which it doesn't). 

Let me clarify further. The user meta fields will be displayed if any numeric and alpha rules from below apply together (e.g. "A and 1", "A and 2", "B and 1", "B and 2"):

A. The currently logged in user is editing their own profile.
B. The currently logged in user has the `edit_users` capability.

1. No `show_on_user_role()` is used
2. The user that you're currently editing has the role that is specified in `show_on_user_role()`.

Please, let me know if you need further help.

**Comment by georgeHtmlBurger** [comment]
@stsdc,

You can try wrapping the codeblock where you're registering the fields themselves in an if, checking whether the user meets your criteria (by using `current_user_can()` for example).

So simply do not register the Carbon Fields if the current user should not see them.

**Comment by stsdc** [comment]
Thank You for Your answers, they clarify how It should work, but this code doesn't work for me:

    add_action('carbon_register_fields', 'crb_register_member_images');
    function crb_register_member_images(){
        include_once dirname(__FILE__).'/profile-images.php';
    }
In `/profile-images.php` I have:

    <?php
    use Carbon_Fields\Container;
    use Carbon_Fields\Field;

    Container::make('user_meta', 'Photos & Images')
        ->add_fields(array(
        Field::make('image', 'crb_member_profile_image', 'Profile image')
            ->set_value_type('url')
        Field::make('image', 'crb_member_cover_image', 'Cover image')
            ->set_value_type('url')
    ));
If I have understood right, those fields should display for every user, that edits his profile. 
But in my case, they are showing up only for administrator, or for the role with `edit_users` capability.

**Comment by tyxla** [comment]
Makes sense, thanks for taking the time to explain in detail.

The issue has been fixed (https://github.com/htmlburger/carbon-fields/commit/52a193a0143c9ae949dd6c700b340d4fa30d30ad) and will be included in the next version. 

Feel free to use the latest `dev-master` if you need this as hotfix in your project.

Thank you!

**Comment by danielezerosi** [comment]
@tyxla i have latest version (3.5.1) and i have same issue. Admin see the field for all users, but if i login with user (editor role) i can't see field

**Comment by tyxla** [comment]
Hey there, thanks for the ping, but I'm no longer working on this library. Also, this was 7 years ago, so something might have been broken in the meantime.
