### ISSUE TITLE
Theme instead plugin

### ISSUE THREAD

**Issue by kulczy** [htmlburger/carbon-fields#211]
Is it possible to use Carbon Fields directly in theme structure instead separate plugin?

**Comment by elvishp2006** [comment]
Yes, you can use the composer for it, this a example of a composer.json file:
```json
{
    "type": "project",
    "require": {
        "htmlburger/carbon-fields": "dev-master",
    },
    "extra": {
        "installer-paths": {
            "vendor/{$vendor}/{$name}/": ["type:wordpress-plugin"]
        }
    }
}
```

**Comment by kulczy** [comment]
Great ;) Can you also tell me how to init this package in my theme, I will be very grateful!

**Comment by elvishp2006** [comment]
* Install the [composer](https://getcomposer.org/);
* Execute the ```composer init``` command into your theme folder;
* Change the ```composer.json``` according to the example I gave you above;
* Run the ```composer install``` command;
* In your functions.php add the following code: ```include 'vendor/autoload.php';```;

**Comment by kulczy** [comment]
Thank you vary much :)
