### ISSUE TITLE
Template Specific Fields Disappeared After upgrading to v1.5

### ISSUE THREAD

**Issue by Jpwaldstein** [htmlburger/carbon-fields#212]
I had template specific page fields that disappeared after upgrading from v1.4 to v 1.5.  The front end is still rendering but all the fields are not visible in the backend.  Everything was working properly before the update, so I know it is the culprit.

**Comment by elvishp2006** [comment]
Try clearing your browser's cache, I had a similar problem.

**Comment by Jpwaldstein** [comment]
@elvishp2006 thanks but that did not resolve.  I had to downgrade to v1.4 for now.  If anyone else has any ideas, I would appreciate a response.

**Comment by emohamed** [comment]
Could you please share the field definition code?

**Comment by Jpwaldstein** [comment]
Yes, Here are the 2 templates that disappeared:

https://gist.github.com/Jpwaldstein/d48498141ca74146e2efc8bcfd2bea91
https://gist.github.com/Jpwaldstein/aef198aaa1911b02fd365dfb37eacfb3

**Comment by atanas-angelov-dev** [comment]
Hi @Jpwaldstein ,

1.5 introduced a backwards compatibility breaking change when defining templates. Simply add
`->show_on_post_type( 'page' )` to the containers to resolve the issue.

**Comment by Jpwaldstein** [comment]
@atanas-angelov-dev awesome that did the trick.  Thanks so much!

**Comment by Santana1053** [comment]
I still think that if you do not specify the post type when constructing the container, it should default to page. There is a ton of legacy code that did not infer the page post type that no longer works.
