### ISSUE TITLE
Options Page and WPML

### ISSUE THREAD

**Issue by leurdo** [htmlburger/carbon-fields#214]
Hello and many thanks for great plugin! Loved and used in every project.
Just asking for one enhancement: it seems like Options Page fields can not be translated with WPML plugin.  Now I have to make several options pages, one for every language.
Please, consider adding this functionality!

**Comment by dmhendricks** [comment]
I have a feel this is a lower priority, but I would like to add a +1 for WPML support!

**Comment by pkostadinov-2create** [comment]
Theme Options are easily extendable. You can check this sample code:

https://github.com/pkostadinov-2create/Snippets/blob/master/Php-Snippets/wpml_theme_options.sublime-snippet

**Comment by atanas-angelov-dev** [comment]
Direct WPML support for theme options will not be implemented in core at this time.
However, we've added a documentation page dedicated to this problem with a simple solution:
https://carbonfields.net/docs/advanced-topics-wpml-support/?crb_version=2-0-0
