### ISSUE TITLE
Containers > Nav Menu

### ISSUE THREAD

**Issue by yooka102** [htmlburger/carbon-fields#216]
Containers> Nav Menu does not work with the Menu Icons plugin
Sorry nothing works with this plugin: Menu Icons.
Sorry for that

**Comment by yooka102** [comment]
Sorry nothing works with this plugin: Menu Icons

**Comment by pkostadinov-2create** [comment]
Hello,

As a quick fix, you can use the `Icon` field as a replacement to the plugin.

You can check the `Icon` field here:
https://bitbucket.org/htmlburger/carbon-field-icon.git
or use `composer require htmlburger/carbon-field-icon`

In addition to including the field, you will need to add some styling, and some code for printing the icon in front-end (probably hook the `nav_menu_item_title` similar to the example here: https://carbonfields.net/docs/containers-nav-menu/ *(at the end of the page)* ). The `Icon` field has support for dashicons and Font Awesome integrated, and the ability to setup your own icons.

**Comment by yooka102** [comment]
I did not know that field icon exist. thx

**Comment by dameer** [comment]
It doesn't exist in official plugin release, it only exists with a bunch of other bug fixes and new fields as a master branch.
Not sure why it takes so long to push at least minor update, at least the one that affects WP widgets ( https://github.com/htmlburger/carbon-fields/commit/9031cd82274631db8db33255d1302d8ec598bf8a ). By me, CF is useless with that bug left open coz it affects entire WP widgets system (and Customizer).
