### ISSUE TITLE
richtext type not save <p> tag

### ISSUE THREAD

**Issue by sanjayatony** [htmlburger/carbon-fields#217]

**Comment by dameer** [comment]
Neither does WordPress' text editor. More precisely, WordPress automatically converts line breaks into paragraphs and new lines into line breaks.

**Comment by sanjayatony** [comment]
but WordPress will add <p> in the front end.
my solution for this I addig '<p class>' to make it add <p>

**Comment by dameer** [comment]
That's exactly what I wrote... all of the line breaks (Enter) and new lines (Shift + Enter) are automatically converted into `<br />` or `<p></p>` correspondingly on front-end so you don't need to take care about HTML.

**Comment by sanjayatony** [comment]
hmm weird, on my end all my `<p>` gone..let me check again. Thanks for your time and your plugin is awesome!

**Comment by pkostadinov-2create** [comment]
What you are experiencing with missing P tags is the MCE feature that removes them, in order to save space in DB, and reduce request size. The main WP editor works the same way, and adds the tags back just before printing the content by applying filter, to which the wpautop function is attached.

Simply put - you can try either `the_content` filter, or `wpautop` function:

```
echo apply_filters( 'the_content', carbon_get_the_post_meta( 'field_key' ) );
```

or:

```
echo wpautop( do_shortcode( carbon_get_the_post_meta( 'field_key' ) ) );
```

**Comment by sanjayatony** [comment]
works like a charm! thanks a lot

**Comment by Obvio** [comment]
hi thanks for this great plugin! I wanted to ask you to reopen this bug since it doesnt work for a rich_text field inside a complex field.

**Comment by atanas-angelov-dev** [comment]
@Obvio can you please expand on what you mean by "doesn't work in a complex field" (e.g. p/br tags are not replaced in the rich text field or p/br tags are not outputted in the front-end etc.)?

**Comment by Obvio** [comment]
exactly, consider this structure:
```
Field::make( 'complex', 'activities' )
     ->add_fields( 'panel', [
	     Field::make('text', 'title', 'Title' ),
	     Field::make( 'complex', 'children' )
	          ->add_fields('connected_items', [
		          Field::make('text', 'subtitle', 'Subtitle' ),
		          Field::make('rich_text', 'description', 'Description' ),
	          ])]);
```
p/br are not outputted on the frontend (strong/em/ul are ok as far as i can tell).
thanks!

**Comment by atanas-angelov-dev** [comment]
p/br tags will be skipped when using WordPress' TinyMCE - you must use a suitable filter (e.g. `the_content`) or `wpautop()` as mentioned in other messages in this thread.

**Comment by Obvio** [comment]
right, i understood that, but since i'm getting everything using `$panels = carbon_get_post_meta(get_the_ID(), 'activities', 'complex');` those fields are already contained in this array.. 

in my setup this `$panels` is then json encoded and fed into JS so I'm not looping on them again.

**Comment by atanas-angelov-dev** [comment]
Then there is no bug - values are without p/br tags as expected regardless of whether you are getting a simple rich text field or a rich text inside a complex field.

Once you get a rich text field's value it is your code's resposibility to filter it as per your needs.
This means that you will have to modify the returned array and pass whichever array values you need through the mentioned filter or function **before** encoding it into json.

**Comment by Obvio** [comment]
got it, thanks!
