### ISSUE TITLE
Order post according to 

### ISSUE THREAD

**Issue by joelschmid91** [htmlburger/carbon-fields#219]
Hey guys!

Is there a way to order the posts which I get with the _get_posts_ function depending on a carbon field?

```
$args = array( 'posts_per_page' => 5, 'offset'=> 0, 'category' => $settings->tax_post_category, 'orderby' => 'crb_ws-id', 'order' => 'DESC' ); ?>
$myposts = get_posts( $args );

```

Thank you in advance for your help!

**Comment by atanas-angelov-dev** [comment]
Hi @joelschmid,

Let me know if this is the correct situation you have:
1. You have the `crb_ws-id` field added to all posts
2. You wish to pull all posts and order them based on the value they have in their `crb_ws-id` field

To achieve the above use this:
	
```php
$args = array(
	'posts_per_page' => 5,
	'offset' => 0,
	'category' => $settings->tax_post_category,
	'meta_key' => '_crb_ws-id', // NOTE: don't forget the leading underscore - meta keys are stored with an underscore prepended to the field name
	'orderby' => 'meta_value_num', // NOTE: change to 'meta_value' if the values in crb_ws-id are not numeric
	'order' => 'DESC',
);
$myposts = get_posts( $args );
```

**Comment by joelschmid91** [comment]
Perfect!! Thank you for your help!

**Comment by laellsr** [comment]
I needed to order the cpt column and this information helped me a lot! 
Thank you very much!
