### ISSUE TITLE
There is no way to add fields to existing tabs

### ISSUE THREAD

**Issue by carlosrgil** [htmlburger/carbon-fields#222]
I can't find a way to add fields to a tab, so i propose the following change to the add_field method

```php
	public function add_fields( $fields, $tab = null ) {

		foreach ( $fields as $field ) {
			if ( ! is_a( $field, 'Carbon_Fields\\Field\\Field' ) ) {
				Incorrect_Syntax_Exception::raise( 'Object must be of type Carbon_Fields\\Field\\Field' );
			}

			$this->verify_unique_field_name( $field->get_name() );

			$field->set_context( $this->type );
			if ( ! $field->get_datastore() ) {
				$field->set_datastore( $this->store );
			}
		}

		$this->fields = array_merge( $this->fields, $fields );

		if ( !is_null( $tab) && isset( $this->tabs[ $tab ] ) ) {

			foreach ( $fields as $field ) {
				$field_name = $field->get_name();
				$this->tabs[ $tab ][ $field_name ] = $field;
			}

			$this->settings['tabs'] = $this->get_tabs_json();
		
		} 

		return $this;
	}

**Comment by atanas-angelov-dev** [comment]
Hi @carlosrgil ,

Containers with tabs are already supported:  
https://carbonfields.net/docs/containers-tabs/

**Comment by carlosrgil** [comment]
Sorry, i did not explain myself correctly. There is a way to add tabs to containers and you can add fields to tabs when you create them, but there is no way ti add fields to tabs after they have been created, My proposal is to extend the add_fields method to include a parameter to specify the tab where you want the fields added, this way it would allow add fields to already defined tabs and it would be backward compatible.

**Comment by atanas-angelov-dev** [comment]
Adding tabs/fields after the `carbon_register_fields` hook is not supported or advised.
If you have conditional logic that you do not want to put where you define your containers you can pass the container through an action/filter similar to this:

```php
// contianer-definitions-file.php
$container = Container::make( 'post_meta', __( 'My Post Meta Container', 'crb' ) )
	->add_tab( 'Tab 1', array( ... ) );
do_action( 'my_post_meta_container_created', $container );

// file-with-conditional-logic.php
add_action( 'my_post_meta_container_created', 'maybe_add_my_custom_tabs' );
function maybe_add_my_custom_tabs( $container ) {
	if ( $my_condition ) {
		$container->add_tab( 'Tab 2', array( ... ) );
	}
}
```
