### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#223]
Hi, there are some features that are only in `master` (e.g: #44) but I'm not sure how stable is the branch to require directly from there. Is there any plan on doing another release prior to `2.0`? Or, do you consider `master` to be good enough for production?

Thank you!

**Comment by atanas-angelov-dev** [comment]
`master` should be stable (but once 2.0 hits we will merge it there so it's risky to go for `dev-master` in composer) and there's a big chance we'll release a maintenance 1.6 version together with or shortly before 2.0.

**Comment by doup** [comment]
Thanks, for the prompt answer. I think that I'll require directly on a commit, and later on update to `1.6`. 👍
