### ISSUE TITLE
Will Carbon Fields 2 support 1 syntax in PHP?

### ISSUE THREAD

**Issue by AlexBa** [htmlburger/carbon-fields#226]
Hey,
I just have a quick question: Will it be possible to safely upgrade Carbon Fields from version 1 to version 2. Will the method names in PHP stay the same?

**Comment by atanas-angelov-dev** [comment]
Hi @AlexBa ,

2.0 is a major rewrite which brings a multitude of new features and changes so upgrading to 2.0 will require changes to your code - we're already preparing an upgrade guide for this purpose.

**Comment by dameer** [comment]
Holy stool! I'm running like 12 websites and all of them depend on CarbonFields. It sounds like I'm gonna have to cancel my holidays.

**Comment by atanas-angelov-dev** [comment]
There will be a maintenance 1.6 release and even if you stay at 1.5 you're still fine for the foreseeable future. Note that there will be no automatic upgrade to 2.0 if you are using CF as a plugin so end users will not be able to break their sites just by updating their plugins.
More info on this will be available on release.
