### ISSUE TITLE
Conditional logic based on Set field

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#228]
I am trying to create a field that is conditional on the options selected in a Set field.
```
$fields = array(
    Field::make( 'set', 'types' )->set_options( $post_types ),
);
foreach ( $post_types as $key => $name ) {
    $fields = array_merge( $fields, array(
        Field::make( 'relationship', 'type' . $key . '_selector', html_entity_decode( $name ) . ' Projects' )
             ->set_conditional_logic( array(
                 array( 'field' => 'types', 'value' => $key, 'compare' => '=' ),
             ) )
             ->set_required( true ),
    ) );
}
```

With this code, if I select one item in my Set, it shows the correct associated conditional field. However i I select more than one item in the Set, none of my conditional fields show. I have also tried using the IN compare operator

**Comment by atanas-angelov-dev** [comment]
Thanks for the report, @Santana1053 . We'll post an update when we have the chance to investigate the issue.

**Comment by atanas-angelov-dev** [comment]
1.6 has just been released which addresses this situation with the new `INCLUDES` and `EXCLUDES` comparison operators.

In your case, the definition should be updated as follows:
```php
->set_conditional_logic( array(
	array(
		'field' => 'types',
		'value' => $key,
		'compare' => 'INCLUDES'
	),
) )
```

**Comment by gardiner** [comment]
@atanas-angelov-dev I think it is really amazing how quickly you respond to issues like this one. Thanks a lot for your efforts! Is there any way we can support you or show our appreciation?

**Comment by atanas-angelov-dev** [comment]
@gardiner spreading the word and what you enjoy about Carbon Fields is plenty support for us : )

PS:  
I assume you meant to post this in another ticket since this one is from May?

**Comment by gardiner** [comment]
Thanks for your reply :) Honestly, I meant to post my comment in this exact ticket because today I've stumbled upon this problem myself, found the ticket and saw that you posted a solution only 11 days after the original post. And since this has happened several times since using Carbon Fields I just had to thank you right away ;)

Thanks again, I will be going back now to enjoying using Carbon Fields and spreading the word :)
