### ISSUE TITLE
Widget doesn't work in the Customizer

### ISSUE THREAD

**Issue by vauvarin** [htmlburger/carbon-fields#23]
Hello,

I have used the code of your documentation to create a widget, it works well in the widget page but bug in the Customizer.

Tested on a clean WP 4.5 install with no other plugins activated and 2016 theme.
Linux (Ubuntu 16.04 and FF)

See the result in the screenshot joined.

![widget](https://cloud.githubusercontent.com/assets/664089/14887634/ee6018ac-0d56-11e6-86f7-f39a87cf9434.png)

**Comment by tyxla** [comment]
Thanks for reporting! We'll investigate as soon as possible.

**Comment by MiguelSantanaCR** [comment]
I am seeing this is still a bug. Has any progress been made to resolving this issue?

**Comment by m1r0** [comment]
@Santana1053 Not sure if this will make it in the next version, but we will try.

**Comment by khromov** [comment]
+1 would love to see progress on this. With WordPress being more and more centered around the Customizer this is a must-have.

**Comment by JoeHana** [comment]
+1 for proper Customizer Support

**Comment by m1r0** [comment]
Created a [branch](https://github.com/htmlburger/carbon-fields/tree/customizer) for this. Got the rendering to work, but there are still some bugs.

**Comment by VladNov** [comment]
Hey guys,

Please make it happen. Customizer support is a must have.

**Comment by dameer** [comment]
Widgets don't even work with SiteOrigin page builder.

**Comment by galengidman** [comment]
Any updates on this? This is kind of a big deal for my use case. Appreciate all the work on what's really a nice plugin!

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which includes Customizer support for widgets.
