### ISSUE TITLE
Image Gallery Field

### ISSUE THREAD

**Issue by atanas-angelov-dev** [htmlburger/carbon-fields#232]
There is need for a gallery-style field as proposed in https://github.com/htmlburger/carbon-fields/pull/97 by @AlexBa .

**Comment by AlexBa** [comment]
The image gallery is a must have! I already implemented a gallery for [Affilicious](https://github.com/affilicious-theme/affilicious)

Here is some working code based on Carbon Fields 1.x. Maybe you can save some time with it:

- https://github.com/affilicious-theme/affilicious/blob/master/src/common/form/carbon/image-gallery-field.php
- https://github.com/affilicious-theme/affilicious/blob/master/assets/admin/es6/carbon-image-gallery.js
- https://github.com/affilicious-theme/affilicious/blob/master/src/product/setup/product-setup.php#L262

**Comment by atanas-angelov-dev** [comment]
This functionality has been introduced as the new Media Gallery field in 2.1.0:
https://carbonfields.net/docs/fields-media-gallery/?crb_version=2-1-0
