### ISSUE TITLE
Scoping hierarchy for conditional logic

### ISSUE THREAD

**Issue by AlexBa** [htmlburger/carbon-fields#236]
Sometimes there are scenarios, where someone wants to dynamically show or hide fields in complex fields based on another field outside of the complex field. This is not possible in Carbon Fields 1.x. The conditional logic is always scoped. 

Just take a look on the example case below to understand it better. The visible attributes of the product variants in the complex fields are based on the first attribute tags.

<img width="795" alt="screenshot 2017-05-17 21 27 58" src="https://cloud.githubusercontent.com/assets/7062807/26172160/c065a618-3b47-11e7-8824-25f47a3d725f.png">

To make it work, you have to use some hidden fields and write some annoying JS which is hacking into Carbon Fields ;)

I would purpose to introduce a scoping hierarchy. Maybe something like:

```
Field::make($field_type, $field_key, $field_name)
    ->set_required(true)
    ->set_conditional_logic(array(
            'relation' => 'and',
            'scope' => 'global', // default is maybe 'local'
            array(
                    'field' => Carbon_Product_Repository::VARIANT_ENABLED_ATTRIBUTES,
                    'value' => $attribute_template->get_name()->get_value(),
                    'compare' => 'CONTAINS',
            )
    ));
```

By the way: 'CONTAINS' would be great to show or hide fields if a substring is present in the target field (e.g. tags) and is rather simple to implement.

**Comment by dackr** [comment]
Please you can share the total code to achieve this type of fields to study the way you do it thanks

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which allows you to target parent scopes by appending `parent.` to the target field name.
An example is available here: https://carbonfields.net/docs/fields-usage/?crb_version=2-0-0
