### ISSUE TITLE
show_on_page() doesn't work without show_on_post_type('page') first

### ISSUE THREAD

**Issue by xsisqox** [htmlburger/carbon-fields#24]
I am trying to register a container for a page with path "menukort" like this:

```
Container::make('post_meta', 'Allergener og kalorieindhold')
    ->show_on_page('menukort')
    ->add_fields(array(
        // pass
    ));
```

And unless I add `show_on_post_type('page')` before `show_on_page`, the container does not appear on the page.

I expect the container to automatically figure out that it needs to be displayed on a `page` post type, if I tell it to `show_on_page`.

**Comment by tyxla** [comment]
Fixed in: https://github.com/htmlburger/carbon-fields/pull/30
