### ISSUE TITLE
Abiity to choose datastore for complex fields as serialized array.

### ISSUE THREAD

**Issue by MDSilviu** [htmlburger/carbon-fields#244]
It would be great if you would consider adding an option for complex fields to be saved as serialized array in the database in a single field. Most of the time there is no need to have separate meta keys for each field saved in the db since all the data stored in a complex field is usually all needed as a block on a page. This feature would save a lot of db space when there are many complex fields with many sub fields in them.

**Comment by atanas-angelov-dev** [comment]
Hi @MDSilviu ,

2.0 will come with a serialized datastore example which achieves exactly that. I believe this is also doable in 1.6 but we haven't prepared an example for that.

I'll close this ticket in favor of #46 which will be updated once 2.0 is released.
