### ISSUE TITLE
Color Field does not support a method set_default_value

### ISSUE THREAD

**Issue by campusboy87** [htmlburger/carbon-fields#246]
Hello. When using the method set_default_value() the Color Field stops working.

**Comment by atanas-angelov-dev** [comment]
Hi @campusboy87 ,

Could you please share your color field definition code?

**Comment by campusboy87** [comment]
```
<?php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

// Изучаем поле Color

Container::make( 'theme_options', 'Настройки темы' )
         ->add_fields( array(
	
	        Field::make('color', 'my_title_color', 'Цвет заголовка')
			->set_default_value('FF0000')
	        
         ) );
```

**Comment by atanas-angelov-dev** [comment]
Changing `->set_default_value('FF0000')` to `->set_default_value('#FF0000')` will fix the issue for you (the missing leading `#` causes it).
We'll investigate the cause and apply a fix in the next version - thanks for the report!

**Comment by campusboy87** [comment]
I made a stupid mistake! Thanks for the tip.
