### ISSUE TITLE
Checkbox Field does not support a method set_required(true)

### ISSUE THREAD

**Issue by campusboy87** [htmlburger/carbon-fields#247]
Hi. My code:

```
Container::make( 'theme_options', 'Theme Options' )
	->add_fields( array(
		
		Field::make('checkbox', 'user_agreement', 'I accept the terms of the user agreement')
			->set_required(true)
		
	) );
```

But the form is preserved when the check mark is not checked. This is my error or plugin?

**Comment by atanas-angelov-dev** [comment]
It seems this is an issue with the plugin - thanks for the report!

**Comment by atanas-angelov-dev** [comment]
After investigating the cause, it appears required was disabled for checkbox by design. We'll keep this behavior in 1.x for backwards-compatibility reasons but the behavior will change in 2.0 so you can set required if needed.
