### ISSUE TITLE
Why the Set field has no method set_options() ?

### ISSUE THREAD

**Issue by campusboy87** [htmlburger/carbon-fields#248]
For me it was a surprise. Radio Field and Select Field have a method set_options(), although it is not necessary, it can be replaced by a method set_default_value(). But the Set field needs the set_options() method, so that you can set several default values, but it does not. Why?

**Comment by atanas-angelov-dev** [comment]
Hi @campusboy87 ,
The Set field does have set_options and add_options methods - why do you think it doesn't?

**Comment by campusboy87** [comment]
```
Container::make( 'theme_options', 'Настройки темы' )
         ->add_fields( array(
	         Field::make( "set", "my_adv", "Расположение блоков с рекламой" )
	              ->set_options( array(
		              'top'     => 'Перед контентом',
		              'sidebar' => 'В сайдбаре',
	              ) )
	              ->add_options( array(
		              'top'     => 'Перед контентом',
		              'sidebar' => 'В сайдбаре',
		              'bottom'  => 'После контента',
	              ) )
         ) );
```

But the default values were not chosen:

![](https://image.prntscr.com/image/6fcb08f392dd4efcadb1654db0ffd495.png)

**Comment by atanas-angelov-dev** [comment]
I think you're confused about what `add_options` and `set_options` do - both just set the available options for the user to select from - `set_options()` removes all previous options while `add_options` appends more options without removing previous options.

The only way to set what options are selected by default is to use `set_default_value()` like this:
```php
Field::make( 'set', 'my_prefilled_set' )
	->set_options( array(
		'one' => 'one',
		'two' => 'two',
		'three' => 'three'
	) )
	->set_default_value( array( 'one', 'three' ) ),
```

This applies to all options-based fields such as set, select etc.

**Comment by campusboy87** [comment]
I thought the set_default_value () and set_options () methods were analogous. Only set_options () for arrays, and set_default_value () for strings. I made a mistake. Thanks for the tips, now everything works. Oh, now I'll have to re-record the video tutorial :-)

**Comment by atanas-angelov-dev** [comment]
No problem - it's our pleasure to help developers with Carbon Fields : )

If you're making a public tutorial feel free to share it in this ticket, if you'd like.
