### ISSUE TITLE
Fail if register more than one widgets with cyrillic titles

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#251]
Core/Widget/Widget.php
in 42 row
`$widget_ID = 'carbon_' . preg_replace( '~\s+~', '_', strtolower( trim( preg_replace( '/[^a-zA-Z0-9]+/u', '', remove_accents( $title ) ) ) ) );`
fixed with
`$widget_ID = 'carbon_' . preg_replace( '~\s+~', '_', strtolower( trim( preg_replace( '/[^\pL\pM0-9]+/u', '', remove_accents( $title ) ) ) ) );`

**Comment by zevilz** [comment]
but fields saving not work

**Comment by zevilz** [comment]
I offer add id parameter in method `setup`

**Comment by zevilz** [comment]
`public function setup( $title, $id, $description, $fields, $classname = '' ) {`
`$widget_ID = 'carbon_' . preg_replace( '~\s+~', '_', strtolower( trim( preg_replace( '/[^a-zA-Z0-9]+/u', '', remove_accents( $id ) ) ) ) );`

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @zevilz !

I've just pushed the fix in the 2.0 branch but in order to preserve backwards compatibility we will not be able to push this in a 1.x release (as this can cause fatal errors for users)
