### ISSUE TITLE
PDF files fields thumbnails

### ISSUE THREAD

**Issue by batz-bar** [htmlburger/carbon-fields#253]
Since 4.7 PDF thumbnails are supported in the media library.
Is it possible to show PDF thumbnail in the field file selector after selected / uploaded? Similar to how image thumbnail is displayed.

**Comment by atanas-angelov-dev** [comment]
Currently only image thumbnails are supported and there are no plans to implement PDF thumbnails at this time.
If PDF thumbnails are implemented in WordPress core then we'll probably add them as well.

**Comment by batz-bar** [comment]
Thanks for the quick reply.
https://make.wordpress.org/core/2016/11/15/enhanced-pdf-support-4-7/

**Comment by atanas-angelov-dev** [comment]
It seems we've missed that feature in the 4.7 changelog - I just pushed thumbnail support for any file that has it (e.g. PDF) to our development branch for 2.0.

Thanks for the suggestion!
