### ISSUE TITLE
set_page_parent() and custom pages

### ISSUE THREAD

**Issue by gtxtymtXYZ** [htmlburger/carbon-fields#254]
Hi.

I have 2 actions: http://imgur.com/a/r6zC5

1 create new page in admin menu:
`add_menu_page('qwe', 'qwe', 'manage_options', 'ref', function() {}, 'dashicons-editor-kitchensink');`

2 create theme options container:
```
Container::make('theme_options', '123')
            ->set_page_parent('index.php') 
```

But if in set_page_parent() paste custom page slug (ref) - this function not working.

**Comment by atanas-angelov-dev** [comment]
Hi @gtxtymtXYZ ,

In 1.6 the set_page_parent does not always behave as expected. It only accepts a Carbon Fields Theme Option container title or a menu slug which ends in `.php`. This means that the work-around for you is to define your menu slug with a `.php` suffix (e.g. `'ref.php'`) and pass that to `set_page_parent()`.

In 2.0 this behavior is fixed and allows for any menu slug.
