### ISSUE TITLE
Is there any way to set the field group header as the text of one of the fields

### ISSUE THREAD

**Issue by MDSilviu** [htmlburger/carbon-fields#256]
I'm using the complex field with the add_fields feature to create some sort of modules
```
Container::make('post_meta', 'Content Modules')
    ->show_on_post_type(array('page'))
    ->add_fields(array(
        Field::make('complex', 'mds_content', __('Content', 'omdesign'))
            ->add_fields( 'p_content', __('Text Block', 'omdesign'), array(
                Field::make('text', 'p-content-title', __("Title", 'omdesign'))
                    ->help_text('Optional, leave blank if the block doesn\'t have a title'),
                Field::make('rich_text', 'p-content-content', __("Content", 'omdesign'))
            ))
            ->add_fields( 'c_caption', __('Text Block Center title & caption', 'omdesign'), array(
                Field::make('text', 'c-caption-title', __("Title", 'omdesign')),
                Field::make('rich_text', 'c-caption-content', __("Content", 'omdesign'))
            ))
    ));
```
Is there any way to set the field group header as the text of one of the fields in that group for example for Text Block when the p-content-title it's added it will be displayed in the template header?
Also i'm using complex fields to select a post and save that post id as meta, is there any way to set the template header for that complex field as the select option html content and not the option value?

**Comment by atanas-angelov-dev** [comment]
Hi @MDSilviu ,

I believe `set_header_template()` is what you need:
https://carbonfields.net/docs/complex-field-setup-methods/

As for the option content instead of value - this is not currently supported.

**Comment by MDSilviu** [comment]
You are correct the set_header_template() works but i did the mistake and use "-" instead of "_" to separate field id works and that's why it wasn't working. 
isn't there any easy possibility to run a function maybe for the header instead of just using one of the fields value?

**Comment by atanas-angelov-dev** [comment]
At this time we are not looking into making templates more complicated than they currently are.

However, we do accept PRs for 2.x versions (1.x versions do not accept feature PRs anymore) so feel free to submit one if you end up implementing a solution for this.
