### ISSUE TITLE
Why is there a field for gravity forms in core?

### ISSUE THREAD

**Issue by mindfullsilence** [htmlburger/carbon-fields#257]
I would think something so specific would be broken out into an extension plugin. Shoot, why even make it gravity forms specific and not just a "post type" field (which really is just the relationship/association field?). All other fields are generic enough to apply to many situations/use cases without dependencies - why the plugin-specific field?

I haven't used your guys' plugin yet but am looking at possibly moving my team over to it from ACF. I certainly don't mean for this to be an attack on your work, it just felt a bit out of place at first glance.

**Comment by atanas-angelov-dev** [comment]
Hi @mindfullsilence ,

First of all, thank you for your interest in Carbon Fields!

As for the Gravity Forms field, it was created a while ago in core out of pure convenience for our internal WordPress development team that uses it - this was even before the plugin went open source.
You are correct that we should probably split it into an extension plugin but it's not a priority right now as we are focused on releasing 2.0.
