### ISSUE TITLE
Theme Options store in post meta

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#259]
I have some theme options that I want to be directly attached to a post. Currently I have the theme option prefixed with the post id. I was wondering if instead of using actual wp_options, if I could use a theme_options container that stores the data in a posts meta.

**Comment by atanas-angelov-dev** [comment]
Hi @Santana1053 ,

This is a special use case that we won't be handling in core.
However, there are 2 possible solutions you can look into:

1. Hook into `carbon_after_save_theme_options` and update the post meta based on the stored values manually
2. Create a new instance of `Post_Meta_Datastore`, assign it the post ID and pass it to all fields of the `theme_options` container.

**Comment by Santana1053** [comment]
Is there any documentation for setting a new datastore?

**Comment by atanas-angelov-dev** [comment]
It appears we haven't added documentation on datastores, however they have a rather simplistic usage:
1. Instantiate a new one with `new Carbon_Fields\Datastore\Post_Meta_Datastore()`
1. Call `->set_id( $post_id )` on it.
1. Assign it to all fields you'd like with `->set_datastore( $datastore )`

**Comment by Santana1053** [comment]
Can I set_datastore to the entire container, or does it have to be done to each field?

**Comment by Santana1053** [comment]
I have done this, but it is not pulling the metadata values
```
$datastore = new \Carbon_Fields\Datastore\Post_Meta_Datastore();
$datastore->set_id( $id );
Container::make( 'theme_options', $location . ' Options' )
         ->set_page_parent( 'edit.php?post_type=' . $id )
         ->set_page_permissions( 'edit_options_' . $id )
         ->set_datastore( $datastore )
```

**Comment by Santana1053** [comment]
The Theme_Options container doesn't prepend an underscore to the meta_key. I tried doing it manually but it is still saving without the underscore
