### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Carbon_Fields\get_file_data()

### ISSUE THREAD

**Issue by wujekbogdan** [htmlburger/carbon-fields#261]
Hey,

I've just installed the Carbon Fields plugin with Composer (`composer require htmlburger/carbon-fields`) and I've the following error:

```
Fatal error: Uncaught Error: Call to undefined function Carbon_Fields\get_file_data() in /my/site/path/carbon-fields/carbon-fields.php on line 8
Error: Call to undefined function Carbon_Fields\get_file_data() in /my/site/path/carbon-fields/carbon-fields.php on line 8
```

It's not a standard WordPress setup. WordPress is installed via Composer thanks to [roots/bedrock](https://github.com/roots/bedrock) (a great tool, btw). So I guess that installing Carbon Fields with composer is not supported or there's some conflict with Bedrock.

It would be good to fix it, Bedrock is a quite popular tool.

---
**UPDATE**

My bad. I've installed Carbon Fields with `composer require htmlburger/carbon-fields` command instead of installing it with the `composer require wpackagist-plugin/carbon-fields` command. Now it works fine :)

**Comment by iljamm** [comment]
How do we install CF 1.6 now that it has been removed from WP plugins repo?

**Comment by emohamed** [comment]
You can still download 1.6 here: https://downloads.wordpress.org/plugin/carbon-fields.1.6.zip

**Comment by iljamm** [comment]
Yes this entails manual installation, I would like to be able to install in via composer. The only approach I see is to fork it, modify plugin's composer.json and require it in my project that way.


On 21 March 2019 at 13:04:39, Emil Mohamed (notifications@github.com) wrote:

You can still download 1.6 here: https://downloads.wordpress.org/plugin/carbon-fields.1.6.zip

**Comment by wujekbogdan** [comment]
> Yes this entails manual installation

You can still install it via composer. You can [specify the version number](https://stackoverflow.com/questions/40914114/how-to-install-a-specific-version-of-package-using-composer) or a [Github tag](https://stackoverflow.com/questions/34784809/how-to-use-a-specific-tag-version-with-composer-and-a-private-git-repository).

**Comment by iljamm** [comment]
Yes one can do that, but then you start getting this error as described in the issue author’s initial post.


On 21 March 2019 at 16:27:41, wujekbogdan (notifications@github.com) wrote:

Yes this entails manual installation

You can still install it via composer. You can specify the version number or a Github tag.
