### ISSUE TITLE
Best way to use CF 2.0 as a plugin?

### ISSUE THREAD

**Issue by galengidman** [htmlburger/carbon-fields#264]
First off, big props to you guys for 2.0 release. Looks like there's a lot of cool stuff there. Carbon Fields is one of the most underrated frameworks for WordPress as far as I'm concerned. Thanks for the hard work.

Obviously since this release has breaking changes, it's not on .org yet. I downloaded the zip of the repo and used that to upgrade the plugin on a local dev environment. Immediately failed due to the missing autoloader files, so I ran `composer install` and that got me going... but also added 2k vendor files to my repo. Will all of these be included in the dist version of this plugin, or is there some kind of toned-down build that will be coming?

Thanks,
— Galen

**Comment by atanas-angelov-dev** [comment]
Hi @galengidman ,

First of all thank you for the kind words - we're really excited about 2.0 as well!

As for the 2k vendor files - you are seeing the development dependencies which are not required for production use (e.g. phpunit, mockery etc.). To skip them use this:
`composer install --no-dev`

This should create a vendor directory with only composer's autoloading and the small composer installer libraries.

**Comment by batz-bar** [comment]
I'm having similar issues as well. When the dist version well be updated in the WordPress plugins repo?
Thanks

**Comment by galengidman** [comment]
@atanas-angelov-dev - Perfect. Thank you!

I'm curious about how this will be distributed too. Seems like the best way would be a second plugin on the repo since it has so many breaking changes. What's the plan?

**Comment by dameer** [comment]
@galengidman totally agreed! I'm maintaining 10+ WP websites and all of them rely on CF. more precisely - an old version of CF.

**Comment by atanas-angelov-dev** [comment]
For the time being we will not be publishing 2.0 in the WordPress plugin repository. 1.x will remain as a maintenance release there while 2.0 will be installable through composer.
