### ISSUE TITLE
Widget setup parameters

### ISSUE THREAD

**Issue by galengidman** [htmlburger/carbon-fields#265]
One breaking change I didn't see mention of in the Upgrade Guide was the addition of the ID parameter in the widget `setup` method. Without adding this, you errors because the 3rd parameter is now `$description` and not `$fields` as was previously the case. I poked around and figured the issue out, but I'm sure others would benefit from having a note about that in the Upgrade Guide.

Thanks,
— Galen

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @galengidman ,

I've updated the docs with the new `Widget::setup()` parameters:
https://carbonfields.net/docs/carbon-fields-upgrade-guide/?crb_version=2-0-0
https://carbonfields.net/docs/containers-widgets/?crb_version=2-0-0
