### ISSUE TITLE
Conflict with Yoast SEO Plugin

### ISSUE THREAD

**Issue by elvishp2006** [htmlburger/carbon-fields#266]
In the last update of the Yoast SEO Plugin, Im getting the follow message on the browser's console:
```only one instance of babel-polyfill is allowed```

I'm using the version 2.0 of Carbon Fields.

**Comment by sachittandukar** [comment]
Hi, 

I am also facing issue with Yoast SEO. With latest version of Yoast SEO and carbon fields 2.0, none of the fields appear on the edit page.
 
I hope it gets fixed urgently. 

I love carbon fields plugin and appreciate all the hard work done by carbon field team to make developers work easier.

**Comment by atanas-angelov-dev** [comment]
2.0.1 has been released which includes a fix for this issue.
