### ISSUE TITLE
Questions about using 2.0 as a plugin

### ISSUE THREAD

**Issue by alixcan** [htmlburger/carbon-fields#268]
Hi,
I'm tring to import new release codes and also tried to use as a plugin but when i tried both ways there was same error
Fatal error: Class 'Carbon_Fields\Carbon_Fields' not found in C:\xampp\htdocs\wp\wp-content\themes\blankslate\admin-folder\carbon-fields\carbon-fields-plugin.php on line 25
thanks for your help and interest.

**Comment by atanas-angelov-dev** [comment]
Hi @alixcan ,

For the time being we will not be releasing 2.0 in the WordPress plugin repository but only as a composer package. Since it's not packaged as a plugin, you will need to manually run "composer install --no-dev" in the Carbon Fields 2.0 directory if you wish to use it as one.

**Comment by chellman** [comment]
For those of us that would rather define our custom fields in a plugin rather than in the theme, what would be the recommended installation procedure? Here's what worked for me.  Once I know, I'll submit a PR over at carbon-fields-docs.

1.  Download the zip from here (I can't update with composer this way, which is a bummer)
2. Place the carbon-fields plugin in WP_CONTENT_DIR/plugins
3. In the plugin directory, `composer install --no-dev`

Then to instantiate it in your custom plugin:

```
<?php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

class MyPlugin {
	private function __construct() {
		add_action( 'after_setup_theme', [$this, 'carbon_fields_load'] );
		add_action( 'carbon_fields_register_fields', [$this, 'carbon_fields_register_fields'] );
	}

	private function carbon_fields_load() {
		require_once(plugin_dir_path(__DIR__) . 'carbon-fields/vendor/autoload.php' );
		\Carbon_Fields\Carbon_Fields::boot();
	}
}
```

**Comment by atanas-angelov-dev** [comment]
Even though it's not distributed as a plugin, 2.0 comes with a plugin loader file - `carbon-fields-plugin.php` - which takes care of initialization so some of the steps are not necessary.

These steps should be sufficient:
1. Download the zip and call `composer install --nodev` OR use `composer require htmlburger/carbon-fields` as the package utilizes composer/installer to position it in the plugins directory.
1. Activate the plugin
1. Write your own plugin just as you have but skip the `carbon_fields_load()` method.

**Comment by chellman** [comment]
I see that the composer_fields_load step isn't needed.  Installing via composer alone doesn't seem to be compatible with the autoloader right now.  For example, I ran `composer require htmlburger/carbon-fields` in the root of my WP installation, and the files were all placed where I think they belong, with vendor in the root and the plugin in the plugins folder.  Problem is, carbon_fields_boot_plugin is only looking in the plugin directory for the autoload file, and of course it's not there.

Maybe the loader could be changed to account for this, something like:

```
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
		require( __DIR__ . '/vendor/autoload.php' );
	} else if (file_exists(ABSPATH . '/vendor/autoload.php')) {
		require_once(ABSPATH . '/vendor/autoload.php');
	}
	\Carbon_Fields\Carbon_Fields::boot();
```

If so, I can submit PRs.

**Comment by chellman** [comment]
If you have a different WP_CONTENT_DIR, you start with a different composer.json so the installer will put the plugin in the right place, instead of creating a wp-content folder.  This is what I used for a content folder that's just called "content".

```
{
    "require": {
        "htmlburger/carbon-fields": "^2.0"
    },
    "extra": {
        "installer-paths": {
            "content/plugins/{$name}/": ["type:wordpress-plugin"]
        }
    }
}
```

**Comment by atanas-angelov-dev** [comment]
> Problem is, carbon_fields_boot_plugin is only looking in the plugin directory for the autoload file, and of course it's not there.

It's only looking there to load it in certain cases (e.g. if used as a plugin where it is packaged with it's own vendor dir) - it's not necessarily the only autoloader that will work.

Here's an example of what I mean:
1. Call 'composer require htmlburger/carbon-fields` in WordPress' root directory (let's call it $root)
1. After the above completes, your vendor directory should be `$root/vendor` and carbon fields should be in `$root/wp-content/plugins/carbon-fields`
1. If you open up `$root/vendor/composer/autoload_psr4.php` you will find this:
```php
return array(
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Carbon_Fields\\' => array($baseDir . '/wp-content/plugins/carbon-fields/core'),
);
```
As you can see the `Carbon_Fields` namespace will properly resolve to `wp-content/plugins/carbon-fields/core` so including `$root/vendor/autoload.php` is enough.

All in all, as long as you install Carbon Fields using composer and you load the generated autoloader, Carbon Fields will be loaded correctly (even if there is no autoloader in it's own directory).

> This is what I used for a content folder that's just called "content".

Yes, `installer-paths` is the solution for when your composer.json is not in WordPress' root. We even use this internally when we require Carbon Fields in themes, for example.
