### ISSUE TITLE
.gitignore dist

### ISSUE THREAD

**Issue by elvishp2006** [htmlburger/carbon-fields#270]
Hi guys, realy needed ignore /assets/dist/ directory?

```
# Bundled assets
/assets/dist/
```

**Comment by atanas-angelov-dev** [comment]
/dist/ is ignored in all branches except `release` so compiled assets do not pollute changesets.
From 2.0.0 on all releases will be created from the `release` branch which does NOT ignore these files.

If you need the compiled assets for development purposes just compile them using `npm install` and then `npm run dev` or `npm run build`.
