### ISSUE TITLE
Vertical Tab Container

### ISSUE THREAD

**Issue by sachittandukar** [htmlburger/carbon-fields#271]
Hi,

I am unsure but I couldn't find option for vertical tabs container similar to vertical tabs for complex fields.
I think it would be great to have this option as well as option to add icons along with tab headings.

**Comment by jorostoyanov** [comment]
Long awaited feature request.

With this commit - https://github.com/htmlburger/carbon-fields/commit/e5e4019a61336a69911401b474d041e615cc5f0d - it is now possible to change the tabs on containers to vertical and add a Dashicon to it.

Will be available with the next release - v3.4.0 - along with the appropriate documentation.
