### ISSUE TITLE
Theme Options in Network/Multisite Admin?

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#272]
I looked through the docs and didn't see a solution, but I thought that I'd ask.

Is there a way to add 'theme_options' to multisite/network admin (/wp-admin/network/)? (Similar to how you can using `add_action('network_admin_menu', 'callback');`?

Thank you,
Daniel

**Comment by atanas-angelov-dev** [comment]
We've had internal discussions about adding this but at this time a Network Options container (or similar) is not available.

**Comment by dmhendricks** [comment]
Thank you A.

I wouldn't think (?) that it would be too difficult to add a `Container::make( 'network_options' )`. Of course, that still requires the developer to manage his gear correctly in a multisite environment.

Since I brought it up, it would be kind of cool that add `blog_id` to the Condition Types so I could do cool things like... `->where( 'blog_id', 'IN', $this->get_blog_by_domain('.specialblogsonly.com') )`...

```
private function get_blog_by_domain($needle) {
  // Return only site IDs of a specific parent domain
  $matches = array();

  foreach(get_sites() as $site) {
    if($needle === substr($site->domain, -strlen($needle))) {
      // This blog's domain ends with ".specialblogsonly.com"!
      $matches[] = $site->blog_id;
    }
  }

  return $matches;
}
```

That's just one crude example, but there are possibilities.

That said, just having the `Container::make( 'network_options' )` option would be swell. I can handle the other magic.

Thanks mate,
Daniel

**Comment by atanas-angelov-dev** [comment]
I just pushed a `blog_id` condition to the `development` branch.

In the mean time, you can use this until the update hits master:

- Create a `Blog_ID_Condition.php` file somewhere in your theme/plugin and autoload/require it:
```php
<?php
namespace Foo_Namespace;

use Carbon_Fields\Container\Condition\Condition;

class Blog_ID_Condition extends Condition {

	/**
	 * Check if the condition is fulfilled
	 *
	 * @param  array $environment
	 * @return bool
	 */
	public function is_fulfilled( $environment ) {
		return $this->compare(
			get_current_blog_id(),
			$this->get_comparison_operator(),
			$this->get_value()
		);
	}
}
```

- Add the following somwhere in your initialization code, after the composer autoloader has been loaded:
```php
\Carbon_Fields\Carbon_Fields::extend( \Foo_Namespace\Blog_ID_Condition::class, function( $container ) {
	$condition = new \Foo_Namespace\Blog_ID_Condition();
	$condition->set_comparers( \Carbon_Fields\Carbon_Fields::resolve( 'generic', 'container_condition_comparer_collections' ) );
	return $condition;
} );
add_filter( 'carbon_fields_theme_options_container_static_condition_types', function( $condition_types, $container_type, $container ) {
	return array_merge(
		$condition_types,
		array( 'blog_id' )
	);
}, 10, 3 );
```

(Above code needs some adjustments to be PHP 5.3 compliant)

The above code creates and registers your very own `'blog_id'` condition for Theme Options containers.

**Comment by dmhendricks** [comment]
You are amazing. Thank you very much!!
