### ISSUE TITLE
Select2-style Multiselects

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#276]
Sometimes, a `set` doesn't always work (UI speaking) with long lists. I think that Select2-style [multiselect dropdown](https://select2.github.io/examples.html#multiple) and/or [tagging](https://select2.github.io/examples.html#tags) (to allow the user to add values that are not in the pre-defined list) fields would be swell.

Then again, perhaps those would be better suited as a plugin. (?)

**Comment by atamaniuc** [comment]
Why you closed  this issue ?) Adding Select2 will be great !

**Comment by dmhendricks** [comment]
I closed it because I figured that it would be better suited as an addon field plugin and started to make one. I got it fairly close but I couldn't get Javascript to cooperate, so I abandoned it.

**Comment by emohamed** [comment]
This is in our backlog ... we'll get to it eventually. We hope to get it done within a month or so. 

I think that it makes sense to include it in the core plugin.

**Comment by dmhendricks** [comment]
Hmm... I suppose a feedback question might be: Select2 or Chosen or Selectize or something else?

I always use Select2 (simply because I'm familiar with it), but it does have [performance](https://jsperf.com/chosen-select2-selectize) issues. Chosen is more basic but it would fulfill the deliverables mentioned in my OP.

Selectize is interesting. It has some cool UI swag, but it also has some that aren't as friendly.

Despite the performance hit, I would probably still vote for Select2 because Ajax.

**What do y'all think?**

**Comment by chetzof** [comment]
Select2 has more features and besides the mentioned perf problems, currently the project is not actively maintained.
Chosen is slightly better maintained,less features, better perf.
No opinion on selectize except that there are no releases since last year and very little activity in repo even compared to select2

**Comment by dmhendricks** [comment]
Select2 did just do a minor release 25 days ago, but I agree, it does not appear to be as active as Chosen. Select2's Ajax support might be an important consideration, though.

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.

**Comment by nebulousGirl** [comment]
How was the issue addressed?

**Comment by atanas-angelov-dev** [comment]
@nebulousGirl a new field was added:
https://carbonfields.net/docs/fields-multiselect/?crb_version=2-2-0

**Comment by nebulousGirl** [comment]
Oh, I see, sorry. Is it possible for the user to add a value that is not listed in the options with this field (like tagging)?

I was also hoping that I could use something similar with single selects to filter a long list of options.
