### ISSUE TITLE
Custom validation: Adding and remove errors via the Javascript API

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [htmlburger/carbon-fields#278]
This is a follow up to issue #199. I want to see .addError(field, msg) and .removeError(field, msg) added to the Javascript API at some point. I am convinced that there are functions by those names or similar ones in the Carbon Fields Javascript backend. If you do not expose these two methods, then you have nothing you can call custom validation. Thank you!

**Comment by atanas-angelov-dev** [comment]
We are already evaluating methods to expose a similar API to enable users to do this.

Note that there are enough tools (barebones, I know) to create your own validation as it is right now (hook into submission, check field values, stop submission and display errors however you need if necessary).

**Comment by atanas-angelov-dev** [comment]
2.0.2 has been released which exposes an event/hook where you can add your custom validation:
https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-0-0

https://github.com/htmlburger/carbon-fields/releases/tag/2.0.2
