### ISSUE TITLE
Different theme_options header text?

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#281]
Is there a supported way to make a `theme_options` container header text different from the menu item label? Example:

```
Container::make( 'theme_options', 'Soylent Green' )
->add_fields( array(
    Field::make( 'text', 'soy_facebook_url') ,
    Field::make( 'textarea', 'soy_footer_text' )
) );
```

Both the menu item label and the H2 header at the top of the options page will be "Soylent Green". I have encountered several times where I want a shorted menu item label (so that it doesn't wrap, which is ugly to me) but a more verbose header.

For example, if my plugin is named "Nearby WordPress Events," I might want the menu item label to be "WordPress Events" but the H2 page header to be "Nearby WordPress Events."

Thank you,
Daniel

**Comment by atanas-angelov-dev** [comment]
This is not currently supported.

Note that you can still achieve this by filtering the admin menus, through (e.g. messing with the global $submenu).

**Comment by atanas-angelov-dev** [comment]
2.0.2 has been released which adds a `set_page_menu_title()` method:
https://github.com/htmlburger/carbon-fields/releases/tag/2.0.2
