### ISSUE TITLE
UX Issue: set_collapsed() + "Add Entry"

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#282]
The narrative:

* My Complex field entries have many fields/options, so I set_collapsed().
* The entry label is set with set_header_template(). (Awesome feature, BTW)
* When I click "Add Entry," a new one is added as expected. However, since it is also collapsed, it is not clear to the user what to do with it (he/she needs to be expanded so that the fields appear).

I feel like the new entry should be expanded by default so that it is clear to the user what to do with it. Perhaps there is already a supported way to do this?

![collapsed-complex-add-entry](https://user-images.githubusercontent.com/8184361/28244701-5549be48-69b7-11e7-91bc-eb8c36b01124.png)

I assume that I can make the lodash template display something like "Click Here to Edit" rather than a blank label for the new entry, but that isn't ideal. I still think that when the user clicks "Add Entry," the new one should be expanded.

(FTR: This particular plugin is using the latest `development` branch pull, if that makes a difference in critique/pathology. I am not completely privy to all of the differences between `development` and the latest release version.)

Thank you,
Daniel

**Comment by atanas-angelov-dev** [comment]
New entries ignoring `set_collapsed()` makes sens so I'll see if we can squeeze this in the next patch/minor version.

**Comment by atanas-angelov-dev** [comment]
2.0.2 has been released which addresses this:
