### ISSUE TITLE
Version 2.0 in WP plugin repo

### ISSUE THREAD

**Issue by batz-bar** [htmlburger/carbon-fields#288]
Is there a date when version 2.0 will be in wp plugin repo?
Thanks!

**Comment by atanas-angelov-dev** [comment]
For the time being we do not plan to release 2.0 in the WordPress plugin repository.
Regardless, you can still load Carbon Fields 2.0.3+ as a plugin using this guide:
https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-0-0

**Comment by timiwahalahti** [comment]
Is there any specific reason why not to release 2.0 in w.org repo?

**Comment by atanas-angelov-dev** [comment]
We actually wrote a short article on the subject here:
https://carbonfields.net/2017/07/31/carbon-fields-distribution-woes/
