### ISSUE TITLE
Issue with installer paths

### ISSUE THREAD

**Issue by JasonHoffmann** [htmlburger/carbon-fields#289]
In the most recent versions of the plugin, `type` and `"composer/installers"` attributes have been removed so it no longer works with the composer installer. Is there any plan to add this back?

Thanks

**Comment by atanas-angelov-dev** [comment]
The plugin loader was split into it's own package which then requires `htmlburger/carbon-fields`.
We've added a dedicated docs page on how to set it up:
https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-0-0
