### ISSUE TITLE
Documentation: Widgets $widget_id

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#290]
Correct me if I'm missing something, but the `class ThemeWidgetExample extends Widget` example appears to be missing the $widget_id parameter?
https://carbonfields.net/docs/containers-widgets/?crb_version=2-0-0

**Comment by atanas-angelov-dev** [comment]
Fixed:
https://carbonfields.net/docs/containers-widgets/?crb_version=2-0-0
