### ISSUE TITLE
Show a field one way for an admin and another for a logged in user

### ISSUE THREAD

**Issue by matgargano** [htmlburger/carbon-fields#293]
My goal is to allow an arbitrary field `user_id` in this example - show up as a TEXT field for administrators and a DISPLAY field for the actual user (display field: https://github.com/statenweb/carbon-field-display) for testing/demo purposes DISPLAY can be substituted for anything -- textarea, etc.

I tried registering two different field sets depending on who the user is but that does not appear to be working. Any idea how I can do this?

Here is an example class: https://gist.github.com/matgargano/63316df5c857675e31b80025610176da

To get it up and running include that file and then execute:

```
$user_settings = new \MyWork\User();
$user_settings->init();
```

**Comment by atanas-angelov-dev** [comment]
Hi @matgargano ,

There are two ways we can approach this, each with it's own drawbacks:
1. Conditionally define containers depending on the currently logged in user (what you currently have)
1. Define both containers and display them conditionally

The first approach is the simpler one, however, it has the potential to cause issues. As long as the two field types used format and store the value in identical ways you will be fine, but if they do either in a different way then you can have unexpected results.

Here's how your code should look using this approach:
```php
// Disable admin-only enforcing for "Data User" container
add_filter( 'carbon_fields_user_meta_container_admin_only_access', function( $enable, $container_title, $container ) {
	if ( $container_title === 'Data User' ) {
		$enable = false;
	}
	return $enable;
}, 10, 3 );

if ( current_user_can( 'administrator' ) ) {
	Container::make( 'user_meta', 'Data Admin' )
		->add_fields( array(
			Field::make( 'text', 'user_id', __( 'User ID', 'my-domain' ) ),
		) );
} else {
	Container::make( 'user_meta', 'Data User' )
		->where( 'current_user_capability', '!=', 'manage_options' )
		->add_fields( array(
			Field::make( 'display', 'user_id', __( 'User ID', 'my-domain' ) ),
		) );
}
```

(You should probably use the above in your case but I'm adding the second approach for more info)

The second approach is more verbose but avoids the mentioned issue:
```php
// Disable admin-only enforcing for "Data User" container
add_filter( 'carbon_fields_user_meta_container_admin_only_access', function( $enable, $container_title, $container ) {
	if ( $container_title === 'Data User' ) {
		$enable = false;
	}
	return $enable;
}, 10, 3 );

$admin_container = Container::make( 'user_meta', 'Data Admin' )
	->add_fields( array(
		Field::make( 'text', 'user_id', __( 'User ID', 'my-domain' ) ),
	) );

$user_container = Container::make( 'user_meta', 'Data User' )
	->where( 'current_user_capability', '!=', 'manage_options' )
	->add_fields( array(
		Field::make( 'display', 'user_id', __( 'User ID', 'my-domain' ) ),
	) );

// We keep the container IDs for later use
define( 'CRB_ADMIN_CONTAINER_ID', $admin_container->get_id() );
define( 'CRB_USER_CONTAINER_ID', $user_container->get_id() );

// Later where you need to get the value
var_dump( carbon_get_user_meta( $some_user_id, 'user_id', CRB_ADMIN_CONTAINER_ID ) ); // using the `text` field type
// or
var_dump( carbon_get_user_meta( $some_user_id, 'user_id', CRB_USER_CONTAINER_ID ) ); // using the `display` field type
```

(You'll notice that we are using the third parameter of `carbon_get_*` functions - this allows us to distingsuish which field we want to resolve to when we have 2 fields with identical names in the same type of containers.)

If both field types load and format the data in identical ways then you don't really need to use the third parameter of `carbon_get_*` functions but you probably should just to be on the safe side.

**Comment by matgargano** [comment]
Thanks for getting back to me so quickly. Let me give them a whirl.

**Comment by matgargano** [comment]
@atanas-angelov-dev Thanks, first option worked like a charm.
