### ISSUE TITLE
Radio Field Issue with Numeric Values

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#295]
I don't know if this is only me, but I've noticed an odd behavior with the radio fields type lately (I'm not sure when it started happening, but I believe it was >=2.0.0). It didn't see it in a search (or missed it), so I'm posting it.

If the radio options have an integer value, they don't seem to select when clicked (they glow in Chrome, but have no bullet and do not save). It doesn't seem to make a difference whether I put the number in quotes (string) or not (integer).

```
Field::make('radio', ... )
  ->add_options(array(
    '1' => 'One',
    '2' => 'Two'
  )
)
```
![carbon-radio-integer-values](https://user-images.githubusercontent.com/8184361/28740445-56d15c86-73ca-11e7-9dcb-a752fefa18ab.png)

```
Field::make('radio', ... )
  ->add_options(array(
    'one' => 'One',
    'two' => 'Two'
  )
)
```
![carbon-radio-string-values](https://user-images.githubusercontent.com/8184361/28740453-6a71631c-73ca-11e7-95bf-781492929f81.png)

Anyone else? Carbon Fields 2.0.4, WordPress 4.8. No console errors.

**Comment by atanas-angelov-dev** [comment]
The issue has been fixed (748fba7c29ad7f35383fc647590b1360dfa89767 and 7ce09bd2c52a82292970e924b94549aa36de24f8) and will be available in the coming 2.0.5 release.
