### ISSUE TITLE
Default value doesn't work for select

### ISSUE THREAD

**Issue by atamaniuc** [htmlburger/carbon-fields#297]
`set_default_value` doesn't works for field type `select` - for frontend.

**Comment by atanas-angelov-dev** [comment]
Hi @atamaniuc ,

Can you please share your entire field definition and give us a bit more details such as what value is selected if not the one you've set as the default one?

**Comment by atamaniuc** [comment]
Hello @atanas-angelov-dev  !
I've also noticed the same issue for `set` filed type.

`$selectFieldWithDefaultValue = Field::make(
            'select',
            'select_field_with_default_value',
            __('Select field with default value', 'myDomain')

        )->set_options(['a' => 'AA', 'b' => 'BB', 'c' => 'CC'])->set_default_value('b');

        $setFieldWithDefaultValue = Field::make(
            'set',
            'set_field_with_default_value',
            __('Select field with default value', 'myDomain')

        )->set_options(['a' => 'AA', 'b' => 'BB', 'c' => 'CC'])->set_default_value('b');`

**Comment by atanas-angelov-dev** [comment]
I am unable to reproduce the issue on 2.0.4 - can you let me know which version you are using exactly?

**Comment by atamaniuc** [comment]
2.0

**Comment by atanas-angelov-dev** [comment]
Please update to 2.0.4 and let us know if the issue persists.

**Comment by atamaniuc** [comment]
I've updated to 2.0.4 and I still have this issue. In global object `carbon_json` the property `default_value:"b"` is set, but there are not selected options in html.

**Comment by atanas-angelov-dev** [comment]
I will need a full reproduce case in order to investigate the issue.

**Comment by atamaniuc** [comment]
Sorry, the problem was in my custom DataStore !

**Comment by atanas-angelov-dev** [comment]
No worries - thanks for updating this ticket!
