### ISSUE TITLE
WPML integration: copy fields & non-translatable fields

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#298]
Hi, 

I'm trying the new version and I've seen that there is a section on the documentation about WPML, it says: "Carbon Fields provide out-of-the-box support for WPML [...]". Cool. :sparkles::sparkles:

I've tried adding a few fields in a translatable post and I can't see how CF integrates with WPML. Could you clarify in the documentation what is the integration about?

Also, there are two features that would be really helpful in the context of WPML:

1. Define non translatable carbon fields, useful for data that it's the same across all the languages (e.g: email, name, surname…)
2. Integration with "Copy content from xx" when creating a new translation. This would copy the translatable carbon fields.[1]

Thanks for another great release!
Asier.

1: Btw, it would be interesting if this was available also afterwards… but this sounds like it's a WPML issue.

**Comment by atanas-angelov-dev** [comment]
Hi @doup ,

> Could you clarify in the documentation what is the integration about?

The integration allows fields to work with translated posts, terms etc.

> Define non translatable carbon fields.

This is not a priority right now, but if you need it you can just fetch the values for the "main" post like this:
```php
// not tested:
$english_post_id = apply_filters( 'wpml_object_id', $post->ID, 'post', false, 'en' );
$english_value = carbon_get_post_meta( $english_post_id, 'some_field_name' );
```

> Integration with "Copy content from xx" when creating a new translation.

Creating a copy of a post should copy all of the meta values as well (which include carbon field values).

**Comment by timiwahalahti** [comment]
Oh, cool that there's integration to translation plugin! Actually I was thinking about making my own for Polylang as plugin. But maybe I'll just look at the WPML integration and try to use it as a base for Polylang integration.

**Comment by zessx** [comment]
This really is the last big feature I need in Carbon Fields. Hoping it'll be added in a near future!
