### ISSUE TITLE
Complex field `set_header_template` not working anymore

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#299]
In the `1.x` series there was an option for Complex fields that it allowed to add a custom template to the Complex field headers, see #27. It would be nice to have this feature back.

Thanks!

**Comment by atanas-angelov-dev** [comment]
The feature has not been removed - it just uses Lodash templates instead of Underscore. See `set_header_template` here:
https://carbonfields.net/docs/complex-field-config-methods/?crb_version=2-0-0

**Comment by doup** [comment]
Ups, sorry. My bad, I didn't look the docs… :sweat:
