### ISSUE TITLE
Delete complex field values by main key

### ISSUE THREAD

**Issue by batz-bar** [htmlburger/carbon-fields#302]
I have the following complex meta fields keys in the database:
_files|title|0|0|value
_files|date|0|0|value
_files|title|1|0|value
_files|date|1|0|value
_files|title|2|0|value
_files|date|2|0|value
Is there a function to delete all fields under main key '_files' at once without writing SQL like % queries?

**Comment by atanas-angelov-dev** [comment]
Hi @batz-bar ,

You can just update the relevant complex field with an empty array as it's value which will effectively delete all of the keys you mentioned:
`carbon_set_post_meta( $post_id_here, 'files', array() );`

Note that this method will save a single `_files|||0|_empty` key instead (this is an internal key which prevents default values from kicking in).

**Comment by austins** [comment]
Is there a way to delete one entry from a complex field by a key?

~~~
_files|title|0|0|value
_files|date|0|0|value
_files|title|1|0|value
_files|date|1|0|value
_files|title|2|0|value
_files|date|2|0|value
~~~
