### ISSUE TITLE
package type wordpress-plugin

### ISSUE THREAD

**Issue by strarsis** [htmlburger/carbon-fields#303]
Compatibility would be improved if composer.json of this project also contains 
```json
[...]
  "keywords": ["wordpress", "plugin"],
  [...]
  "type": "wordpress-plugin",
  "require": {
    [...]
    "composer/installers": "v1.0.6"
  },
[...]
````
(According to [Composer/WordPress Bedrock docs](https://roots.io/wordpress-plugins-with-composer/)).

Edit: If this is actually meant to be installable as module shared between plugins/theme.

**Comment by atanas-angelov-dev** [comment]
Hi @strarsis ,

There is a separate `wordpress-plugin` package which includes these and acts as a plugin loader for Carbon Fields - https://github.com/htmlburger/carbon-fields-plugin.

Please refer to these 2 documentation articles:
- [Quickstart](https://carbonfields.net/docs/carbon-fields-quickstart/?crb_version=2-0-0)
- [Plugin Quickstart](https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-0-0)
