### ISSUE TITLE
Fields with hyphen symbol don't work

### ISSUE THREAD

**Issue by olegburakov** [htmlburger/carbon-fields#304]
Hello guys, and thank you a lot for your plugin and ver 2.0!

I think i have found a little but annoying bug. When I name a field in theme options page with hyphen symbol ("-") there was no errors when i open theme options page, and enter data and save it. But when i have tryied to get fields with carbon_get_theme_option( ) i have empty string instead of value.
I replace hyphen with undescore - and finally get value.
I think that hyphen symbol was forbidden in versions 1.x but as i remember there was an error message about wrong name (help a lot to understand where is a problem), when you try to create field with hyphen symbol.

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @olegburakov !

I've applied a fix in ab5fc906d79478bc80c7ac55760297053c90d806 which should make it into the coming 2.0.5 release.

**Comment by olegburakov** [comment]
Thank you a lot !

**Comment by atanas-angelov-dev** [comment]
2.1.0 has been released which addresses this issue:
https://github.com/htmlburger/carbon-fields/releases/tag/2.1.0
