### ISSUE TITLE
Access tinymce  / rich_text

### ISSUE THREAD

**Issue by Fritze1602** [htmlburger/carbon-fields#305]
Hi, first of all. Thank you for your great plugin.

I created an additional rich_text field. I am able to access values with following code.

tinymce.editors[1].getContent() 

Is there a way to access it with the id from "post_meta" So its mor dynamic???

I wonder if you would be so kind to give me a hint.

Many thanks in advance.

**Comment by atanas-angelov-dev** [comment]
Hi @Fritze1602 ,

You can check out how to pull field values from post meta here (the "Accessing field values" section):
https://carbonfields.net/docs/containers-post-meta/?crb_version=2-0-0

**Comment by Fritze1602** [comment]
Thank you very much for your fast reply and your help. 
And once more for your great plugin. Allthough I am a php noob ... 
Everything is working real fantastic.
