### ISSUE TITLE
[2.0] Complex Field: Rich Text Bug

### ISSUE THREAD

**Issue by bjoernhasse** [htmlburger/carbon-fields#307]
Hey,

I discovered the following reproducible bug with the tinymce editor inside a complex field. 
After moving an item of a complex field the tinymce editor removes the line breaks of the moved item and hides the content of the visual editor of the other items.

![ezgif-1-d3c9fc9fc2](https://user-images.githubusercontent.com/16560273/29067958-149d09dc-7c35-11e7-9b36-354606a5e43f.gif)

This bug does only occur on version 2.0 and throws no error in the console.

Keep up the good work!
Cheers

**Comment by iamntz** [comment]
Hey guys! 

Just wanted to let you know that this problem is also present when you try to clone a field.

PS: first time here, great plugin 🍻

**Comment by atanas-angelov-dev** [comment]
2.1.0 has been released which addresses this issue:
https://github.com/htmlburger/carbon-fields/releases/tag/2.1.0

**Comment by bjoernhasse** [comment]
Thanks a lot!
This solves a great issue for us!
