### ISSUE TITLE
app.js?ver=1.6.0:338 Uncaught ReferenceError: carbon_json is not defined

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-fields#308]
I get this error and the fields do not appear.

app.js?ver=1.6.0:338 Uncaught ReferenceError: carbon_json is not defined
    at Object.carbon.init (app.js?ver=1.6.0:338)
    at HTMLDocument.<anonymous> 

I do not know what's happening, please help me.

**Comment by atanas-angelov-dev** [comment]
Hi @dackr ,

You most probably have a PHP fatal error which cuts off your page. Please check your full page's source to confirm.

**Comment by dackr** [comment]
Thanks for your reply but I tried it on localhost and this is the image on the server still the same.
https://ibb.co/mCGzCF

**Comment by atanas-angelov-dev** [comment]
Can you paste the full error message you see after `<b>Warning</b>:` and your field definitions as well?
