### ISSUE TITLE
Complex Field set_header_template() Question

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#309]
(sorry, I'm not familiar with lodash)

Given the example at the bottom of this page:
https://carbonfields.net/docs/complex-field-config-methods/?crb_version=2-0-0

Is there a way to reference the complex/parent field name in the template?

The example above has something like:
```
->set_header_template( '
    <% if (name) { %>
        Passenger: <%- name %>
    <% } %>
' )
```

I have dynamically-created fields and would like it if I could do something like the following (as a crude example):
```
->set_header_template( '
    <% if (name) { %>
        <%- this.label %>: <%- name %>
    <% } %>
' )
```

...where `this.label` would return "Passenger" or "Driver" in this case.

Thank you,
Daniel

**Comment by atanas-angelov-dev** [comment]
`set_header_template()` only supports field values at this time, however, if you are dynamically generating the complex fields aren't you able to dynamically generate the header template as well (replacing this.label with the literal complex field label string)?

**Comment by dmhendricks** [comment]
Sorry, I guess I had a brain fart. I was looking at it too hard at it and missing the obvious. I feel silly for asking now. 👅 

I'm using a variable to store the template, but that's easy to modify.

Thank you,
Daniel
