### ISSUE TITLE
Detect if field id contains underscore already

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#312]
Right now second underscore is added to start of field id, if there's underscore defined to id when field is registered. This should not happen. One underscore is enough.

```Field::make( 'text', '_fp_big_upsell_button', __( Button text', 'demo' ) )```

becomes like this in db

```__fp_big_upsell_button```

**Comment by atanas-angelov-dev** [comment]
We actually had checks for leading underscore in 1.x but in the end we really saw no benefit in doing them - it only complicates logic for no real benefits other than a 1 character key length reduction.

**Comment by timiwahalahti** [comment]
Yup. This was actually just something that did come from old habits and habits can be changed :) Will close this issue.
