### ISSUE TITLE
Field::set_attribute() doesn't work with [type=select]

### ISSUE THREAD

**Issue by kaleidoscopique** [htmlburger/carbon-fields#315]
Hey,

When I try to add a (data) attribute to a `<select>` field, it doesn't work. No error, just nothing added to the DOM.

Simple example : 

```php
Field::make( 'select', 'my_select', 'Foo' )->set_attribute('data-type', 'bar');
```

Is it a known bug, a problem with my code, a bad practise... ? Thanks a lot for your help.

**Comment by atanas-angelov-dev** [comment]
Hi @kaleidoscopique ,

As stated in the documentation, only text and textarea fields support custom attributes at this time but I believe it won't be a problem to add select fields to this list as well. I'll update this ticket if there's any development on this.

**Comment by kaleidoscopique** [comment]
I would love to do it by myself, but I'm not sure to understand how to do... yet. Can't wait to see the changes you will make to understand how CF works under the hood.

Thank you so much, have a nice day.

**Comment by atanas-angelov-dev** [comment]
2.1.0 has been released which addresses this issue:
https://github.com/htmlburger/carbon-fields/releases/tag/2.1.0
