### ISSUE TITLE
Wrong German Translation

### ISSUE THREAD

**Issue by obstschale** [htmlburger/carbon-fields#316]
I created an association field and I found a wrong german translation. Though I cannot update the translation file, because Carbon Fields is not programmed to do that correctly.

Let me show what I mean: The english string says `0 selected items out of 1` the german string says `0 Ausgewählte Einträge außerhalb 1`.

The wording "out of" is translated with "außerhalb". That is correct but in this sentence it has a different meaning and needs another translation.

I see that Carbon Fields builts this string and so the string "%d selected items out of %d" does not exist. Please use always complete sentences and don't try magic string concatination, because that makes it really hard sometimes impossible to provide a correct translation.

For this particular string you should use something like this:

     sprintf( __( '%1$d selected items out out %2$d', 'textdomain' ), $selected, $total );

Please not the numbering `%1$d` makes it possible for translators to change the order of variables. Some languages would first name the total and than the selected number.

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @obstschale !

We are aware of the need for sentence rather than phrase translation, however, it seems this one was left in by mistake.
We should have this fixed in the next patch or minor release.

**Comment by atanas-angelov-dev** [comment]
2.1.0 has been released which addresses this issue:
https://github.com/htmlburger/carbon-fields/releases/tag/2.1.0
