### ISSUE TITLE
[2.0.4] Image in Complex Field

### ISSUE THREAD

**Issue by TigroWeb** [htmlburger/carbon-fields#317]
Multiple duplication of the modal window when sorting nested fields.

Code:
```
Container::make( 'post_meta', 'Bug Image' )
->add_fields( [
	Field::make( 'complex', 'photogallery', 'Photo gallery' )
	->add_fields( [
		Field::make( 'image', 'img', 'Image' )
	] )
] );
```
Steps that cause an error:
Step 1. Add several elements with images to the complex field.
Step 2. Sort the items.
Step 3. Click the "Select Image" button in one of the moved items.
As a result, several windows are immediately opened for selecting an image. The more times we move the item in the list, the more duplicate windows we get.
P.S. I'm sorry for my english from Google.translate :)

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @TigroWeb - I was able to reproduce the issue locally and we'll take a look at this for the next release.
