### ISSUE TITLE
Association field performance

### ISSUE THREAD

**Issue by xsynaptic** [htmlburger/carbon-fields#318]
I'm experimenting with using CF's association field to hand-pick related posts on one of my blogs but I notice that the UI loads every object that matches the condition (*e.g.* post type is post). Since I've got 900 posts I now have 900 extra queries to populate the association field. From a quick scan of the codebase it looks non-trivial to implement pagination, but it would be cool to see in some future update. Thanks again for the excellent library/plugin/toolkit!

**Comment by atanas-angelov-dev** [comment]
As a quick FYI, pagination for the Association field is already in our internal TODO and will probably be added in one of the next minor releases.

**Comment by karex** [comment]
Having a site with 3000+ posts the association field is slowing down edit screens a lot. Any update on this?

**Comment by iamntz** [comment]
Probably it would be better to have this implemented as an AJAX search?

**Comment by HugoLachance** [comment]
So, is there a solution for the performance of the association field when there is a lot a posttype ?

**Comment by emohamed** [comment]
Progress on this issue is being made here: https://github.com/htmlburger/carbon-fields/tree/feature/ajaxify-association-field

Next 2.X release will include a fix for the performance issues related with the association field.

**Comment by emohamed** [comment]
Hi @HugoLachance,

The feature is still in progress, we're aware of the complex field issue(and a few others). We hope to have them fixed next week.

**Comment by jorostoyanov** [comment]
Hi @HugoLachance,

I have updated the `feature/ajaxify-association-field` branch with a fix for the **Association field** for when used in a **Complex field**.

Can you give it a try and let me know if you experience any issues?

Thanks!

**Comment by vvasilev-** [comment]
Hi @JiveDig,

This is included into 3.0 release of Carbon Fields so you can test it. The AJAX requests get executed only when the user types something in the search field.

**Comment by JiveDig** [comment]
Great news, thanks 🙌🏼
