### ISSUE TITLE
HTML field in Complex field: use values from other fields

### ISSUE THREAD

**Issue by bclarkau** [htmlburger/carbon-fields#322]
Hi,

Is it possible for an HTML field inside a Complex field to access the value of an adjacent field in the set? I was hoping that the set_html() method could use the same templating functionality that the set_header_template() function can, but it doesn't look like that's the case. Is there another way to do this currently?

For a real-world example that I was struggling with, I wanted to have the following fields: 
* Complex Field Group
  * Title (Text Field)
  * Description (Textarea Field)
  * Jump Link (HTML Field)

The "Jump Link" field was to display a URL that could be used as an anchor link. eg. If the Title field is set to `Hello World`, the Jump Link field would use set_html() to create this URL: `www.example.com/page#helloworld`. 

The workaround I'm using at the moment is to use jQuery in the Wordpress dashboard to grab the value of the Title field and append it to the end of the HTML created in set_html(), which works but it's a little messy and not ideal.

Thanks!

ps. This is the jQuery I'm using in the Wordpress back-end to do this, just in case it's helpful for anyone else: 
> // get all root-level complex fields
> var $fieldsInFields = $('.fields-container', '.fields-container');
> var $complexFields = $('.carbon-field .fields-container').not( $fieldsInFields );
> 
> // replace text in section_anchor_tag element with title of section
> $('.section_anchor_tag', $complexFields).text(function(){
>   // get the container
>   var $container = $(this).closest('.fields-container');
> 
>   // get the value of the 'title' field in same section as section_anchor_tag element
>   var anchorTitle = $('> .carbon-row > LABEL:contains("Title")', $container).siblings().find('INPUT').val();
> 
>   // lowercase and remove non-word characters before returning
>   return anchorTitle.toLowerCase().replace(/\W/g, '');
> });

**Comment by jorostoyanov** [comment]
You can always use the `carbon_get_post_meta`, `carbon_get_theme_option` and the rest of the helper functions in order to display the needed data, once the container is saved.
