### ISSUE TITLE
Simple File Upload Field

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#324]
I'm not sure that this is a feature request (I may try to make my own field), but more of a request for comment. I feel like I'm over-thinking this.

I have a need for a field that allows me to upload a file. However, I do not want them uploaded to the Media Library (There will be several files, and I don't want them to clutter up the library. I also don't want WordPress to rename existing for this deliverable.) Basically, I'd like a `input[type=file]` where I can:

* Set allowable mime types (I know that this is already doable with the File field type). This actually isn't a big deal, but would be nice.
* Ability to set a destination path (ex: `uploads/my_plugin/`)
* Ability to specify whether an existing file of a matching name should be _overwritten_ with the newly uploaded version, or if the new file should be _renamed_ (ex: `my_file-1.zip`). (In my current need, I _do_ want them to be overwritten with the new file because of external links.) For my purposes, I would be fine without having the option to choose as long as the file was not renamed.
* This upload field must work in a Complex field (this may make using the hook mentioned below tricky??)

I could probably make a custom field type using the template, but perhaps it would make more sense to just `->set_attribute( 'type', 'file' );` and then do the rest of the work with `carbon_fields_{container_type}_container_saved`? Am I missing some caveats?

A very crude & ugly example:

<img width="702" alt="carbon-field-file-upload" src="https://user-images.githubusercontent.com/8184361/29878781-0734fec2-8d69-11e7-8130-3c0e44f9c17d.png">

(I should have labeled the "Upload File" button as "Browse", since the URL shown would be the **previously**-uploaded file URL - available for copy/paste - and not the actual file that is to be uploaded)

Thank you for ideas,
Daniel

**Comment by dmhendricks** [comment]
This has suddenly become an "emergency" deliverable for me, so I'm thinking that developing a custom field may be the best bet. Yeah? Input is still welcome.

**Comment by atanas-angelov-dev** [comment]
In this case the best approach is to create a custom field (especially when you want it to work in a complex field).

**Comment by dmhendricks** [comment]
Thank you A. After some thought, I agree.

A custom field would be ideal, and I make may one eventually as time permits. Given my time constraints, I decided to use CFs File field (this will also let me use core functions normally without messing around).

As far as my "clutter" concern, I'm just going to use another plugin to organize Media Library.

I still have an issue where some of the uploaded files are to be marked private and `wp-content/uploads` doesn't allow for an easy way to do that (to my knowledge). I will probably just do some `.htaccess` manipulation for that.

If I do get the time to write a custom field, it should be fairly easy to convert the plugin to use that field instead.

Thanks again,
Daniel

**Comment by nebulousGirl** [comment]
@dmhendricks Did you ever write the custom field? Or maybe it is now possible to do it in Carbon Fields? I need the same features.
