### ISSUE TITLE
Multiple Select, Html in title fields, Color Fields

### ISSUE THREAD

**Issue by sergeyterr** [htmlburger/carbon-fields#327]
How can I make a multiple select field?

**Comment by sergeyterr** [comment]
Second question:
Can I insert html tags щк  icons in the field title,
example:
Field::make( 'set', 'crb_product_features', 'Features <i class="fa"></i>' )

**Comment by sergeyterr** [comment]
Hey. There is another question. How can I leave only the fixed colors in the color field?

**Comment by 9585999** [comment]
@sergeyterr 
```php
Field::make('color', 'color_palette', 'Background')
        ->set_palette(['#007bff', '#6610f2'])
```

**Comment by sergeyterr** [comment]
I want to get only fixed colors, but in this case the palette is also displayed

**Comment by atanas-angelov-dev** [comment]
Hi @sergeyterr ,

> How can I make a multiple select field?

Multiple select field is not currently supported. You could use a Set field instead (list of checkboxes).

> Can I insert html tags or icons in the field title?

I believe field labels are escaped, so no. `set_help_text()` allows you to enter unescaped html so check if that works for you.

> I want to get only fixed colors, but in this case the palette is also displayed

The Color field does not currently support not showing the full palette. If you want to allow the user to select only from a pre-filled list of colors then you should either create a custom field or use a Radio Image field and just add the colors as images, for example.

**Comment by 9585999** [comment]
@sergeyterr or through css remove unnecessary elements :)

![img 2017-09-01 11 35 16](https://user-images.githubusercontent.com/16165904/29961944-ebec62ca-8f09-11e7-8823-773292df41e3.PNG)

**Comment by sergeyterr** [comment]
> Multiple select field is not currently supported. You could use a Set field instead (list of checkboxes).

Bad, "set" is the solution, but it's not exactly what you need

> I believe field labels are escaped, so no. set_help_text() allows you to enter unescaped html so check if that works for you.

I did, but the icon in the title would have been more understandable.

> The Color field does not currently support not showing the full palette. If you want to allow the user to select only from a pre-filled list of colors then you should either create a custom field or use a Radio Image field and just add the colors as images, for example.

Radio Image - this is what fits best.
Thank's

**Comment by sergeyterr** [comment]
Closed )
