### ISSUE TITLE
Field in default WordPress container.

### ISSUE THREAD

**Issue by 9585999** [htmlburger/carbon-fields#328]
Hi, is it possible to place a field with a color in a default WordPress container with a thumbnail?

**Example:**
![img_2017-09-01_ _12_47_46](https://user-images.githubusercontent.com/16165904/29964941-6c3c8694-8f14-11e7-80f4-97aa5810d9d1.png)

**Comment by atanas-angelov-dev** [comment]
Hi @9585999 ,

At this time, fields can only be placed in Carbon Fields-created containers. You could probably hack a solution in (moving the DOM element that instantiates the container etc.) but it will be messy and not advisable.

**Comment by 9585999** [comment]
@atanas-angelov-dev Sorry, I would like to have this opportunity ...

In any case, thanks for the prompt reply.
