### ISSUE TITLE
[2.0.4] Image and Complex Field in Term Meta

### ISSUE THREAD

**Issue by TigroWeb** [htmlburger/carbon-fields#330]
The "Image" field is not reset when adding a new category.

Code:
```
Container::make( 'term_meta', 'cat' )
->where( 'term_taxonomy', '=', 'category' )
->add_fields( [
	Field::make( 'image', 'img', 'Image' )
] );
```
Steps that cause the error:
1. Fill in the fields and add an image
2. Click Add a new category

![screenshot_1](https://user-images.githubusercontent.com/31143531/29984402-9b4540e8-8f5a-11e7-87f9-1b6bcf4e02d3.jpg)
![screenshot_2](https://user-images.githubusercontent.com/31143531/29984403-9b4bfb0e-8f5a-11e7-9565-f2f347e04c75.jpg)

After that all fields are reset. But the image remains on the page.

Similarly, when you add a new category,  "Complex Field" are not reset.

P.S. I'm using WP 4.8.1

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @TigroWeb !

Fixed in 2.1.1 - closing.
