### ISSUE TITLE
Plugin translate

### ISSUE THREAD

**Issue by sergeyterr** [htmlburger/carbon-fields#331]
Hi. How can I translate the plugin into Russian language?
Carbon Fields is included as a library

**Comment by sergeyterr** [comment]
http://joxi.ru/8An6lqEuj9jzaA

**Comment by 9585999** [comment]
support,
plugin installed via composer in theme folder
![img 2017-09-02 12 20 26](https://user-images.githubusercontent.com/16165904/29994502-6beb317a-8fd9-11e7-85a1-26523f3f6c79.PNG)
![img 2017-09-02 12 20 49](https://user-images.githubusercontent.com/16165904/29994503-6bec8f5c-8fd9-11e7-9fdb-b5e5bd65b88c.PNG)

**Comment by sergeyterr** [comment]
No - this translation line is marked as "requires verification", so it is not translated.

In the previous version, the carbon-fields-image-gallery class was added.
[https://github.com/schrapel/carbon-fields-image-gallery](url)

When can we expect such a class in the second version?
Thank's
