### ISSUE TITLE
How to disable Carbon Fields on the front-end?

### ISSUE THREAD

**Issue by erikjoling** [htmlburger/carbon-fields#333]
Hi, 

I want to use Carbon Fields purely as a back-end framework. On the front-end I intend to use my own _getter_ functions. Is there a way to completely prevent the framework from loading on the front-end?

Huge compliments by the way for how you handle support!

**Comment by atanas-angelov-dev** [comment]
Hi @erikjoling ,

> Is there a way to completely prevent the framework from loading on the front-end?

Everything is loaded through the `Carbon_Fields\Carbon_Fields::boot()` method so if you put that and your container definitions inside an `is_admin()` check I think you will achieve what you are looking for.
(note that this is not supported but I guess it should work)

> Huge compliments by the way for how you handle support!

Thank you for the great feedback - we try our best! 👍

**Comment by erikjoling** [comment]
Hi @atanas-angelov-dev ,

Ok, thank you. I'll let you know if I run into problems, though I don't really expect them.
