### ISSUE TITLE
image-gallery

### ISSUE THREAD

**Issue by sergeyterr** [htmlburger/carbon-fields#335]
In the previous version, the carbon-fields-image-gallery class was added.
https://github.com/schrapel/carbon-fields-image-gallery

When can we expect such a class in the second version?
Thank's

**Comment by atanas-angelov-dev** [comment]
hi @sergeyterr ,

A new Media Gallery field will be available in the 2.1.0 release which should be ready very soon.

**Comment by sergeyterr** [comment]
Thanks.
