### ISSUE TITLE
Main options menu item content merged with first options submenu item

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#339]
I'm add multiple option pages in admin
```
$basic_options_container = Container::make('theme_options', 'Main options')
	.....

Container::make('theme_options', 'Contacts')
	->set_page_parent($basic_options_container)
	....

Container::make('theme_options', 'Socials')
	->set_page_parent($basic_options_container)
	....
```
But "Main Options" not showed in menu and his content merged with content of first submenu

![04-09-2017 19-47-22](https://user-images.githubusercontent.com/12094229/30031203-eeb2c330-91a9-11e7-989b-53c28458ae43.png)

carbon version: 2.0.4

**Comment by zevilz** [comment]
Now i'm add new submenu item between main options item and first submenu item
![05-09-2017 16-58-28](https://user-images.githubusercontent.com/12094229/30060265-fb1a1b70-925b-11e7-9be7-a06bca05362c.png)

[original code](https://pastebin.com/K49FaJCJ)

**Comment by atanas-angelov-dev** [comment]
Hi @zevilz ,

I was unable to reproduce the issue using this code:
```php
$basic_options_container = Container::make('theme_options', 'Main options')
	->add_fields( array(
		Field::make( 'text', 'main_options' ),
	) );

Container::make('theme_options', 'Contacts')
	->set_page_parent($basic_options_container)
	->add_fields( array(
		Field::make( 'text', 'contacts' ),
	) );

Container::make('theme_options', 'Socials')
	->set_page_parent($basic_options_container)
	->add_fields( array(
		Field::make( 'text', 'socials' ),
	) );
```

Can you send us a full code snippet that reproduces it? Also, can you reproduce the issue on a fresh WordPress install?

**Comment by zevilz** [comment]
I will try reproduce the issue on a fresh WordPress install. Full code i'm put to pastebin and leaved link to it in my previous comment.

**Comment by zevilz** [comment]
I'm put code in fresh wordpress install, clean it and found problem. Issue arises when name of submenu item in cyrillic symbols:
```
$basic_options_container = Container::make('theme_options', 'Настройки темы')
	.......
Container::make('theme_options', 'Контакты') ### here
	->set_page_parent($basic_options_container)
	......
```
I'm change code like below
```
$basic_options_container = Container::make('theme_options', 'Настройки темы')
	.......
Container::make('theme_options', 'Contacts') ### here
	->set_page_parent($basic_options_container)
	->set_page_menu_title('Контакты') ### and here
	.......
```
Issue fixed, but page title and title on page taken from from submenu title and not from set_page_menu_title().
![06-09-2017 13-53-58](https://user-images.githubusercontent.com/12094229/30103025-dd44a2d2-930a-11e7-8fc7-5e3794a4d5ab.png)

**Comment by zevilz** [comment]
Also i'm find wrong code in  **Documentation > Containers > Theme Options** in **Menu Title** section. Code duplicate from next section.
![06-09-2017 13-30-29](https://user-images.githubusercontent.com/12094229/30103333-c1d57746-930b-11e7-9bf3-7ff3d48dec92.png)

**Comment by zevilz** [comment]
Issue fixed by below code
```
Container::make('theme_options', 'Контакты')
	->set_page_parent($basic_options_container)
	->set_page_menu_title('Контакты')
	->set_page_file('theme_contacts')
```

**Comment by atanas-angelov-dev** [comment]
I've fixed the documentation issue and it will be live once the next Carbon Fields version is released.
Thank for reporting it!
