### ISSUE TITLE
"Including" CF in a wp.org plugin

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#340]
I feel like this has probably been asked before, but I didn't see it in a search. This is sort of a wordpress.org question, but it relates to Carbon Fields.

So far, I've almost exclusively used Carbon Fields for private, client projects. However, I've been working on a plugin that I would put in the wordpress.org repo, if allowed by them. Of course, we know that WP [doesn't allow frameworks to be included](https://wptavern.com/the-wordpress-plugin-directory-will-no-longer-accept-frameworks) by plugins hosted there.

**The Question:** Has there been any discussion on updating the CF plugin in the repo (currently 1.6.0)?  I imagine that it is not a favorite priority since it is difficult to manage "what ifs" that may be presented by _other developers_ (who will then rate it a 1 star). I also know how much of a complaintfest that it will be when people get the update notification and click "update now" _without testing first_.

I currently use my own [loader](https://github.com/dmhendricks/carbon-fields-loader) for projects where it is applicable, however, I have a strong feeling that WP.org is also going to dislike having another plugin as a requirement when it is not currently in their repo.

It is not a big deal if I cannot release it on wp.org because I wouldn't make money off of wp.org anyway (I just thought that I would be nice in the spirit of open source; though, there are other benefits to releasing it there, such as convenient update management for my own purposes (and GitHub updater can have weird quirks sometimes)), but perhaps someone here has encountered the same issue.

Does anybody have experience with this or wp.org's other Draconian rules, and would be willing to share answers/advice?

Thank you everyone,
Daniel

**Comment by dmhendricks** [comment]
(Complete tangent: We need a new marketplace for WordPress. Something like Envato, except a) allow both free and commercial plugins, b) has less awful licensing requirements (I laugh at Envato's "shared license" given that they are **clearly** derivatives of a GPL'd product, c) allow more flexibility in payment terms - ie, one-time vs. subscription.)

**Comment by atanas-angelov-dev** [comment]
Hi @dmhendricks ,

> WP doesn't allow frameworks to be included by plugins hosted there.

WP does not allow frameworks to be uploaded **by themselves** - not in other plugins.
This means that plugin should include their framework instead of relying on another "framework-only" plugin as confirmed in the article you linked:

> Are you saying the best way to handle this scenario is to include the parent framework in each child plugin
> > Currently, yes. That would have been the best way.

**Comment by dmhendricks** [comment]
Thank you again, A!

I completely misremembered their policy and also misread the reference link.

Daniel

**Comment by atanas-angelov-dev** [comment]
No worries : )
