### ISSUE TITLE
Feature Request: Seamless Metaboxes

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#342]
I was thinking of ACF, and he has the ability to set a metabox style to "standard" or "seamless." I would like it if I could do that with a CF container (shown below). I currently do it with CSS, but something like a `->set_style( 'seamless' )` or `->set_style( false )` would be less hacky if it was available. Sometimes, I like to add inline comments on various edit screens.

(Related to this, it would be nice to be able to remove the metabox title, which is named "After Title" in the examples below.)

This example just uses an `html` field:

## Before / Normal Appearance
![contrainer-with-style](https://user-images.githubusercontent.com/8184361/30079228-1e49bf5e-9245-11e7-8687-14be7b7f29ee.png)

## After / "Seamless" Appearance
![container-no-style](https://user-images.githubusercontent.com/8184361/30079249-310307cc-9245-11e7-97f2-b13c89537d6e.png)

**Comment by atanas-angelov-dev** [comment]
Unfortunately we probably won't be adding that due to Gutenberg - it's still not clear how meta boxes will be displayed when it hits and the concept of seamless meta boxes probably won't exist.

Feel free to reopen this if it is still relevant once Gutenberg is live.
