### ISSUE TITLE
Complex field: require even amount of rows

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#343]
Would it be possible to add such config method for complex field, that row amount must be even (2, 4, 6 etc...)? This is quite specific use case tho.

**Comment by atanas-angelov-dev** [comment]
I'd have to agree that this is a very specific use case so we won't be adding it at this time.

Regardless, you can still achieve this using custom validation:
```js
$(document).on('carbonFields.apiLoaded', function(e, api) {
    $(document).on('carbonFields.validateField', function(e, fieldName, error) {
        if (fieldName === 'some_field_name_here') {
            var value = api.getFieldValue(fieldName);
            if (value.length % 2 !== 0) {
                return 'You must add an even number of rows to the "Some Field Label Here" field.';
            }
        }
        return error;
    });
});
```

_Note: you must call `set_required()` on the field in question or custom validation will not be applied._

More info here: https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-0-0
