### ISSUE TITLE
Media_Gallery_Field comments typo

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#345]
I assume that it is a work-in-progress, so this is just an FYI - the Media Gallery field comment at the top has copy pasta description from the Set field (lines 9-10):

https://github.com/htmlburger/carbon-fields/blob/master/core/Field/Media_Gallery_Field.php

**Comment by atanas-angelov-dev** [comment]
Fixed in 70052f9eeedfa6c1c7a80a1621d49d74ba8ca754
