### ISSUE TITLE
Conditional display - post meta in all subcategories

### ISSUE THREAD

**Issue by Dimox** [htmlburger/carbon-fields#346]
I want to display post meta in all subcategories of specified category. Is what possible? May be using CUSTOM operator, but how?

**Comment by atanas-angelov-dev** [comment]
Hi @Dimox ,

I'm actually surprised we've missed adding parent/ancestor conditions for terms so I added them to our internal TODO. In the mean time you are correct that you would use the `CUSTOM` operator but I just found a bug while preparing an example for you (kind of a silly situation).

I'll do my best to get these items addressed by 2.1.0 which should be ready (very) soon.

**Comment by Dimox** [comment]
Thank you, Atanas! I'll be waiting for 2.1.0.

**Comment by atanas-angelov-dev** [comment]
2.1.0 has been released which addresses this issue:
https://github.com/htmlburger/carbon-fields/releases/tag/2.1.0
