### ISSUE TITLE
Options are prefixed with underscore, should it be like that?

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#347]
Traditionally WordPress options are not prefixed with underscore (excluding transients) and there's no same kind of publicity aspect as in post/term meta. It is kinda strange that CF prefixes options.

Yes, that is because field handling was unified but I think this should be considered again. There's no any real benefit on prefixing option. It does rather confuse when `get_option` is used instead of `carbon_get_theme_option` (it is much more reasonable in the name of performance, at least when we're dealing with simple key=>value fields).

This is again one of those very small things 😄  But i'd like to see CF work in accordance with core as much as possible.

**Comment by atanas-angelov-dev** [comment]
> There's no any real benefit on prefixing option.

The benefit is simplicity and maintainability. The added complexity is not worth it in my opinion and acts as an exception to the rule in comparison to all other datastores.

It _may_ be possible to drop the prefix with changes only in the `Theme_Options_Datastore` class but this is not really a priority for us right now.

**Comment by erikjoling** [comment]
My case is very much related to this. 

I would like to wrap some default WordPress options in a Carbon Field theme-option wrapper. Options like `blogdescription` and `page_on_front`. (So my custom client-role can change them without having `manage_options` capabilities). With the way things are now there will be redundant database entries. 

![underscore_option_name](https://user-images.githubusercontent.com/20614110/30240817-ce91930c-9577-11e7-833c-971bfcc3cd91.PNG)

I believe WordPress has a convention to store temporary data in underscored prefixed entries and the rest without the prefix.

**Comment by erikjoling** [comment]
Is it possible to override the datastore for multiple fields at once? Or do I have to add it specifically to every field?

**Comment by dmhendricks** [comment]
It is certainly not ideal, but if you were okay with just using CF for the UI in this case, you could do some `carbon_fields_{container_type}_container_saved` manipulation as a cheap trick.
