### ISSUE TITLE
[2.0] Carbon Fields loaded on every admin page

### ISSUE THREAD

**Issue by erikjoling** [htmlburger/carbon-fields#349]
Hi,

I have noticed that the CF containers and fields I use are being loaded on every page in the admin. This includes a lot of calls to the database, which hurts performance significantly I assume. 

Is there a reason for this?

**Comment by atanas-angelov-dev** [comment]
Hi @erikjoling ,

I just tested this using Query Monitor and found no queries are made by Carbon Fields on pages that do not have containers.

I found that we load all JS files (they are all loaded in the footer) which we should probably address but nothing related to database queries.

Do you have a specific query or performance slowdown that is an issue?

**Comment by erikjoling** [comment]
Hi @atanas-angelov-dev ,

Hmmz, I can't seem to reproduce it. This was my test function. 

```
Container::make('theme_options', 'Test')
    ->set_page_parent('themes.php')
    ->add_fields(array(
        Field::make('select',  'ejo_test')->add_options('ejo_test_function')
    ));

function ejo_test_function() {
	write_log('this is a test');
	return array( 0 => '' );
}
```
Sorry for the inconvenience :/

**Comment by atanas-angelov-dev** [comment]
Was this message supposed to be posted in another ticket? I'm not sure what you are referring to.

**Comment by erikjoling** [comment]
> Was this message supposed to be posted in another ticket?

No, but I should have elaborated some more I guess.

I used that functionality to test if it would write to the debug.log on some pages. What I was trying to say was that I should have tested it some more before bothering you. 

Thank you for your time.
