### ISSUE TITLE
Bug with map field

### ISSUE THREAD

**Issue by MaximZorya** [htmlburger/carbon-fields#350]
When i  save the selected address, the placemark (after updating the post) is shifted. Most likely the fact is that the coordinates of the placemark are saved with "," and not with "."

**Comment by atanas-angelov-dev** [comment]
Hi @MaximZorya ,

I could not reproduce this issue:
1. Searched for an address
2. Saved
3. Confirmed the pin was at the exact same position

Can you share a reproduction case?

> Most likely the fact is that the coordinates of the placemark are saved with "," and not with "."

The coordinates are saved with `.` - the `,` you see is a separator between `lat,lng`.

**Comment by MaximZorya** [comment]
Hello,
i'm search http://joxi.ru/Grqz68QSQ70ZLm
after update post/theme options http://joxi.ru/RmzeOjRH0g3a6r
how i get params in template : carbon_get_theme_option('restart_map')
return http://joxi.ru/zANyZ7KuBGaR32

**Comment by atanas-angelov-dev** [comment]
This is what I receive when I do the same:
```
Array
(
    [value] => 50.430004,30.4871595
    [lat] => 50.430004
    [lng] => 30.4871595
    [zoom] => 17
    [address] => г. Киев, ул. Кудряшкова 20А
)

```

Is it possible that you have a translation/localization plugin that affects how decimals are displayed (comma instead of fullstop) and thus breaks the coordinates?

**Comment by MaximZorya** [comment]
Thank you very much, the thing was this :
setlocale(LC_ALL, 'ru_RU.UTF-8');

Thanks for your work. Wonderful plugin !!!

**Comment by atanas-angelov-dev** [comment]
Always happy to help! 👍
