### ISSUE TITLE
Fields missing

### ISSUE THREAD

**Issue by remendoapp** [htmlburger/carbon-fields#352]
I have set up the project with Composer and are having the Containers showing like they should. Bot the fields in the containers are missing. There is just an empty <fieldset> tag.

If i feed a random string or class into the container instead of a Field class it complains like expected. So it seems like the Fields are getting loaded but are somehow not shown.

I am getting no errors.

Theme is sage 9 on a bedrock installation.

**Comment by atanas-angelov-dev** [comment]
Hi @remendoapp ,

Please take a look at the Bedrock support docs page as there's a caveat you should be aware of - https://carbonfields.net/docs/guides-bedrock-support/?crb_version=2-0-0

Also, please confirm if you are getting 404s on carbon field assets failing to load (carbon.core.js, carbon.vendor.js etc.)

**Comment by remendoapp** [comment]
Damn. Totally overlooked it. 

That did the trick, thank you.

**Comment by jeffmagill** [comment]
For anyone else that stumbles on this, heres an extra tidbit. The page that atanas referenced says to replace `YOUR_DESIRED_PUBLIC_LOCATION` without saying what it should be replaced with. If youre using Carbon Fields in your theme, it should be replaced with the base path to your theme.

```
"extra": {
    "installer-paths": {
        "web/app/themes/<your theme slug here>/vendor/{$vendor}/{$name}": ["htmlburger/carbon-fields"]
    }
}
```

**Comment by porobertdev** [comment]
> For anyone else that stumbles on this, heres an extra tidbit. The page that atanas referenced says to replace `YOUR_DESIRED_PUBLIC_LOCATION` without saying what it should be replaced with. If youre using Carbon Fields in your theme, it should be replaced with the base path to your theme.
> 
> ```
> "extra": {
>     "installer-paths": {
>         "web/app/themes/<your theme slug here>/vendor/{$vendor}/{$name}": ["htmlburger/carbon-fields"]
>     }
> }
> ```

Thank you! I can confirm that it's working with sage11.

By default composer installs in root's /vendor which causes `TypeError: can't access property "initialize", cf.core is undefined` in the WP admin panel and the fields are missing.

If someone using sage 11 comes here, **ignore** [this 2018 thread on root's forum](https://discourse.roots.io/t/how-to-setup-carbon-fields-in-sage/12315). All I had to do was the [quickstart](https://carbonfields.net/docs/carbon-fields-quickstart-2/?crb_version=2-2-0) from carbon's documentation.
