### ISSUE TITLE
set_conditional_logic checkbox

### ISSUE THREAD

**Issue by filippozanardo** [htmlburger/carbon-fields#353]
Hi,
i saw that if i use set_conditional_logic on checkbox the beahviur is strange:
for example:

`Field::make( 'checkbox', 'crb_show_socials2', 'Show content' )
				    ->set_option_value( 'yes' ),

				Field::make( 'text', 'crb_facebook', 'Facebook URL' )
				    ->set_conditional_logic( array(
				        'relation' => 'AND', // Optional, defaults to "AND"
				        array(
				            'field' => 'crb_show_socials2',
				            'value' => 'yes', // Optional, defaults to "". Should be an array if "IN" or "NOT IN" operators are used.
				            'compare' => '=', // Optional, defaults to "=". Available operators: =, <, >, <=, >=, IN, NOT IN
				        )
				    ) ),
`

when i tick the checkbox the field crb_facebook never show, but if i make the reverse condition with:
`'value' => ''`

when i tick the  checkbox the field disappear.

I'm using the latest composer version.
Thanks

**Comment by atanas-angelov-dev** [comment]
Hi @filippozanardo ,

I believe the docs are a bit out of date in this case - the value for checkbox should be compared with a boolean value rather than the option string (we should have a fix for this in the docs soon).

**Comment by filippozanardo** [comment]
Ok thanks works now.
