### ISSUE TITLE
Generate nested fields using a function

### ISSUE THREAD

**Issue by kaleidoscopique** [htmlburger/carbon-fields#362]
Hey,

Thanks for the v2.1.0! It's great to see so many improvements and new features on CarbonFields.

I've got an issue with ::add_fields, I hope you can help me figure out why! I need to generate :add_fields using a function – because field's names and ids depends on dynamical data.

It works fine "visually", **but nothing is saved when I use it**. Maybe because created fields share the same object, with the same ID, or something like that?

If you understand the situation, do you have any opinion on what to do? Maybe a workaround or a better way to do it?

```php
Field::make( 'complex', 'main_field')
->add_fields( $this->generateFields() );
```

and

```php
private function generateFields()
{
	$data = [........]; /* fetch data from database */
	$fields = [];
	foreach ($data as $id => $_data)
	{
		$fields[] = Field::make( 'select', "field_$id" )
		->add_options( [$_data => $_data] );
	}
	return $fields;
}
```

Thanks a lot!
Stéphane

**Comment by atanas-angelov-dev** [comment]
Most likely your ids change from request to request so you end up with "different" fields being defined every request. You can confirm this is the problem by inspecting the fields using your browser's DevTools and check if the generated &lt;select&gt;'s name attribute is different before and after you submit.

In order to help you further I'll need more information on these IDs (what they are, how you get them etc.)

**Comment by kaleidoscopique** [comment]
Hey @atanas-angelov-dev,

I got what you mean, so I investigate a lot on my side. 

I'm now working on a simplified version of my real code to understand what's happening. What I have discovered is REALLY strange, tell me if it means something for you!

```php
// My CarbonFields structure
$container->add_tab( 'Test', array(
	 Field::make( 'complex', 'complex_field' ) 
		->add_fields( 'sub_complex_field', array(
			Field::make( 'complex', 'sub_sub_complex_field' )
		                ->add_fields( $this->generateFields() ),
			))
	    ));
```

In the following code, when I'm using $data1, it doesn't work. I can't save anything, it always come back to the default value. If I'm using $data2, it works fine!

```php
private function generateFields()
{
		$data1 = $this->getPersonalities(); // get data from a function
		$data2 = ['Perso1', 'Perso2', 'Perso3']; // "hard coded" data, but EXACTLY the same as $data1 as you will see

		// if ($data1 === $data2) {
		// 	die('equal');
		// } else { 
		// 	die('not equal'); 
		// }
		// => Returns 'equal'
		
		// var_dump($data1);
		// var_dump($data2);
                // Returns :
		// array(3) { [0]=> string(6) "Perso1" [1]=> string(6) "Perso2" [2]=> string(6) "Perso3" } 
		// array(3) { [0]=> string(6) "Perso1" [1]=> string(6) "Perso2" [2]=> string(6) "Perso3" }

		$fields = array();

		foreach ($data1 as $id => $_data)
		{
			$fields[] = Field::make( 'select', "my_fields_$id", $_data )
			    ->add_options( ['foo' => 'foo', 'bar' => 'bar', 'foobar' => 'foobar'] );
		}

		return $fields;
	}
```

First step, I'm setting some data (bar, bar, foo) :

<img width="752" alt="screen shot 2017-09-27 at 13 02 12" src="https://user-images.githubusercontent.com/1452735/30910237-34b1d4a2-a384-11e7-94f0-109a0dfb58e7.png">

Then I save. Page refreshes, and here is what's displayed (foo, foo, foo)

<img width="738" alt="screen shot 2017-09-27 at 13 02 42" src="https://user-images.githubusercontent.com/1452735/30910241-37a4746c-a384-11e7-86e1-f519d781fa18.png">

I'm very frustrated but curious to understand this issue. Do you have any clue?

**Comment by kaleidoscopique** [comment]
(and `$data1` DOESN'T change. They are dynamical data from other CarbonFields values, but on another part of the site – which I don't change between tests, of course)

**Comment by atanas-angelov-dev** [comment]
I believe the situation with `getPersonalities()` may not be as simple as it appears as you cannot pass identical data to add_fields() and receive different results - the source of `getPersonalities()` may be helpful.

It would be best if you can setup a blank WordPress installation using the twentyseventeen theme and reproduce the problem there.

**Comment by kaleidoscopique** [comment]
Hey @atanas-angelov-dev,

I created a blank WP site for you, then I've simplified my code the most I could. Even with a very simple code, the bug happens! It's very, very curious.

**Login :** atanas
**Password :** h$#D49fQPPvU9i@B9LzDajsc

**URL of the custom post type :** http://debug.institut-pandore.com/wp-admin/post.php?post=8&action=edit

**URL of the plugin's file to investigate :** http://debug.institut-pandore.com/wp-admin/plugin-editor.php?file=wp-viral-quiz-debug%2Fincludes%2FWPVQGR_type_perso_meta.php&plugin=wp-viral-quiz-debug%2Fwp-viral-quiz-debug.php

**How to reproduce the bug easily :** 

1. On the "My Test" tab, try to change values and save. It won't work. "Perso1, Perso2, Perso3" are generated getting the values created in the "Personalities" tab.

2. If you change $data1 by $data2 (line 85) in the foreach statement, it will work fine. But $data1 and $data2 are exactly the same.

Thanks a lot for helping me to understand what's happening.

**Comment by atanas-angelov-dev** [comment]
Can you zip this up and send it to me for further investigation? I have to be able to reproduce it locally in order to debug it (you can send it privately through Gitter - https://gitter.im/carbon-fields/Lobby).

_(also I locked myself out with a conditional exit in a very stupid way ... oops)_

**Comment by kaleidoscopique** [comment]
Issue found by @atanas-angelov-dev. In case it can help someone else, here's the answer.

Don't use `$_GET['post']` to get the the current post/page's ID on an edit page, like for instance : 

```php
$carbon_data  =  carbon_get_post_meta($_GET['post'], 'personalities');
```
As @atanas-angelov-dev explained:

In a normal request you have the `$_GET['post']` value, however, when you save a post you have `$_POST['post_ID']` instead so during a POST request `carbon_get_post_meta()` will return an empty array instead of the personality values since an empty value is passed as the post id.

To fix this your code should be something like this:

```php
$post_id = 0;
if ( $_SERVER['REQUEST_METHOD'] === 'POST' ) {
    $post_id = isset( $_POST['post_ID'] ) ? intval( $_POST['post_ID'] ) : 0;
} else {
    $post_id = isset( $_GET['post'] ) ? intval( $_GET['post'] ) : 0;
}
$carbon_data  =  carbon_get_post_meta($post_id, 'personalities');
```

Good to know :)
