### ISSUE TITLE
Only the following attributes are allowed: data-*

### ISSUE THREAD

**Issue by jackreichert** [htmlburger/carbon-fields#364]
Updated to 2.1

Getting the following error: "Only the following attributes are allowed: data-*"

But on https://carbonfields.net/docs/fields-text/ it says that these are allowed: 'max', 'maxLength', 'min', 'pattern', 'placeholder', 'readOnly', 'step', 'type' and 'data-*'.

Pretty sure https://github.com/htmlburger/carbon-fields/blob/b14a7d783ac3967034d5c98fb0c1bc950c1e12a5/core/Field/Field.php#L166 should be 
`protected $allowed_attributes = array( 'max', 'maxLength', 'min', 'pattern', 'placeholder', 'readOnly', 'step', 'type' );`

**Comment by atanas-angelov-dev** [comment]
Hi @jackreichert ,

Are you creating a text or a textarea field? You can see that those fields are setup:
https://github.com/htmlburger/carbon-fields/blob/master/core/Field/Text_Field.php
https://github.com/htmlburger/carbon-fields/blob/master/core/Field/Textarea_Field.php

**Comment by jackreichert** [comment]
Hmm, thanks, ok. I guess composer pulled the wrong version.

I'll see what's up with that.

**Comment by jackreichert** [comment]
Config issue, thanks for your quick response!
