### ISSUE TITLE
Filter field & container visibility

### ISSUE THREAD

**Issue by uamv** [htmlburger/carbon-fields#370]
Are there any filters that can be used to determine whether a field (or container) is displayed after having been declared? I notice there are ways to define conditionals for containers and fields upon declaration. I'm looking for some way to remove fields after they've been declared in a container.

If this is not possible, I'd propose as a feature request. Thank you!

**Comment by atanas-angelov-dev** [comment]
Hi @uamv ,

You can use conditional logic (near the bottom of https://carbonfields.net/docs/fields-usage/?crb_version=2-1-0) to conditionally show fields based on other fields in the same container.

**Comment by uamv** [comment]
I did see that. However, that also needs to be defined when the container is declared. I'm curious about some way in which to limit the fields after declaration. For example, I have a situation where I have declared a container within a plugin and am wanting to use some other plugin or the theme's `functions.php` to hide a specific field.

**Comment by atanas-angelov-dev** [comment]
Then I'd suggest you pass your fields array through `apply_filters()` before passing it to `add_fields()`, for example.

**Comment by uamv** [comment]
Just revisiting this. Thanks. It works great for filtering the available fields. However, if I filter out all fields and return an empty array, the container still shows. It'd be great to also have some way that the container itself disappears if no fields are registered within it. Any thoughts on that?

**Comment by uamv** [comment]
I was digging into the condition types for containers, but don't see any simple boolean condition. Am I missing something or is that not currently an option?

**Comment by atanas-angelov-dev** [comment]
Why not simply do this:

```php
$fields = apply_filters( 'my_fields_filter', $fields );
if ( ! empty( $fields) ) {
	Container::make( ... )
		->add_fields( $fields );
}
```

Boolean condition doesn't really make sense when you can simply not define the container at all.
Regardless, you can still achieve something like that using a suitable condition with the CUSTOM operator e.g.:
```php
Container::make( ... )
	->where( 'post_id', 'CUSTOM', function( $post_id ) {
		return false;
	} );
```

**Comment by uamv** [comment]
Where's the hand-to-face reaction? This is great. Thank you for your response and time!
