### ISSUE TITLE
Date_Field enable/disable option callback

### ISSUE THREAD

**Issue by soulseekah** [htmlburger/carbon-fields#371]
As per https://chmln.github.io/flatpickr/examples/#disabling-all-dates-except-select-few flatpickr allows us to enable and disable dates based on a javascript callback. There is no mechanism of supplying a callable in JSON.

Any thoughts on how to do this?

**Comment by atanas-angelov-dev** [comment]
Hi @soulseekah ,

Currently there is no built-in way to do this. I suggest you write a custom field for this as you will have full control of the php and js side so you can write back-end validation as well.
