### ISSUE TITLE
Display error message to front-end when "Uncaught Error: Call to a member function format() on boolean"

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#373]
I had complex fields imported with a few bad formatted dates ( d-m-Y instead of Y-m-d).
This prevented the fields from loading on post screen, but no error was displayed in front end / console, only in server PHP error log.

Is it possible to display when this error occurs "Uncaught Error: Call to a member function format() on boolean" a error message to front end or at least to js console log.

php error log of this error:
2017/10/06 16:23:10 [error] 9342#0: *3426 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function format() on boolean in /var/www/html/site/wp-content/themes/theme/vendor/htmlburger/carbon-fields/core/Field/Date_Field.php:63
Stack trace:
#0 /var/www/html/site/wp-content/themes/theme-underscores/vendor/htmlburger/carbon-fields/core/Field/Complex_Field.php(562): Carbon_Fields\Field\Date_Field->to_json(false)
#1 /var/www/html/site/wp-content/themes/theme-underscores/vendor/htmlburger/carbon-fields/core/Container/Container.php(781): Carbon_Fields\Field\Complex_Field->to_json(true)
#2 /var/www/html/site/wp-content/themes/theme-underscores/vendor/htmlburger/carbon-fields/core/Loader/Loader.php(221): Carbon_Fields\Container\Container->to_json(true)
#3 /var/www/html/site/wp-content/themes/theme-underscores/vendor/htmlburger/carbon-fields/core/Loader/Loader.php(248): Carbon_Fields\Loader\Loader->get_json_data()
#4 /var/www/html/site/wp-includes/class-wp-hook.php(298): Carbon_Fie" while reading upstream

**Comment by atanas-angelov-dev** [comment]
Thank you for the report @BenBroide !

Fixed in 2.1.1 - closing.
