### ISSUE TITLE
select add_options() callback slows site down

### ISSUE THREAD

**Issue by batz-bar** [htmlburger/carbon-fields#374]
I noticed while optimizing loading time of a site that when a select field is set with a callback in add_options() to get array of options, the callback is called on every WordPress load and slow the site when the callback calls DB for data.

I probably could save the values in a transient, but it would be better if the callbacks will be called only on edit post pages

Example: 

`Field::make('select', 'city')->add_options(get_cities() )`

It it possible that the get_cities() function would be called only on edit post page instead of every site load?

Attached screenshot from monitor query which shows in wp-admin main page a query from a callback inside add_options( )

The field is:

`Field::make('select', 'client_id', 'Client')->add_options(Client_Data::get_clients_select() )`

![select callback](https://user-images.githubusercontent.com/11011901/31320988-f112a0a2-ac4b-11e7-8dac-217780f21a84.png)

This ticket may be about the same issue https://github.com/htmlburger/carbon-fields/issues/349

Thanks for this great plugin.

**Comment by atanas-angelov-dev** [comment]
Hi @batz-bar ,

To improve performance pass the callback function's name as a string (or any [callable](http://php.net/manual/en/language.types.callable.php)) like this:
```php
Field::make('select', 'city')->add_options( 'get_cities' )
```
This way the callable will be called only when the select needs to load/display the options.

I added a note to our internal TODO to improve the docs with emphasis on this way of using add_/set_options.

**Comment by erikjoling** [comment]
> This ticket may be about the same issue #349

Yes, exactly my problem! Obviously I couldn't reproduce it because I used a callback function's name in my example. 

Is it possible to pass variables to a callback function?

**Comment by atanas-angelov-dev** [comment]
Just wrap it in an anonymous function:
```php
Field::make('select', 'city')
	->add_options( function() {
		return get_cities( $my, $custom, $args );
	} );
```

**Comment by erikjoling** [comment]
Thank you. I'll try it out

**Comment by erikjoling** [comment]
Got it working. I ended up using an easier case of an anonymous function.

```
Field::make('select', 'city')
	->add_options( function() {
		return get_cities( 'Amsterdam' );
	} );
```

**Comment by atanas-angelov-dev** [comment]
Docs updated: https://carbonfields.net/docs/fields-select/?crb_version=2-1-0
