### ISSUE TITLE
PHP Deprecated: Non-static method ... get_attachment_id() should not be called statically

### ISSUE THREAD

**Issue by tova-moskowitz** [htmlburger/carbon-fields#377]
Error log:
PHP Deprecated:  Non-static method Carbon_Fields\Helper\Helper::get_attachment_id() should not be called statically in htmlburger/carbon-fields/core/Helper/Helper.php on line 471

Resolved this by turning get_attachment_id into a public static function on line 406

**Comment by atanas-angelov-dev** [comment]
Hi @tova-moskowitz 

A fix is already in our development branch (e7b731ca8d93bde83a46df5dd1cfa76de0f2aeb2) - thank you for the report regardless :)

I'll close this ticket once the fix is live.

**Comment by tova-moskowitz** [comment]
Great, thank you

**Comment by atanas-angelov-dev** [comment]
Fixed in 2.1.1 - closing.
