### ISSUE TITLE
WordPress 4.9 / Code Editor field

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#380]
It would be neat if the `textarea` field could be extended to enable WP 4.9's new CodeMirror support: https://kinsta.com/blog/wordpress-4-9/#attachment_13855

Although not everyone will update to 4.9+ right away, given time, it will be ubiquitous enough to be a handy option. Of course, if WP version <4.9, I would assume it would default to a `textarea`.

This would also be handy for the header/footer scripts field types, too. I would love it if it was an option on any `textarea`, though, because I often do my own logic or preprocessing.

**Comment by dmhendricks** [comment]
I think you could just add a `->set_code_editor( 'css' );` method (for example) to `textarea`, which would add a special CSS class to it (such as `carbon-code-editor` and maybe a `data-language="css"` attribute)... then inject some jQuery like:

```
$( '.carbon-code-editor' ).each( function( idx, el ) {
    var editor = CodeMirror.fromTextArea( el, {
        lineNumbers: true, // This code be added as a method/data option as well, or maybe added as a parameter to set_code_editor()
        mode: el.data( 'language' )
    });
});
```

Untested for syntax, but you get the idea (and, of course, the selectors and injection could be optimized - it is just an example). I will test later as I need this for some fields - maybe I'll try it with Gutenberg as well and see how it blows up. Of course, this would only work with WordPress 4.9+ unless you also enqueued CodeMirror (I probably wouldn't bother with that - just don't enable it if $wp_version < 4.9).

There is probably a better way to do it with React, but I am not an expert in that.

**Comment by jorostoyanov** [comment]
I don't think this should be added in core since the feature request didn't gain any popularity for the last 3 years.

Instead, an add-on library can be developed and used if needed.

Thanks for understanding! :-)
