### ISSUE TITLE
Place post_meta metabox above main editor?

### ISSUE THREAD

**Issue by drdogbot7** [htmlburger/carbon-fields#382]
I'm wanting to place a metabox below the title and above the main editor. I this know it can be done with a separate function, but is there a way to do it using the built-in configuration?

I've tried:

```
    ->set_priority( 'high' )
    ->set_context( 'advanced' )
```

**Comment by atanas-angelov-dev** [comment]
Hi @drdogbot7 ,

We recently added support for this out-of-the-box:
`->set_context( 'carbon_fields_after_title' )`

https://carbonfields.net/docs/containers-post-meta/?crb_version=2-1-0

**Comment by drdogbot7** [comment]
Awesome,Thanks!
