### ISSUE TITLE
How to set dynamic options via js in associate component? it's possible?

### ISSUE THREAD

**Issue by kassyn** [htmlburger/carbon-fields#384]

**Comment by atanas-angelov-dev** [comment]
Hi @kassyn ,

Could you please clarify your question a bit - are you looking into:
- adding more options to the field which the user can select (i.e. populating the left column)
- selecting options (i.e. marking items as selected from the left into the right column)
- or something else?

**Comment by kassyn** [comment]
Hi @atanas-angelov-dev,

I need adding more options to the field which the user can select (i.e. populating the left column).

In my page where the associate metabox will be displayed I will have filters (i.e. by terms of a taxonomy). When the filter checkbox is checked I need to filter the items in the left column

Thank's

**Comment by atanas-angelov-dev** [comment]
Unfortunately, there is no built-in functionality for this, however, you can achieve this by writing your own custom field instead (you can use our starter template here: https://github.com/htmlburger/carbon-field-template).

**Comment by kassyn** [comment]
@atanas-angelov-dev thanks
