### ISSUE TITLE
Can't install Carbon Fields

### ISSUE THREAD

**Issue by dameer** [htmlburger/carbon-fields#387]
Anyone having idea what's going on with regards to installing the library?
![error](https://user-images.githubusercontent.com/1826261/31939251-117b9068-b8ba-11e7-961d-b7c0d2d7d440.png)

**Comment by atanas-angelov-dev** [comment]
Hi @dameer ,

This looks like a local problem with your composer setup - you can see it properly detected the latest stable version (`Using version ^2.1`) but then it failed to resolve that same version.
In addition, I just ran the same command and composer correctly installed the latest stable version on my setup.

Please make sure your composer is up to date and clear it's cache before testing again.

**Comment by dameer** [comment]
Thanks for a speedy response!
Latest Composer installed, cache cleared, it worked fine  until I tried to install CF. I'm going crazy (about to take a couple or tranquilizers).
Does the following tell anything being wrong?

![composer](https://user-images.githubusercontent.com/1826261/31945510-af4a2e70-b8cf-11e7-8588-c1e2bb5fe226.png)

![bash_profile](https://user-images.githubusercontent.com/1826261/31945513-b3318542-b8cf-11e7-9067-86111bf31909.png)

**Comment by atanas-angelov-dev** [comment]
Just tested in another dev environment and could not reproduce the issue here as well.
Could you please share your composer.json?

**Comment by dameer** [comment]
I've been told by another friend of mine that the error comes from Composer itself and has nothing to do with Carbon Fields' "composer.json".  Symfony is not CF's dependency so there's actually no reason for such error.

However, I'm still not clear why the problem persist. CF library is downloaded from this repo (including "composer.json") and Composer re-installed by following instructions found here: https://gist.github.com/kkirsche/5710272

On a side note, I have also tried to install Fragment Cache ( http://composer.rarst.net/case-study/fragment-cache#composerjson ) via Composer and the installation failed for another reason:

![fragment_cache](https://user-images.githubusercontent.com/1826261/32039952-54c6c164-ba2f-11e7-8800-7ba44989f874.png)

I'm using MAMP Pro 4.2.1 (MacOSX) running the latest PHP 7.1.8.

I am really sorry for causing troubles here, you may want to shut this thread down coz I'm obviously dealing with an issue that CF is not involved with. I'll continue investigation as far as my knowledge goes and eventually get back here to re-post in case the problem is actually CF related.

**Comment by atanas-angelov-dev** [comment]
No worries - thanks for letting us know!
