### ISSUE TITLE
[Feature] Set field as tab title in complex field

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#388]
Please add method for fields to set field as title of tabs in complex field. It will add convenience of editing content in elements of complex fields.

Example:
```
Field::make('complex', 'complex_field', 'Complex field')
	->set_layout('tabbed-vertical')
	->add_fields(array(
		Field::make('text', 'title', 'Title')
			->set_as_tab_title(),
		Field::make('textarea', 'text', 'Text')
	))
```
![25-10-2017 11-25-51](https://user-images.githubusercontent.com/12094229/31983585-4dc19118-b977-11e7-93bd-058953e040a1.png)

**Comment by atanas-angelov-dev** [comment]
Hi @zevilz ,

Please refer to the `set_header_template()` part of the documentation here:
https://carbonfields.net/docs/complex-field-config-methods/?crb_version=2-1-0

**Comment by zevilz** [comment]
@atanas-angelov-dev , thanks. It working perfectly
```
Field::make('complex', 'complex_field', 'Complex field')
	->set_layout('tabbed-vertical')
	->add_fields(array(
		Field::make('text', 'title', 'Title'),
		Field::make('textarea', 'text', 'Text')
	))
	->set_header_template( '
		<% if (title) { %>
			<%- title %>
		<% } else { %>
			empty
		<% } %>
	' )
```
This is flexible solution, but it would be advisable to add a separate method for set value of field as tab title)

**Comment by atanas-angelov-dev** [comment]
We are not looking into adding this in the near future as templates already cover this functionality and the cost of the shortcut doesn't seem to be warranted as it will complicate the codebase in order to cover use-cases that are already covered by templates.
