### ISSUE TITLE
Media gallery UI issue in tabs

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#389]
It is a issue in the media gallery field, in which each image takes full horizontal space. Problem only when field in tab (not first). However, resizing and maximizing browser brings back all images in a row only on opened tab.

After page load
![08-10-2017 21-18-55](https://user-images.githubusercontent.com/12094229/31318594-54469ef4-ac6e-11e7-972b-968a4d8b09f0.png)

After window resize
![08-10-2017 21-37-00](https://user-images.githubusercontent.com/12094229/31318793-f576e55c-ac70-11e7-8676-ecefb0030bd3.png)

Issue present in Linux (tested in Firefox 53/57 and Crome 61.0.3163.100) and in Windows (tested in Firefox 47 and Crome 59.0.3071.115)
Issue isn't present in MacOS (tested in Safari v. 11.0 and Chrome v. 60.0.3112.90)

CF v. 2.1.0/2.1.1-beta.2/2.1.1-beta.5 

[issue video demonstration](https://yadi.sk/i/QwDX9mPb3P5rzj)

**Comment by jorostoyanov** [comment]
Hi @zevilz ,

Thank you for the report!

I was able to reproduce the issue and I've pushed a fix in the development branch -- https://github.com/htmlburger/carbon-fields/commit/d9eaaa2702e4b645cb5871f0004315c63b5f2359

I'll close this ticket once the fix is live.

**Comment by atanas-angelov-dev** [comment]
Fixed in 2.1.1 - closing.
