### ISSUE TITLE
Checkbox return value should be boolean?

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#39]
I've noticed that the checkbox field returns `yes` as it's value, shouldn't it be better a boolean value? I imagine that changing this will break old code so probably there is nothing to do. At least this can go to the wishlist of the next major version… :-)

**Comment by doup** [comment]
Btw, it's not a big issue:
```
$is_not_ready = carbon_get_the_post_meta('is_not_ready') === 'yes';
```

**Comment by lceberg** [comment]
You can still change the checkbox value if you need to by using the `set_option_value($value)` method:
https://carbonfields.net/docs/fields-checkbox/

**Comment by doup** [comment]
Closing this since it has a simple solution (`=== 'yes'`) and probably it would be backward incompatible to change the behaviour.
