### ISSUE TITLE
Change return class for the chained field calls to improve IDE completion

### ISSUE THREAD

**Issue by chetzof** [htmlburger/carbon-fields#395]
The problem:
When using chaining to build the field, 
```
/** @var Field\Complex_Field $field */
$field =  Field::make('complex','id');
$field
->set_collapsed() // php doc return type Field
->add_fields() // Method marked as undefined, because the method does not exist in the Field class
```
I suggest changing all return values for chained calls from
`@return Field $this` to `@return self $this` or `@return $this` so that the IDE can understand which field instance is returned.

What do you think?

**Comment by atanas-angelov-dev** [comment]
Thank you for the suggestion @chetzof !

Closing as addressed in 2.1.1
