### ISSUE TITLE
WP_Query with meta_query holds the same post

### ISSUE THREAD

**Issue by obstschale** [htmlburger/carbon-fields#396]
The following bug was first experienced at version "2.0.5-beta.1", then I updated to "2.1.1-beta.5" but the bug is still there.

---

I have several fields on a custom post type and I want to query posts given a specific meta_query.

So I have a container with a date field and an association field. The query looks for `crb_statistics_season` field and for a specific season with the ID 219. 

If there is only 1 post that matches this condition the query will return this post. However if there exist many posts with season 219 the query will return the last post, which matches this condition x times, where X is the correct number of posts, which fulfill the condition. For example: I have 3 posts where the association field holds the season post 219. The Query will return 3x the last post object.

I tested this with simple fields, association fields, and even complex fields.

My Container looks like
```
Container::make( 'post_meta', __( 'Match Information', 'textdomain' ) )
            ->show_on_post_type( self::NAME )
            ->add_fields( [
                Field::make( 'date', 'crb_statistics_match_date', __( 'Matchday', 'textdomain' ) )->set_input_format( 'd. M Y', 'd. M Y'),
                Field::make( 'association', 'crb_statistics_season', __( 'Season', 'textdomain' ) )
                    ->set_types( [
                        [
                            'type'      => 'post',
                            'post_type' => Seasons::$name,
                        ]
                    ] )
                    ->set_max( 1 )
                    ->set_min( 1 ),
            ] );
```

My Query looks like
```
$query = new WP_Query( [
            'post_type'  => Match::NAME,
            'meta_query' => [
                [
                    'key' => 'crb_statistics_season',
                    'value'  => 'post:vfb-seasons:219', // This is the same value as in the database. The 219 is the ID of the season post.
                ],
            ],
        ] );
```

**Comment by obstschale** [comment]
Through debugging I found some new information:

Given the following query. I use a `while` loop to get the posts.

```php
$query = new WP_Query( [
    'post_type'  => Match::NAME,
    'meta_query' => [
        // carbon field meta query
    ],
] );

while ( $query->have_posts() ) {
    // some code
   $query->next_post();
}
```

The `$query` object holds all correct posts in `$query->posts[]`. When I call `$query->next_post()` the `$query->post` property should be updated to the next post from this `posts[]` array. However the property stays the same. So the update mechanism does not work.

**Comment by atanas-angelov-dev** [comment]
Just to clarify, have you tried this:
```php
<?php
$query = new WP_Query( [
	'post_type'  => Match::NAME,
	'meta_query' => [
		// carbon field meta query
	],
] );

while ( $query->have_posts() ) {
	$query->the_post();
	// some code
}
wp_reset_postdata();
```

This is how custom queries should be looped - if this is not how you originally tried it then this is not a bug with Carbon Fields.
https://codex.wordpress.org/Class_Reference/WP_Query (Usage -> Standard Loop)

**Comment by obstschale** [comment]
Oh man 😖 That is embarrassing. I don't know how I could up mixed up `the_post()` and `next_post()`. 

Sry for wasting your time and thank you for your kind reply :+1:
