### ISSUE TITLE
Option to display fields in edit_form_* hooks

### ISSUE THREAD

**Issue by mikeschinkel** [htmlburger/carbon-fields#398]
We would really like to be able to display fields in the `'edit_form_after_title'` area instead of in meta boxes.  

I worked really how to try to find a way to do so but was stymied by almost every approach I tried. I tried to create my own container type, but you have hardcoded containers to your namespace.  I then tried to inherit from it and modify via a hook, but your `private` properties stopped me from changing `id` and there was also no way to delete a container that I attempted to clone and modify.

So after I tried many things I finally said screw it and used this hacky way:

```<?php

class Carbon_Fields_Post_Meta_After_Title {

	/**
	 * Just a unique value to output so a str_replace() can replace it.
	 */
	const PLACEHOLDER = '~<[' . __CLASS__ . ']>~';

	static function on_load() {
		add_action( 'edit_form_after_title', [ __CLASS__, '_edit_form_after_title' ] );
		add_action( 'dbx_post_sidebar', [ __CLASS__, '_dbx_post_sidebar' ] );
	}

	/**
	 * Buffers output and outputs a placeholder into the buffer.
	 * Buffered output will be processed by _dbx_post_sidebar().
	 */
	static function _edit_form_after_title() {

		ob_start();

		echo self::PLACEHOLDER;

	}

	/**
	 * Processes the output buffered by _dbx_post_sidebar().
	 * Finds a "{Whatever Details}" Carbon Fields container and
	 * moves to location of edit_form_after_title placeholder.
	 */
	static function _dbx_post_sidebar() {

		do {

			$replacement = null;

			$html = ob_get_clean();

			$regex = '#^(.+)(<div id="carbon_fields_container_[^_]+_details" class="postbox\s+carbon-box"\s*>.+?</div>\s+</div>)(.+)$#ms';
			if ( ! preg_match( $regex, $html, $matches ) ) {
				break;
			}

			$html = "{$matches[ 1 ]}{$matches[ 3 ]}";
			$replacement = "<br>{$matches[2]}";

		} while ( false );

		$html = str_replace( self::PLACEHOLDER, $replacement, $html );

		echo $html;

	}

}
Carbon_Fields_Post_Meta_After_Title::on_load();
```
Suffice it to say I would really like to be able to do this cleanly.

**Comment by atanas-angelov-dev** [comment]
Hi @mikeschinkel,

Isn't the custom `carbon_fields_after_title` context what you are looking for?
https://carbonfields.net/docs/containers-post-meta/?crb_version=2-1-0

**Comment by mikeschinkel** [comment]
@atanas-angelov-dev Oh excellent!  Sorry for that oversight. 

I think the reason is because I was using AutoComplete on PhpStorm and did not see it.  As you can see PhpStorm does not recognize `set_context()` as a valid option because `Container::make()->where()` returns a generic container and `set_content()` is only available in a Post Meta container:

![set-context](https://user-images.githubusercontent.com/153285/32644002-e62bf6e6-c5ac-11e7-900a-76a204def333.png)

That said, there are many places where PhpStorm does not provide autocomplete and/or flags code as invalid so I'm going to close this issue and work on sending you a pull request in hopes of making Carbon Fields fully compatible with PhpStorm's inspections and autocomplete.  Hopefully you'll be interested in that?
