### ISSUE TITLE
Allow registering new Container and Field Types w/custom Namespace

### ISSUE THREAD

**Issue by mikeschinkel** [htmlburger/carbon-fields#399]
Currently you have no way for us to build our own container types and then register them. It seems you force them to be within your namespace. I ran into this at the same time [as here](https://github.com/htmlburger/carbon-fields/issues/398).

It would be really nice if you could make it possible to add custom container and field types under our own namespace.

**Comment by atanas-angelov-dev** [comment]
Hi @mikeschinkel ,

Adding fields under whatever namespace is already available - https://github.com/htmlburger/carbon-field-template includes an example of this.
There are also extension quickstart docs here:
https://carbonfields.net/docs/extending-field-in-a-theme/?crb_version=2-1-0
https://carbonfields.net/docs/extending-field-as-a-library/?crb_version=2-1-0
(both use the template I mentioned)

As for containers - their implementation is much more involved and we are yet to implement a simpler way to write your own. If there's a specific container type you are interested in feel free to post a separate feature request for it (I've already responded to #398 so no need for this case specifically).

**Comment by mikeschinkel** [comment]
@atanas-angelov-dev Thanks for the reply.  Sorry I missed how to add a new field; I will study that.

Also, my desire for new containers was based on my interest in adding features to existing containers as we discussed in #398 and not a full understanding of the best way to approach it. 

So it seems this issue is moot and I will close it.  Thanks so much for what was in effect tech support!
