### ISSUE TITLE
Select field not working correctly when option keys are both numeric and strings

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#400]
If `select` field option keys are mixed numeric and strings, the string ones does not get recognized as a selected.

**Comment by atanas-angelov-dev** [comment]
Hi @timiwahalahti ,

Can you please paste an example set of options that reproduce this issue? Also, can you confirm the issue persists on the latest beta?

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
