### ISSUE TITLE
set_default_value doesn't work for AssociationField

### ISSUE THREAD

**Issue by atanas-angelov-dev** [htmlburger/carbon-fields#402]
_Originally posted by @sebastiengregoire_

---

Hi!
`set_default_value` doesn't work on Association field because of the `strval` used in the body of the function (core/Field.php line 605).

Or maybe I don't have the right input format for this setting.

**Comment by atanas-angelov-dev** [comment]
Closing as addressed in 2.1.1

**Comment by pablo-sg-pacheco** [comment]
How can I use the `set_default_value` with the `'association'` field? And does it work with the `'type' => 'term'`?
