### ISSUE TITLE
js & css assets missing

### ISSUE THREAD

**Issue by nabileisa** [htmlburger/carbon-fields#404]
Hi , I followed your instructions on  how to install `carbon-fields` using composer , but it seems to have a problem as it attempts to load this file `vendor/htmlburger/carbon-fields/assets/dist/carbon.boot.min.js?ver=2.1.1-beta.5`  for example when neither this file not the folder `dist` does not exist in the package 
this problem resulted in the library not working at all.
is this a bug or am i missing something ?

**Comment by atanas-angelov-dev** [comment]
Hi @nabileisa ,

Please make sure you are installing a specific stable version of Carbon Fields and not a branch such as `dev-master` as most branches do not contain the dist build files. Here's the correct composer command:
`composer require htmlburger/carbon-fields:^2.1`

**Comment by atanas-angelov-dev** [comment]
The command in the docs is correct. It can install incorrect versions only if you have changed your minimum stability in your composer.json (which is not advisable for production use).
