### ISSUE TITLE
Issue with theme_options, set_page_file and set_page_parent

### ISSUE THREAD

**Issue by vanilium** [htmlburger/carbon-fields#405]
Hi. When I create theme option page and then add subpages for this main page, all work fine. But, when I try set "set_page_file" for main page, in admin panel subpages are hide, hovewer acces for subpages is exists.
How this can be resolved?

Thanks

**Comment by atanas-angelov-dev** [comment]
Hi @vanilium ,

Could you please install the latest beta and confirm if the issue persists?
`composer require htmlburger/carbon-fields:^2.1@dev`

**Comment by vanilium** [comment]
Hi @atanas-angelov-dev ,
Thank you for quick answer. I updated to latest dev version, and now all worked fine.
After update I got a new issue, when I try get option value ( function carbon_get_theme_option ) before call action 'carbon_fields_register_fields'/'carbon_fields_fields_registered', and I resolved this with $wpdb.
Perhaps this is undesirable behavior, or it is caused by the need.
However, my main issue is resolved.

Thank you.

**Comment by atanas-angelov-dev** [comment]
Happy to know the issue is resolved!

PS:
Yes, trying to fetch values before fields are registered is not supported.

**Comment by timiwahalahti** [comment]
@vanilium you can always use wp core function `get_option( '_option_name' )` if the field is that type where value is stored in one row :) It can be used before CRB is loaded.

**Comment by vanilium** [comment]
@timiwahalahti , it's 'set' field, so get_option in this situation not actual. But yes, usage any wp core way can be helped resolve similar issue.
