### ISSUE TITLE
How show options pages for specified user role?

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#407]
How show options pages and some subpages for specified user role (e.g. editor)? CF options pages visible only for admins by default.

**Comment by timiwahalahti** [comment]
With [conditional display](https://carbonfields.net/docs/containers-conditional-display/?crb_version=2-1-0).

```
Container::make( 'theme_options', 'Theme Options' )
    ->where( 'current_user_role', 'IN', array( 'administrator', 'editor' ) )
    ->add_fields( array( ... ) );
```

**Comment by zevilz** [comment]
Not working.

**Comment by timiwahalahti** [comment]
Oh yeah, sorry my bad. That conditional display rule does not work with `theme_options` container as you said.

Correct way to achieve this is by using filter `carbon_fields_theme_options_container_admin_only_access` ([documentation](https://carbonfields.net/docs/advanced-topics-hooks/?crb_version=2-1-0)).

@atanas-angelov-dev conditional types documentation needs some updating since it falsely says that `current_user_role` works with any container.

**Comment by atanas-angelov-dev** [comment]
It does work with the container - please refer to https://github.com/htmlburger/carbon-fields/issues/326#issuecomment-326236771

**Comment by zevilz** [comment]
`add_filter( 'carbon_fields_theme_options_container_admin_only_access', '__return_false' ); `
make access to all options pages and subpages for all user roles.

`->where('current_user_role', 'IN', array('administrator', 'editor'))` make visible options page/subpage only for specified user roles.

But all user roles will have access to options subpages if set options page only for admin and editor.

Example:
```
$basic_options_container = Container::make('theme_options', 'Theme Options') // access and visible only for admins and editors
	->where('current_user_role', 'IN', array('administrator', 'editor'))
	...
Container::make('theme_options', 'Services')  // access and visible only for admins and editors
	->where('current_user_role', 'IN', array('administrator', 'editor'))
	->set_page_parent($basic_options_container)
	->set_page_menu_title('Services')
	->set_page_file('theme-services')
	...
Container::make('theme_options', 'Services 2') // visible only for admins and editors, access for all user roles
	->set_page_parent($basic_options_container)
	->set_page_menu_title('Services 2')
	->set_page_file('theme-services-2')
	...
```

**Comment by atanas-angelov-dev** [comment]
Is there anything pending on this ticket or it can be closed?
