### ISSUE TITLE
Map Field: set_position() method should be deprecated in favor of set_default_value()

### ISSUE THREAD

**Issue by sun1001sun** [htmlburger/carbon-fields#408]
I couldn't cange default position of the map.
I used this code:
<pre>
    Container::make( 'post_meta', __( '06 Карта', 'crb_map' ) )
        ->where( 'post_type', '=', 'post' )
        ->add_fields( array(
            Field::make( 'map', 'crb_house_location', 'Месторасположение' )
	    ->set_position( 55.80938 , 49.11438 , 10)
            ->set_help_text( 'drag and drop the pin on the map to select location' ),
        ) );
</pre>

**Comment by atanas-angelov-dev** [comment]
Hi @sun1001sun ,

It seems we've missed to remove the outdated `set_position()` method. Use this instead:
```php
->set_default_value( array(
	'value' => '55.80938,49.11438',
	'lat' => 55.80938,
	'lng' => 49.11438,
	'zoom' => 10,
	'address' => '',
) )
```

**Comment by sun1001sun** [comment]
Thank you very much!
Now it works with last update :)
Very happy with this plugin!

**Comment by campusboy87** [comment]
@atanas-angelov-dev Previously, using the `set_position()` method, you could center the map in the right place without saving any data if the field was not filled. The `set_default_value()` method saves the value in any case. How can you avoid saving data?

**Comment by atanas-angelov-dev** [comment]
Hi @campusboy87 ,

`set_default_value()` does not save data. It is only autofilled in admin and returned in `carbon_get_*` functions as a convenience. The default value is not stored in the database until a user goes to the appropriate container page and hits the Save/Update button.

**Comment by campusboy87** [comment]
Hi @atanas-angelov-dev  :-)

I perfectly understand your words. But the problem is that these data are preserved. Let's look at the situation. I want the page to have an optional field with a geographic map, which is immediately centered on Paris. Not the default value, which is then saved, but just the initial settings for displaying the map. Now I can not do this, right?

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
