### ISSUE TITLE
File field breaks all fields if file not found

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#409]
When a file field is set to a file ID that not on server, the script errors out and preventing all fields from rendering. 
Is possible to check before if file exist and display message to user if not to prevent breaking all fields.
The error when file does not exists:
```
var carbon_json = <br />
<b>Warning</b>:  filesize(): stat failed for /var/www/html/site/wp-content/uploads/2017/11/file_name.csv in <b>/var/www/html/site/wp-content/themes/theme/vendor/htmlburger/carbon-fields/core/Helper/Helper.php</b> on line <b>499</b><br />
```
Thanks

**Comment by atanas-angelov-dev** [comment]
Hi @BenBroide ,

This is an already addressed issue in 2.1.1 - please update to the latest version and confirm if the issue is resolved.

**Comment by BenBroide** [comment]
Thanks! 
Where I could see 2.1.1 release notes?

**Comment by atanas-angelov-dev** [comment]
We keep our release notes in the Releases section of Github:
https://github.com/htmlburger/carbon-fields/releases

**Comment by BenBroide** [comment]
Thanks
