### ISSUE TITLE
Complex Field: add `collapse all` button

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#41]
It would be a nice addition a `collapse all` link at the top right of the field.

**Comment by wrongman77** [comment]
That feature would be extremely useful. I'm now working on the site with a couple of section consisting a couple of complex fields each and scrolling down every time I save it is very painful.

**Comment by doup** [comment]
See #44 I posted an snippet there. It's a workaround but it'll make your life better. :-)

**Comment by wrongman77** [comment]
Hi, we tried to use it. It worked fine untill we started to use tabs to safe the space. Then tabs wouldn't work. Any solution? I would be very grateful.

**Comment by atanas-angelov-dev** [comment]
A Collapse/Expand All button has been added in 2.1.1
