### ISSUE TITLE
Error Media Gallery

### ISSUE THREAD

**Issue by Grafs** [htmlburger/carbon-fields#415]
Warning: include_once(\wp-content\plugins\carbon-fields/core/Field\Media_Gallery_Field.php): failed to open stream: No such file or directory in \wp-content\plugins\carbon-fields\carbon-fields-plugin.php

**Comment by atanas-angelov-dev** [comment]
Hi @Grafs ,

This doesn't seem like something that can occur normally - Media_Gallery_Field is not referenced in `carbon-fields-plugin.php`:
https://github.com/htmlburger/carbon-fields-plugin/blob/master/carbon-fields-plugin.php

I suspect your file is modified - please copy-paste it's contents to confirm.

**Comment by Grafs** [comment]
I just reinstalled the plugin from the WordPress repository. There is an error.
In the folder with the plugin \wp-content\plugins\carbon-fields\core\ the field file Media_Gallery_Field.php is not present
Code not work:
```
Field::make( 'media_gallery', 'sisters_contest_fotos', 'Test' )
                ->set_type( array( 'image'))
```

**Comment by atanas-angelov-dev** [comment]
The WordPress repository contains the old 1.6 version of the plugin. To install the latest 2.1 version follow this guide instead:
https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-1-0
(You probably want to look at the `Without Composer` section)

**Comment by atanas-angelov-dev** [comment]
You can read more on why the WordPress Plugin repository has an old version here:
https://carbonfields.net/2017/07/31/carbon-fields-distribution-woes/

**Comment by Grafs** [comment]
You can write in the WordPress repository in the description how to install the new version.
Then the questions to you would be less
