### ISSUE TITLE
Can't download from your site

### ISSUE THREAD

**Issue by SaprykinSemen** [htmlburger/carbon-fields#416]
Hello! I can't download that from your site. It's doesn't work.

**Comment by atanas-angelov-dev** [comment]
Hi @SaprykinSemen ,

Did you check out the following pages:
Quickstart: https://carbonfields.net/docs/carbon-fields-quickstart/
Plugin Quickstart: https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-1-0 (especially the "Without Composer" section if you are interested in a zip download)
