### ISSUE TITLE
Documentation correction for Conditional Display page

### ISSUE THREAD

**Issue by iljamm** [htmlburger/carbon-fields#417]
Hi there, awesome code!

Please correct me if I am wrong, but on the following doc page https://carbonfields.net/docs/containers-conditional-display/?crb_version=2-1-0
the sentence "A condition type name as a string (refer to the **Container** Types page)" should read "A condition type name as a string (refer to the **Conditional** Types page)", notice substitution Container -> Conditional.

**Comment by iljamm** [comment]
Another one, on the same page. The sentence "In order to achieve nested display logic the **when()** and **or_when()** methods also support being invoked with a callable:" should read "In order to achieve nested display logic the **where()** and **or_where()** methods also support being invoked with a callable:"

**Comment by atanas-angelov-dev** [comment]
Thank you for the report - both issues have been fixed.

**Comment by iljamm** [comment]
thumbs up!
