### ISSUE TITLE
How to create tabbed theme option panel

### ISSUE THREAD

**Issue by ashraf92** [htmlburger/carbon-fields#42]
Hi 

Just saw the plugin . I have used Option tree for many years but this plugin seems interesting . I was able to create theme option panel . How can I create tabbed group/option panel?

**Comment by emohamed** [comment]
HI @ashraf92,

Glad to hear that you like the plugin! 

Please follow this example for tabbed interface: https://carbonfields.net/docs/containers-tabs/

You'll just need to switch `post_meta` container type with `theme_options`
