### ISSUE TITLE
Add documentation about how to contribute

### ISSUE THREAD

**Issue by timiwahalahti** [htmlburger/carbon-fields#424]
I think there would be people interested about contributing more to CRB (like me 😊), but there's no good documentation how to make it. Since there is some build processed etc in place, it would be nice to have some kind of instructions about how to start contributing and making PR's.

As i'm using CRB daily in my work, I would really like to help you guys with this awesome library.

**Comment by atanas-angelov-dev** [comment]
`CONTRIBUTING.md` was added a couple months ago but I've missed to update this ticket:
https://github.com/htmlburger/carbon-fields
