### ISSUE TITLE
Access Complex fields using the Javascript API

### ISSUE THREAD

**Issue by AMO-MGTSYS** [htmlburger/carbon-fields#425]
I'm trying to set field values of a complex field in a for loop using Javascript API.
let suppose i have two entries with index 0 and 1 (<%- $_index %>).

the first iteration of the loop (i=0) sets a value of the entry with index 1 (the last entry).

Is this normal?

**Comment by atanas-angelov-dev** [comment]
Hi @AMO-MGTSYS ,

Could you please share your loop code snippet so we can better understand your use-case and problem?

**Comment by AMO-MGTSYS** [comment]
Hi @atanas-angelov-dev 
This is my code and screenshots:
A) Definition
        ->add_tab( __('Services'), array(
            Field::make( 'complex', 'services', 'Service' )
                ->set_layout( 'tabbed-horizontal' )
                ->add_fields( array(
                    Field::make( 'text', 'title', 'Title' )
                        ->set_width(50)

                        ))
                ->set_header_template( '
                    <% if (title) { %>
                             Index <%- $_index %> (<%- title %>)
                          <% } %>
                      ' )
         ));
![image](https://user-images.githubusercontent.com/16602122/33324266-0e6efe70-d447-11e7-9329-146982467b6f.png)

B) Javascript:
$(document).on('carbonFields.apiLoaded', function(e, api) {
    var i;
    var services = api.getFieldValue('services');
    for (i = 0; i < services.length; ++i) {
        console.log(i);
        console.log(services[i].title);
    }
});
![image](https://user-images.githubusercontent.com/16602122/33324318-392d94e6-d447-11e7-8253-1ec674013f01.png)

**Comment by atanas-angelov-dev** [comment]
I was able to reproduce the issue locally - it seems the values are retrieved in reverse order (last service is first, first is last).

I will update this ticket when the issue is fixed.

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
