### ISSUE TITLE
[2.1.0] Alert message on pages with carbon fields in admin panel

### ISSUE THREAD

**Issue by frontier-code** [htmlburger/carbon-fields#427]
Always when I exit pages with carbon meta fileds (pages, products, theme option page) and if I am not change and not edit anything each time opened Chrome alert box: 
## Do you want to leave this site?

Changes you made may not be saved. 

| **Leave** | | **Stay** |

What does it mean?

**Comment by atanas-angelov-dev** [comment]
Hi @frontier-code ,

Please update to 2.1.1 and let us know if the issue persists.

**Comment by frontier-code** [comment]
Hi @atanas-angelov-dev ! After updating to 2.1.1 this bug was fixed. Thanks
