### ISSUE TITLE
How can i set "name_prefix" to Carbon_Fields\Field\Field object ?

### ISSUE THREAD

**Issue by mimosafa** [htmlburger/carbon-fields#428]
Hi,

Please let us know how to set "name_prefix" for Fields.
i want to do that "_" to ""(empty string) due to compatible, so i wrote like below
```
$field = Field::make( 'text', 'default_0_item_text' )
    ->set_name_prefix( '' )
;
```
but it seems don't work.

Or is it impossible?

Thank you.

**Comment by atanas-angelov-dev** [comment]
Hi @mimosafa ,

This is not currently available as a built-in option. You can, however, write a custom Datastore class that skips the leading underscore and apply it to the fields you need.

For example, if you are interested in theme options you can duplicate the built-in `Theme_Options_Datastore.php` class, rename it, update it's code so leading underscores are removed from keys and apply it to fields:
```php
$datastore = new MyCustomDatastore();
Field::make( ... )
	->set_datastore( $datastore );
```

**Comment by mimosafa** [comment]
Thank you for your reply @atanas-angelov-dev  !

Receiving your advice, i got what i wanted :)
There seems to be some other problem, but I tried this
https://gist.github.com/mimosafa/57fa35a773be818b2a02249dccd37272

Thank you, so mush !
