### ISSUE TITLE
Relationship Field: filter should work with accents

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#43]
Given that one of the items in the relationship field is "Antònia" 
When the user enters "anto" in the filter field
The field should show "Antònia"

**Comment by doup** [comment]
The method to change is this one, `carbon.fields.View.Relationship.searchFilter`:
https://github.com/htmlburger/carbon-fields/blob/master/assets/js/fields.js#L1501

I'll try to prepare a PR, but just in case… :-)

**Comment by m1r0** [comment]
Hi @doup, we are in the process of rewriting the JS using React and will try to account for this issue. Maybe a better approach will be for the relationship field search to use AJAX and let PHP handle the latinization (if that's a word ) :-)

**Comment by doup** [comment]
OK! Thanks for keeping me informed. Maybe `slugify` (slugification? 😆 ) would have been a better name… jeje. Check these issues also, they may be of interest for the JS rewrite: #40, #41, #44, #43 (this one) & #60.

**Comment by doup** [comment]
Anyway, is there a possibility of merging some PRs and making a release before the rewrite?
Thanks!

**Comment by atanas-angelov-dev** [comment]
2.0.0 has just been released - can you let us know if you still experience this issue on the new version?
