### ISSUE TITLE
A curated list of awesome Carbon Fields extensions.

### ISSUE THREAD

**Issue by mohamdio** [htmlburger/carbon-fields#431]
A curated list of awesome Carbon Fields extensions.

[Awesome Carbon Fields Extensions](https://github.com/mohamdio/awesome-carbon-fields-extensions)

I hope it maybe useful for someone, also i think carbon-fields team should collect all trusted extensions in somewhere here in the repo or in the site, sure will be useful for everyone.

**Comment by BenBroide** [comment]
Very useful, thanks. 
This tool is still in process but you might want to add it as well CARBON FIELDS GENERATOR https://wpcodewizard.com/

**Comment by mohamdio** [comment]
@BenBroide done 👍

**Comment by edwardhew** [comment]
FYI some of these have higher requirements than core, for example core uses get_class(), where for example the Icon, and Number field uses Icon_Field::class, Number_Field::class respectively and that just won't run on older versions of PHP, yes I know it's 2018 :)

**Comment by jorostoyanov** [comment]
There is another repo - https://github.com/htmlburger/awesome-carbon-fields - which should be used for this purpose.

Feel free to open a pull request to add something there :-)
