### ISSUE TITLE
Localisation for flatpickr

### ISSUE THREAD

**Issue by proweb** [htmlburger/carbon-fields#432]
In [Date](https://carbonfields.net/docs/fields-date/?crb_version=2-1-0), [Date Time](https://carbonfields.net/docs/fields-date-time/?crb_version=2-1-0) and [Time](https://carbonfields.net/docs/fields-time/?crb_version=2-1-0) field Carbon Fields uses [flatpickr](https://github.com/chmln/flatpickr)

---

Do we have [localization part](https://chmln.github.io/flatpickr/localization/) of flatpickr in carbon fields?
If not, would it be included in future versions? 

And which is the right way to add localisation (for example Russian) for actual version of Carbon fields?

**Comment by atanas-angelov-dev** [comment]
Hi @proweb ,

You can translate Flatpickr by following these steps:
1. Add the following to your functions.php:
	```php
	add_action( 'admin_enqueue_scripts', function() {
	    wp_enqueue_script( 'flatpickr-locale-ru', 'https://npmcdn.com/flatpickr/dist/l10n/ru.js', array('carbon-fields-boot') );
	} );
	```
1. Add the following to the date/time/datetime field definition:
	```php
	->set_picker_options( array(
		'locale' => 'ru',
	) ),
	```

I've also just pushed an update to `development` which will make step 2 optional (the locale will be passed to Flatpickr automatically but can be overriden) and added relevant help text in the docs (changes will be reflected on next release).

> And which is the right way to add localisation (for example Russian) for actual version of Carbon fields?

Carbon Fields already include Russian translation files that will be automatically used if your administration language is set to Russian. If you notice any untranslated or incorrectly translated strings feel free to modify the `languages/carbon-fields-ru_RU.*` files and submit a pull request with the changes.

**Comment by proweb** [comment]
big thanks @atanas-angelov-dev Great support as always =)

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
