### ISSUE TITLE
date_time fields seconds are updated to :00 if post updated

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#434]
I have a date_time field that has a value saved correctly. 
When other fields of post is updated from the edit screen, the value of the date_time field are saved with the seconds values ":00" even there was no change done to that date_time field.
Examples: 
2017-12-05 15:29:46 would be saved as 2017-12-05 15:29:00
2017-12-03 08:15:22 would be saved as 2017-12-03 08:15:00
even that no change has done to this date_time field value.

**Comment by atanas-angelov-dev** [comment]
Hi @BenBroide ,

Can you please share your container definition?

**Comment by BenBroide** [comment]
Turned out I needed to setup the date like this ->set_input_format( 'Y-m-d H:i:s', 'Y-m-d H:i:S' )
I assumed from the [docs  ]([url](https://carbonfields.net/docs/fields-date-time/?crb_version=2-1-0))that the date_time input defaults to Y-m-d H:i:s in the input as well.

Turned out the default input is without the S|s that's why the dates seconds were resetting (The dates were imported with the seconds)

Thanks

**Comment by BenBroide** [comment]
@atanas-angelov-dev  Iv'e sent a pull request to the docs with a note about this https://github.com/htmlburger/carbon-fields-docs/pull/28
