### ISSUE TITLE
Options page slows down after adding 30+ options to a complex field.

### ISSUE THREAD

**Issue by rohan2388** [htmlburger/carbon-fields#437]
I created a Option page and it has about 15 static text and textareas and 2 complex fields.
I added about 35 options and then it started to slow down, cpu usage was really high, I can't even type text in field. I can link video if its allowed. Let me know.

**Comment by atanas-angelov-dev** [comment]
Hi @rohan2388 ,

Could you please share your entire container definition?

**Comment by rohan2388** [comment]
$pages = get_pages();
    $pages_sorted = array();
    foreach( $pages as $page ) {
        $pages_sorted[$page->ID] = $page->post_title;
    }




    Container::make( 'theme_options', 'Skin Analysis' )
    ->add_fields( array(
        Field::make( 'select', 'skin_analysis_page', 'Skin analysis page' )
            ->add_options( $pages_sorted )
            ->set_width(50)
        ,Field::make( 'select', 'contact_page', 'Contact page link' )
            ->add_options( $pages_sorted )
            ->set_width(50)
        ,Field::make( 'textarea', 'checkout_disclaimer', 'Checkout | disclaimer' )
        ,Field::make( 'textarea', 'cart_notification_default', 'Cart | default text' )
            ->set_width(50)
        ,Field::make( 'textarea', 'cart_notification', 'Cart | update text' )
            ->set_width(50)
    
        ,Field::make( 'separator', 'sep_email', 'Email' )
        ,Field::make( 'text', 'email_client_skan_complete_subject', 'Subject (complete notification to client)')
            ->set_width(45)
        ,Field::make( 'textarea', 'email_client_skan_complete_message', 'Message (notification to client)')
            ->set_width(55)
    
        ,Field::make( 'text', 'email_admin_skan_complete_subject', 'Subject (notification to admin)')
            ->set_width(45)
        ,Field::make( 'text', 'email_admin_skan_recipient', 'Admin email address')
            ->set_width(55)
    
        ,Field::make( 'separator', 'excerpt', 'Content' )
        ,Field::make( 'complex', 'excerpt_texts', 'Profile content' )
            ->set_collapsed(true)
            ->add_fields( array(
                Field::make( 'text', 'text' ),
            ) )
            ->set_header_template('<%- _.truncate(text, {length: 100}) %>')
    
        ,Field::make( 'separator', 'sep_profile', 'Profile' ),
        Field::make( 'text', 'profile_heading', 'Heading text'),
        Field::make( 'text', 'profile_name', 'Name')
            ->set_width( 33.33333 ),
        Field::make( 'text', 'profile_surname', 'Surname')
            ->set_width( 33.33333 ),
        Field::make( 'text', 'profile_email', 'Email')
            ->set_width( 33.33333 ),
        Field::make( 'text', 'profile_password', 'Password')
            ->set_width( 33.33333 ),
        Field::make( 'text', 'profile_password_re', 'Confirm password')
            ->set_width( 33.33333 ),
        Field::make( 'text', 'profile_newsletter', 'Newsletter')
            ->set_width( 33.33333 ),
        Field::make( 'text', 'profile_submit', 'Submit'),
    
        Field::make( 'separator', 'sep_question', 'Questions' ),
        Field::make( 'complex', 'questions', 'Questions' )
            ->setup_labels( array(
                'singular_name' => 'question',
                'plural_name' => 'questions',
            ) )
            ->set_collapsed( true )
            ->add_fields( array(
                Field::make( 'text', 'question_id', 'Unique ID' )
                    ->set_help_text('Do not use any special characters.')
                    ->set_attribute( 'placeholder', 'e.g. question-1' )
                    ->set_required( true )
    
                // Field for layout type
                ,Field::make( 'select', 'type', 'Layout' )
                    ->add_options( array(
                        'default' => 'Default',
                        'text' => 'Text',
                        'image-and-label' => 'Image and label',
                        'circle-label' => 'Circular label',
                        'image-uploader' => 'Image uploader',
                    ) )
                    ->set_width( 50 )
                ,Field::make( 'text', 'admin_question', 'Question (admin panel)' )
                    ->set_width( 50 )
    
                // Category and main question text
                ,Field::make( 'text', 'question', 'Question' )
                    ->set_width( 50 )
                ,Field::make( 'text', 'category', 'Cetegory' )
                    ->set_width( 50 )
                ,Field::make( 'text', 'question_excerpt', 'Text below question' )
                    ->set_width( 80 )
                ,Field::make( 'checkbox', 'multiple_select', 'Allow multiple selection' )
                    ->set_option_value( 'yes' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'default'
                        )
                    ) )
                    ->set_width(20)
                ,Field::make( 'text', 'text_placeholder', 'Placeholder text' )
                    ->set_default_value( 'Please type something here...' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'text'
                        )
                    ) )
    
    
                // Option field for default layout
                ,Field::make( 'complex', 'options_1', 'Options' )
                    ->setup_labels( array(
                        'singular_name' => 'option',
                        'plural_name' => 'options',
                    ) )
                    ->set_collapsed( true )
                    ->add_fields( array(
                        Field::make( 'text', 'label', 'Label' )
                    ) )
                    ->set_header_template('<%- label %>')
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'default'
                        )
                    ) )
                // Additional text field
                ,Field::make( 'checkbox', 'text_field', 'Additional text input' )
                    ->set_option_value( 'yes' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'default'
                        )
                    ) )
                    ->set_width(20)
                ,Field::make( 'text', 'text_field_placeholder', 'Label' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'text_field',
                            'value' => true
                        )
                    ) )
                    ->set_width(40)
                ,Field::make( 'text', 'text_field_admin', 'Label (admin panel)' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'text_field',
                            'value' => true
                        )
                    ) )
                    ->set_width(40)
                ,Field::make( 'separator', 'sep_1', '' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'text_field',
                            'value' => false
                        ),
                        array(
                            'field' => 'type',
                            'value' => 'default'
                        )
                    ) )
                    ->set_width(80)
                // secondary heading
                ,Field::make( 'checkbox', 'secondary_heading', 'Heading (secondary)' )
                    ->set_option_value( 'yes' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'default'
                        )
                    ) )
                    ->set_width(20)
                ,Field::make( 'text', 'secondary_heading_heading', 'Heading' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'secondary_heading',
                            'value' => true
                        )
                    ) )
                    ->set_width(40)
                ,Field::make( 'text', 'secondary_heading_subheading', 'Text' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'secondary_heading',
                            'value' => true
                        )
                    ) )
                    ->set_width(40)
                ,Field::make( 'separator', 'sep_3', '' )
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'secondary_heading',
                            'value' => false
                        ),
                        array(
                            'field' => 'type',
                            'value' => 'default'
                        )
                    ) )
                    ->set_width(80)
    
    
                // Option field for image and label layout
                ,Field::make( 'complex', 'options_2', 'Options' )
                    ->setup_labels( array(
                        'singular_name' => 'option',
                        'plural_name' => 'options',
                    ) )
                    ->set_collapsed( true )
                    ->add_fields( array(
                        Field::make( 'text', 'label', 'Label' )
                        ,Field::make( 'image', 'photo', 'Image' )
                            ->set_width( 50 )
                        ,Field::make( 'image', 'photo_hover', 'Image (hover)' )
                            ->set_width( 50 )
                    ) )
                    ->set_header_template('<%- label %>')
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'image-and-label'
                        )
                    ) )
    
                // Option field for circular label layout
                ,Field::make( 'complex', 'options_3', 'Options' )
                    ->setup_labels( array(
                        'singular_name' => 'option',
                        'plural_name' => 'options',
                    ) )
                    ->set_collapsed( true )
                    ->add_fields( array(
                        Field::make( 'text', 'label', 'Label' )
                    ) )
                    ->set_header_template('<%- label %>')
                    ->set_conditional_logic( array(
                        array(
                            'field' => 'type',
                            'value' => 'circle-label'
                        )
                    ) )
    
    
    
                // Conditions
                ,Field::make( 'complex', 'conditions', 'Conditions (hide if)' )
                    ->setup_labels( array(
                        'singular_name' => 'condition',
                        'plural_name' => 'conditions',
                    ) )
                    ->set_collapsed( true )
                    ->add_fields( array(
                        Field::make( 'select', 'match', 'Match' )
                            ->add_options( array(
                                'equal' => 'Equal',
                                'not_equal' => 'Not equal',
                            ) )
                            ->set_width(33.3333)
                        ,Field::make( 'text', 'field', 'Field ID' )
                            ->set_width(33.3333)
                        ,Field::make( 'text', 'match_value', 'Value' )
                            ->set_width(33.3333)
                    ) )
                    ->set_header_template('<% if(field && match_value) { %>If <%- field %> is <%= match.toLowerCase() %> <%- match_value %> <% } %>')
    
            ) )
            ->set_header_template('[<%- question_id %>] <%- category %> :: <%- question %>'),
    ) );

**Comment by atanas-angelov-dev** [comment]
You have a massive amount of fields - with just 30 entries in one of the complex (the other is empty) there are __436__ input fields. Combined with features such as validation, conditional display and dynamic complex headers I'm not too surprised React is choking.

I'd suggest you move the questions into their own post type which will significantly simplify the UI, improve performance and give you the full functionality of posts for the questions (e.g. use the built-in slug validation instead of the Unique ID field, use a normal WP_Query to get all of the questions etc.).
If you need to reorder questions you can either enable the WordPress order field (through the `'page-attributes'` post type support) or add an Association field to pick and order the questions.

**Comment by rohan2388** [comment]
I am not React expert but I don't get it, why would it stuck when typing a text in a text field. I guess it validates on every keypress event? I guess its required to test conditions but I still think it can be more simplified or maybe add validation event to "change" event instead of "input", which will let me type text without delay. 

I understand what you're saying to improve UI and performance, I will see what I can do.

**Comment by atanas-angelov-dev** [comment]
It checks on every `change` event React emits (i.e. every time a value changes which includes keypresses) so that dynamic complex headers and validation are as responsive as possible.

The normal `change` event is only triggered when you change focus for text input and textarea fields - here's a quote from MDN (https://developer.mozilla.org/en-US/docs/Web/Events/change):
```
When the element loses focus after its value was changed, but not commited
(e.g. after editing the value of <textarea> or <input type="text">).
```

This means that if we switch to the traditional `change` event, headers and validation will only update if you click outside of the current field (so it loses focus) which is far from ideal in terms of UX.

**Comment by rohan2388** [comment]
Cool. Thanks.
