### ISSUE TITLE
Hide "Add Entry" button if fields limit is reached

### ISSUE THREAD

**Issue by leurdo** [htmlburger/carbon-fields#441]
Hello!
Is it possible to hide "Add Entry" button when fields limit set by set_max() method is reached? Thank you!
In addition:  I found information that "add entry" button should be hidden if set_max() limit is reached. But it is not working for me, maybe because I have complex field with multiple groups. Please, advise.

**Comment by atanas-angelov-dev** [comment]
Hi @leurdo ,

Thank you for the suggestion - I'm pretty sure we had discussed implementing this internally but it seems we've missed it which is why I fixed it in 101eeb8654ae7af7f48d07e782d5021ccc162b7a right now 😃
