### ISSUE TITLE
Media Gallery field: Editing existing image adds duplicate

### ISSUE THREAD

**Issue by jchristopher** [htmlburger/carbon-fields#443]
Steps to replicate

1. Add item to Media Gallery
1. Click edit icon for that item
1. Click Select File button

Expected behavior: chosen item inherits edits

Actual behavior: a duplicate of that item is appended to the set of items

**Comment by conschneider** [comment]
Hi mate, 

> Expected behavior: chosen item inherits edits
Actual behavior: a duplicate of that item is appended to the set of items

Issue is a bit old, but is this still current?
If yes, could you tell me whether you get a duplicated file or a duplicated entry in the media library only (https://conschneider.de/duplicate-images-when-using-woocommerce-product-csv-import-suite/)?

**Comment by jorostoyanov** [comment]
Version 3 of Carbon Fields doesn't yet support edit inline.

You can track the progress here -- https://github.com/htmlburger/carbon-fields/issues/937
