### ISSUE TITLE
Media Gallery field: cannot drag and drop newly added items

### ISSUE THREAD

**Issue by jchristopher** [htmlburger/carbon-fields#444]
After adding multiple items to a Media Gallery you cannot sort the items.

However, saving, and reloading the Media Gallery with existing items does support sorting via drag and drop.

**Comment by jorostoyanov** [comment]
Hi @jchristopher ,

Thank you for the report!

I've pushed a fix in the development branch -- https://github.com/htmlburger/carbon-fields/commit/3648c64c320fc79df9292ad1449d39e5a6100a4d

I'll close this ticket once the fix is live.

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
