### ISSUE TITLE
Add placeholder attribute support to the date field

### ISSUE THREAD

**Issue by Fellan-91** [htmlburger/carbon-fields#446]
Hi, it seems we found another issue. It seems the date field does not support the placeholder attrbut.
We get the following message in the admin panel:

> Carbon Fields library encountered errors that may prevent your custom fields or theme options to work properly. Here's a quick summary of the issue:
> 
> Only the following attributes are allowed: data-*

Back End:
```
add_action( 'carbon_fields_register_fields', 'crb_attach_theme_options' );
function crb_attach_theme_options() {
Container::make( 'theme_options', __( 'Theme Options', 'crb' ) )
            ->add_tab( 'Social', array(
                Field::make( 'date', '_player_date_birth',  'Date of Birth' )
                    ->set_attribute( 'placeholder', 'Enter your date of birth' )
            ) );
}
```
Please add support for the placeholder attribute in the next version.
Thank you for attention.

**Comment by BenBroide** [comment]
Meanwhile seems like ` ->set_help_text( 'Enter your date of birth' ) ` will get you what you want to achieve  
https://carbonfields.net/docs/fields-usage/

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
