### ISSUE TITLE
wpml translate field not translate

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-fields#448]
I have created custom post type with carbon field and when I translate it does not appear in my page it stays in spanish or other languaje  have to do here I leave the page in three languages thanks for your help.

![captura de pantalla 2018-01-02 a la s 13 16 04](https://user-images.githubusercontent.com/1920588/34494564-267b92f6-efbf-11e7-9718-72272e3848c8.png)

**Comment by atanas-angelov-dev** [comment]
Hi @dackr ,

Did you edit the custom fields for every language or only for Spanish? You have to go through each language version of the post and edit the custom fields accordingly.

**Comment by dackr** [comment]
thanks for your answer, if I have translated to each language, but when I change language for example the slider does not change the language I could do to fix this detail please.

**Comment by atanas-angelov-dev** [comment]
If the values are displayed correctly for every language in the administration panel, then this is most likely to do with how you fetch these values on the front-end.
Can you please share your code which pulls the incorrect data?

**Comment by dackr** [comment]
`function shortcode_slider($atts, $content = null)
        {
            extract(shortcode_atts(array(
                'title' => '',
                'id' => '',
                'type' => '',
                'styles' => ''
            ), $atts));
            $styless      = $atts['styles']; //array( 'slide-main', 'slider-part', 'list', 'slider', 'slider-offer' );
            $slider_TITLE = $atts['title'];
            $sliders_ID   = $atts['id'];
            $slider_TYPE  = $atts['type'];
            $slider_CLASS = $atts['class'];
            
             
            $slider_data  = carbon_get_post_meta( $sliders_ID, '_tour_slider', 'complex');
            //$slider_data = get_post_meta($sliders_ID, 'tierra_sliders_details', true);
            if ($styless == "main-slider") {?>
            <section class="home-intro">
                <div class="main-slider">
                    <?php
                    if (!empty($slider_data)):?>
                        <?php
                        foreach ($slider_data as $slide):?>
                            <?php
                            $linkData = $slide['link_slider']['0'];
                            if ($linkData['type'] == 'type' || $linkData['subtype'] == 'page') {
                                $link = get_page_link($linkData['id']);
                            } elseif ($linkData['type'] == 'post' || $linkData['subtype'] == 'tour') {
                                $link = get_permalink( $linkData['id']);
                            } elseif ($linkData['type'] == 'post' || $linkData['subtype'] == 'post') {
                                $link = get_permalink($linkData['id']);
                            } elseif ($linkData['type'] == 'term' || $linkData['subtype'] == 'destination') {
                                $link = get_category_link($linkData['id']);
                            } elseif ($linkData['subtype'] == 'post_tag') {
                                $link = get_tag_link($linkData['id']);
                            } elseif ($linkData['type'] == 'user' || $linkData['subtype'] == 'user') {
                                $link = get_author_posts_url($linkData['id']);
                            };

                            $get_bg_image = wp_get_attachment_image_src($slide['image'], 'large') ;
                            $text_align   = !empty($slide['text_aling']) ? $slide['text_aling'] : 'left';
                            ?>
                            <div class="slide" style=" text-align:<?php echo esc_attr($text_align);?>" >
                                <div class="inner" style="background-image: url( <?php echo esc_url($get_bg_image[0])?> )">
                                    <div class="overlay">
                                      <div class="overlay-inner">
                                        <a href="<?php echo esc_url($link) ?>" class="overlay-link">
                                        </a>
                                        <?php if (!empty($slide['title_slider'])): ?>
                                        <h1 class="page-title"><?php echo esc_attr($slide['title_slider'])?></h1>
                                        <h6><?php echo $slide['content'] ?></h6>
                                        <?php endif; ?>
                                      </div>
                                    </div>
                                </div>                      
                            </div>
                        <?php
                        endforeach; ?>
                    <?php
                    endif;?>
                </div>
                <a href="#adventures-section" class="scroll-down">
                  <img src="<?php echo get_stylesheet_directory_uri() ?>/css/img/icons/arrow-down.svg" alt="Icon" class="bounce">
                </a>
            </section>
        <?php
                wp_reset_postdata();
            } elseif ($styless == 'slide-part') { ?>
        <div class="destinations">
            <div class="container-fluid">
                <header><h3> <?php echo esc_html($slider_TITLE);?></h3></header></div>
            <div class="variable-width" style="background:#000;">
                <?php
                foreach ($slider_data as $slider) {
                    foreach ($slider as $slide) {
                        $img = wp_get_attachment_image_src($slide['image'], 'full');?> 
                        <img src="<?php echo $img[0] ?>" style="margin:25px 30px"> <?php
                    }
                }?>
            </div>
        </div>
            <?php
            wp_reset_postdata();
        }
    }`

**Comment by atanas-angelov-dev** [comment]
My guess is the culprit is this:
`$sliders_ID = $atts['id'];`

Did you change the ID in the shortcode for every language version of the post? If not - then this is your problem - you are passing the same ID for every language (each language version of a post has it's own post ID).

**Comment by dackr** [comment]
thank you very much for your help, I will do otherwise then.
