### ISSUE TITLE
Bugs in image areas

### ISSUE THREAD

**Issue by zavaremre** [htmlburger/carbon-fields#449]
![7c090341-8747-4a9a-8989-6e6139591cec](https://user-images.githubusercontent.com/35058780/34512303-8720981e-f072-11e7-94a8-f946183ce7dd.gif)

**Comment by timiwahalahti** [comment]
Could you share code for this container, so that looking into this would be much more easier.

**Comment by zavaremre** [comment]
`<?php
use Carbon_Fields\Field;
use Carbon_Fields\Container;
use Carbon_Fields\Widget;
	class PATIKA_PROFILE_WIDGET extends Widget {
    // Register widget function. Must have the same name as the class
	function __construct() {
		$this->setup( 'PatikaProfileWidget', 'PATIKA | Profile Widget', 'Authors corner', array(
			Field::make( 'image', 'profile_widget_header_image', 'Select Profile Header Image' )
				->set_width( 50 ),
				
			Field::make( 'image', 'profile_widget_profile_image', 'Select Profile Avatar Image' )
				->set_width( 50 ),
				
		   Field::make( 'text', 'profile_widget_title', 'Title' )
		        ->set_attribute( 'placeholder', 'Type your name or nickname in this field.' )
				->set_default_value( 'Hello World!') ,
				
			Field::make( 'textarea', 'profile_widget_content', 'Content' )
				->set_attribute( 'placeholder', 'Write your short bio in this field' ),
				
			Field::make( 'text', 'profile_widget_social_facebook', 'Facebook' )
				->set_attribute( 'placeholder', 'Facebook Url' )
				->set_width( 50 ),
				
			Field::make( 'text', 'profile_widget_social_twitter', 'Twitter' )
				->set_attribute( 'placeholder', 'Twitter Url' )
				->set_width( 50 ),
				
			Field::make( 'text', 'profile_widget_social_instagram', 'Instagram' )
				->set_attribute( 'placeholder', 'Instagram Url' )
				->set_width( 50 ),
				
			Field::make( 'text', 'profile_widget_social_youtube', 'Youtube' )
				->set_attribute( 'placeholder', 'Youtube Url' )
				->set_width( 50 ),
			Field::make( 'checkbox', 'crb_show_content', 'If the save button is passive.Click here' )
				->set_option_value( 'no' )
		) );
	}
    // Called when rendering the widget in the front-end
    function front_end( $args, $instance ) { 
		//echo $args['before_title'] . $instance['title'] . $args['after_title'];
	?>
	<div class="profile-header">
		<div class="profile-header-image" style="background-image:url('<?php echo wp_get_attachment_url($instance['profile_widget_header_image']); ?>')"></div>
		<div class="profile-image">
			<a class="image-open" data-effect="mfp-zoom-in" href="<?php echo wp_get_attachment_url($instance['profile_widget_profile_image']); ?>">
				<img src="<?php echo wp_get_attachment_url($instance['profile_widget_profile_image']); ?>">
			</a>
		</div>
	</div>
	<div class="profile-details">
		<h3><?php echo $instance['profile_widget_title'] ?></h3>
		<?php echo $instance['profile_widget_content'] ?>
		<div class="social">
			<ul>
				<li>
					<a data-placement="top" data-toggle="tooltip" href="<?php echo $instance['profile_widget_social_facebook'] ?>" title="Facebook">
						<i class="ion-social-facebook"></i>
					</a>
				</li>
				<li>
					<a data-placement="top" data-toggle="tooltip" href="<?php echo $instance['profile_widget_social_twitter'] ?>" title="Twitter">
						<i class="ion-social-twitter"></i>
					</a>
				</li>
				<li>
					<a data-placement="top" data-toggle="tooltip" href="<?php echo $instance['profile_widget_social_instagram'] ?>" title="Instagram">
						<i class="ion-social-instagram-outline"></i>
					</a>
				</li>
				<li>
					<a data-placement="top" data-toggle="tooltip" href="<?php echo $instance['profile_widget_social_youtube'] ?>" title="Youtube">
						<i class="ion-social-youtube"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<?php	
    }
}
    register_widget( 'PATIKA_PROFILE_WIDGET' );   
 
 `

**Comment by zavaremre** [comment]
multiple selections are made and errors in newly uploaded images

![b17d84ac-d9cf-438d-a02a-9c73477964f4](https://user-images.githubusercontent.com/35058780/34512502-ff775fd6-f073-11e7-895a-332a2acf844b.gif)

**Comment by atanas-angelov-dev** [comment]
Hi @zavaremre ,

Can you please make sure you are on the latest version of Carbon Fields and let us know the exact version number you have after updating?

**Comment by zavaremre** [comment]
I have installed the latest version.
Here again the problem continues.

![screenshot_5](https://user-images.githubusercontent.com/35058780/34553696-04f718f4-f13a-11e7-8617-ad82a09ab0e1.png)

**Comment by atanas-angelov-dev** [comment]
I believe all of these issues are already fixed in the latest beta release (zip packages are not available for beta releases so you have to use composer to get it).

**Comment by zavaremre** [comment]
Could it be originating without loading?

Error on top setup
Use me below.

![screenshot_6](https://user-images.githubusercontent.com/35058780/34554907-30a50820-f140-11e7-86ac-d1f0d79a9083.png)

**Comment by zavaremre** [comment]
can you review it from the teamviewer?

**Comment by zavaremre** [comment]
I installed WordPress from scratch.
The error persists.

**Comment by zavaremre** [comment]
@atanas-angelov-dev @timiwahalahti 

ı do All versions installed.
but It did not.
Please to me help .I would be very happy.
Only this part is left.
The whole site was made with this plugin.

**Comment by atanas-angelov-dev** [comment]
Your subsequent messages are a bit confusing - you initially show a bug with widgets but then show some issue with the ABSPATH constant that is not clear at all.

Please describe your issues in detail otherwise I will not be able to help you.

As for the widget bug, please test with the latest beta version (`2.2.0-beta.4`). There are no zip packages for beta versions so you will have to use composer (https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-1-0).

**Comment by zavaremre** [comment]
The problem is in the first message.
I wanted to ask you if the others are wrong.

**Comment by zavaremre** [comment]
I solved the save button problem.
The remaining problem.
Just disable the multiple image selection field.


**JQuery widget fix**
```
$( document ).ajaxComplete(function() {
	jQuery('.carbon-description img').on('load', function () {
		jQuery('.widget-control-save').prop({
			disabled: false
		});
	});
 });
```
