### ISSUE TITLE
Allow zero as a value, if field is required

### ISSUE THREAD

**Issue by MikkoVirenius** [htmlburger/carbon-fields#450]
## Version

  - Carbon Fields: 2.1.1
  - WordPress: 4.9.1
  - PHP: 5.6

## Expected Behavior
If field is set required, only empty or null value should trigger a "this field is required" warning.

## Actual Behavior
If value is 0, field triggers a "this field is required" warning.

## Container definition
```php
Field::make( 'select', 'select-test', 'Select' )
	              ->add_options( array(
		              '' => 'Select',
		              '0'  => 'No',
		              '1'  => 'Yes',
	              ) )
	              ->set_required( true ),
```

## Steps to Reproduce the Problem

  1. Add field defined above to any container
  2. Select value "No" 
  3. Save field. First save doesn't trigger the warning, but second does.

**Comment by deqngeorgiev** [comment]
Hi @MikkoVirenius ,

This is fixed in version 2.2.0
