### ISSUE TITLE
Allow arbitrary callback for conditionals

### ISSUE THREAD

**Issue by mindfullsilence** [htmlburger/carbon-fields#453]
## Version

  - Carbon Fields: 2.2.0-beta.4

## Expected Behavior
Allow any arbitrary conditional without passing a conditional type. 
```php
Container::make('post_meta', 'Header')
  ->where(function () use ($theme_whitelist) {
      $theme_name = wp_get_theme()->get('Name');
      return in_array($theme_name, $theme_whitelist);
    });
```

## Actual Behavior
Although possible, I would consider this a side effect of the intent of the 'CUSTOM' condition type, and a developer must pass in a conditional type for their callback that potentially has nothing to do with the actual function body.
```php
Container::make('post_meta', 'Header')
  ->where('current_user_id', 'CUSTOM', function ($current_user_id) use ($theme_whitelist) {
      // note current_user_id has nothing to do with the function, 
      // but its a way to get the callable to be called. 
      $theme_name = wp_get_theme()->get('Name');
      return in_array($theme_name, $theme_whitelist);
    });
```

## Comments
Note the above code is untested and just for an example. There is a huge amount of custom conditionals that could be generated with the callback without ever actually needing to take in any arguments.

I'd say this is pretty low priority since creating a custom conditional is currently possible, but passing in a conditional type and comparison operator is redundant in more complex cases.

**Comment by atanas-angelov-dev** [comment]
Hi @mindfullsilence ,

The following syntax serves a different purpose:
```php
->where(function ($condition) {
	$condition->where('foo', 'bar');
	$condition->orWhere('foo', 'baz');

	$condition->orWhere(function ($condition) {
		$condition->where('bar', 'bar');
		$condition->orWhere('bar', 'baz');
	});
});
```
With this you can have nested logic so you have full `AND` and `OR` relationships between conditions on any level (you can keep nesting conditions).
See https://carbonfields.net/docs/containers-conditional-display/?crb_version=2-1-0 for more information (`Nested logic`).

The `CUSTOM` operator is helpful when you wish to test some value from the available ones against a custom function.
When you wish to create a condition which does not rely on any of the built-in condition values (e.g. `post_id`, `post_template` etc.), you can create you own custom condition class (https://carbonfields.net/docs/extending-container-conditions/?crb_version=2-1-0).

Here's an untested example for your use case:

### Theme_Condition.php
```php
class Theme_Condition extends Condition {
    /**
     * Check if the condition is fulfilled
     *
     * @param  array $environment
     * @return bool
     */
    public function is_fulfilled( $environment ) {
        return $this->compare(
            wp_get_theme()->get('Name'),
            $this->get_comparison_operator(),
            $this->get_value()
        );
    }
}
```

### functions.php
```php
\Carbon_Fields\Carbon_Fields::extend( Theme_Condition::class, function( $container ) {
    // create an instance of our new class
    $condition = new Theme_Condition();
    $condition->set_comparers( \Carbon_Fields\Carbon_Fields::resolve( 'nonscalar', 'container_condition_comparer_collections' ) );
    return $condition;
} );

// Change filter depending on container type this condition is available to (theme_options in this case)
add_filter( 'carbon_fields_theme_options_container_static_condition_types', function( $condition_types, $container_type, $container ) {
    // append our new condition type to allowed theme options conditions
    return array_merge(
        $condition_types,
        array( 'theme' ) // based on Theme_Condition class name
    );
}, 10, 3 );
```

With the above additions, you should now be able to do this:
```php
Container::make( 'theme_options', __( 'Foobar Container', 'crb' ) )
    ->where( 'theme', '=', 'foobar' );
```

**Comment by mindfullsilence** [comment]
Cant believe I missed that in the docs. Thanks @atanas-angelov-dev. Sorry for waisting your time!
