### ISSUE TITLE
Question: Filter Select Options based on another Field Value

### ISSUE THREAD

**Issue by AMO-MGTSYS** [htmlburger/carbon-fields#455]
Hi Community,
is there a way to Filter Select Options based on another Field Value using plain javascript or Jquery?

**Comment by atanas-angelov-dev** [comment]
Hi @AMO-MGTSYS ,

At this time, no, dynamically changing select options is not built-in. I suggest you either create your own custom field which extends the select field, or see if using conditional logic with a couple select fields can work out in your case.

**Comment by AMO-MGTSYS** [comment]
Hi @atanas-angelov-dev ,

Thank you very much.
