### ISSUE TITLE
Problems with the container Widget

### ISSUE THREAD

**Issue by campusboy87** [htmlburger/carbon-fields#456]
Hey. I have problems with the container Widget.

## Version

  - Carbon Fields 2.1.1
  - WordPress 4.9.2
  - PHP 7.1

## Problem
Downloaded CF on the [link](https://carbonfields.net/zip/latest/), installed on the [instructions](https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-1-0) as a plugin.

I create a file cf-widget.php and connected it to a theme:

```php
require get_template_directory() . '/inc/cf-widget.php';
```

File contents:

```php
<?php

use Carbon_Fields\Widget;
use Carbon_Fields\Field;

class ThemeWidgetExample extends Widget {
	// Register widget function. Must have the same name as the class
	function __construct() {
		$this->setup( 'theme_widget_example', 'Theme Widget - Example', 'Displays a block with title/text', array(
			Field::make( 'text', 'title', 'Title' )->set_default_value( 'Hello World!') ,
			Field::make( 'textarea', 'content', 'Content' )->set_default_value( 'Lorem Ipsum dolor sit amet' )
		) );
	}
	
	// Called when rendering the widget in the front-end
	function front_end( $args, $instance ) {
		echo $args['before_title'] . $instance['title'] . $args['after_title'];
		echo '<p>' . $instance['content'] . '</p>';
	}
}

function load_widgets() {
	register_widget( 'ThemeWidgetExample' );
}
add_action( 'widgets_init', 'load_widgets' );
```

As a result I get an error **Fatal error: Class 'Carbon_Fields\Widget'**

![erorr](https://user-images.githubusercontent.com/20075333/35481678-273a36c8-0439-11e8-831e-27fc67457aff.png)

Where did I make a mistake? Thank you!

**Comment by campusboy87** [comment]
Sorry, I did not think that this code from the example should also be called by **carbon_fields_register_fields**. The problem is solved!

**Comment by bilalmalkoc** [comment]
@campusboy87  Hello. I don't understand your solution. Can you explain me? I got same issue.

**Comment by campusboy87** [comment]
> @campusboy87 Hello. I don't understand your solution. Can you explain me? I got same issue.

Hello. Code with the ad containers and fields need to call to hook `carbon_register_fields`, as in the [example](https://carbonfields.net/docs/carbon-fields-getting-started/). And I ran my code directly, which caused my code to be executed before the CF itself connects. Running your code on the hook `carbon_register_fields` ensures that the library is connected, initialized, and that all its elements are ready to go.

**Comment by bilalmalkoc** [comment]
Ok. It is **theme/inc/widgets.php**

```
use Carbon_Fields\Widget;
use Carbon_Fields\Field;

class ThemeWidgetExample extends Widget {
    // Register widget function. Must have the same name as the class
    function __construct() {
        $this->setup( 'theme_widget_example', 'Theme Widget - Example', 'Displays a block with title/text', array(
            Field::make( 'text', 'title', 'Title' )->set_default_value( 'Hello World!') ,
            Field::make( 'textarea', 'content', 'Content' )->set_default_value( 'Lorem Ipsum dolor sit amet' )
        ) );
    }

    // Called when rendering the widget in the front-end
    function front_end( $args, $instance ) {
        echo $args['before_title'] . $instance['title'] . $args['after_title'];
        echo '<p>' . $instance['content'] . '</p>';
    }
}

function load_widgets() {
    register_widget( 'ThemeWidgetExample' );
}

add_action( 'widgets_init', 'load_widgets' );
```

And i call it, from functions.php like this:

```
add_action('carbon_fields_register_fields', 'crb_register_custom_fields');
function crb_register_custom_fields() {
    require get_template_directory() . '/inc/widgets.php';
}
```

Now, my widget shows in wp-admin/widgets page. But now also i have [this ](https://github.com/htmlburger/carbon-fields/issues/684)problem. Did you got same issue?
