### ISSUE TITLE
Displaying Containers on Public Post Types

### ISSUE THREAD

**Issue by digisavvy** [htmlburger/carbon-fields#458]
## Version

  - Carbon Fields: Latest
  - WordPress: 4.9.2
  - PHP: 7

## Expected Behavior
I've written a container with two fields that I want to display for all publicly_queryable posts. 

## Actual Behavior
The containers only show up for Post and Page post types.

## Container definition
```
use Carbon_Fields\Field;
use Carbon_Fields\Container;

add_action( 'carbon_fields_register_fields', 'crb_attach_post_meta' );
add_action( 'wp_head', 'crb_attach_post_meta' );
function crb_attach_post_meta() {

	$args = array( 'public' => true );
	$post_types = get_post_types( $args );

	foreach ( $post_types as $post_type ) {
		Container::make( 'post_meta', __( 'Post Options', 'crb' ) )
			->where( 'post_type', '=', $post_type )
			->show_on_post_type( array( $post_type ) )
			->set_context( 'side' )
			->set_priority( 'low' )
			->add_fields( array(
				Field::make( 'radio', 'some_like_it_neat_hide_title', 'Hide Page Title' )
					->set_help_text( 'Useful for Landing Pages' )
					->set_default_value( 'no' )
					->add_options( array(
						'no' => 'No',
						'yes' => 'Yes',
					) ),
				Field::make( 'radio', 'some_like_it_neat_hide_featured_image', 'Hide Featured Image' )
					->set_help_text( 'Hide featured image on singular post, while still using it throughout the rest of your site' )
					->set_default_value( 'no' )
					->add_options( array(
						'no' => 'No',
						'yes' => 'Yes',
					) )
			) );

	}

}
```

## Steps to Reproduce the Problem

  1. Create a new public post type and create a new post. Go to edit screen for the new post and see the container is not there. 

## Comments
When I do a 'foreach' on 'get_post_types()' and echo it does print all post types. Also '->where' and '->show_on_post_type' seem redundant. What am I missing there?

Thanks.

**Comment by atanas-angelov-dev** [comment]
Hi @digisavvy ,

You do not need to loop all post types and define a container for each of them. Simply define a `post_meta` container without specifying a post type and that container will appear on ALL post types by default. If you wish to attach it to a specific set of post types, you can use the `IN` comparison operator and pass an array as the comparison value.

In addition, you should not create containers outside of the `carbon_fields_register_fields` hook as it can lead to unexpected behavior.

Here's how your code should look:
```php
use Carbon_Fields\Field;
use Carbon_Fields\Container;

add_action( 'carbon_fields_register_fields', 'crb_attach_post_meta' );
function crb_attach_post_meta() {

	$args = array( 'public' => true );
	$post_types = get_post_types( $args );

	Container::make( 'post_meta', __( 'Post Options', 'crb' ) )
		->where( 'post_type', 'IN', $post_types )
		->set_context( 'side' )
		->set_priority( 'low' )
		->add_fields( array(
			Field::make( 'radio', 'some_like_it_neat_hide_title', 'Hide Page Title' )
				->set_help_text( 'Useful for Landing Pages' )
				->set_default_value( 'no' )
				->add_options( array(
					'no' => 'No',
					'yes' => 'Yes',
				) ),
			Field::make( 'radio', 'some_like_it_neat_hide_featured_image', 'Hide Featured Image' )
				->set_help_text( 'Hide featured image on singular post, while still using it throughout the rest of your site' )
				->set_default_value( 'no' )
				->add_options( array(
					'no' => 'No',
					'yes' => 'Yes',
				) )
		) );
}
```

> Also '->where' and '->show_on_post_type' seem redundant

`show_on_post_type()` was left to reduce backwards compatibility/upgrade friction. You should use `where()` instead in new projects.

FYI, Carbon Fields comes with a `checkbox` field which works with real boolean values which you may find more useful instead of radio buttons with `yes`/`no` string values.

**Comment by digisavvy** [comment]
Howdy @atanas-angelov-dev,
So I totally get what you're saying and thanks for the tips and code sample! Very helpful and enlightening! =)

So I created a custom post type that is public and the meta fields do not show up. At first, I thought it was a misconfiguration of the post type. I used Pods to create the post type and it does show that the post type is public and queryable.. When I do a 'var_dump()' of 'post_types()' within the above function it returns 'page,' 'post', and 'attachment'. It should return those post types plus the additional custom post type. When I change the hook to 'init' or 'wp_head' the correct post types are returned (obviously no fields show up on the post at that point). 

I have my code loading from a separate file, which is included/called from functions.php. However, even if I place the above code in functions.php it makes no difference. So obviously I'm missing something here. Thanks for the help!

**Comment by atanas-angelov-dev** [comment]
Yup, I missed an important point - `carbon_fields_register_fields` runs before `init` has finished and `init` is where post types are registered. In order to "lazyload" the post types you can do this:

```php
->where( 'post_type', 'CUSTOM', function( $post_type ) {
	$args = array( 'public' => true );
	$post_types = get_post_types( $args );
	return in_array( $post_type, $post_types );
} )
```

This way your condition will be evaluated during a later hook, when determining if the container should be visible or not rather than on definition.

**Comment by digisavvy** [comment]
Awesome, that worked! I understand why the fields didn't show up now since I know when the `carbon_fields_register_fields` hook runs. I'm still not clear on _why_ your solution worked, so if you have any other thoughts that that would be awesome. But it works so that's great.Thank you again for your time and your help. Loving this project.

**Comment by atanas-angelov-dev** [comment]
Happy to help!

It all boils down to the fact that container definitions are run **before** all post types are registered so if you use `get_post_types()` it will not give you post types that are registered after `carbon_fields_register_fields`.
Conditions, on the other hand, are evaluated in a hook that runs after `init` has finished completely, so moving the `get_post_types()` call inside a custom condition will cause it to be ran later then the `init` hook, thus it will return all registered post types by that point.
