### ISSUE TITLE
[Help Wanted] French translation is missing a number of strings

### ISSUE THREAD

**Issue by yukulelix** [htmlburger/carbon-fields#465]
## Version
  - Carbon Fields: 2.1.0
  - WordPress: 4.8
  - PHP: 7.1

## Expected Behavior
Wordpress should load .po to display Carbon Field's UI in the current language

## Actual Behavior
UI is still in English !

Is there something I should do to load the languages files ?

**Comment by atanas-angelov-dev** [comment]
Hi @yukulelix ,

There should be no additional steps. Could you please let us know the language you switched to? Also, please try again with the latest beta release and let us know if the issue persists.

**Comment by yukulelix** [comment]
Hi @atanas-angelov-dev, I installed the latest beta and it is still not working !
The language is French. The _carbon-fields-fr_FR.po_ and _carbon-fields-fr_FR.mo_ files seem perfectly fine.
Carbon Fields is loaded via composer in a Bedrock install !

**Comment by atanas-angelov-dev** [comment]
Just got around to testing this and I can confirm our French translation files are outdated and we are missing a number of translations, but the translations we have are loaded correctly (for example the "Save Changes" button in theme options is translated to "Enregistrer les modifications").

We encourage public contributions so you are welcome to help us out with the French translations, if this is something you are interested in.

**Comment by yukulelix** [comment]
You're definitely right, sorry for the troubles ! I'll update the translation and make a push request :) ! Keep up the good work, thanks !

**Comment by jorostoyanov** [comment]
The french translations were last updated here - c3f7b483974a6da72524ad06842a264f2eca269e

Please open a PR if there are any additions needed.

Thanks!
