### ISSUE TITLE
data is not stored with a date (Flatpickr) field in mode "multiple"

### ISSUE THREAD

**Issue by creanodesign** [htmlburger/carbon-fields#466]
## Version

  - Carbon Fields: 2.1.1 (& Carbon Fields: 2.0.4)
  - WordPress: 4.9.4
  - PHP: 7.1

## Expected Behavior
Wordpress/CF should store multiple dates that comes from a date field, ie. Flatpickr in multiple mode.

## Actual Behavior
When we select one single date in the datepicker the date is stored.
When we select more that one date it is not stored (wether we are in a complex field or not it doesn't work).

## Container definition
```php
Field::make( 'date', 'deleted_date', 'Select dates' )
	->set_picker_options( array(
		'mode' => "multiple",
	) )
	->set_required( true )
	->set_input_format( "d/m/Y", "d/m/Y" )
```

## Comments
Is there something else to do to make this works?

**Comment by atanas-angelov-dev** [comment]
Hi @creanodesign ,

Multiple date/date range selection is not supported at this time. Feel free to extend the date field to support it ( and possibly contribute it :) ) or use 2 date fields (to - from) instead.

**Comment by max16150** [comment]
same issue, is this not fixed yet ?
