### ISSUE TITLE
Hebrew translation files not in plugin when composer require htmlburger/carbon-fields

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#469]
## Version 

  - Carbon Fields: 2.1
  - WordPress: 4.9.4
  - PHP: 7

## Expected Behavior
Hebrew translation files should be in repo when I'm installing via composer require htmlburger/carbon-fields

## Actual Behavior
Hebrew translation files are not in the language folder when I install with composer require htmlburger/carbon-fields

## Steps to Reproduce the Problem

  1. Install with composer require htmlburger/carbon-fields 
  2. check languages folder

**Comment by atanas-angelov-dev** [comment]
Hi @BenBroide ,

The latest Hebrew language files are in the latest beta release and composer will not install beta releases unless you specifically tell it to (e.g. `composer require htmlburger/carbon-fields:^2.1@dev`.

The latest language files will, of course, be included in the next stable version.
