### ISSUE TITLE
Set labels by row values - Complex fields set_layout() 'tabbed-horizontal' 'tabbed-vertical'

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#472]
## Version

  - Carbon Fields: 2.1
  - WordPress: 4.9.4
  - PHP: 7.1

## Expected Behavior
I would like to send a pull request which will allow to set the tab labels by the value of a fields inside the complex fields as screenshot attached. This will make the complex fields updating more user friendly.
![complex tabs labels](https://user-images.githubusercontent.com/11011901/36683439-946df45a-1aeb-11e8-8510-7570d147c103.png)

## Actual Behavior
The fields tab label id displaying the key or name of row which does not give enough info to users which tab there are looking for.

## Container definition
```php
Field::make( 'complex', 'files', 'Files' )
  ->set_layout( 'tabbed-vertical' )
  ->add_fields( array(
    Field::make( 'file', 'file', 'File' )->set_width( 20 ),
   Field::make( 'text', 'title', 'File Title' )->set_width( 40 ),
   Field::make( 'date', 'date', 'File Date' )->set_width( 20 ),
) ),
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Comments
Which files in code which handle the tab display? I didn't find them.

**Comment by atanas-angelov-dev** [comment]
Hi @BenBroide ,

Unless I'm misunderstanding something, this is already supported - check out `->set_header_template()` (https://carbonfields.net/docs/complex-field-config-methods/?crb_version=2-1-0)

**Comment by BenBroide** [comment]
I missed that, works great.
Thanks!

**Comment by shohelrrrana** [comment]
Brother Are got solution ?

**Comment by serhumanos** [comment]
yes, the solution is to use "set_header_template()" [https://docs.carbonfields.net/learn/fields/complex.html#set-header-template-template](url), in my experience this option must be used AFTER add_fields()
