### ISSUE TITLE
Namespace code docs issue/enchancement

### ISSUE THREAD

**Issue by erikkubica** [htmlburger/carbon-fields#474]
## Version

  - Carbon Fields: 2.1

## Expected Behavior
When coding, thanks to namespace it should autocomplete.

## Actual Behavior
 It does not autocomplete. Note: it affects Field class also.

## Container definition
```php
/**
 * A proxy for the abstract container factory method.
 *
 * @see    Carbon_Fields\Container\Container::factory()
 * @return Carbon_Fields\Container\Container
 */
public static function factory() {
	return call_user_func_array( array( '\Carbon_Fields\Container\Container', 'factory' ), func_get_args() );
}

```

## Comments
In the @return Carbon_Fields\..... it should be @return \Carbon_Fields    (at least PHP storm does not like it without the slash on the beginning)

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
