### ISSUE TITLE
WP Query Meta Query: When it doesn't have a value, it returns all? 

### ISSUE THREAD

**Issue by Xilonz** [htmlburger/carbon-fields#477]
## Version

  - Carbon Fields: 2.1.1
  - WordPress: 4.9.1
  - PHP: 7.0

## Expected Behavior
Return empty ```WP_Post``` object

## Actual Behavior
Returns all posts

## Container definition
```php
  $ids = wp_list_pluck( $other_posts->posts, 'ID' );

  $defaults = array(
    'posts_per_page'   => -1,
    'post_type'        => $post_type,
    'meta_query'       => array(
        array(
            'key' => 'associated_technology',
            'carbon_field_property' => 'id',
            'value' => $ids, // $ids might be empty
            'compare' => 'IN',
        ),
    ),
  );

  $args = wp_parse_args( $args, $defaults );
  return new \WP_Query( $args );
```

## Comments
I'm not sure this is caused by carbon fields, or if this is the default behavior of WP.
I now use a check to see if ```$ids``` is empty and return an empty ```WP_Post``` object, but its a hacky solution, and creates confusion.

**Comment by atanas-angelov-dev** [comment]
Hi @Xilonz ,

This is the default WordPress behavior as you can test it with this simple query which does not involve Carbon Fields at all:
```php
$q = new WP_Query( [
	'meta_query' => [
		[
			'key' => '_edit_lock',
			'compare' => 'IN',
			'value' => [],
		],
	],
] );
print_r($q->posts);
exit;
```
