### ISSUE TITLE
Is there a way to programatically update theme options fields?

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#479]
Hi,

First, thank you for this great library!

I was wondering if there is a "carbon fields" way of updating theme options fields or if I should simply use the WordPress function `update option` ?

Thanks a lot!

**Comment by atanas-angelov-dev** [comment]
Hi @KevinSupertramp ,

Please refer to this portion of the documentation:
https://carbonfields.net/docs/advanced-topics-updating-values/?crb_version=2-1-0

**Comment by KevinSupertramp** [comment]
Hi @atanas-angelov-dev ,

Thank you for your reply. I've read the documentation but it doesn't mention if the fields are in the theme options (not a post meta). Or did I miss something?

Thanks a lot.

**Comment by atanas-angelov-dev** [comment]
You can see the following signature on the page I linked:

`carbon_set_{container_type}( [$id,] $field_name, $value )`

All `carbon_get_*` functions have a respective `carbon_set_*` function:
`carbon_set_theme_option( $field_name, $value )`, `carbon_set_post_meta( $id, $field_name, $value )` etc.

**Comment by KevinSupertramp** [comment]
Oooh I see!
It makes sense now, thanks a lot!!
