### ISSUE TITLE
Reset validation errors using Javascript API

### ISSUE THREAD

**Issue by AMO-MGTSYS** [htmlburger/carbon-fields#483]
Hello,
Question please: is there a way to reset validation errors to No errors?

To illustrate the use case imagine you have a three fields and you want to rise an error if sum different than a number 100 for example. Imagine you input 20, 20,60, errors rise for the first and second field and i need to reset them to No errors when the third value is taped.

**Comment by atanas-angelov-dev** [comment]
Hi @AMO-MGTSYS ,

I do not believe this use case is covered by the JS API as only the field you edit is validated instead of every field on every keystroke.

**Comment by AMO-MGTSYS** [comment]
Thank you @atanas-angelov-dev 

I was thinking of resetting field values i want to re-validate using api.setFieldValue.

Do you think it's a viable solution?

**Comment by atanas-angelov-dev** [comment]
(@AMO-MGTSYS sorry for the late reply)

If forcing the value of related fields using api.setFieldValue() triggers the validation (I expect that it does) then feel free to use it.
