### ISSUE TITLE
network_container_saved hook

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#484]
## Version

  - Carbon Fields: 2.2.0-beta.5
  - WordPress: 4.9.4
  - PHP: 7.2.0

## Expected Behavior
Per current [docs](https://carbonfields.net/docs/advanced-topics-hooks/?crb_version=2-1-0) for `carbon_fields_{container_type}_container_saved` (which I realize have not been updated for 2.2.x yet), saving `network` containers should observe a `carbon_fields_network_container_saved` hook.

## Actual Behavior
It appears that the `carbon_fields_theme_options_container_saved` hook is used.

## Container definition
```php
Container::make( 'network', 'some_container', 'Some Container' )
    ->set_page_parent( 'settings.php' )
    ...
```

## Steps to Reproduce the Problem

  1. Create `network` container. Add 1 or more fields.
  1. Add `carbon_fields_network_container_saved` that var_dump's $_POST and exits.
  1. Hook is not triggered.

## Comments
This may be an intended convention. I bring it up for consistency. Thank you.

**Comment by atanas-angelov-dev** [comment]
Hi @dmhendricks ,

Thank you for the report - I've added a fix for this in `development` which will make it into the next beta/major release.

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
