### ISSUE TITLE
Association Field Titles: HTML Entities Not Decoded

### ISSUE THREAD

**Issue by austins** [htmlburger/carbon-fields#485]
## Version

  - Carbon Fields: 2.1.1
  - WordPress: 4.9.4
  - PHP: 7.2.3

## Expected Behavior
The association field should decode HTML Entities from displayed post titles or not encode them in the beginning.

## Actual Behavior
I have a post with the title `Example's Awesome Title`. The association field displays the title as `Example&#8217;s Awesome Title`.

## Container definition
```php
Container::make('post_meta', __('My Container', 'myplugin'))
    ->where('post_type', '=', 'customtype')
    ->add_fields([
        Field::make('association', 'related_posts', __('Related Posts', 'myplugin'))
            ->set_types([['type' => 'post', 'post_type' => 'post']])
    ]);
```

## Steps to Reproduce the Problem

  1. Add a post with a special character in the title such as `Example's Awesome Title`.
  2. Go to add a new customtype post where the container and association field is shown.
  3. See that the association field doesn't decode the HTML entities from title strings.

**Comment by atanas-angelov-dev** [comment]
2.2.0 is now live which addresses this issue.
