### ISSUE TITLE
Multiple query hooks breaking association fields on theme options

### ISSUE THREAD

**Issue by RachelRVasquez** [htmlburger/carbon-fields#487]
## Version

  - Carbon Fields: 2.1.1
  - WordPress: 4.9.4
  - PHP: 7.1.15

## Expected Behavior
I'm have a theme options page with association fields. I'm using the `carbon_fields_association_field_options_[assoc_field_name]_post_post` filter to hook into the association field and add query arguments. I have 6 association fields on the one  theme options page. I'd like to modify query arguments for each association field separately without interfering with one another.

## Actual Behavior
I tried to set it where 3 assoc. fields use one query argument function, and the other 3 use a different query function and it throws a PHP error. The syntax is exactly the same as the others - the field name is correct in the hook and the right function name is being called without typos. I even simplified during troubleshooting down to 2 fields, each a different query argument function and it still throws errors.

Here is an example of what my code looks like. If the filter for both association fields use the function `query_foobar_field()` then it will work. But if I try to add query arguments per association field - that is where the problem kicks in.

**Note:** Using a PHP class with an `init()` function but I didn't add it below for the sake of simplicity.

```php
add_filter( 'carbon_fields_association_field_options_foobar_assoc_name_post_post', [
				$this,
				'query_foobar_field'
			] );

add_filter( 'carbon_fields_association_field_options_foobar2_assoc_name_post_post', [
				$this,
				'query_foobar_field_2'
			] );

function query_foobar_field( $query_arguments ) {
		$query_arguments['orderby']        = 'date';
		$query_arguments['posts_per_page'] = '100';
		$query_arguments['category_name']  = 'foobar';
	}

//why can't I use modify each assoc. field's arguments separately?
function query_foobar_field_2( $query_arguments ) {
		$query_arguments['orderby']        = 'date';
		$query_arguments['posts_per_page'] = '50';
		$query_arguments['category_name']  = 'foobar-2';
	}
```

## PHP Error
```php
PHP Notice:  Object of class WP_Post could not be converted to int in [my_project_path]/vendor/htmlburger/carbon-fields/core/Field/Association_Field.php on line 280
```

Sometimes the error above points to line 277 or 278 as well. Something in that area of core is causing the error. My guess is trying to run two different query hooks on the same theme options page with several association fields is confusing the logic. 🤔 If I keep it to one query only for all the association fields, I don't have an issue.

## Steps to Reproduce the Problem

  1. Create a theme options page
  1. Add 2 association fields to the page
  1. Use the query filter hook to change the query to 1 association field only
  1. Then try to use the query filter hook to change the query to the other association field and see if a PHP error is thrown

In the meantime, I may have to create additional theme options pages just to keep the association fields separate so it's one query per theme options page. 😞

**Comment by atanas-angelov-dev** [comment]
Hi @RachelRVasquez ,

I don't see you using `return $query_arguments;` in your filters - make sure you do this otherwise you can trigger unexpected behavior (filters should always return the filtered value).

**Comment by RachelRVasquez** [comment]
@atanas-angelov-dev Thank you, I was staring at this for like 2 hours! 🥇 🎉 🎈 🍰 That's what it was, I didn't return. #devLife
