### ISSUE TITLE
How to disable the sidebar generator?

### ISSUE THREAD

**Issue by alessandrotesoro** [htmlburger/carbon-fields#488]
Hi there,

Thanks for this fantastic library. I'm using it just to generate custom fields and do not need the sidebar generator. Is there a built-in way to disable the sidebar generator from the widgets screen? I tried searching in the docs and here on github and unless I've missed it, I couldn't find anything.

**Comment by atanas-angelov-dev** [comment]
Hi @alessandrotesoro ,

Note that this is neither supported nor tested but should do the trick:
```php
// immediately after calling \Carbon_Fields\Carbon_Fields::boot();
$sidebar_manager = \Carbon_Fields\Carbon_Fields::resolve('sidebar_manager');
remove_action( 'admin_enqueue_scripts', array( $sidebar_manager, 'enqueue_scripts' ) );
```

**Comment by alessandrotesoro** [comment]
Sweet thanks it works 👍
