### ISSUE TITLE
RichText field TinyMCE initialization bug

### ISSUE THREAD

**Issue by m1r0** [htmlburger/carbon-fields#49]
The TinyMCE editor initialization fails with the following code:

```
Container::make( 'post_meta', __( 'Profile' ) )
    ->add_fields( array(
        Field::make( 'rich_text', 'first_name', __( 'First Name' ) )
            ->set_width( 50 ),
        Field::make( 'rich_text', 'last_name', __( 'Last Name' ) )
            ->set_width( 50 ),
    ) );
```

It only fails on the first RichText field.

If a third field is added - the initialization is OK.

**Comment by alpanayotov** [comment]
@m1r0  Probably is due to lazy loading :)

**Comment by m1r0** [comment]
Fixed in https://github.com/htmlburger/carbon-fields/commit/3fe5f994e24a7438ce79c627745220f2d4d208ae.
