### ISSUE TITLE
Modify Rich Text

### ISSUE THREAD

**Issue by sanjayatony** [htmlburger/carbon-fields#492]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9
  - PHP: 7

Can modify the looks of 'rich text'. Example : hide media button

**Comment by deqngeorgiev** [comment]
Hi @sanjayatony ,

I've added `crb_media_buttons_html` filter (development branch) with which you can remove the media buttons from a rich_text field. This will be added in the next release.
Example:
```
add_filter( 'crb_media_buttons_html', function( $html, $field_name ) {
	if ( $field_name === 'rich_text_field_name_here' ) {
		return;
	}
	return $html;
}, 10, 2);```

**Comment by sanjayatony** [comment]
Thanks man!
