### ISSUE TITLE
Docs: Network Container example

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#493]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.4
  - PHP: 7.0.3

## Comments

Currently, the page for the new [`network` container](https://carbonfields.net/docs/containers-network/?crb_version=2-2-0) suggests that you reference the `theme_options` docs.

I'm thinking that it may be useful to add some quick examples, particularly since `carbon_get_network_option()` requires a site site ID to be passed.

Further, since the function does not accept `null` for the network site ID (as [`get_network_option()`](https://developer.wordpress.org/reference/functions/get_network_option/) does), it may be helpful to include in the example passing the current `SITE_ID_CURRENT_SITE` (if defined).

**EDIT:** In looking at the code to verify this post, I discovered the `carbon_get_the_network_option()` function, which I was not aware of until now. It may be useful to mention that function on the page as well, since I would imagine (??) that, quite often, you're probably looking to get a network option for the current site ID. YMMV

Semi-related note: `carbon_get_network_option()` should probably allow `null` for the site ID (and thus default to `SITE_ID_CURRENT_SITE`) to be consistent with WordPress's `get_network_option()`.

**EDIT 2:** I am _swamped_ with my current project, but when/if I ever have time, I would be willing to submit a PR for the docs. It may be awhile, though, so if anyone here has time, I would be open to assisting.

**Comment by BenBroide** [comment]
I could give you hand with this. Could you paste the code example you want yo add to docs? I'm not sure from what you wrote want you want to add

**Comment by dmhendricks** [comment]
I'd be happy to come up with an/some example(s) that follow(s) the conventions of the current CF docs. However, I probably won't have time until this weekend. I will keep you updated here.

**Comment by dmhendricks** [comment]
Closed and moved to [htmlburger/carbon-fields-docs/issues/32](https://github.com/htmlburger/carbon-fields-docs/issues/32).
