### ISSUE TITLE
Textarea field stripping backslashes (network container)

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#494]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.4
  - PHP: 7.0.3

## Expected Behavior
When saving a `textarea` field in a `network` container, it should not strip backslashes.

## Actual Behavior
When saving a `textarea` field in a `network` container, it strips out backslashes.

## Container definition
```php
Container::make( 'network', 'crb_my_network_test_container', 'CF Test' )
  ->set_page_parent( 'settings.php' )
  ->add_fields( array(
    Field::make( 'textarea', 'crb_network_textarea_field', 'Text Area Field' )
  )
);
```

## Steps to Reproduce the Problem

  1. Create `network` container with `textarea` field.
  1. Go to the page with the container created above.
  1. Type some random text in the `textarea` field, making sure that it contains one or more backslashes (\\).
  1. Save Changes

## Comments
This behavior appears inconsistent using the same `textarea` field definition in a `theme_options` container, where it is not stripping backslashes (\\) from text that I save. In other words, the following does not strip backslashes for me (the notable difference from the code above being the container type):

```php
Container::make( 'theme_options', 'crb_my_site_test_container' )
  ->set_page_parent( 'options-general.php' )
  ->add_fields( array(
    Field::make( 'textarea', 'crb_textarea_field', 'Text Area Field' )
  )
);
```

**Comment by deqngeorgiev** [comment]
WordPress expects slashed data when adding a network option. The issue will be fixed in the next release.

As a workaround, you can override the `save_key_value_pair` method of the `Meta_Datastore` class.

```
protected function save_key_value_pair( $key, $value ) {
	$value = wp_slash( $value ); // Fix value unslash

	if ( ! update_metadata( $this->get_meta_type(), $this->get_object_id(), $key, $value ) ) {
		add_metadata( $this->get_meta_type(), $this->get_object_id(), $key, $value, true );
	}
}
```

**Comment by dmhendricks** [comment]
Thank you @deqngeorgiev! I fixed it temporarily by escaping the fields via `carbon_fields_network_container_saved`, but it's inconvenient. I like your solution better.

Thanks again,
Daniel
