### ISSUE TITLE
Previously-saved Content in Conditional Fields Disappears

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#495]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.4
  - PHP: 7.0.3

## Expected Behavior
I assume that this is by design, but it would be nice if there is a way to preserve data in conditional fields when they are toggled on/off by condition.

## Actual Behavior
When I save data in conditional field(s), then later the fields are disabled by condition, when re-enabled, the content is gone.

## Container definition
```php
Container::make( 'theme_options', 'crb_my_options_container', 'CF Test (Site)' )
  ->set_page_parent( 'options-general.php' )
  ->add_fields( array(
    Field::make( 'checkbox', 'crb_subsite_checkbox_test', 'My Checkbox Field' ),
    Field::make( 'textarea', 'crb_subsite_textarea_test', 'My Conditional Textarea Field' )
      ->set_conditional_logic( [ [
        'field' => 'crb_subsite_checkbox_test',
        'value' => true,
        'compare' => '='
      ]
    ]
  )
));
```

## Steps to Reproduce the Problem

  1. Create conditional fields using above example.
  1. Tick the checkbox field to display the conditional textarea.
  1. Add some content to the textarea.
  1. Save Changes
  1. Un-tick the checkbox field. The textarea will disappear.
  1. Save Changes
  1. Re-tick the checkbox field.

The conditional textarea will display (as expected), but the content added in steps 3-4 is missing/empty.

## Comments
Is there a way to preserve the data that has been previously saved to conditional fields if/when they are temporarily toggled off? I didn't notice anything in the docs.

I believe that I can do it using the `carbon_fields_{container_type}_container_saved` hook, but I was wondering if there was a better/less clunky way (as I would have to create the extra logic for each/new field).

<img width="781" alt="cf22-conditional-field-data-disappears" src="https://user-images.githubusercontent.com/8184361/37986451-19c445e6-31c1-11e8-8bd3-8a01c425a214.png">

**Comment by deqngeorgiev** [comment]
Hi @dmhendricks ,

That is by design and I believe the value from a toggled off field shouldn't be saved to the database.

**Comment by dmhendricks** [comment]
Ok. It would be nice if the default would still appear even if the content isn't preserved. Thank you.
