### ISSUE TITLE
header_scripts/footer_scripts fields do not work in network container

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#499]
## Version

  - Carbon Fields: 2.2.0 (plugin)
  - WordPress: 4.9.4
  - PHP: 7.0.3

## Expected Behavior
When `header_scripts` and `footer_scripts` fields are used in `network` container, I expected the head injections to apply globally to **_all_** sub-sites.

## Actual Behavior
`header_scripts` and `footer_scripts` appear to do nothing when used in the `network` container.

## Container definition
```php
// These do not work
Container::make( 'network', 'crb_my_network_container', 'CF Test' )
  ->set_page_parent( 'settings.php' )
  ->add_fields( array(
    Field::make( 'header_scripts', 'crb_network_header_scripts', 'Global Header Script' ),
    Field::make( 'footer_scripts', 'crb_network_footer_scripts', 'Global Footer Script' )
  )
);

// ...versus...

// These work
Container::make( 'theme_options', 'crb_my_theme_container', 'CF Test' )
  ->set_page_parent( 'options-general.php' )
  ->add_fields( array(
    Field::make( 'header_scripts', 'crb_header_scripts', 'Site Header Script' ),
    Field::make( 'footer_scripts', 'crb_footer_scripts', 'Site Footer Script' )
  )
);
```

## Steps to Reproduce the Problem

  1. Create network container. Add `header_scripts` and/or `footer_scripts` field(s).
  1. Add data to said field(s) and click Save Changes.
  1. View source on front-end - no apparent injections occur.

## Comments
I got around this by using textarea fields and injecting manually, but it feels like something that should be consistent and would probably be handy.

**Comment by deqngeorgiev** [comment]
Hi @dmhendricks ,

I've fixed this in the development branch.
