### ISSUE TITLE
Migrating site with carbon fields

### ISSUE THREAD

**Issue by samducker** [htmlburger/carbon-fields#500]
Hey I'm migrating carbon fields from a site with it installed to the next.

I used WP-DB Migrate, but this has kept all of the content on the new site the same but I can no longer see the editable fields in the admin panel.

Which database table are carbon fields for the admin panel stored in?

**Comment by BenBroide** [comment]
post meta would be in wp_postmeta and theme options would be in wp_options.
Is this post meta or theme options?

**Comment by deqngeorgiev** [comment]
Hi @samducker ,

The fields should be visible even if there are no values stored in the database, so I believe the issue is not the migration. Can you provide, please, more information about your setup and how you have registered the fields? Also, check the console for errors.

**Comment by m1r0** [comment]
Hm, just tested the plugin and it successfully migrated a database that has many fields in it. Not really sure where the problem might be in your case...

Closing the issue due inactivity and until we the info requested by @deqngeorgiev.
