### ISSUE TITLE
Set_conditional_logic two conditions ad more

### ISSUE THREAD

**Issue by Excelsiorer** [htmlburger/carbon-fields#501]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.5
  - PHP:

## Expected Behavior
I need the DATE field to be displayed only if TYPE = EVENTS. 
And I need the Title field to be displayed only if TYPE = MEDIA. 

## Actual Behavior
But when you apply my code, the fields are not displayed at all

## Container definition
`<?php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

Container::make( 'post_meta', __( 'Options', 'crb' ) )
    ->where( 'post_type', '=', 'post' )
    ->add_fields( array(
        Field::make( 'select', 'blog_type', 'Type:' )
	    ->add_options( array(
	        'events' => 'EVENTS',
	        'media' => 'MEDIA',     
	    ) ),
    	Field::make( 'text', 'event_date', 'Date' )
	 		->set_conditional_logic( array(
		        array(
		            'field' => 'blog_type',
		            'value' => events,
		        )
		    )),
    	Field::make( 'text', 'event_title', 'Title' )
	 		->set_conditional_logic( array(
		        array(
		            'field' => 'blog_type',
		            'value' => events,
		        ),
		        array(
		            'field' => 'blog_type',
		            'value' => media,
		        )
		    )),    	
) );`

## Comments

Good day!
I can not understand how to add to one field, two conditions?

I have like this, but it doesn't work.

**Comment by deqngeorgiev** [comment]
Hi @Excelsiorer ,

You should set the `relation` key when there is more than one rule. The `relation` key defaults to `AND` but in your case, it should be set to `OR`: 

```
Field::make( 'text', 'event_title', 'Title' )
	->set_conditional_logic( array(
		'relation' => 'OR',
		array(
			'field' => 'blog_type',
			'value' => 'events',
		),
		array(
			'field' => 'blog_type',
			'value' => 'media',
		)
) ),
```
