### ISSUE TITLE
Carbon Fields & Gutenberg

### ISSUE THREAD

**Issue by broskees** [htmlburger/carbon-fields#502]
Was reading this [thread](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjGxM_bgqXaAhVDWq0KHTEvBlgQFggyMAE&url=https%3A%2F%2Fgithub.com%2FWordPress%2Fgutenberg%2Fissues%2F952&usg=AOvVaw0oUROBTzOf1moXYugvboeq), and saw a reference to Carbon Fields by the lead developer. What are your plans for support? Sounds like you're going to keep legacy Metaboxes?

**Comment by dzmitROCK** [comment]
Agreed. It would be great

**Comment by emohamed** [comment]
We're currently investigating the options for integrating Carbon Fields with Gutenberg. We'll publish roadmap for integration by end of April.

**Comment by emohamed** [comment]
https://carbonfields.net/2018/04/27/plans-for-carbon-fields-and-gutenberg-integration/

The tl;dr is:

 * we'll make sure that Carbon Fields work well in the custom fields area below the Gutenberg Editor
 * we'll experiment with new container type `block` that will define dynamic Gutenberg blocks(example here: https://gist.github.com/emohamed/28782aa3ee48b9c232134a5ac98dcae4)

**Comment by dmhendricks** [comment]
Nice moves! The `block` container type would be _**very**_ excellent.

**Comment by jorostoyanov** [comment]
We have just released a Release Candidate for Carbon Fields v3 with added support for Gutenberg.

You can read more about it here: https://carbonfields.net/2018/12/13/introducing-carbon-fields-v3/
