### ISSUE TITLE
Is there a way to santize fields before saving them?

### ISSUE THREAD

**Issue by ShariqKhan2012** [htmlburger/carbon-fields#504]
## Version

  - Carbon Fields:2.2.0
  - WordPress:4.8.6
  - PHP:5.6.25

## Issue
I have a 'complex' group containing many fields like textbox, textarea, dropdown, and color-picker.
I entered some JavaScript in one of the textboxes and some HTML in another. I did the same for the textarea fields. The values were getting saved as it is in the database without any sanitization.
At least the JavaScript should have been stripped off.

I was expecting textboxes to strip HTML as well as JavaScript, and textareas to support HTML but strip JavaScript.
With the current behavior, there seems to be no difference between textarea and textbox other than their visual appearance.

Is it something that I am doing wrong on my end, or is the just the way it works?
Is this is the expected behavior, is there a way to specify a callback function for sanitization?
Or perhaps any hook just before the values are being saved?

To be honest, I looked up in the codebase and the git issues but could not find anything relevant, but thought I'd ask anyway.

I understand that I can totally sanitize the values before outputting them on the frontend, but I think I should be able to sanitize the values before they are saved into the database. The reason is if the values are sanitized on the frontend but saved as they are on the backend, it results in inconsistent behavior.

For example, in my case, I am using your fantastic library to create a plugin. I want the users to not be able to save any HTML in certain fields (textboxes) as it would break the layout and would defeat the purpose of having another field (a textarea).
As of now, the user is able to save HTML markup in the textboxes. And I cant do anything about it.
I can, of course, sanitize the value before outputting it on the frontend, but it will leave user confused why the value they saved is not being saved as it is. They may also think of it as a bug.

I believe there would be many more cases where people would want to be able to sanitize the values of the fields.

If this is not supported yet, do you plan to include it shortly? Or perhaps, would you accept a pull request to add this functionality?

**Comment by andrewostrin** [comment]
You can use included filters/actions to add your own validation rules or adjust stored data.

https://carbonfields.net/docs/advanced-topics-hooks/
https://codex.wordpress.org/Plugin_API

**Comment by ShariqKhan2012** [comment]
Thanks for the reply. Would `carbon_fields_should_save_field_value ` be the right hook for the purpose?

**Comment by deqngeorgiev** [comment]
Hi @ShariqKhan2012  ,

The `carbon_fields_should_save_field_value` allows you to modify whether the field will save its value, so it will not be helpful for your purposes. As @andrewostrin mentioned, you can use the JavaScript API and add custom validation -- https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-2-0

**Comment by ShariqKhan2012** [comment]
@deqngeorgiev Thank you. You are correct. Using `carbon_fields_should_save_field_value `, I could either save the value as it is or not at all. I could not use it (or any other hook) to save the sanitized value.
So I used JavaScript to sanitize the values on pressing the submit (Publish/Update) button. 

I would have very much preferred if there was a hook to sanitize values on the server side rather than the client side.

**Comment by pablo-sg-pacheco** [comment]
I love Carbon Fields, but I must say this should be urgently implemented!

This is how I'm doing for the time being though:

```php
add_action( 'carbon_fields_container_activated', function ( $container ) {
	foreach ( $container->get_fields() as $field ) {
		add_filter( "sanitize_option__{$field->get_base_name()}", function ( $value, $option ) {
			$value = sanitize_text_field( $value );
				return $value;
		}, 10, 2 );
	}
} );
```

**Comment by pablo-sg-pacheco** [comment]
Ok,

I found out a better way. First you need to create a [custom data store](https://docs.carbonfields.net/learn/advanced-topics/serialized-datastore.html) for your containers. I'm following the same example from the link, except one thing. I'm not exending a `Datastore` class. I'm extending the data store for the container I want. For example. For my `post_meta` container I'm extending the `Post_Meta_Datastore` class.

I'm now extending the `save()` and `save_key_value_pair()` methods.

And I'm setting the datastore like this:
`Container::make( 'post_meta', 'My Container' )->set_datastore( new Carbon_Fields_Datastore() )`

I lost many hours with this. I hope it helps someone.

**Comment by netlas** [comment]
There is an action hook I found in the source, `carbon_fields_before_field_save` that is not mentioned in the docs. This can be used instead of declaring a whole `Datastore` class.

I use it to sanitize some SVG code like this:

```
add_action( 'carbon_fields_before_field_save', 'sanitize_svg');
function sanitize_svg(\Carbon_Fields\Field\Field $field)
{
    if ($field->get_base_name() == 'svg') {
        $svg = Utils::sanitize_svg($field->get_value());
        $field->set_value($svg);
    }
    return $field;
}
```
