### ISSUE TITLE
How are fields stored in the database ( user meta )?

### ISSUE THREAD

**Issue by alessandrotesoro** [htmlburger/carbon-fields#507]
Hi there,

I've been rebuilding an old plugin of mine and I decided to use carbon fields for the custom user fields, however I've come across a weird issue with all custom fields.

If I use `get_user_meta` to retrieve the value of a meta field it doesn't work. Nothing is printed out. If I use the built-in `carbon_get_user_meta` it correctly displays the value of the field. This is an issue, since existing custom fields generated by other plugins ( who simply use `update_user_meta` ) will not work with carbon fields. So I can't release an update that will break thousands of sites.

How are user meta fields being stored into the database? 

Edit: I've just noticed fields are being stored with an underscore _ before the meta key name. Is there a way to avoid that?

Thank you.

**Comment by deqngeorgiev** [comment]
Hi @alessandrotesoro ,

By default, the fields are stored with `_` before the key name. You can use custom Datastore for you fields to avoid that. 

There is an example for serializing Theme options with a custom Datastore in the docs - https://carbonfields.net/docs/guides-serialized-datastore/?crb_version=2-2-0

You can make something similar but remove the underscore and save the user meta.

**Comment by alessandrotesoro** [comment]
@deqngeorgiev I've tried different things but I can't get it to work. Do you have any email address where I can reach you to discuss how much you'd charge for this?

**Comment by emohamed** [comment]
@alessandrotesoro we'll be happy to provide paid support. Please drop us a note here: https://htmlburger.com/wordpress-development#app-order-simple
