### ISSUE TITLE
Options Page Container

### ISSUE THREAD

**Issue by vaurdan** [htmlburger/carbon-fields#51]
I'm developing a plugin using Carbon Fields, and I think there's an important feature missing. I want to add a Options Page that is not a Theme Options page.

This menu item should be able to be a parent of any other WordPress admin menu, like Options or even a Custom Post Type menu. 

I tried to use Theme Options Container for this, but I can only create top menu items (or submenu items that are childs of other Carbon Container page), I can't create a sub menu item of any other non Carbon Fields menu item.

Is there any time line for this feature?

Thanks!

**Comment by m1r0** [comment]
Hi @vaurdan,

You can use the `set_page_parent()` method of the Theme Options container to set the parent admin menu by passing the menu slug name (similar to the `add_submenu_page()` WordPress function). For example, to show the container on the page post type you can do:

```
Container::make('theme_options', 'Page Options')
    ->set_page_parent('edit.php?post_type=page')
    ->add_fields(array(
        Field::make('text', 'some_option'),
        Field::make('text', 'another_option')
    ));
```

Hope this helps.

**Comment by vaurdan** [comment]
Oh that's perfect! I was trying with the page name, which now sounds stupid. Thanks!

**Comment by m1r0** [comment]
No problem.
