### ISSUE TITLE
Show current widget type in set_header_template

### ISSUE THREAD

**Issue by iamntz** [htmlburger/carbon-fields#511]
The issue is simple: when you have multiple fields type within a complex field, is hard to see which is which.

So there is any way of having this:

![](https://img.iamntz.com/2018-04-25_10h10_17.jpg)

Instead of:

![](https://img.iamntz.com/2018-04-25_10h10_56.jpg)

Thanks!

**Comment by ght** [comment]
You can do this manually in your `set_header_template()` call, with the added advantage of being able to localize the strings. We usually end up doing something like:
```php
->set_header_template('<# if (heading) { #>{{ heading }}<# } else { #>Untitled<# } #> ('.__('FooBar field', 'yourtextdomain').')');
```

**Comment by deqngeorgiev** [comment]
Hi @iamntz ,

Thank you for your feedback. I believe the label should be shown by default. We will check this out.

**Comment by deqngeorgiev** [comment]
The tab labels are changed in the development branch to show the group name instead of the index when `set_header_template` is used and the field used for header is empty (https://github.com/htmlburger/carbon-fields/commit/89b46ea42d8c1ed5eca8646681035ca026cac14e).
