### ISSUE TITLE
Image select-Field-Type

### ISSUE THREAD

**Issue by breath-ee** [htmlburger/carbon-fields#512]
# Version

- Carbon Fields: 2.2.0
- WordPress: 4.9
- PHP: 7

Use thumbnail image/icon for selectors. Would make for pretty theme option pages.

![Image_select-_Field-_Type.jpg](https://s18.postimg.cc/v7xncmmp5/image_select-_Field-_Type.jpg)

Source: 

- https://github.com/monecchi/cmb2-image-select-field-type
- https://www.proy.info/how-to-create-cmb2-image-select-field-type/

**Comment by breath-ee** [comment]
dmhendricks... Your on fire! Thanks again. I'll check this out.

Btw, it was your [post](https://www.danhendricks.com/2016/12/carbon-fields-for-wordpress/) that showed me Carbon Fields when looking for ACF alternatives!

**Comment by m1r0** [comment]
Thanks for the suggestions guys! I added a new feature request for the radio image labels, feel free to continue the conversation there.
