### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by breath-ee** [htmlburger/carbon-fields#513]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9
  - PHP: 7

Vertical tabs.

![Vertical tabs](https://s18.postimg.cc/sqlw5lfq1/vertical-_Tab-meta.jpg)

Source: https://github.com/LeadSoftInc/cmb2-tabs

**Comment by deqngeorgiev** [comment]
Hi @breath-ee ,

Currently, you can use vertical tabs by adding `->set_layout( 'tabbed-vertical' )` . You can find more information in the documentation -- https://carbonfields.net/docs/complex-field-config-methods/?crb_version=2-2-0

**Comment by breath-ee** [comment]
Thanks dmhendricks... again!

I've only just found Carbon Fields project after looking at [CMB2](https://github.com/CMB2/CMB2) and the dated [OptionsTree](https://github.com/valendesigns/option-tree). I just liked some of the presentation styles those projects had that didn't come across in the Carbon docs.
