### ISSUE TITLE
Correct way to include as a library in my plugin while accouting for older versions.

### ISSUE THREAD

**Issue by ShariqKhan2012** [htmlburger/carbon-fields#519]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.1
  - PHP: 5.6.25

KIndly excuse me for asking the question which has been asked (and answered) multiple times it seems.
But I am a novice with composer, so I feel the need to confirm again.

I want to include CF inside my plugin as a library, and not as a separate plugin.
I believe the right way to do that would be to use the composer method.
So I used the following command from my WP root:
`composer require htmlburger/carbon-fields-plugin`

This created a vendor directory in WP root which had another subdirectory 'carbon field'. It also downloaded 'carbon-fields-plugin' inside the wp-content/plugins folder.
From what I understand after going through similar issues, is that the one is the actual plugin itself and the other is the autoloader plugin for that.

Since I want my plugin to use CF as a library (and not as a separate plugin), this did not look right to me.
So, I deleted the files downloaded by the above command, created a composer.json inside my **plugin's** root directory and executed the `composer install` command from there. The contents of composer.json were:
```
{
	"extra": {
        "installer-paths": {
            "vendor/{$vendor}/{$name}/": ["type:wordpress-plugin"]
        }
    },
	"require": {
		"htmlburger/carbon-fields-plugin": "^2.2"
	}
}
```
Now the plugin and the autoloader got downloaded within vendor subdirectory inside my plugin, just as I wanted.
Everything is working fine, yet due to my almost-negligible knowledge about using composer, I am still doubtful whether the steps I followed are correct, or if there is a better way of doing this.
Would really appreciate any comments on this.

Further, I am still not sure what will happen if someone activating my plugin already has an older version of 'Carbon Fields' already active, either installed as a plugin or included through any other plugin (just like my plugin is doing).
How should one handle such potential conflicts in code?

**Comment by QWp6t** [comment]
Carbon Fields won't load two different versions. It will bail early if another version is already loaded (regardless of whether the already-loaded version is newer or older).

Your plugin can check for the minimum supported version of Carbon Fields by looking at the constant `Carbon_Fields\VERSION`.

**Comment by ShariqKhan2012** [comment]
Thank you @QWp6t. That was very helpful. I guess I can use the constant to display admin notice (warning) if the requirement of minimum supported version is not met.
I will close the ticket as my query has been resolved.

**Comment by reigelgallarde** [comment]
In relation to this, I have a problem.
Another plugin is using an older version, is there a way I can run another version in my plugin?
Taking the consideration that I have no control of that another plugin...
Also, what is the best way if ever I'm the plugin owner and don't want to lock another plugin from using a different version?
