### ISSUE TITLE
Google maps new policy

### ISSUE THREAD

**Issue by edwardhew** [htmlburger/carbon-fields#522]
## Version 2.2.0

  - Carbon Fields: Map
  - WordPress: not related
  - PHP: not related

## Expected Behavior
Map display issue on admin, Google maps does not display, I think this might be due to changes at Google, of course the new policy changes - all users of the API need billing account, so owner of the key will be charged for all our uses.

## Actual Behavior
Display of map and location marker

## Container definition
```php
Field::make( 'map', 'company_map', 'Google map' )
```
## Comments
Myself, I've started using the share embed code, the one you get from Share button > Embed a map (Example [Apple's old HQ address](https://www.google.com/maps/place/Infinite+Loop,+Cupertino,+CA+95014,+USA/@37.3320003,-122.0329699,17z/data=!3m1!4b1!4m5!3m4!1s0x808fb5b6e7b4b9fb:0x697a4332574f50d9!8m2!3d37.3320003!4d-122.0307812)), except without their custom encoding. Seems to be a free and easy way to add a Google map, way easier than doing the Maps API.
```html
<iframe src="https://www.google.com/maps?q=<?= urlencode($address_str); ?>&output=embed&zoom=<?= $map['zoom']; ?>" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
```
What do you guys think if this is also used for admin side? I like how it looks for user facing side due to the easy full screen and Directions buttons.

**Comment by deqngeorgiev** [comment]
Hi @edwardhew,

Unfortunately we can't just use an iframe because that way we'll loose interactivity on the map for things like geocoding address, placing marker on the map, etc. 

According to Google Maps Platform pricing, there is free tier for $200 monthly usage which should be enough for most cases(even though you need a valid credit card to get the key). 

I've opened a new issue(#524) for introducing new field type for a free mapping service(e.g. [Leaflet](http://leafletjs.com/)).

**Comment by edwardhew** [comment]
Oh right, I rarely move the marker, forgot that feature. Honestly, I'm totally fine without the map field at all, typically I'll have address inputs anyway and the Maps field, I can just pull the data from my Address inputs and build the free embed map. Google Maps is accurate enough most of the time when you send it a full address, and if it's not, the free embed map won't help in marker placement anyway. I'm good with this issue then, you guys are always super helpful, thank you!!
