### ISSUE TITLE
Add elements at the beginning of the Complex container

### ISSUE THREAD

**Issue by aginev** [htmlburger/carbon-fields#525]
Any option to add elements at the beginning of the Complex container?

Regards

Nasko

**Comment by emohamed** [comment]
Hi @aginev 

Do you mean that you'd like to add some HTML in the beginning of a complex field?

**Comment by aginev** [comment]
@emohamed Nope asking about way to add new entries on top of the existing one https://i.imgur.com/pZB75S4.png

Regards

**Comment by emohamed** [comment]
Unfortunately this is not supported at this time. Nevertheless, you could try to create a new field that prepends groups insteads of appending them(by using the current complex field as reference). 

Here is quickstart for creating fields: https://carbonfields.net/docs/extending-field-in-a-theme/?crb_version=2-2-0

Here is the source of the complex field: https://github.com/htmlburger/carbon-fields/tree/master/assets/js/fields/components/complex

The actual redux store change is happening here: https://github.com/htmlburger/carbon-fields/blob/859396c016ddf05543e4837c4ae3f97e2e7122d9/assets/js/fields/reducer.js#L37

Hope that this helps.
