### ISSUE TITLE
date_time field doesn't display time selector in network container

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#526]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.5
  - PHP: 7.1.15

## Issue Summary
The `date_time` field type doesn't display the time selector in `network` containers.

## Container definition
```php
Container::make( 'network', 'crb_network_container', 'Network Container' )
    ->add_fields( array(
        Field::make( 'date_time', 'crb_event_start', 'Event Start' )
    )
);
```

## Steps to Reproduce the Problem

  1. Create `network` container
  1. Add basic `date_time` field.

## Comments
When I use the same field definition in a `theme_options` container, the time picker displays correctly. However, when used in a `network` container, it is not present.

**Comment by deqngeorgiev** [comment]
Hi @dmhendricks,

Sorry for the late reply.

I've tested the `date_time` field in `network` container and it works the same way as in `theme_options` container. The time selector is displayed after the date is selected. 

Can you provide more information about your setup and the browser on which is the problem? Also, are there any errors in the console?

**Comment by dmhendricks** [comment]
Hmm, there were no errors in the console. I will investigate further and perhaps try it again on a fresh install to see if I can reproduce it. Thank you.
