### ISSUE TITLE
2.2.0 version cloning error with composer package.

### ISSUE THREAD

**Issue by yubarajrai** [htmlburger/carbon-fields#534]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.6
  - PHP: 7.*

## Expected Behavior
media_gallery

## Actual Behavior
V2.2.0 carbon fields is not cloning in composer framework

## Container definition
```php
I am using composer custom framework in, and trying to clone new 2.2.0 of carbon fields as you have updated media gallery feature in. But, there is not proper repository. So, can you please anyone can help me out for this?```

## Steps to Reproduce the Problem

  1. media gallery

## Comments
I need to add media gallery in my WordPress Theme.

**Comment by emohamed** [comment]
Hi @yubarajrai 

How precisely do you install Carbon Fields? Do you follow https://carbonfields.net/docs/carbon-fields-quickstart/?crb_version=2-2-0 ?

If not -- could you please paste the command you're using(along with the relevant composer output).
