### ISSUE TITLE
Widget not work with Site Origin Page Builder

### ISSUE THREAD

**Issue by eonis8** [htmlburger/carbon-fields#545]
## Version

  - Carbon Fields: 2.0.2
  - WordPress: 4.7
  - PHP: 7

## Expected Behavior
Widget not work with Site Origin Page Builder

## Actual Behavior
Widget not work with Site Origin Page Builder. The form of widget not show up

## Container definition
```php
![siteorigin](https://user-images.githubusercontent.com/40438202/41718259-b95a6912-755c-11e8-9f24-05bc87124e9f.PNG)

Unknown error. Failed to load the form. Please check your internet connection, contact your web site administrator, or try again later.
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Comments
_Please add any other comments here_

**Comment by deqngeorgiev** [comment]
Hi @eonis8,

Thank you for the feedback.

The Carbon Fields are designed to render on the default WordPress' widgets page. The `Page Builder` plugin adds custom functionality to WordPress and provide an ability to add widgets to posts/pages in custom page builder container. This behaviour is not supported from Carbon Fields at the moment.
