### ISSUE TITLE
Flexible content field like in ACF

### ISSUE THREAD

**Issue by olegburakov** [htmlburger/carbon-fields#547]
Hello guys, and huge thank you for your work!

**Question:** is there a way to use functionality like field type of "flexible content" in ACF https://www.advancedcustomfields.com/resources/flexible-content/ ?

_In short describe behaviour:_ possibility to create common blocks (for example slider, images, rich_text etc) and fill empty page from this set of blocks, and possibility to place this blocks in different order on page. I guess this is a little similar to sidebar with widgets, but the main profit is to build page from typical elements with different order, content etc

Sorry if I duplicate someone question, but I didn't find it in issues.

**Comment by emohamed** [comment]
Hi @olegburakov 

In Carbon Fields, we don't have separate fields for repeaters and flexible content. Instead, you use complex field for both purposes:

 * when you need a repeater, you use a complex field with single group
 * when you need flexible content, you use a complex field with multiple groups

See https://carbonfields.net/docs/complex-field-multiple-groups/?crb_version=2-2-0

Happy coding!
