### ISSUE TITLE
PHP Fatal Error when installed with composer alongside wordpress

### ISSUE THREAD

**Issue by Blindmikey** [htmlburger/carbon-fields#55]
When installing wordpress and carbon-fields both through composer, when attempting the wordpress install process PHP throws a fatal error:

```
PHP Fatal error:  Call to undefined function trailingslashit() in /.../vendor/htmlburger/carbon-fields/carbon-fields.php on line 13
```

This is because carbon-fields expects to be installed in a location where wordpress is fully installed by use of the wordpress function `trailingslashit()`. 

A quick fix might be to check the existence of wordpress ( or perhaps just `trailingslashit()` ) and return if not found.

**Comment by Blindmikey** [comment]
This is also because I've put the require to `vendor/autoload` in wp-config.php. 

Perhaps that is not a suitable place to invoke auto-load now that I'm thinking about it. 

It might still be good practice to ensure wordpress's functions are available and fail non-fatal early if not. Otherwise I'll close this ticket.

**Comment by Blindmikey** [comment]
I see roots/bedrock is doing this as well - I'll re-open this ticket, as it would be an issue for anyone using roots/bedrock as well as carbon-fields

https://github.com/roots/bedrock/blob/master/web/wp-config.php

**Comment by m1r0** [comment]
Unfortunately this is a WordPress plugin and WordPress functions and global variables need to be included first in order for it to work. The bedrock composer requirements are lower level and not WordPress dependent, so they can afford to include them before loading the WordPress files.  

You can try moving the `autoload.php` after `wp-settings.php` or make another autoloader in the theme. Hope this helps.
