### ISSUE TITLE
Please need help, front end view for users registered

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-fields#556]
- Carbon Fields: 2.2
  - WordPress: 4.9.7
  - PHP:  7.2.1

Please I need your help of this great plugin and I congratulate your disposition.
The users of the web that I am developing have to upload their information from front end. I asked the question a few days ago or one of the collaborators answered that if you can from the api and I can not find how to do it I already asked the question in http://stackoverflow.com/ but I do not opt for answers please if you could give me a clue more clear how to do it. Agradesco the response to this great community.

**Comment by deqngeorgiev** [comment]
Hi @dackr,

You can create your custom UI on the front end and use the default WP functions (`update_post_meta`, `update_user_meta`, etc.) or WordPress REST API to add/update the values in the database and show them in Carbon Fields in the WordPress admin area.

If you need further help with your project we offer paid support too -- https://carbonfields.net/support/

**Comment by dackr** [comment]
thanks for your help.
