### ISSUE TITLE
Possible to add an option to include a custom field in Yoast SEO content analysis feature?

### ISSUE THREAD

**Issue by nickdavis** [htmlburger/carbon-fields#562]
If you've used the Yoast SEO plugin, you're probably familiar with its Analysis feature which scores the content on the page or post (in the default content editor) based on certain criteria.

Wondering how difficult it would be to add a parameter when registering a new Carbon Field to include that field in the Yoast SEO analysis (defaulting to false), something like `'add_to_wpseo_analysis' => true`?

(This would be particularly useful for Rich Text fields).

For something similar take a look at:
- https://github.com/Yoast/yoast-acf-analysis
- https://github.com/wpmetabox/mb-yoast-seo (where I got the parameter idea from)

Thanks.

**Comment by deqngeorgiev** [comment]
We think that such feature would be better suited as an add-on for Carbon Fields, rather than a built-in functionality. Unfortunately, we don't have the dev resources to make it happen. 

I'm going to leave this issue open in case someone wants to contribute with this add-on.

**Comment by enky00** [comment]
Hey, is there any solution for this right now ?

And are there any addon-ons for carbon fields out there ?

**Comment by nickdavis** [comment]
@enky00 See if the following helps. I'll try to do a proper write up of it later, but for now if you follow the links in the doc blocks in the following files it should explain more how I achieved it.

https://gist.github.com/nickdavis/2d052d77464bd16b3fe20a5df37c1351

**Comment by jorostoyanov** [comment]
Hey :)

We have just released a new library which aims to provide you with the ability to add Post Meta fields to Yoast SEO Readability Analysis. You can check it out here -- https://github.com/htmlburger/carbon-fields-yoast

There is a composer package and README to help you get started.

Check it out and if you notice any issues or you have questions, please open a new Issue in the Carbon Fields Yoast repository 🥂
