### ISSUE TITLE
Bug: Edit link modal in rich_text flickers (Chrome only)

### ISSUE THREAD

**Issue by tomasz-nolberczak** [htmlburger/carbon-fields#564]
## Version

  - Carbon Fields: 2.2
  - WordPress: 4.9.7
  - PHP: 7.2
  - Browser: [Info here](https://mybrowser.fyi/report/5b55d9b97e8a1100147ef191)

## Expected Behavior
Edit link modal in _rich_text_ field is working like standard "edit link modal" in WYSIWYG (like in standard built-in WYSIWYG in WordPress).

## Actual Behavior
Field with editable link flickers. User cannot save value of field with URL

## Steps to Reproduce the Problem

  1. Create _rich_text_ field for _theme_options_ container
  1. Open WordPress in the newest version of Chrome.
  1. Edit _rich_text_field_.
  1. Try to add link and edit it.
  1. Hover on "save icon".

## Comments
**Only in Chrome** - on Firefox it seems to be working properly.

**Comment by ttamnedlog** [comment]
Just to add my 2 cents, I think this isn't strictly a Carbon Fields issue. Seems to be a lot at play here. I'll try and go through the various scenarios I tested.

Browser info: https://mybrowser.fyi/report/5b648c4ff73d430014c7edd2

### Site A - Scenario 1 - Flickering
WP: 4.9.8
No Gutenberg; No Classic Editor
Custom Theme
Carbon Fields: 2.2
PHP: 7.2

### Site A - Scenario 2 - Flickering
All plugins disabled
Twenty Seventeen Theme

### Site B - Scenario 3 - Flickering
WP: 4.9.8
Gutenberg Enabled
Custom theme
ACF Pro: 5.7.1
PHP: 7.2

### Site B - Scenario 4 - Not flickering
Gutenberg Disabled

### Site C - Scenario 5 - Not flickering
WP: 4.9.8
No Gutenberg; Classic Editor Enabled
Custom theme
ACF Pro: 5.7.1
PHP: 7.2

### Site D - Scenario 6 - Not flickering
WP: 4.9.4
Twenty Seventeen
No plugins
PHP: 7.1

### Site D - Scenario 7 - Flickering
Updated WP to 4.9.8

### Conclusion
I have no idea what's going on, ha. All this to say, I don't think Carbon Fields is the problem. At least, it's not the only problem. Seems like many things may be causing this.

**Comment by tomasz-nolberczak** [comment]
@ttamnedlog thank you for detailed report. The problem is not related straight with Carbon Fields itself, so let me close that issue.

Have a nice day!
