### ISSUE TITLE
set_visible_in_rest_api() only to logged in users

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#565]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.7
  - PHP: 7.2

## Container definition
```php
Container::make( 'post_meta', 'Custom Data' )
    ->where( 'post_type', '=', 'page' )
    ->add_fields( array(
        Field::make( 'image', 'crb_photo' )->set_visible_in_rest_api(),
    ));
```

## Comments
How could I set logic php to set set_visible_in_rest_api only for logged in users?

I could create the hole container twice inside a if /  else statement, but I prefer to set only the set_visible_in_rest_api() in a condition to avoid duplicated code  

Thanks

**Comment by deqngeorgiev** [comment]
Hi @BenBroide,

The `set_visible_in_rest_api` method accepts a parameter which defaults to true. You can use some condition and change it. For example: `->set_visible_in_rest_api( is_user_logged_in() ? true : false )`

If you have more questions I will be happy to help.

**Comment by BenBroide** [comment]
@deqngeorgiev Thanks!
