### ISSUE TITLE
Not translate "Entry"

### ISSUE THREAD

**Issue by Grafs** [htmlburger/carbon-fields#569]
## Version
  - Carbon Fields: 2.2.0
  - WordPress: 4.9.8
  - PHP: 5.6

## Expected Behavior
Translate "Entry, Entries" for any languages

## Actual Behavior
Not translate

## Steps to Reproduce the Problem
Add complex fields and show english Entry

## Comments
How to translate "Entry"?

In file vendor\htmlburger\carbon-fields\core\Field\Complex_Field.php 
str 92-93 not translated strings

**Comment by KevinSupertramp** [comment]
Hi there,

I believe you should be able to do it with "setup_labels" function. [https://carbonfields.net/docs/complex-field-config-methods/?crb_version=2-2-0](See here).

Hope it helps!

**Comment by viterzbayraku** [comment]
Still untranslatable "Add" after changing of labels

![Image 337](https://user-images.githubusercontent.com/4019353/72154153-88c78e80-33b8-11ea-9edf-13633e011b5f.png)

**Comment by jorostoyanov** [comment]
There was a problem with the translation files and there is now a fix here -- https://github.com/htmlburger/carbon-fields/commit/45b4509ffa6a92fe2bc83c8f3a8bc3cdb693d460

It will be released in the next version where you will be able to use it :-)
