### ISSUE TITLE
Select_Field->template() does not escape option.name but it should

### ISSUE THREAD

**Issue by catahac** [htmlburger/carbon-fields#57]
```
<option value="{{ option.value }}" {{{ option.value == value ? 'selected="selected"' : '' }}}>
	{{{ option.name }}}
</option>
```

option.name should be surrounded in {{ }} to escape it.

**Comment by georgeHtmlBurger** [comment]
Considering the names are provided by the developer (even if they are dynamically loaded from somewhere they are still set via a method) it should be up to them to escape the string if necessary.

If the option's name is always escaped, then the developers would be limited to using any special characters within the name (for example `&mdash;`).
