### ISSUE TITLE
Rich Text incorrectly triggers update on twitter embeds.

### ISSUE THREAD

**Issue by atanas-vasilev-dev** [htmlburger/carbon-fields#571]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.8
  - PHP: 7

## Expected Behavior
The "Do you want to leave this page" dialog should not show up when trying to go to another page when there are no changes made to the content.

## Actual Behavior
The alert shows up:
![screenshot from 2018-08-13 14-32-41](https://user-images.githubusercontent.com/24589439/44029397-dceb6aac-9f05-11e8-9b7c-0766fcdb56b1.png)

## Container definition
```php
// Please add your entire container defintion here so issues
// are easy to reproduce
Container::make( 'post_meta', __( 'Top Menu', 'crb' ) )
	->where( 'post_type', '=', 'page' )
	->add_fields( [
		Field::make( 'rich_text', 'test_rich_text', __( 'Test', 'crb' ) ),
	] );
```

## Steps to Reproduce the Problem

  1. Add a twitter status link to the rich text content (ex: https://twitter.com/CNN/status/1028966973638631424 ).
  2. Save the page.
  3. Refresh/go to another page.

## Comments
It seems that the twitter preview is triggering an update on tinyMCE.

**Comment by jorostoyanov** [comment]
The issue doesn't exist in the latest version v3.3.0 and WordPress v5.7
