### ISSUE TITLE
Carbon Fields roadmap / milestones?

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#575]
Hi guys,

Firstly I'd like to thank you for all the great work towards Carbon Fields which is an awesome addition to WordPress. It's been so far a great tool to work with!

I was wondering if you had any roadmap / milestones / plans for the future of Carbon Fields?
It would be interesting to see how you want to evolve and how the community can get involved to help going in the right direction.

Hope it makes sense!

**Comment by emohamed** [comment]
Hi @KevinSupertramp 

We're currently actively developing version 3 which will bring support for Gutenberg blocks creation. You can track the progress here: https://github.com/htmlburger/carbon-fields/tree/v3

Additional information is available here: http://emil.2create.studio/2create/carbon-fields/2018/04/27/plans-for-carbon-fields-and-gutenberg-integration/

We hope to have it up & running for WordPress release date(November 19th).

We don't have any other long-term milestones planned. I guess that we'll have to see what impact will Gutenberg have on the WordPress ecosystem.

Thanks!

**Comment by KevinSupertramp** [comment]
Hi @emohamed,

That's awesome! Thanks for the update.
Really excited to see the Gutenberg support.

Thank you again for the great work!
