### ISSUE TITLE
Uploading WP Appearance > Customize > Site Identity > Logo (Default Logo Upload) using Carbon image field

### ISSUE THREAD

**Issue by yubarajrai** [htmlburger/carbon-fields#579]
## Version: 2.2.0

  - Carbon Fields: Image
  - WordPress: 4.9.8 
  - PHP: 7.1.7

## Expected Behavior
_
I am trying to upload logo image for the site by using carbon image field and updating it on WP- Appearance > Customize > Site Identity > Logo automatically.
_

## Actual Behavior
_
There is no issues with carbon image field. But, how can I relate carbon image field and WP custom logo field to update automatically while uploading image in carbon image field.
_

## Container definition
```php
$options_container = Container::make( 'theme_options', 'Options' )
	                                  ->add_fields( array( ) );
	#region contact under 'Site Options'
Container::make( 'theme_options', 'Basic Settings' )->set_page_parent( $options_container )
	         ->add_fields( [
		         Field::make( 'image', 'site_logo', __( 'Logo' ) )
	         ] );
```

## Steps to Reproduce the Problem

  1. I have no idea how to relate WP custom logo field to Carbon Image field which automatically updates logo on WP Custom Logo field while uploading it in Carbon image field.

## Comments
_
I am using and loving all the features of Carbon Fields. But, I have no idea on it. so, I am requiring for the reference.
_

**Comment by sachittandukar** [comment]
I am assuming that you want to add field to upload site logo.
You can do that by default WordPress custom logo support.
`add_theme_support( 'custom-logo' );`

Please add above code. I hope this will fix your issue.

**Comment by yubarajrai** [comment]
Thank you @sachittandukar for your kind response. 👍 

But, I am willing to know about the relation or update of carbon meta fields with customizer' fields in WordPress where I am trying to populate automatically the default site logo field in customizer when I upload an image in carbon theme meta for now.  

Is there any update or solution in Carbon Fields where I can handle customizer's default fields from carbon meta fields dynamically?

**Comment by jorostoyanov** [comment]
Hi @yubarajrai,

Sorry for the late response.

Currently the Carbon Fields library doesn't support the Customizer. However, you can get around this and sync the "Site Logo" in the Customizer and Theme Options with the example below:

```
Container::make( 'theme_options', __( 'Theme Options', 'crb' ) )
	->set_page_file( 'crbn-theme-options.php' )
	->add_fields( array(
		Field::make( 'image', 'site_logo', __( 'Site Logo', 'crbs' ) ),
	) );
```

```
// functions.php

/**
 * Update "Site Logo" option in Customizer after setting the image in "Theme Options".
 *
 * @return void
 */
add_action( 'carbon_fields_theme_options_container_saved', 'crb_sync_site_logo_theme_option_with_customizer' );
function crb_sync_site_logo_theme_option_with_customizer() {
	if ( isset( $_POST['_site_logo'] ) ) {
		set_theme_mod( 'custom_logo', absint( $_POST['_site_logo'] ) );
	}
}

/**
 * Attaches the function that will sync "Site Logo" customizer option with
 * the Theme Option that we've registered.
 *
 * @return void
 */
add_action( 'admin_init', 'crb_attach_site_logo_sync_customizer_with_theme_option' );
function crb_attach_site_logo_sync_customizer_with_theme_option() {
	$theme = get_option( 'stylesheet' );
	$option_name = "theme_mods_{$theme}";

	add_action( "update_option_{$option_name}", 'crb_sync_site_logo_customizer_with_theme_option', 10, 2 );
}

/**
 * Updates the Theme Option value based on the "Site Logo" customizer option.
 *
 * @return void
 */
function crb_sync_site_logo_customizer_with_theme_option( $old_value, $value ) {
	if ( isset( $value['custom_logo'] ) ) {
		carbon_set_theme_option( 'site_logo', absint( $value['custom_logo'] ) );
	}
}
```

This way you will keep both options in sync no matter which of them gets updated.

Hopefully, this will solve your issue :)

**Comment by yubarajrai** [comment]
Hi @jorostoyanov 

Sorry for testing it lately.
I am using **Carbon Fields 3.0**
And, this sync function you suggested is not working
