### ISSUE TITLE
Ordering of containers?

### ISSUE THREAD

**Issue by davejtoews** [htmlburger/carbon-fields#580]
Is there a means of specifying the order of containers? A parameter to pass? A hook to call to enforce order after the fact?

I can't find mention of this in the docs.

**Comment by deqngeorgiev** [comment]
Hi @davejtoews,

You can use the `->set_priority()` method to change the priority within the context where the boxes should show. Also, you can reorder the containers by drag and drop which is the default WordPress behavior.

I believe you can use the `get_user_option_meta-box-order_{post_type}` filter if you want to change the order of the meta boxes programmatically.

If you have more questions I will be happy to help.
