### ISSUE TITLE
Custom field not showing with Gutenberg

### ISSUE THREAD

**Issue by rabirom** [htmlburger/carbon-fields#584]
Hello, I have been struggling with the custom fields after Gutenberg update.
Kindly check the images below to understand the issue.

https://imgur.com/a/pk7xg9H

Thanks in advance

**Comment by antonhedling** [comment]
I am also having issues. Specifically for me I can't seem to use the post_template conditional. Tried debugging and it seems like the code Post_Template_Condition class never runs, but I don't have time to debug any more.

**Comment by rabirom** [comment]
Yes even I tried several coders, but the issue persists. I tried to contact htmlburger for this, offered them to do it on against fees, but they did not respond. Carbon field has died with Gutenberg it seems.

**Comment by deqngeorgiev** [comment]
I believe both problems are from the `post_template` condition. The current version of Carbon Fields is designed to work as the default WordPress meta boxes but Gutenberg brings many changes to the page. Even though most of the fields and containers work with Gutenberg we can't guarantee full compatibility.

Currently, we are working on a new version of Carbon Fields which will support Gutenberg as well.

**Comment by vvasilev-** [comment]
Closing this issue since Carbon Fields 3.0 is compatible with Gutenberg. Feel free to reopen it if you still face the problem.
