### ISSUE TITLE
Need to filter values before displaying

### ISSUE THREAD

**Issue by nebulousGirl** [htmlburger/carbon-fields#585]
I have a dropdown with multiple options. When the user selects "other", a text field pops up to enter a custom value. The problem is that it creates 2 metadata fields when I need only one. I have figured out to save in  one field using the filter `carbon_fields_should_save_field_value`. 

But, I can't seem to find a way to change the values of form fields before they are displayed in the edit form.

**Comment by nebulousGirl** [comment]
I found a way to change the values before display using the filter `carbon_fields_datastore_storage_array`.

Is it safe to use? I see that it is not documented.

**Comment by jorostoyanov** [comment]
Hi @nebulousGirl 

Apologies for the late reply.

Yes, the filter is save to use :-)
