### ISSUE TITLE
Condition not work on the fly with Gutenberg

### ISSUE THREAD

**Issue by zorca** [htmlburger/carbon-fields#587]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.8
  - PHP: 7.1.20

## Container definition
```php
	Container::make( 'post_meta', 'People Section' )
	            ->where( 'post_type', '=', 'post' )
				->where( 'post_term', '=', array(
					'field' => 'slug',
					'value' => 'people',
					'taxonomy' => 'category',
				) )
				->add_fields( [
					Field::make( 'text', 'newconomy_post__people', 'People' )
				] );
```

## Steps to Reproduce the Problem
Setting People category does not appear on the container visibilty.
In console (when check/uncheck category):
```Warning: Unsafe lifecycle methods were found within a strict-mode tree:```
With Classic Editor works fine without errors.

**Comment by deqngeorgiev** [comment]
Closing this in favor of #584
