### ISSUE TITLE
Add a way to edit/allow other attributes

### ISSUE THREAD

**Issue by psaikali** [htmlburger/carbon-fields#592]
Hey there!

## Version
  - Carbon Fields: 2.2.0
  - WordPress: 4.9.8
  - PHP: 7.2.10

## Issue
It's currently impossible to define custom values for attributes on a field, except for the `placeholder` attribute.
![capture 2018-10-15 a 11 54 16](https://user-images.githubusercontent.com/1606655/46943933-14952280-d071-11e8-82dc-48ff2fe68ba0.jpg)

I'd like to pass a simple, secure, `'autocomplete' => 'off'` attribute to a `Date_Field` field in order to disable Chrome autocomplete overlaying and hiding the calendar widget.
![capture 2018-10-15 a 11 30 24](https://user-images.githubusercontent.com/1606655/46944092-79e91380-d071-11e8-921f-5a813d2e43b8.jpg)

But for now, it's impossible to do so.

It would be great to have a way to override the `$allowed_attributes` parameter (with some filter maybe?) to allow for a larger set of accepted attributes. 
Or maybe at least add a few more valid HTML attributes in Carbon Fields core, attributes which could be useful in some cases, like `autocomplete`.

**Comment by deqngeorgiev** [comment]
Hi @psaikali,

Thank you for your feedback.

For time being you could use `->set_picker_options( ['allowInput' => false] )` to work around this issue. 

In the next major update(v3) we'll be deprecating `$allowed_attributes`.

**Comment by psaikali** [comment]
Thanks for letting me know!
