### ISSUE TITLE
Adding hooks to display additional content on a Theme Options page

### ISSUE THREAD

**Issue by psaikali** [htmlburger/carbon-fields#593]
I am using CF to handle fields and admin settings page for one of my plugin. I feel that the Theme Options page could use a few action hooks here and there, to let plugin/theme developers add additional content.

![image](https://user-images.githubusercontent.com/1606655/47069491-55b34100-d1ef-11e8-9b55-6e7bb57c9bed.png)

In my case, I'd like to link to my plugin documentation / support forum in the sidebar.
That's just a small enhancement idea that I wanted to share. What do you guys think?
 
Anyway, big thanks for the library, it's really awesome. I know that y'all working on v3 and I'm really excited to try it out!

**Comment by deqngeorgiev** [comment]
Hi @psaikali,

I've added hooks to the Theme Options page in the development branch and they will be available in the next release.

The hooks are prepended by the `Container ID` so the different options pages can be managed. We will add this in the documentation for the next release.

In your case the hooks will be:

 * carbon_fields_container_wp_timeliner_options_before_fields
 * carbon_fields_container_wp_timeliner_options_after_fields
 * carbon_fields_container_wp_timeliner_options_before_sidebar
 * carbon_fields_container_wp_timeliner_options_after_sidebar

**Comment by psaikali** [comment]
Hey @deqngeorgiev,

Thanks for v3, it's awesome!
I'm glad these hooks were added, it's very useful to have them.

### Current state
After some xDebugging, I noticed that the `$container_id` dynamic part of these filter names is localized.
I could not find any way of creating a Theme Options container by separating its `$title` from its `$id`, as it seems that both are internally setup equal and we have no "external" way of setting different value for Title / ID.

### Problem
Because the `$id` comes from the title of the Theme Options Container we create, and because this title could possibly be i18n-ed with `__(...)`, I run into issues where I can't be sure of the ID used by these filters.

Do you know how we could fix this?

Thanks a lot!

**Comment by vvasilev-** [comment]
Hi @psaikali,

Just pass an identifier as the second param in `Container::make` call.

```
Container::make( 'post_meta', 'your_desired_id_here', __( 'Localized Title' ) )
```

You can find more information about this behaviour here - https://docs.carbonfields.net/#/containers/usage.
