### ISSUE TITLE
Docs: search doesn't work and docs seem to be incomplete

### ISSUE THREAD

**Issue by pim013** [htmlburger/carbon-fields#594]
## Version

  - Carbon Fields: 2.2 - This question is about the docs.
  - WordPress: n/a
  - PHP: n/a

## Expected Behavior
This question is about the docs.

I expect (important) documentation about using fields in every version where a function of CF is still a viable option. I.e.  `->show_on_template($template_path)` is only in the docs for version 1.4 while it still works in version 2.2 and (AFAIK) the only way to specifically state that a field should only show up when using a specific template.

I want to search a complete documentation and see all the functions that CF has for the version I have. I am afraid I am missing important information this way.

Is there a reason for making the docs behave this way?

Link to example: 
[https://carbonfields.net/docs/containers-post-meta-5/?crb_version=v1-4](https://carbonfields.net/docs/containers-post-meta-5/?crb_version=v1-4)

## Comments
And: the search function in the docs doesn't work.

**Comment by emohamed** [comment]
Hi @pim013!

In v2 we changed the conditionals definition, as described here: https://carbonfields.net/docs/containers-condition-types/?crb_version=2-2-0

I.e. `->show_on_template($template_path)` is now `->where( 'post_template', '=', $template_path ) )`. We didn't break the old methods in order to keep backward compatibility. 

> And: the search function in the docs doesn't work.

This seems OK on my end. What browser are you using? 

Thanks!

**Comment by pim013** [comment]
Hi @emohamed 

Thanks for the swift reply.
Didn't know of the new behaviour, thanks for the link!

> This seems OK on my end. What browser are you using?
Firefox Quantum 62.0.3. My colleague had it also on latest Chrome. Now it's working fine, maybe a small hiccup with the search provider? 

Issue can be closed if you're okay with that.

**Comment by jorostoyanov** [comment]
Closing this ticket.

Please open new issues related to the docs here -- https://github.com/htmlburger/carbon-fields-docs
