### ISSUE TITLE
Metaboxes/fields don't show up anymore in Gutenberg 4.1.0

### ISSUE THREAD

**Issue by psaikali** [htmlburger/carbon-fields#598]
I just updated to Gutenberg 4.1.0 and it looks like the CarbonFields JS logic (in charge of displaying metabox where needed) is not working any longer.

## Version
  - Carbon Fields: 2.2.0
  - WordPress: 4.9
  - PHP: 7.1

## Expected Behavior
I should see my metaboxes when creating/editing a post type.
![ie](http://media.mosaika.fr/7e794e94411c/Capture%2525202018-10-25%252520a%2525CC%252580%25252011.21.10.jpg)

## Actual Behavior
My metabox markup is present in the page HTML, but a `display:none;` CSS property hides it. That just happened after Gutenberg 4.1.0 update. 

## Container definition
Metabox/fields declaration is done via CarbonFields this way: https://github.com/psaikali/wp-timeliner/blob/master/classes/schema/fields-achievement.php

## Temporary fix
For those having the same issue, hooking on `admin_head` to add an `!important` CSS declaration will do the trick for now (https://github.com/psaikali/wp-timeliner/commit/06161f4474da54a1b93a70f47fefd2c3aa9d71d2).

**Comment by jorostoyanov** [comment]
Hi @psaikali,

We are currently working on version 3 which will bring support for Gutenberg. You can track the progress here: https://github.com/htmlburger/carbon-fields/tree/v3

Additional information can be found here -- https://carbonfields.net/2018/04/27/plans-for-carbon-fields-and-gutenberg-integration/

Stay tuned!
