### ISSUE TITLE
condition post_template with Sage.

### ISSUE THREAD

**Issue by 9585999** [htmlburger/carbon-fields#602]
Hi. How can I make a condition for displaying fields depending on the page template.

I use the starting theme of Sage.

I tried 
```php
$condition->where('post_template', '=', 'page-contacts-blade.php');
``` 
but it does not work ...

**Comment by emohamed** [comment]
@9585999 The following should work:
```php
add_action( 'carbon_fields_register_fields', 'crb_attach_post_options' );
function crb_attach_post_options() {
    Container::make( 'post_meta', __( 'Some meta', 'crb' ) )
        ->where( 'post_type', '=', 'page' )
        ->where( 'post_template', '=', 'page-contacts-blade.php' )
        ->add_fields([/**/])
// ... 
```

If it doesn't, please reopen the issue and provide more complete code so we can investigate the exact problem.

**Comment by 9585999** [comment]
@emohamed not work... see #603
