### ISSUE TITLE
Add new field types (email, url) or regex validation

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#61]
It would be interesting to have more options to constraint the user input, useful for email, url… fields. Maybe the most versatile option would be to add a regex validation option to the "text" field. CF could add some constants for the most commonly used regexes (`CF_EMAIL_REGEX`, `CF_URL_REGEX`…).

In the case of adding regex validation I imagine that we should provide the JS version, since there is no real server side validation of the input. (is there?)

Another issue might be the visual feedback of the errors as noted in #60.

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which includes a JS API so you can hook into form submissions and perform your own client-side validation.
More info here: https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-0-0
