### ISSUE TITLE
"Theme Option" fields created by "Carbon Fields" are not giving "Polylang" Language Translation feature to add different content having multiple language.

### ISSUE THREAD

**Issue by yubarajrai** [htmlburger/carbon-fields#610]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.8
  - PHP: 7.0.0

## Expected Behavior
_
I have created "Theme Option" by using Carbon Fields. Now, I need to add different content on multiple language such as En, Fr, De using "Polylang Language Translation" on Theme Option Fields. 
_

## Actual Behavior
_
There is no polylang language translator associated with "Theme Option" which is created by using "Carbon Fields"
_

## Container definition
```php
$basic_options_container = container::make( 'theme_options', __( 'General Setting', 'my-textdomain' ) )
	                                    ->set_page_menu_title( 'Options' )
	                                    ->set_page_file( 'theme-options' )
	                                    ->add_fields( [
		                                    Field::make( 'file', 'themeopt_logo', __( 'Logo' ) )->set_help_text( 'Upload your website logo' )
	                                    ] );
container::make( 'theme_options', 'Home Settings' )->set_page_parent( $basic_options_container )
	         ->add_fields( [
		         Field::make( 'rich_text', 'themeopt_welcome', __( 'Welcome/Intro Message' ) )->set_help_text( 'Your welcome message would go here.' )
	         ] );
```

## Steps to Reproduce the Problem

  1. I can add content after creating theme option in the field called "Home Settings > Welcome / Intro Message"
  2. But, there is no option to add/switch another language to add different language content.

## Comments
_Hoping for your kind response_

**Comment by seriiserii825** [comment]
> And after this you can add different content for every language. Select language on dropdown menu on top of admin page and add text.

And what, i must to install WPML plugin too?

**Comment by viterzbayraku** [comment]
Only Polylang

**Comment by seriiserii825** [comment]
> Only Polylang

Ok, i will try, and after i will get a answer...

**Comment by seriiserii825** [comment]
> Only Polylang

woooaaaaaoooo, its worked, coooool.
I am so happyyyyyyyy. 
Where i you from?

Can you help me to translate the options titles? 
https://i.imgur.com/yZ0xjAi.png

I cant find the titles in polylang.

`add_action( 'carbon_fields_register_fields', 'crb_attach_theme_options' );
function crb_attach_theme_options() {
	$basic_options_container = Container::make( 'theme_options', __( 'Basic Options', 'medical' ) )
    ->set_page_menu_title(  __( 'Setari Pagina Principala', 'medical' ))
    ->add_tab( 'Header', array(
	    Field::make( 'text', 'crb_lang'.carbon_lang(), __( 'Test lang', 'medical' ) ),
        Field::make( 'text', 'crb_header_slogan', __( 'Slogain in header', 'medical' ) ),
    ) )
    ->add_tab( 'Slider', array(
        Field::make( 'complex', 'crb_slider_item' )
        ->add_fields( array(
            Field::make( 'image', 'crb_slider_image' )
            ->set_help_text( 'Incarcati imagini cu dimensiunile de 1920x900' ),
        ) )
    ) )
`

**Comment by seriiserii825** [comment]
And there https://i.imgur.com/87NfIv9.png

I can't understand how to do this.
And you will be my best friend)))

**Comment by viterzbayraku** [comment]
For example, you can change 'Basic Options' to __('Basic Options', 'yourtextdomain'), where youtextdomain is translation domain of your theme. And after you can translate this captions via Loco Translate plugin.

**Comment by seriiserii825** [comment]
ok, i will try

**Comment by viterzbayraku** [comment]
All captions as a parts of plugins can be translated via Loco Translate

**Comment by seriiserii825** [comment]
i write how you write '	$basic_options_container = Container::make( 'theme_options',  __('Basic Options', 'medical') )
'
But, where i must search Basic Options to translate? 
https://i.imgur.com/cJXHr9L.png
In themes, plugins, wordpress? 
I suppouse that in the themes.

**Comment by seriiserii825** [comment]
Ok, i found the word "Primary" in loco-translate, this word is in functions.php 
https://i.imgur.com/4y4gGmt.png

I install carbon-fields without composer. Just download zip archive. 
May be this is the reason, why loco-translate dont found the carbon-fields title?

**Comment by seriiserii825** [comment]
I find a solution. 
Just need to remove all files *.pot from languages directory and activate plugin. 
At now, loco-translate work fine. 

Dont forget to push button syncrhonize.

**Comment by vitamineart** [comment]
@viterzbayraku thanks for nice solution, it works for single text field. 
What about **'complex' fields**, for example I want to create Slider with title and subtitle. 
Here is my code:
**_theme-options.php_**
`
Container::make( 'theme_options', __( 'Настройки' ))
			->add_fields( array(
            Field::make( 'complex', 'crb_slides', 'Slides' )
                ->set_layout( 'tabbed-horizontal' )
                ->add_fields( array(
					Field::make( 'image', 'image', 'Изображение' ),
                    Field::make( 'text', 'title'.carbon_lang(), 'Заголовок' ),
                    Field::make( 'textarea', 'subtitle'.carbon_lang(), 'Текст подзаголовка' ),
                    Field::make( 'text', 'cta_text'.carbon_lang(), 'Текст кнопки' ),
                ) ),
        ) );
`

**_page.php_**

`
<?php
					$slides = carbon_get_theme_option( 'crb_slides' );
					
					foreach ( $slides as $index => $slide ) {
						$slide_image_url = wp_get_attachment_image_url( $slide['image'], $size = 'full', $icon = false );
						$slide_title = $slide['title'.carbon_lang()] ;
						$slide_subtitle = $slide['subtitle'.carbon_lang()] ;
						$cta_text = $slide['cta_text'.carbon_lang()] ;
						$active = $index == 0 ? 'active' : '';
						
						echo '
							 <div class="carousel-item ' . $active . ' " style="background-image: url(' . $slide_image_url . ')">
								<div class="main-banner-title">
									' .$slide_title  . '
								</div>
								<div class="second-banner-title">
									' . $slide_subtitle . '
								</div>
								<div class="take-info">
									<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#info-order">' .  $cta_text . '</button>
								</div>
							</div>
						';
						
					}
					
				?>
`

After adding this code I get no errors, but when I try to change fields values for different languges it overrides the prev value, so only last value left. 
Any ideas how to fix that ?

**Comment by viterzbayraku** [comment]
> Any ideas how to fix that ?

Just add the language prefix to the name of the current complex field without changing of subfields.

`Container::make( 'theme_options', __( 'Настройки' )) ->add_fields( array( Field::make( 'complex', 'crb_slides'.carbon_lang(), 'Slides' ) ->set_layout( 'tabbed-horizontal' ) ->add_fields( array( Field::make( 'image', 'image', 'Изображение' ), Field::make( 'text', 'title', 'Заголовок' ), Field::make( 'textarea', 'subtitle', 'Текст подзаголовка' ), Field::make( 'text', 'cta_text', 'Текст кнопки' ), ) ), ) );`

**Comment by vitamineart** [comment]
@viterzbayraku you save me hoursss!!!

Thanks a lot for quick response!
