### ISSUE TITLE
What is CF block slug for allowed_block_types filter?

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#622]
Hi there,

First, thanks so much for the Gutenberg support, these new blocks system looks really good!

Basically what I am trying to do is to:

1. Hide all the defaut WP block
2. Display only my custom CF blocks

`
add_filter('allowed_block_types', function($allowed_blocks) {
    return [
        'common/banner'
    ];
}, 10, 2);
`
https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/

But I can't figure out how to display my custom blocks, I'm not sure what is the correct slug to use? As when we register a block we don't give an ID?

I hope it makes sense.

Thanks a lot!!

**Comment by vvasilev-** [comment]
Hi @KevinSupertramp,

Thanks for feedback!

Basically the slug is generated from the identifier assigned to the container.
If you're interested here is the implementation - https://github.com/htmlburger/carbon-fields/blob/master/packages/blocks/index.js#L36.

Block with generated identifier:

```
<?php

Block::make( __( 'Text and Image' ) )
    ->add_fields([
        
    ]);
```

The slug will be `carbon-fields/text-and-image`.

---

Block with predefined identifier:

```
<?php

Block::make( 'image_banner', __( 'Text and Image' ) )
    ->add_fields([
        
    ]);
```

The slug will be `carbon-fields/image-banner`;

---

On a side note, `Block::make` is just a proxy for `Container::make( 'block' )` so everyting documented [here](https://docs.carbonfields.net/#/containers/usage) can be used.

**Comment by KevinSupertramp** [comment]
Amazing as always! Works perfectly.

Thank you!!
