### ISSUE TITLE
Can't use "set_editor_style" -> "wp_register_style was called incorrectly"

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#625]
Hi,

It's me again, sorry!

I'm trying to use the "set_editor_style" for my Gutenberg Blocks but can't get it to work. I load CF with the "after_setup_theme" hook and then register all my fields and blocks but it looks like it's too early to use the "wp_register_style" function.

If I try to load my blocks later on (with "admin_enqueue_scripts" by example they don't display in the backend).

Am I doing it the wrong way? 

Many thanks!

**Comment by vvasilev-** [comment]
Hi @KevinSupertramp,

Thanks for your feedback! Can you provide us a snippet with your configuration so we can try to reproduce the issue?

**Comment by KevinSupertramp** [comment]
Hi @vvasilev- ,

Thank you for your reply. I don't know what happened but it seems like it's working now. Maybe I had a cache problem or something else weird with my configuration.

I'm finally not gonna use this function anyway as I will load a merged CSS instead.

So I guess for now it was a "false alarm", my bad!!

Kind regards,
