### ISSUE TITLE
"set_render_callback" adds random "</p>" - Gutenberg Block

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#630]
## Version

  - Carbon Fields: v3.0.1
  - WordPress: 5.0.2
  - PHP: 7.2.4

## Container definition
```php
       CF_Block::make($this->id, $this->name())
            ->set_description($this->description)
            ->set_icon($this->icon)
            ->set_keywords($this->keywords)
            ->set_preview_mode($this->preview)
            ->add_fields($this->fields())
            ->set_render_callback(function ($block) {
                    ?>
        <section>
            <div class="container">

                    <h2>title</h2>

                <div class="row">
                    <div class="col">
                        <div>
                            <?= apply_filters('the_content', '<p>Content column</p>') ?>
                        </div>
                    </div>
                    <div class="col">
                        <div>
                            <?= apply_filters('the_content', '<p>Content column</p>') ?>
                        </div>
                    </div>
                </div>

            </div>
        </section>
                    <?php
                }
            );
```

## Comments
Hi,

I'm using the new Gutenberg Block Field but I get some random ```</p>``` tag added (sometimes). It looks like the spaces are sometimes interpreted as paragraph (even in normal HTML) with the set_render_callback function (see screenshot attached).
![cf_er](https://user-images.githubusercontent.com/1142786/50729903-0881a400-113a-11e9-9231-403769eb0f2c.png)

Many thanks!

**Comment by ggeorgiev96** [comment]
Hi @KevinSupertramp ,

The unexpected behaviour is caused by the call of `apply_filters('the_content' ...)` filter which WordPress 5.0 uses to render the blocks of Gutenberg. If you want to be sure that your content will display correctly please only use the methods needed for the content formatting - `wpautop` for example.
