### ISSUE TITLE
set_context('carbon_fields_after_title') with Gutenberg

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#631]
Hi guys,

Sorry it's me again, I'd like to display a container (for a Main Banner) straight under the Gutenberg page title (or before). I'm using the "set_context('carbon_fields_after_title')" function but it doesn't seem to change anything. My container is always displayed under the Gutenberg Editor. Same result with ('side' or 'advanced' as well).

Here is my code:
```php
            Container::make('post_meta', __('Main Banner', 'swell'))
                ->where('post_type', '=', 'page')
                ->set_context('carbon_fields_after_title')
                ->add_fields($fields);
```

Thanks for your help.

**Comment by ggeorgiev96** [comment]
Hi @KevinSupertramp ,

Unfortunately in WordPress 5.0 the `context` property has no effect as the new Gutenberg editor doesn't support locations and the metaboxes are automatically rendered below it.
