### ISSUE TITLE
[Feature Request] Association field with custom values

### ISSUE THREAD

**Issue by speedwheel** [htmlburger/carbon-fields#633]
First of all I would like to say thank you for this awesome Wordpress library, I always use it in my projects.

So far it pretty much covered all my needs in terms of custom fields, but I feel that there is something missing, see below.

I would like to have predifined a list of values, and to be able to select multiple values from that list and also have the possibility to order and reorder them how I want. 

I didn't find any custom field type that could do this, but the **Association** custom field type is very close to what I want, the only problem is that it only works with post types. I would like it to work with a predefined list of values.

Would this be something difficult to implement? I think it would a great plus to the library and benefit many users that want to sort a list of custom values easily.

**Comment by ggeorgiev96** [comment]
Hi @speedwheel !

Could you please give us an example of the use case you have intended for this feature and how you expect it to work code-wise ? 

On a side note you could take a look at the supported [multiselect field](https://docs.carbonfields.net/#/fields/multiselect) which allows the usage of pre-defined list of values ( without option to re-order the items in the front-end currently ).

**Comment by speedwheel** [comment]
@ggeorgiev96  For example I have a page that is build from blocks, and you can select which blocks you want on that page and in which order.

It would work something like this:
```php
Field::make( "association", "crb_association", "Association" )
    ->add_options( array(
        'red' => 'Red',
        'green' => 'Green',
        'blue' => 'Blue',
    ) )
```
Yes I am using the `Multiselect field` now for doing this, but as you said: it doesn't have the options for reordering the list of values.

What do you think?

**Comment by jorostoyanov** [comment]
This request feels like it should be added as an addon for Carbon Fields instead of being available in core.

You can extend the Association Field and try to build the feature there.

Closing as won't fix in core
