### ISSUE TITLE
Unable to implement custom "complex" field due to hardcoded frontend check

### ISSUE THREAD

**Issue by luishdz1010** [htmlburger/carbon-fields#634]
## Version

  - Carbon Fields: 3 
  - WordPress: 5 
  - PHP: 7.2

## Expected Behavior
I'm trying to implement a custom complex field, following the logic in the JS source. Even though the code to make such a field work is scattered in many places (due to the metabox/gutenblocks separation) I am almost able to, but this line `/packages/metaboxes/utils/flatten-field.js:30` has a hardcoded check for `field.type === 'complex` so I am not able to load values in my custom nested field because flattening is not happening.

Is what I am doing risky (in a future-proof sense)? Seems to me that I need to depend on many internal things to make the custom field work, some of these dependencies are within the `metabox` and `blocks` packages, which do not export anything and forces me to copy/paste some of the dependencies. Maybe I'm not supposed to use carbon fields like this.

**Comment by ggeorgiev96** [comment]
Hi @luishdz1010,

Could you please describe what you are attempting to achieve and provide some pieces of code which will help us better understand the issue you've came across ?

**Comment by luishdz1010** [comment]
I'm creating a code clone of the complex field, mainly I wan to abstract the functionality of fields containing other fields. The project I am working on requires very precise meta boxes with things like step-by-step forms, modals and stylized arrangement of fields.

My thought process is that, if I can make a complex field from userland then I'll be able to start coding my other purpose-built nested fields. The question is, is creating custom nested fields possible/encouraged?

I can share what code I have but is really messy at this point, I am just testing out if a complex field can be programmed from "outside" the library, which things like `field.type === 'complex'` seem to indicate it is not.
