### ISSUE TITLE
Association field within Complex field not loading properly after being saved

### ISSUE THREAD

**Issue by thomas-figved** [htmlburger/carbon-fields#636]
## Version

  - Carbon Fields: 3.0.0
  - WordPress: 5.0.2
  - PHP: 7.2.7

## Expected Behavior
I created an association field inside a complex field. 

What is expected: 
I can chose one or more associated post, save the post I'm editing, then when I reload the page my choices should be conserved and I should be able to associate to a different post.

## Actual Behavior
When I reload the page after saving the post, the interface for the association field looks broken. I cannot remove the association or associate another post. Adding another field altogether works fine though.
![image](https://user-images.githubusercontent.com/28971514/50946578-6cf78700-14dd-11e9-9a4e-f704dd4400de.png)

## Container definition
```php
Container::make( 'post_meta', 'People and role' )
    ->where('post_type', '=', 'post')
    ->add_fields(  array(
        Field::make( 'complex', 'nw_post_people', __( 'People appearing in this post' ) )
          ->set_layout( 'tabbed-horizontal' )
          ->add_fields( array(
              Field::make( 'association', 'nw_post_people_assoc', __( 'Person\'s page' ) )
                ->set_types( 
                  array(
                    array(
                        'type'      => 'post',
                        'post_type' => 'post',
                    )
                  )
                )
                ->set_max(1),
          ) ),
  ));
```
## Steps to Reproduce the Problem

  1. Add the container definition in your code
  2. Create or edit a new post. 
  3. In the "People and role" meta box, add a new association field and associate a post
  4. Save the post
  5. Reload the post edition page
  6. Go back to the "People and role" meta box: the values that were selected in step #3 seems to be saved but there is no way to change it. The interface looks broken.

## Comments
When reloading the post edition page it will trigger Javascript error:

> Uncaught (in promise) An error occured.

There is a http request that looks like this:
`[SITE URL]/wp-json/carbon-fields/v1/association/?container_id=carbon_fields_container_people_and_role&options%5B0%5D%5Btype%5D=post&options%5B0%5D%5Bsubtype%5D=post&options%5B0%5D%5Bid%5D=1&options%5B0%5D%5Btitle%5D=Hello+world!&options%5B0%5D%5Blabel%5D=Post&options%5B0%5D%5Bis_trashed%5D=false&field_id=nw_post_people_assoc%5B0%5D%3Aundefined%2Fnw_post_people_assoc`

The intresting part seems to be the field_id param:
nw_post_people_assoc[0]:**undefined**/nw_post_people_assoc

The response to this request shows a php error:

> Fatal error: Uncaught Error: Call to a member function get_thumbnail_by_type() on null in [SITE PATH]\wp-content\mu-plugins\carbon-fields-plugin\vendor\htmlburger\carbon-fields\core\REST_API\Router.php on line 296

My guess is that there is an issue somewhere with the Javascript responsible for rendering the field: it doesn't generate the correct field_id.

**Comment by joeyblake** [comment]
@ggeorgiev96 This patch does not fix this issue in the beta. I'm looking into it further to see if I can better locate the isse.

**Comment by muzanaka** [comment]
Ok, solved.
For anyone facing this problem… keep an eye on your hook priorities…!

**Comment by erimeilis** [comment]
I wonder where it was fixed?
I face the similar problem.

```
Field::make( 'complex', 'crb_wooproductoptions', __( 'Woo custom product options' ))
            ->set_collapsed( true )
            ->add_fields( array(
            	Field::make( 'text', 'option_name', 'Option name' ),
            	Field::make( 'text', 'option_price', 'Option price' ),
            	Field::make( 'association', 'option_cats', 'Option product categories')
    				->set_types( array(
        				array(
            				'type' => 'term',
            				'taxonomy' => 'product_cat',
        				),
            	))
            ))

```

**Comment by muzanaka** [comment]
> I wonder where it was fixed?
> I face the similar problem.
> 
> ```
> Field::make( 'complex', 'crb_wooproductoptions', __( 'Woo custom product options' ))
>             ->set_collapsed( true )
>             ->add_fields( array(
>             	Field::make( 'text', 'option_name', 'Option name' ),
>             	Field::make( 'text', 'option_price', 'Option price' ),
>             	Field::make( 'association', 'option_cats', 'Option product categories')
>     				->set_types( array(
>         				array(
>             				'type' => 'term',
>             				'taxonomy' => 'product_cat',
>         				),
>             	))
>             ))
> ```

add_action('carbon_fields_register_fields', 'postsCustomFields', 1); keep an eye on your hook priorities…!

**Comment by erimeilis** [comment]
> > I wonder where it was fixed?
> > I face the similar problem.
> > ```
> > Field::make( 'complex', 'crb_wooproductoptions', __( 'Woo custom product options' ))
> >             ->set_collapsed( true )
> >             ->add_fields( array(
> >             	Field::make( 'text', 'option_name', 'Option name' ),
> >             	Field::make( 'text', 'option_price', 'Option price' ),
> >             	Field::make( 'association', 'option_cats', 'Option product categories')
> >     				->set_types( array(
> >         				array(
> >             				'type' => 'term',
> >             				'taxonomy' => 'product_cat',
> >         				),
> >             	))
> >             ))
> > ```
> 
> add_action('carbon_fields_register_fields', 'postsCustomFields', 1); keep an eye on your hook priorities…!

Actually, i found a fix.
If you use ->set_layout( 'tabbed-horizontal' ) you won't get a problem. Magic

**Comment by norixx** [comment]
> > > I wonder where it was fixed?
> > > I face the similar problem.
> > > ```
> > > Field::make( 'complex', 'crb_wooproductoptions', __( 'Woo custom product options' ))
> > >             ->set_collapsed( true )
> > >             ->add_fields( array(
> > >             	Field::make( 'text', 'option_name', 'Option name' ),
> > >             	Field::make( 'text', 'option_price', 'Option price' ),
> > >             	Field::make( 'association', 'option_cats', 'Option product categories')
> > >     				->set_types( array(
> > >         				array(
> > >             				'type' => 'term',
> > >             				'taxonomy' => 'product_cat',
> > >         				),
> > >             	))
> > >             ))
> > > ```
> > 
> > 
> > add_action('carbon_fields_register_fields', 'postsCustomFields', 1); keep an eye on your hook priorities…!
> 
> Actually, i found a fix.
> If you use ->set_layout( 'tabbed-horizontal' ) you won't get a problem. Magic

I use Ver.3.2.1 and did both set priority '1' and set_layout('tabbed-horizontal') but still generates same error 'Uncaught (in promise) An error occured'.

![image](https://user-images.githubusercontent.com/1718332/102629651-c28b4280-418e-11eb-87c2-3b30b9094811.png)

**Comment by KjSerg** [comment]
I had a problem because of the code 509. I contacted the hosting support service.
Take a look at the console.
![image](https://user-images.githubusercontent.com/32456334/116213002-1239d600-a74e-11eb-866c-e715d7f21573.png)

**Comment by Borea** [comment]
> I solved this issue with removing i18n function from theme-options initialization:
> 
> before: `Container::make('theme_options', __('Theme Options')) ->set_icon('dashicons-heart') ...`
> 
> after: `Container::make('theme_options', 'Theme Options') ->set_icon('dashicons-heart') ...`

OMG, thanks bro

**Comment by AsEAsEAsEROMaSe** [comment]
> Я решил эту проблему, удалив функцию i18n из инициализации параметров темы:
> 
> до: `Container::make('theme_options', __('Theme Options')) ->set_icon('dashicons-heart') ...`
> 
> после: `Container::make('theme_options', 'Theme Options') ->set_icon('dashicons-heart') ...`

it really works. thank you

**Comment by vakarchuk** [comment]
Tried everything from this topic, nothing works for me :(
