### ISSUE TITLE
Incorrect edit post link in the association field.

### ISSUE THREAD

**Issue by joeyblake** [htmlburger/carbon-fields#640]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.0.3
  - PHP: 7.2

## Expected Behavior
Clicking an edit link for a post in an association field should take the user to the correct post edit page.

## Actual Behavior
The edit link is escaped, so the user is sent to the post list screen in the admin.

## Steps to Reproduce the Problem

  1. Create an association field
  2. Click on the "Edit Post" Icon for one of the posts displayed in the association field list.

**Comment by jorostoyanov** [comment]
Hi @joeyblake,

Thank you for reporting this.

The issue has been fixed in the `development` branch -- https://github.com/htmlburger/carbon-fields/commit/5c5e1465e651b1c51a8238038cef46e7737512c0 -- and will be available in the next release.

**Comment by joeyblake** [comment]
Hi @jorostoyanov 

I do have a question about this patch, I had submitted a PR to address this issue which I believe fixes the trouble at the root cause. Which makes me curious as to why this is being fixed in the JavaScript layer. Again, I'm just curious, this is an excellent library and I look forward to contributing more, so I want to make sure my thinking about this issue is correct. Thanks!

https://github.com/htmlburger/carbon-fields/pull/641

**Comment by jorostoyanov** [comment]
Hi @joeyblake 

I have merged your PR request.

I did this in the JS just in case a filter hooks in `get_edit_post_link` and adds another escaped symbol.

However, your solution makes total sense and that's why I've included it as well!
