### ISSUE TITLE
Compatibility with Ninja Forms plugin

### ISSUE THREAD

**Issue by tschortsch** [htmlburger/carbon-fields#643]
## Version

  - Carbon Fields: 3.0.2
  - Ninja Forms: 3.4.1
  - WordPress: 5.0.2
  - PHP: 7.2

## Expected Behavior
Carbon Fields and Ninja Forms plugins should be compatible.

## Actual Behavior
As soon as I activate Carbon Fields and Ninja Forms my `association` fields break. As long as no post is selected in the association field everything works. But as soon as I select an entry the loading of the field doesn't work anymore. It throws the following JavaScript error:

```javascript
Uncaught (in promise) TypeError: Cannot read property 'thumbnail' of undefined
    at eval (index.js:287)
```

Before selecting value:
![association_test_nothing_selected](https://user-images.githubusercontent.com/1061850/51240446-014d6800-197c-11e9-85b9-cc78adc8a1ab.png)

After selecting value:
![association_test_after_selection](https://user-images.githubusercontent.com/1061850/51240524-27730800-197c-11e9-8f34-75a3cd4044c6.png)

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

add_action( 'carbon_fields_register_fields', 'crb_attach_association_field' );
function crb_attach_association_field() {
    $association_test = Field::make( 'association', 'association_test', 'Association Test' );
    $association_test->set_types( array( array( 'type' => 'post', 'post_type' => 'page' ) ) );

    $association_test_container = Container::make( 'post_meta', 'Association Test Container' );
    $association_test_container->add_fields(
        array(
            $association_test,
        )
    );
}
```

## Steps to Reproduce the Problem

  1. Create association field
  1. Enable Carbon fields plugin
  1. Enable Ninja Forms plugin
  1. Edit random post
  1. Select page in association field
  1. Save post

**Comment by daniftinca** [comment]
Did you have any luck in solving this for you?

**Comment by daniftinca** [comment]
I just finished solving this bug and it turned out to be an incompatibility issue with the theme. The theme authors didn't include proper error handling in their addon plugin and it was echoing PHP notices and warnings in the REST API JSON response. Visit your-site.com/?rest_route=/ and see if you have any.

**Comment by jorostoyanov** [comment]
Seems you have found the reason for the issue.

Closing this ticket! Feel free to re-open if the issue persists
