### ISSUE TITLE
Weird display on Radio (Gutenberg & complex field on Gutenberg)

### ISSUE THREAD

**Issue by ESirop** [htmlburger/carbon-fields#644]
# Version

* Carbon Fields: 3.0.2
* WordPress: 5.0.3
* PHP: 7.2

# Expected Behavior

Put a radio field on a Gutenberg block (or a complex field in Gutenberg).
Each block (or complex item) manages its radio field.

# Actual Behavior

When using a radio field on a block (or complex item), it kinda changes the display of other radio field from identical block or on complex fields.

![ezgif-4-8c7d4418391d](https://user-images.githubusercontent.com/3872849/51240940-14146c80-197d-11e9-85f0-f534a6a672c3.gif)

N.B : Still working fine on front, just weird on WordPress Admin.

**Comment by jeffdrumgod** [comment]
+1

**Comment by kaesetoast** [comment]
I am running into the same issue with the RadioImage field. @ESirop Did you manage to find a workaround for this behavior?

**Comment by ESirop** [comment]
Actually, it's fixed for me here (radio and radio image). I didn't knew because the issue is still open, but it seems that @jorostoyanov did something with the name attribute, so each field has a unique name.

@kaesetoast I suppose you don't have an updated version, but if you do and still have some issues, you can use a select. It's not great, but it will work.

**Comment by kaesetoast** [comment]
@ESirop nope, I have version 3.1.14 installed. Still exactly the same issue you described. A select is not really an option here. I have to figure it out somehow I guess.

**Comment by jorostoyanov** [comment]
This should be fixed with the latest releases just like @ESirop said.

Please re-open if you happen to experience it again
