### ISSUE TITLE
Alpha Transparency (RGBA) is not saved with Color Field

### ISSUE THREAD

**Issue by KevinSupertramp** [htmlburger/carbon-fields#648]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.0.3
  - PHP: 7.3

## Expected Behavior
Saving the opacity/alpha of the color (Color Field).

## Actual Behavior
It's not saved. Returning RGB only on the front-end and in the back-end always back to 100% after update.

## Container definition
```php
Field::make('color', 'header_background', __('Header Background Color', 'swell'))->set_alpha_enabled()->set_width(50),
```

Thanks a lot!

**Comment by jorostoyanov** [comment]
Hi @KevinSupertramp,

I have added a fix in the `development` branch -- https://github.com/htmlburger/carbon-fields/commit/449935d9ebb2a433fe71741f24c3c3d04fa5a793 -- and it will be available in the next release.

Thank you for reporting :-)

**Comment by KevinSupertramp** [comment]
Awesome, thanks so much!
