### ISSUE TITLE
Media Gallery image editing

### ISSUE THREAD

**Issue by kyosifov** [htmlburger/carbon-fields#656]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.0.3
  - PHP: 7.2

## Expected Behavior
In carbon fields 2 you can edit the image metadata like (title, caption etc...), but the feature is not present in carbon-fields 3

## Actual Behavior
Can't edit the image metadata

## Steps to Reproduce the Problem

  1.Create a `media_gallery` field

### Carbon fields 2
https://imgur.com/a/zWeYa4f

### Carbon fields 3
https://imgur.com/a/neRPanp

**Comment by viterzbayraku** [comment]
I agree too. This is a very important feature.

**Comment by underdoeg** [comment]
Yes, I am missing this feature as well

**Comment by mamunur105** [comment]
I am still missing this feature.

**Comment by jorostoyanov** [comment]
Duplicate of https://github.com/htmlburger/carbon-fields/issues/937
