### ISSUE TITLE
Complex Field additional row actions

### ISSUE THREAD

**Issue by V1adDone** [htmlburger/carbon-fields#657]
## Version

  - Carbon Fields: 3.0

Hello, guys. Is there any way how can I edit Complex Field each row actions?
for now, there are "clone" and "remove" actions. I would like to add custom tumbler like "enabled" and hide "remove" action on conditional logic depend on values.

**Comment by jorostoyanov** [comment]
This seems like a very rare use case and since there aren't a lot of requests for this I am closing the issue for now.

If this becomes a must add feature, we will consider adding it in future.
