### ISSUE TITLE
Association Field issue -- The URLs of the edit buttons are incorrect

### ISSUE THREAD

**Issue by gogoraz** [htmlburger/carbon-fields#662]
## Version

  - Carbon Fields: 3.0.*
  - WordPress: 5.0.3
  - PHP: 7.0

## Actual Behavior

The URLs of the edit buttons are incorrect. They use `&amp;action=edit` inside them instead of `&action=edit`.

For example: http://example.com/wp-admin/post.php?post=18&amp;action=edit

## Steps to Reproduce the Problem

  1. Go to an edit page that uses an association field
  2. Click on any edit button on the left column of the field 
  3. After that, you'll be redirected to an incorrect page.

## Comments

It will be good if the edit buttons open new browser tabs. That way, users won't lose their new added data when the edit button of the association field is clicked.

**Comment by jorostoyanov** [comment]
Hi @gogoraz,

The issue has been fixed in the development branch -- https://github.com/htmlburger/carbon-fields/commit/5c5e1465e651b1c51a8238038cef46e7737512c0 -- and will make it in the next release.

The link will now open in new tab as well.

Thank you for pointing this out!
