### ISSUE TITLE
Media Gallery field shows only 3 image after theme options saved

### ISSUE THREAD

**Issue by Dimox** [htmlburger/carbon-fields#665]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.0.3
  - PHP: 7.1.7

## Expected Behavior
Media Gallery field must show all selected images.

## Actual Behavior
It shows not more then 3 images.

## Container definition
```php
Container::make( 'theme_options', 'Theme Options' )
  ->set_page_menu_position( 60 )

  ->add_tab( 'Tab name', array(

    Field::make( 'media_gallery', 'gallery' ),

  ) ) // end tab

;
```

## Steps to Reproduce the Problem

  1. Select more then 3 image.
  1. Save theme options.
  1. Media Gallery field shows only 3 images.

**Comment by jorostoyanov** [comment]
Hi @Dimox,

Can you tell me what types of images are you using? Are there any SVGs selected in the Media Gallery field?

**Comment by Dimox** [comment]
Only PNG and JPG files.

**Comment by jorostoyanov** [comment]
Hi @Dimox,

I am not able to reproduce the issue.

If possible, can you send me the images that you are using? In addition, will you be able to record a video with the issue?

**Comment by Dimox** [comment]
I have tested it now again - the problem is disappeared. Very strange... Okay, then I'm closing the issue. Thank you!

**Comment by celerart** [comment]
on v3 version may saved only 10 images
