### ISSUE TITLE
More Control over Post-Meta 

### ISSUE THREAD

**Issue by rawsta** [htmlburger/carbon-fields#666]
Currently i utilise the complex fields to add post-meta to a CustomPostType and to a single page. 
I got everything running fine so far (thanks to the helpful docs) but have some tiny things that kind of bother me. Nothing to wild, i hope. But i thought it could be a useful addition to an already really useful plugin.

## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.03
  - PHP: 7.1

## Feature Request: "Add New" Button on Post-Meta Accordion
When you have a lot of post-meta entries it could be tedious to scroll to the bottom and manually move a new entry to the right position. The "Duplicate" button does already something similar, but you have to clear all fields. A new "Add" button would be nice.

## Feature Request: Option to Remove "Add ...." at the Bottom
Right after the last post-meta element ist the "Add ..." Button. 
I couldn't find a way to disable it for specific pages/post-types.
Would already help, if i could remove that button when i set up the fields.

## Comments
I hope it's ok that i opened an issue for this "non-issue".

**Comment by jorostoyanov** [comment]
Hi @rawsta,

I'll try to answer your questions below:

> When you have a lot of post-meta entries it could be tedious to scroll to the bottom and manually move a new entry to the right position. The "Duplicate" button does already something similar, but you have to clear all fields. A new "Add" button would be nice.

There is already an "Add Entry" button available below the Complex field.

How will your proposed "Add" button differ from the already existing one?

In addition, please note that there is a `->set_layout( 'tabbed-horizontal|tabbed-vertical' )` method which outputs the Complex Field groups as tabs either in horizontal or vertical order. This results in a better rendering and less taken space.

> Right after the last post-meta element ist the "Add ..." Button.
> I couldn't find a way to disable it for specific pages/post-types.
> Would already help, if i could remove that button when i set up the fields.

You can set a maximum / minimum number of fields for the Complex Field by using the `->set_max( $max ) / ->set_min( $min )` methods.

You can restrict the Administrator to add no more than 2 fields per complex field, for example:

```
Field::make( 'complex', 'Team Members', __( 'Team Members' ) )
	->set_max( 2 )
	->add_fields( [
		Field::make( 'text', 'name', __( 'Name' ) ),
		Field::make( 'text', 'position', __( 'Position' ) ),
		Field::make( 'image', 'avatar', __( 'Avatar' ) ),
	] ),
```

After the Administrator adds two Team Members, the "Add Entry" button will remain hidden with the above setup.

---

Let me know if the above details are helpful for your case :)

**Comment by rawsta** [comment]
Hi @jorostoyanov 

thanks for your quick reply.

> > When you have a lot of post-meta entries it could be tedious to scroll to the bottom and manually move a new entry to the right position. The "Duplicate" button does already something similar, but you have to clear all fields. A new "Add" button would be nice.
> 
> There is already an "Add Entry" button available below the Complex field.
> 
> How will your proposed "Add" button differ from the already existing one?

The only difference would be that it's easier to add a new item between two other items. 
The idea was to add one next to the duplicate and delete button. 
That could be useful when there are  a lot of entries.

> In addition, please note that there is a `->set_layout( 'tabbed-horizontal|tabbed-vertical' )` method which outputs the Complex Field groups as tabs either in horizontal or vertical order. This results in a better rendering and less taken space.

That's an even better solution to my "problem". 
Made everything much easier to sort.  


> > Right after the last post-meta element ist the "Add ..." Button.
> > I couldn't find a way to disable it for specific pages/post-types.
> > Would already help, if i could remove that button when i set up the fields.
> 
> You can set a maximum / minimum number of fields for the Complex Field by using the `->set_max( $max ) / ->set_min( $min )` methods.

And again. An even better solution than my "proposal"

> Let me know if the above details are helpful for your case :)

Very helpful! 
You've found even better solutions. 

Thanks for taking the time to help me out.
