### ISSUE TITLE
Gutenberg Blocks Category

### ISSUE THREAD

**Issue by sebastienserre** [htmlburger/carbon-fields#673]
Hello,
I'm developping 2 WP Plugins and use Carbon Fields 3 to create Gutenbergs Block.
if the both plugins are activated then all blocks (with different category name) are grouped in the same Category :-/

**Comment by vvasilev-** [comment]
Hi @sebastienserre,

Can you provide us with minimal test code so we can reproduce the issue?

**Comment by sebastienserre** [comment]
Hello,
I reproduce it by activating
https://wordpress.org/plugins/wpcasa-mail-alert/
and
https://wordpress.org/plugins/compare-affiliated-products/

**Comment by jorostoyanov** [comment]
Cannot reproduce. Re-open if the issue is still valid for the latest release
