### ISSUE TITLE
Conditional logic broken in nested complex fields in v3

### ISSUE THREAD

**Issue by grantcodes** [htmlburger/carbon-fields#675]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.1
  - PHP: 7

## Expected Behavior
A complex field within another complex field should support conditional logic

## Actual Behavior
Works in v2.2.0 but not v3.0.2 

## Container definition
```php
Container::make( 'post_meta', 'Buggy Example' )
  ->add_fields(
    array(
      Field::make( 'complex', 'complex' )
      ->set_min( 1 )
      ->set_max( 1 )
      ->set_layout( 'tabbed-vertical' )
      ->add_fields( array(
        Field::make( 'checkbox', 'toggle' ),
        Field::make( 'complex', 'complex' )
          ->set_min( 1 )
          ->set_max( 1 )
          ->set_layout( 'tabbed-vertical' )
          ->add_fields( array(
            Field::make( 'text', 'hello' ),
          ) )
          ->set_conditional_logic(
            array(
              array(
                'field' => 'toggle',
                'value' => true,
              ),
            )
          ),
      ) )
    )
  );
```

## Steps to Reproduce the Problem

  1. Load the container
  2. Click the checkbox and nothing happens
  3. You will see a console error saying "An unknown field is used in condition - "toggle""

## Comments
So I am honestly not 100% sure what it causing this, I think when I was trying to reproduce this bug I had code very similar to this and it worked...

But I can confirm the exact code above doesn't work for me in v3.0.2 but it does in v2.2.0 so there is definitely something wrong somewhere.

**Comment by gardiner** [comment]
Have you tried prefixing the field with "parent"? See https://docs.carbonfields.net/#/fields/conditional-logic?id=nb-conditional-logic-fields-are-scoped-to-the-current-field39s-siblings for details...

**Comment by EMembrillas** [comment]
Can you fix this error? I have the same problem

**Comment by lstoyanoff** [comment]
Hi, I believe this issue was fixed in https://github.com/htmlburger/carbon-fields/releases/tag/v3.1.8

**Comment by siaeb** [comment]
Can you fix this error? I have the same problem
