### ISSUE TITLE
How to make plugin add prefix to meta fields?

### ISSUE THREAD

**Issue by Dudaevskiy** [htmlburger/carbon-fields#679]
## Version

  - Carbon Fields: 3
  - WordPress: 5
  - PHP: 7.0

My friends are not able to force the plugin not to add the prefix in the form of an underscore to the keys of arbitrary fields. I beg you to help in removing the prefix because it is not possible to use custom fields in the dynamic fields of the Elementor plug-in.

**Comment by vvasilev-** [comment]
Hi @Dudaevskiy,

Can you provide us with more information regarding your use case, e.g. example code? Thanks.

**Comment by jorostoyanov** [comment]
Closing this ticket due to inactivity
