### ISSUE TITLE
I can't change the date field localisation.

### ISSUE THREAD

**Issue by melt-cdk** [htmlburger/carbon-fields#680]
## Version

  - Carbon Fields: 3
  - WordPress: 5
  - PHP: 7.2

Hello, it's possible to translate the calendar on date field ?

## Container definition
```php
add_action( 'admin_enqueue_scripts', 'enqueue_french_date' );
function enqueue_french_date() {
wp_enqueue_script( 'flatpickr-locale-fr', 'https://npmcdn.com/flatpickr/dist/l10n/fr.js', array('carbon-fields-boot') );
}

Container::make('post_meta', 'informations projet')
        ->where('post_type', '=', 'projet')
        ->add_fields( array(

            Field::make( 'date', 'cdk_projet_start_date', __( 'Date de début' ) )
                ->set_picker_options( array(
                    'locale' => 'fr',
                ) )
                ->set_attribute( 'placeholder', __( 'Date de fin de projet' ) )
                ->set_storage_format( 'F Y' )
                ->set_input_format( 'F Y', 'F Y' ),

        ));
```

**Comment by NZX-DeSiGN** [comment]
Hi,

I have the same issue, Flatpickr `Error: flatpickr: invalid locale fr`.
With the `carbon-fields-boot` script dependency, the locale js file isn't rendered.
And without the script dependency I have the same error, even if I load it after Carbon Fields script.

**Comment by olegburakov** [comment]
Have the same error, tried `'ru'` and` "Russian"` - no progress. https://i.imgur.com/cFwEFJ3.png
And with `'carbon-fields-boot'` dependency locale script `ru.js` will not load at all.

**Comment by lstoyanoff** [comment]
Hi, I've noticed that the Carbon Fields core script handle (id) was changed and currently you should use `carbon-fields-core` as dependency instead of `carbon-fields-boot`. Example:

```php
add_action( 'admin_enqueue_scripts', function() {
	wp_enqueue_script(
		'flatpickr-locale-fr',
		'https://npmcdn.com/flatpickr/dist/l10n/fr.js',
		[ 'carbon-fields-core' ]
	);
} );
```
