### ISSUE TITLE
Multiselect styling issues

### ISSUE THREAD

**Issue by JiveDig** [htmlburger/carbon-fields#685]
First off, nice work on the Block builder!

## Version

  - Carbon Fields: 3.1.0-beta.1
  - WordPress: 5.1
  - PHP: 7.2

## Expected Behavior
Multiselect to look as good as the other fields

## Actual Behavior
Multiselect looks like it may have broken styling

## Container definition
functions.php has this:
```
require_once( __DIR__ . '/vendor/autoload.php' );

add_action( 'after_setup_theme', 'jivedig_load_carbon_fields' );
function jivedig_load_carbon_fields() {
	require_once( 'includes/carbon/carbon-grid-posts.php' );
	\Carbon_Fields\Carbon_Fields::boot();
}
```
My carbon-grid-posts.php file has this:
```
use Carbon_Fields\Container;
use Carbon_Fields\Field;
use Carbon_Fields\Block;

add_action( 'carbon_fields_register_fields', 'jivedig_test_multiselect_block_field' );
function jivedig_test_multiselect_block_field() {

	$grid = Block::make( __( 'Mai Carbon Grid' ) );
	$grid->set_keywords( [ __( 'mai' ), __( 'grid' ), __( 'post' ) ] );

	$grid->add_fields( array(
		Field::make( 'multiselect', 'content', __( 'Post Type', 'mai-theme-engine' ) )
		->add_options( 'jivedig_get_post_types' )
		->set_default_value( 'post' )
	) );

	$grid->set_render_callback( function ( $block ) {
		echo '<h2>Mai Carbon Block</h2>';
	} );

}

function jivedig_get_post_types() {
	$choices    = array();
	$post_types = get_post_types( array(
		'public'             => true,
		'publicly_queryable' => true,
	), 'objects', 'or' );
	if ( $post_types ) {
		foreach ( $post_types as $name => $post_type ) {
			$choices[ $name ] = $post_type->label;
		}
	}
	return $choices;
}
```
This is what I see (same in the block and the editor sidebar):
![Screenshot 2019-03-10 21 30 26](https://user-images.githubusercontent.com/540990/54095395-78e8b380-437d-11e9-8516-9e261f2c0e52.png)

EDIT: The styling is the same for me on a theme options page. Maybe I'm just used to the styling of Select2/Chosen/Choices. I love the styling of other Carbon fields but this one feels hard to use from a UI standpoint (if this is how it supposed to look).

EDIT 2: I tweaked the CSS very slightly but IMO this is already a nice improvement on what I'm seeing. I'm still fairly new to Carbon Fields so not sure what my expectations really should be with multiselect. The docs don't have a screenshot and this is my only test site I have CF running.

![Screenshot 2019-03-10 22 24 45](https://user-images.githubusercontent.com/540990/54096769-a0427f00-4383-11e9-8b9d-c906b53d6eb2.png)

**Comment by zessx** [comment]
This CSS can be used to improve MultiSelect appearance:
```css
/* Improve Carbon Fields Multiselect */
.cf-container .cf-multiselect__control {
  height: 36px;
}
.cf-container .cf-multiselect__multi-value {
  align-items: center;
  margin: 0;
  background-color: transparent;
  background: #eee;
  padding: 0.2em 0.3em;
  margin-right: 0.3em;
}
```

**Comment by jorostoyanov** [comment]
Fixed in development branch and will be available in the next release :)
