### ISSUE TITLE
Search posts by a multiselect value

### ISSUE THREAD

**Issue by zessx** [htmlburger/carbon-fields#690]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: *not relevant*
  - PHP: *not relevant*

## Expected Behavior
Be able to search posts by a multiselect value

## Container definition
```php
Field::make( 'multiselect', 'subtypes', __( 'Subtypes' ) )
    ->add_options(array('foo', 'bar', 'baz', 'qux'));
```

## Comments
Not an issue, but I haven't been able to find any help in the documentation.   
How could I search for any post having the `bar` value set in the `subtypes` field? 

To be more clear, here is the pseudo-query I'm trying to have:
```
SELECT *
FROM posts 
WHERE subtypes CONTAINS ('bar')
```

I've been trying to play with the `meta_query` param, but I would need something like `CONTAINS`, not `IN`:
```php
$query_args['meta_query'][] = array(
    'key'     => 'subtypes',
    'value'   => ['bar'],
    'compare' => 'in'
);
```

**Comment by lstoyanoff** [comment]
Hi, if you provide an indexed array with no key values as options for the multiselect, the default indexes (0, 1, 2, ...) of the elements will be used as the values. So in your example in the database will be stored the selected options indexes not the strings. Here is how you should define the field and make the query:

```php
<?php

Container::make( 'post_meta', __( 'Post Settings' ) )
	->add_fields( [
		Field::make( 'multiselect', 'subtypes', __(  'Subtypes' ) )
			->add_options( [
				'foo' => __( 'Foo' ),
				'bar' => __( 'Bar' ),
				'baz' => __( 'Baz' ),
			] ),
	] );
```

and the query will look like:

```php
<?php

$posts = get_posts( [
	'meta_query' => [
		[
			'key' => 'subtypes',
			'value' => 'foo',
		]
	],
] );
```
