### ISSUE TITLE
Gutenberg Block example throws Class not found error

### ISSUE THREAD

**Issue by moinzaman** [htmlburger/carbon-fields#694]
## Version

  - Carbon Fields: 3.0.2 and v3.1.0-beta.1
  - WordPress: 5.1.1
  - PHP: 7.0.3

## Expected Behavior
Admin pages to load and for block to be available in edit mode

## Actual Behavior
Error on saving functions.php file and navigating to any page in wp-admin

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;
use Carbon_Fields\Block;

Block::make( __( 'My Shiny Gutenberg Block' ) )
    ->add_fields( array(
        Field::make( 'text', 'heading', __( 'Block Heading' ) ),
        Field::make( 'image', 'image', __( 'Block Image' ) ),
        Field::make( 'rich_text', 'content', __( 'Block Content' ) ),
    ) )
    ->set_render_callback( function ( $block ) {
        ?>

        <div class="block">
            <div class="block__heading">
                <h1><?php echo esc_html( $block['heading'] ); ?></h1>
            </div><!-- /.block__heading -->

            <div class="block__image">
                <?php echo wp_get_attachment_image( $block['image'], 'full' ); ?>
            </div><!-- /.block__image -->

            <div class="block__content">
                <?php echo apply_filters( 'the_content', $block['content'] ); ?>
            </div><!-- /.block__content -->
        </div><!-- /.block -->

        <?php
    } );

```

## Steps to Reproduce the Problem

  1. Vanilla wordpress install with twentynineteen theme with no plugins activated
  2. Carbon Fields installed via zip package plugin
  3. functions.php file edited with above code at the top and saved.

## Comments
See screenshot of error.
![image](https://user-images.githubusercontent.com/505711/54896767-caff0c80-4f19-11e9-85ef-e402ffc5e499.png)

**Comment by moinzaman** [comment]
Ok, I've figured out why. It's a documentation issue which has been logged before but hasn't been resolved by correcting the documentation.

The block code above needs to be inside a `carbon_fields_register_fields` hook

```
add_action( 'carbon_fields_register_fields', 'crb_attach_theme_options' );
function crb_attach_theme_options() {
    //.. code needs to go here
}
```

**Comment by lstoyanoff** [comment]
Hi, it is supposed that you'll be familiar with the Carbon Fields booting/registering which is well documented in the [Quickstart](https://docs.carbonfields.net/#/quickstart) section when following a further guide.
