### ISSUE TITLE
set_width does not work in gutenberg container

### ISSUE THREAD

**Issue by moinzaman** [htmlburger/carbon-fields#695]
## Version

  - Carbon Fields: 3.0.2 and v3.1.0-beta.1
  - WordPress: 5.1.1
  - PHP: 7.0.3

## Expected Behavior
set_width on a field to make the label and field of the specified width

## Actual Behavior
No change to label or field

## Container definition
```php
//.... excerpt only
Block::make( __( 'Carbon Stock Pick' ) )
    ->add_fields( array(
        Field::make( 'text', 'asx_code', __( 'ASX Code' ) )
            ->set_attribute( 'placeholder', __( 'XYZ' ) )
            ->set_attribute( 'maxLength', __( '3' ) )
            ->set_attribute( 'min', __( '3' ) )
            ->set_width( 4 ),
//....
```

## Steps to Reproduce the Problem

  1. Make simple gutenberg block with a few carbon text fields
  2. add `->set_width(4)` to the field
  3. view in gutenberg edit mode in admin, inspect html, no change

## Comments

Would be great for the fields to layout side by side if the width is small enough to allow it

**Comment by lstoyanoff** [comment]
Hi, in order `set_width` method to work there should be multiple sibling fields with width attribute.
