### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by nlemoine** [htmlburger/carbon-fields#7]
I noticed many files containing whites paces at the end of lines. Would you consider adding adhering to coding standards? Using PHP CodeSniffer for example?

**Comment by nlemoine** [comment]
(I can submit a PR to set it up)

**Comment by tyxla** [comment]
We're using Scrutinizer for code analysis and code standards compliance. 

But yes, feel free to submit your PR and we'll review it when we have the time.

**Comment by nlemoine** [comment]
I saw that but the Scrutinizer code standard analysis is limited to a few properties. I ran a quick check ont he whole codebase. It will probably change many many files (for small reasons like trailing whitespaces).

**Comment by tyxla** [comment]
Hey @nlemoine,

I've ran a quick local `phpcs` check as well, there are indeed many small issues and incompatibilities with the [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards), so let's postpone that for after we release version `1.1` (which will be the next few days). We can then start working on addressing those issues.

**Comment by nlemoine** [comment]
Hi @tyxla 

As you released 1.1, I submitted a PR regarding Coding Standards: https://github.com/htmlburger/carbon-fields/pull/10

Many files have been changed but you will see that's mostly some trailing white spaces, quotes and tiny syntax related issues. I only ran automatic fixing with `phpcbf`.

- I removed the autoload files from the composer.json because they break `phpcs` from the vendor dir. Actually these files are loaded anyway (composer autoload or not) by these lines: https://github.com/htmlburger/carbon-fields/blob/master/carbon-fields-plugin.php#L33-L34
- I added basic standards (WordPress-Core only), of course, you can adapt it to yours needs by tweaking the `phpcs.xml` file
- To run the coding standards checks, run `composer install` and `vendor/bin/phpcs --standard=phpcs.xml core/`

Let me know if something's wrong in this PR.

**Comment by tyxla** [comment]
Hi @nlemoine,

Thanks for your work so far! I've posted some comments in the PR, it looks fine with several exceptions, once we take care of them the PR will be ready for merge.
