### ISSUE TITLE
Unable to get theme_options fields data with REST API

### ISSUE THREAD

**Issue by brnteka** [htmlburger/carbon-fields#702]
Hi, when i am trying to get data from theme_options container with this endpoint -- `/wp-json/carbon-fields/v1/options` -- i get :

`{
  "code": "rest_forbidden",
  "message": "Sorry, you are not allowed to do that.",
  "data": {
    "status": 401
  }
}`

even when i have my field registered with `->set_visible_in_rest_api()`

what am i missing here?

**Comment by lstoyanoff** [comment]
Hi, in order to have permissions to use the REST API you have to be authenticated. You can read more about WordPress REST API authentication here -- https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
