### ISSUE TITLE
Unable to make container in the sidebar highest priority on Gutenberg pages

### ISSUE THREAD

**Issue by Jakob-Maudience** [htmlburger/carbon-fields#704]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.1.1
  - PHP:  7.2.4

## Expected Behavior
Post meta container should be placed at the top of the sidebar.

## Actual Behavior
The container does not seem to be highest priority on pages with the Gutenberg editor enabled, the container is at the bottom of the list no matter what priority I set it to. The priority works as expected on pages without the Gutenberg editor.

![crb_priority](https://user-images.githubusercontent.com/24442559/55838707-f7ef1a00-5aea-11e9-9dfc-b7d1b735107e.png)

## Container definition
```php
Container::make( 'post_meta', 'Header Settings' )
    ->where( 'post_type', 'IN', array('page', 'custom_post_type') )
    ->add_fields( array(
       Field::make( 'image', 'logo' ),
    ) )
   ->set_priority( 'high' )
   ->set_context( 'side' )
```

## Steps to Reproduce the Problem

  1. Create a container with the context set to 'side' and the priority set to 'high'
  1. Add the container to a post type with the Gutenberg Editor (like page) as well as one that doesn't (like a custom post type)
  1. The container will be at the top of the custom post type, but at the bottom of the page

## Comments
It's entirely possible that this is some kind of limitation of the new WordPress editor. (I haven't dug to deep into this yet). If there is some kind of limitation, then I feel that should be mentioned in the documentation.

**Comment by benbowler** [comment]
I'm seeing the same thing and I'm having to resort to jQuery to shift the order.

**Comment by lstoyanoff** [comment]
Hi, this is a WordPress limitation. Internally Carbon Fields is using [add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/) function.

**Comment by Jakob-Maudience** [comment]
That is unfortunate, if this is the case, that should be noted in the documentation (if that hasn't been noted already)

**Comment by jorostoyanov** [comment]
This is now working as desired.

Tested it with Carbon Fields v3.3.0 and WordPress v5.7.

The post meta container is positioned above the "Publish" container in the upper right corner.
