### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by paul-brain** [htmlburger/carbon-fields#705]
## Version

  - Carbon Fields: 3.1.0
  - WordPress: 5.1.1
  - PHP: 7.1.28

  - Custom Post Type 'infoproduct'
  - Role Editor and higher: all OK!
  - Role Author - trouble:

vendor.min.js?ver=3.1.0:49 TypeError: Cannot read property 'replace' of null
    at core.min.js?ver=3.1.0:1
    at Array.map (<anonymous>)
    at n.value (core.min.js?ver=3.1.0:1)
    at ci (vendor.min.js?ver=3.1.0:49)
    at li (vendor.min.js?ver=3.1.0:49)
    at vendor.min.js?ver=3.1.0:49
    at Ki (vendor.min.js?ver=3.1.0:49)
    at qi (vendor.min.js?ver=3.1.0:49)
    at Au (vendor.min.js?ver=3.1.0:49)
    at Cu (vendor.min.js?ver=3.1.0:49)

Problem with:
Field::make( 'association', 'association_info', 'Relations' )
  ->set_types( array(
	  array(
		  'type'      => 'post',
		  'post_type' => 'info_author',
	  ),
	  array(
		  'type'      => 'post',
		  'post_type' => 'company',
	  ),
  ) ),

**Comment by rbsmidt** [comment]
I had the same issue, but only when logged in as something else than admin. For instance editor as my client used as role. We solved it by upgrading Carbon Fields to 3.1.2 - might work for you as well.
