### ISSUE TITLE
Add pre-populated pallets for color field

### ISSUE THREAD

**Issue by Avakulenko** [htmlburger/carbon-fields#71]
Currently, Iris colorpicker ( color field ) uses default set of palettes: `palettes: true`
But it accepts the array of pre-defined palettes: `palettes: ['#125', '#459', '#78b', '#ab0', '#de3', '#f0f']`

Lets consider pre-populate palettes set based on latest used colors by current user.
This data could be saved, for example, as hidden user meta or just in global $_SESSION variable.

**Comment by ChipRyan** [comment]
Is this still being considered?

**Comment by atanas-angelov-dev** [comment]
@ChipRyan Yes, however, it's on the backburner until we handle the main 2.0 release.

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which adds a `->set_palette()` method to color fields.
Adding the last used colors is a special use-case which will not be covered in core.
