### ISSUE TITLE
Programmatically delete meta

### ISSUE THREAD

**Issue by alessandrotesoro** [htmlburger/carbon-fields#712]
Hi there,

Is there a way to programmatically delete meta values? I know I can use delete_user_meta or delete_post_meta but this only works for simple fields that support one value. 

Multiselect, checkboxes sets etc... all store multiple rows into the database so I wouldn't be able to know the full meta_key string that would look like `_multiselect|||0|value` etc.

I've searched the code in the repo and couldn't see anything useful. Maybe there's other ways around it?

Thank you.

**Comment by lstoyanoff** [comment]
Hi, you can use `carbon_set_post_meta()` helper function -- https://docs.carbonfields.net/#/advanced-topics/updating-values
