### ISSUE TITLE
Association Field uses URLs too long

### ISSUE THREAD

**Issue by zessx** [htmlburger/carbon-fields#713]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.2
  - PHP: 7.2

## Description of the problem
With a large amount of values, Association Field may stop to work. It calls the `/carbon-fields/v1/association/` REST endpoint with this kind of URL:

https://domain.tld/wp-json/carbon-fields/v1/association/?container_id=carbon_fields_container_options_theme&options%5B0%5D%5Btype%5D=post&options%5B0%5D%5Bsubtype%5D=restaurant&options%5B0%5D%5Bid%5D=123&options%5B0%5D%5Btitle%5D=Post%20Title&options%5B0%5D%5Blabel%5D=Label&options%5B0%5D%5Bis_trashed%5D=false&field_id=order_restaurant

Equivalent JSON, for readability:
```json
{
  "container_id": "carbon_fields_container_options_theme",
  "options": [
    {
      "type": "post",
      "subtype": "restaurant",
      "id": "123",
      "title": "Post Title",
      "label": "Label",
      "is_trashed": "false"
    }
  ],
  "field_id": "order_restaurant"
}
```

We can see that, with ***a single element*** added, the URL is already 330+ chars long. Some hosting companies will block URLs larger than a few thousand characters. In my case I'm not able to add more than 24 or 25 elements per Association Field.

As this is partly due to the hosting service, I think we can highly improve the Association Field to reduce the amount of data send through the URL. I checked the REST endpoint code, and it appears `title`, `label` and `is_trashed` are not used (`subtype` may be optional too):

```php
/**
 * Get Carbon Fields association options data.
 *
 * @return array
 */
public function get_association_data() {
	$container_id = $_GET['container_id'];
	$field_id     = $_GET['field_id'];
	$options      = isset( $_GET['options'] ) ? $_GET['options'] : array();
	$return_value = array();

	$field = Helper::get_field( null, $container_id, $field_id );

	foreach ( $options as $entry ) {
		$item = array(
			'type'       => $entry['type'], 
			'subtype'    => $entry['subtype'],
			'thumbnail'  => $field->get_thumbnail_by_type( $entry['id'], $entry['type'], $entry['subtype'] ),
			'id'         => intval( $entry['id'] ),
			'title'      => $field->get_title_by_type( $entry['id'], $entry['type'], $entry['subtype'] ), // $entry['title'] is not used
			'label'      => $field->get_item_label( $entry['id'], $entry['type'], $entry['subtype'] ),  // $entry['label'] is not used
			'is_trashed' => ( $entry['type'] == 'post' && get_post_status( $entry['id'] ) === 'trash' ),  // $entry['is_trashed'] is not used
		);

		$return_value[] = $item;
	}

	return $return_value;
}
```

We should:
- Remove these 3 keys from the query string 
- Consider to use POST instead of GET, to avoid any size restriction

## Container definition
```php
Field::make('association', 'order_restaurant', __('Restaurants Order', $domain) )
  ->set_types(array(
    array(
      'type'      => 'post',
       'post_type' => 'restaurant',
    )
  ))
  ->set_duplicates_allowed(false);
```

**Comment by jorostoyanov** [comment]
Hi @zessx 

Please, consider updating to the currently latest version v3.1.1 as this problem is already fixed there.

**Comment by zessx** [comment]
Good job! Thanks :)
