### ISSUE TITLE
Fatal Error Installing via Composer on Bedrock

### ISSUE THREAD

**Issue by christianmagill** [htmlburger/carbon-fields#72]
When installing via composer on a Roots / Bedrock project.

Fatal error: Call to undefined function trailingslashit() in /srv/www/influencebydesign/htdocs/vendor/htmlburger/carbon-fields/carbon-fields.php on line 13

**Comment by m1r0** [comment]
Duplicate of https://github.com/htmlburger/carbon-fields/issues/5
