### ISSUE TITLE
HTML tags in Field title are rendered in plain text, not as markup

### ISSUE THREAD

**Issue by taliesinpenbardd** [htmlburger/carbon-fields#721]
## Version

  - Carbon Fields: 3.1
  - WordPress: 5.2
  - PHP: 7.3.2

## Expected Behavior
Since I haven't found the way to add a "description" to a Field (some text under the Field to explain what it'll be about), I would like to differentiate parts of the text in the title of the Field.

## Actual Behavior
The `<strong>`, `<b>`, `<i>` and `<em>` tags inserted in the title are rendered in plain text, not as markup.

## Container definition
```php
[...]
Field::make( 'text', 'my_primary_goal', sprintf( '<strong>%1$s</strong>: %2$s', __(  'Primary goal' ), __( 'Set your primary goal.' ) ) ),
Field::make( 'checkbox', 'augment_goal', sprintf( '<strong>%1$s</strong>: %2$s', __( 'Augment goal' ), __( 'Shall the goal be automatically raised if reached?' ) ) ),
[...]
```

## Comments
I've seen a partial answer to this on #485 but I'm asking for a bit more.

Would it be possible to either render the HTML markup in those functions (sanitization too strong, perhaps ?), or allow a "description" field under those Fields ?

```php
Field::make( 'text', 'my_primary_goal', __( 'My primary goal' ) )
    ->set_attribute( 'description', __( 'Set your primary goal' ) ),
```

Thanks a lot!

**Comment by lstoyanoff** [comment]
Hi, to add a description under the field you can use the `set_help_text()` method -- https://docs.carbonfields.net/#/fields/usage?id=help-text
