### ISSUE TITLE
carbon_set_post_meta adds unnecessary backslash

### ISSUE THREAD

**Issue by speedwheel** [htmlburger/carbon-fields#722]
## Version

  - Carbon Fields: 3.1
  - WordPress: 5.2
  - PHP: 7.3

## Expected Behavior
// add a new custom field with the value "here's a testimonial"
```php
carbon_set_post_meta($newTestimonialsID, 'crb_testimonial_content',"Here's my testimonial");
```

## Actual Behavior
// instead of `"Here's my testimonial"`, I get `"Here\'s my testimonial"`

How can I make it to not add the \ before any single quote?
![cvzxcvzx](https://user-images.githubusercontent.com/5404341/58323909-093b7e00-7e2e-11e9-95b8-47cb9ebcfef0.JPG)

**Comment by jorostoyanov** [comment]
Hi @speedwheel 

I have tested this with the latest version 3.1.4, however, I am not able to reproduce it.

Please feel free to re-open the issue if you happen to experience the problem again :)
