### ISSUE TITLE
Widgets not saving properly

### ISSUE THREAD

**Issue by alessandrotesoro** [htmlburger/carbon-fields#724]
## Version

  - Carbon Fields: 3.1.1
  - WordPress: 5.2.1
  - PHP: any version

## Expected Behavior
When pressing the save button for each CF powered widget, it should save and allow the user to navigate away from the page.

## Actual Behavior
Widget is saved but WordPress still thinks the widget is "dirty". Preventing users to navigate away from the page and displays an alert.

When inspecting the dom classes assigned to the widget, all widgets are assigned a `widget-dirty` class to the wrapper, once the widget is saved the class is removed. This works for all default widgets except the ones powered by Carbon fields. 

The class `widget-dirty` stays assigned to the wrapper which I think makes WordPress think the widget hasn't been saved yet and it displays the browser alert.

**Comment by bilalmalkoc** [comment]
Did you find any solution?

**Comment by alessandrotesoro** [comment]
@bilalmalkoc unfortunately not, I'm no React expert otherwise I would have submitted a pull request :(

**Comment by bilalmalkoc** [comment]
Why authors not answer? I am waiting for 3 months to fix that.

**Comment by rayhanuddin2019** [comment]
I am also waiting for author reply

**Comment by zarino** [comment]
Sadly this is still an issue.

**Comment by joannesalfa** [comment]
Same here, it has not been fixed for years...

**Comment by bilalmalkoc** [comment]
Don't waste time here. Go to ACF or Codestar.

**Comment by jorostoyanov** [comment]
Guys, I have released v.3.2.2 with a fix for this issue. Please test and let me know if it is being fixed on your side :)

**Comment by jorostoyanov** [comment]
Please open a new issue if you happen to experience the problem again :-)
