### ISSUE TITLE
Select field in Gutenberg block

### ISSUE THREAD

**Issue by yunusga** [htmlburger/carbon-fields#728]
## Version

  - Carbon Fields: ^3.1 (composer)
  - WordPress: 5.2.1
  - PHP: 7.2

## Expected Behavior
Gutenberg block with select field with one or more options must trigger post content change for enable button **Publish/Update** post.

## Actual Behavior
If add new Gutenberg block with `select` Carbon field with one or more options, button **Publish/Update** post becomes disabled `aria-disabled="false"` until `select` field change.

If select has only one option, button **Publish/Update** post always disabled `aria-disabled="false"` on post Create or Update.

`Ctrl + S` post Save/Update is working.

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;
use Carbon_Fields\Block;

function crb_attach_theme_options() {
    Block::make( 'gnt_subscribe_form_test', __( 'Subscribe Form Test' ) )
        ->add_fields( array(
            Field::make( 'select', 'subscribe_list', __( 'Choose List to Subscribe (MailPoet)' ) )
                ->add_options( array(
                    'facebook'  => 'Facebook',
                ) )
                ->set_required( true ),
        ) )
        ->set_icon( 'email-alt' )
        ->set_keywords( array( 'subscribe', 'form') )
        ->set_category( 'Forms' )
        ->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {
        ?>
        test
	<?php
    } );
}
add_action( 'carbon_fields_register_fields', 'crb_attach_theme_options', 50 );

function crb_load() {
	require_once( get_template_directory() . '/vendor/autoload.php' );
	\Carbon_Fields\Carbon_Fields::boot();
}
add_action( 'after_setup_theme', 'crb_load' );
```

## Steps to Reproduce the Problem
1. Gutenberg block with `select` field with one option
   1. Create Gutenberg block with `select` field with one option
   2. Add created block in Gutenberg editor (button **Publish/Update** disabled)
   3. Save post with `Ctrl + S`
   4. Reload page (button **Publish/Update** disabled)
2. Gutenberg block with `select` field with two options
   1. Create Gutenberg block with `select` field with two options
   2. Add block with two options in Gutenberg editor (button **Publish/Update** disabled)
   3. Do not change select field
   4. Save post with `Ctrl + S`  (button **Publish/Update** disabled)
   5. Reload page (button **Publish/Update** disabled)
   6. Try to change `select` field (button **Publish/Update** enabled)
   7. Save post with
   8. Reload page (button **Publish/Update** enabled)

**Comment by jeffdrumgod** [comment]
+1
