### ISSUE TITLE
[Question] - Add to container from plugin

### ISSUE THREAD

**Issue by dbenson91** [htmlburger/carbon-fields#729]
I'm using Carbon Fields to build a plugin to be used on multiple Wordpress sites.

I have a Container containing multiple Fields. However some of these websites will need extra fields adding to this Container.

Is it possible to add more fields to this Container through the child theme, rather than having to edit the plugin?

Thanks!

**Comment by emohamed** [comment]
Hi @dbenson91 

You could provide themes with ability to filter the fields, so they can add new fields before the container is created

Here is some (not tested) code:

```php
// wp-content/plugins/shiny-plugin/fields.php:
$fields = apply_filters('shiny_plugin_fields_for_posts', [
    Field::make('text', 'subtitle'),
    Field::make('color', 'subtitle_color')
]);
Container::make('Fields for posts')->add_fields($fields);
```

```php
// wp-content/themes/twentythirty/functions.php:
add_filter('shiny_plugin_fields_for_posts', function ($fields) {
    $fields[] = Field::make('color', 'subtitle_background_color');
    return $fields;
});
```

Hope this helps.

**Comment by dbenson91** [comment]
Thanks @emohamed - This works.

Is it also possible to do something similar with a complex field?

For example, if I wanted to add another '->add_fields' into the complex field through the child theme:

`Container::make( 'post_meta', 'test' )->add_fields( array(
        Field::make( 'complex', 'test_complex' )
            ->add_fields( 'fields_one', array(
              Field::make( 'text', 'field_one' ),
            ))
            ->add_fields( 'fields_two', array(
              Field::make( 'text', 'field_two' ),
            ))
);`

**Comment by emohamed** [comment]
Sure, something like this should suffice:

```php
// plugin ... 
$groups =  [
    'fields_one' => [
        Field::make( 'text', 'field_one' ),
    ],
    'fields_two' => [
        Field::make( 'text', 'field_two' ),
    ]
];

$groups = apply_filter('shiny_plugin_complex_groups', $groups);

$complex_field = Field::make( 'complex', 'test_complex' );
foreach( $groups as $group_name => $group_fields ) {
    $complex_field->add_fields($group_name, $group_fields);
}

Container::make( 'post_meta', 'test' )->add_fields( [
    $complex_field
]);

```

----

```php
// theme ... 
add_filter('shiny_plugin_complex_groups', function ($groups) {
    
    $groups['fields_three'] = [
        Field::make( 'text', 'field_three' ),
    ];

    return $groups;
});
```

**Comment by dbenson91** [comment]
Great! Thanks again @emohamed
