### ISSUE TITLE
Class 'Carbon_Fields\Block' not found in

### ISSUE THREAD

**Issue by Hellion35** [htmlburger/carbon-fields#730]
Привет всем, насколько я понял, тут и по-русски разговаривают? У меня возникла проблема при подключении блоков Gutenberg. Беру пример из документации и вставляю его как есть.
`
use Carbon_Fields\Block;

Block::make( __( 'My Shiny Gutenberg Block' ) )
    ->add_fields( array(
        Field::make( 'text', 'heading', __( 'Block Heading' ) ),
        Field::make( 'image', 'image', __( 'Block Image' ) ),
        Field::make( 'rich_text', 'content', __( 'Block Content' ) ),
    ) )
    ->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {
        ?>

        <div class="block">
            <div class="block__heading">
                <h1><?php echo esc_html( $fields['heading'] ); ?></h1>
            </div>

            <div class="block__image">
                <?php echo wp_get_attachment_image( $fields['image'], 'full' ); ?>
            </div>

            <div class="block__content">
                <?php echo apply_filters( 'the_content', $fields['content'] ); ?>
            </div>
        </div>

        <?php
    } );
`
В итоге у меня выдает ошибку:
Fatal error: Uncaught Error: Class 'Carbon_Fields\Block' not found in.
Что я делаю не так? Подключение CarbonFields:
`
function crb_load() {
    require_once( 'inc/vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();
}
add_action( 'after_setup_theme', 'crb_load' );
`

**Comment by emohamed** [comment]
Hi @Hellion35 

Could you please make sure that you're using Carbon Fields version 3? I guess that you're using older version of the library.

**Comment by webangon** [comment]
I have same issue. I am using this version - https://carbonfields.net/zip/v3.1.2/ . It is a bug or file missing, but other things (theme option, metabox, widget etc) work fine just have issue with guttenberg block. 
Can you please recheck @emohamed ?

**Comment by james0r** [comment]
I know this will be very obvious for most, but for me I had failed to switch to the theme where I had installed Carbon Fields. Embarrassingly this took me 10 - 15 minutes to realize.

**Comment by vvasilev-** [comment]
Hi @Hellion35,

You should register your blocks after the `boot` method call.

```php
function crb_load() {
    require_once( 'inc/vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();

    // Register your blocks here...
}
add_action( 'after_setup_theme', 'crb_load' );
```

----

@webangon, Can you try the same thing? :)

**Comment by drzraf** [comment]
In terms of developer-friendliness, could this boot process be done automatically by the plugin under the hood, so that instructions get simpler and more consistent, like:
`Define your blocks within the action_X hook or any action hook between X and Z`
 (X and Z being part of https://codex.wordpress.org/Plugin_API/Action_Reference)

**Comment by coder618** [comment]
I had face the same problem, but i later i realize that, that there are two version for creating Gutenberg Component with Carbon Fields,
1. Without Composer
2. With Composer 
Using appropriate function solve my issue.
https://docs.carbonfields.net/#/containers/gutenberg-blocks

**Comment by coder618** [comment]
I been using 3.1.2 version, (Plugin Edition).

Register the component within 'carbon_fields_register_fields' hooks works fine for me.
add_action( 'carbon_fields_register_fields', 'custom_function_to_register_block'  );

Full sample code: [Show code](https://gist.github.com/coder618/952b287df83672efc2056932a56638b4)
