### ISSUE TITLE
How to create fields block in the attributes panel?

### ISSUE THREAD

**Issue by Grafs** [htmlburger/carbon-fields#731]
## Version
  - Carbon Fields: 3.1.1
  - WordPress: 5.2.1
  - PHP: 7.2

How to create fields in the attributes panel on the right panel,  for a block?
Now all the parameter fields are displayed only in the block itself.

**Comment by dackr** [comment]
Hello a question please did you manage to solve what you wanted to do? If so, could you share your code?
or could someone help please?

**Comment by NovalnetLLC** [comment]
Not
In carbon-fields there is no such functionality

**Comment by Grafs** [comment]
Not
In carbon-fields there is no such functionality

**Comment by dackr** [comment]
ok thanks

**Comment by jorostoyanov** [comment]
@Grafs @dackr You can use the `set_mode('preview')` callback method to achieve that :-)
