### ISSUE TITLE
Runtime loading value of html field

### ISSUE THREAD

**Issue by LaetitiaDall** [htmlburger/carbon-fields#736]
## Version

  - Carbon Fields: 3
  - WordPress: 5.2
  - PHP: 7.2

## Expected Behavior
When using a Callable with HTML field, it should be run at runtime like set_options of select.

## Actual Behavior
The callable is called immediately, causing multiple issues like some post_type not being registered, or meta values unavailable at current time.

## Container definition

        $fields[] = Field::make('html', $prefix . 'example', __('Event', 'dallinge'))
            ->set_html('callback');

**Comment by jorostoyanov** [comment]
Fixed in https://github.com/htmlburger/carbon-fields/pull/845
