### ISSUE TITLE
Complex field label isn't visible

### ISSUE THREAD

**Issue by Vmadmax** [htmlburger/carbon-fields#737]
## Version

  - Carbon Fields: 3.1
  - WordPress: 5.2.2
  - PHP: 7.2.4

## Expected Behavior
Complex field label is visible in backend

## Actual Behavior
Complex field label isn't visible in backend

## Container definition
```php
->add_fields('model-gallery', 'Model-Galerie', array(
    Field::make('media_gallery', 'media_gallery')
        ->set_type(array('image')),
))
->add_fields('news', 'Neuigkeiten', array(
    Field::make('text', 'heading', 'Überschrift - 1.'),
    Field::make('text', 'heading_second', 'Überschrift - 2.'),
))
->add_fields(array(
    Field::make('complex', 'slider', 'Slideshow')
        ->set_layout('tabbed-horizontal')
        ->add_fields(array(
            Field::make('text', 'heading', 'Überschrift - 1. Zeile'),
            Field::make('text', 'heading_second', 'Überschrift - 2. Zeile'),
            Field::make('image', 'image', 'Image'),
            Field::make('checkbox', 'has_button', 'Button hinzufügen?'),
            Field::make('text', 'button_label', 'Button-Beschriftung')
                ->set_conditional_logic(array(
                    array(
                        'field' => 'has_button',
                        'value' => true,
                    )
                )),
            Field::make('text', 'button_url', 'Button-Url')
                ->set_conditional_logic(array(
                    array(
                        'field' => 'has_button',
                        'value' => true,
                    )
                )),
        )),
))
```

## Comments
<img width="317" alt="Bildschirmfoto 2019-07-13 um 20 52 32" src="https://user-images.githubusercontent.com/1713226/61175562-11a07180-a5b2-11e9-9556-4457bdd50f81.png">

I don't know if this is an issue, or I make a mistake.
In the backend, the labels "Model-Galerie" and "Neuigkeiten" are visible, but not the complex field "Slideshow".
It's an empty list element in the backend, but it is working well. Only the label isn't visible after clicking "add new entry"

**Comment by lstoyanoff** [comment]
Hi, in the code that you've provided the last complex group has no id nor label and that's why it doesn't appear. When you're using complex groups it is recommended to define id for each of them.
