### ISSUE TITLE
Error: cf is not defined

### ISSUE THREAD

**Issue by brnteka** [htmlburger/carbon-fields#741]
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 4.9.10
  - PHP: 5.6.38

Hello, i have troubles with making CF working, i installed it as a plugin via dashboard, activated it and even before i start to create fields in functions.php, there is already an error in the console:  

`Uncaught Reference Error: cf is not defined at index.php:2079`

No other plugins are enabled and the error appears even on dashboards main page. And still if i register fields ignoring error they will not show up in admin UI

**Comment by shvlv** [comment]
You need update WP to 5.0 at least. Bug/feature caused by this commit https://github.com/htmlburger/carbon-fields/commit/cc10058364f29723b922bf206823d97f84fd4776
wp-polifill script was added to WP 5.0.

Maybe miminimal required WP version is good info for documentation?
