### ISSUE TITLE
Association field value is not loading - "Call to a member function get_thumbnail_by_type() on null"

### ISSUE THREAD

**Issue by filipecsweb** [htmlburger/carbon-fields#742]
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 5.2.2
  - PHP: 7.3

## Expected Behavior
Association field values (user type) should load previously saved users.

## Actual Behavior
Instead of showing which users were selected/saved it displays nothing due to the fatal error generated in the server after the request to the REST API.

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

function carbon_fields_register_fields_callback() {
	Container::make( 'theme_options', __( 'Pay Author Per Post', 'ss_papp' ) )
	         ->set_page_file( 'ss_papp_settings' )
	         ->set_page_menu_title( 'Pay Author Per Post' )
	         ->where( 'current_user_role', 'IN', [ 'administrator' ] )
	         ->add_tab( __( 'Configurações de pontuação', 'ss_papp' ), [
		         Field::make( 'association', 'papp_included_users', __( 'Usuários que pontuam', 'ss_papp' ) )
		              ->set_help_text( __( 'Qualquer usuário selecionado acima pontuará, independentemente de qual seja sua função.', 'ss_papp' ) )
		              ->set_types( [
			              [ 'type' => 'user' ]
		              ] )
		              ->set_visible_in_rest_api( true ),
		         Field::make( 'association', 'papp_excluded_users', __( 'Usuários que NÃO pontuam', 'ss_papp' ) )
		              ->set_help_text( __( 'Qualquer usuário selecionado acima não pontuará, independentemente de qual seja sua função. Essa opção predominará caso um mesmo usuário esteja selecionado em "Usuários que pontuam".',
			              'ss_papp' ) )
		              ->set_types( [
			              [ 'type' => 'user' ]
		              ] )
		              ->set_visible_in_rest_api( true )
	         ] );
}

add_action( 'carbon_fields_register_fields', 'carbon_fields_register_fields_callback', 1 );
```

## Steps to Reproduce the Problem

  1. Run the code above within `functions.php` or inside a plugin.
  2. Access http://localhost/wp-admin/admin.php?page=ss_papp_settings. Of course, change `http://localhost` if necessary.
  3. Save users under `Usuários que pontuam`.
  4. Check the console and see that the request `http://localhost/wp-json/carbon-fields/v1/association/?container_id=carbon_fields_container_pay_author_per_post&options=1%3Auser%3Auser&field_id=papp_included_users` generates a fatal error:   
`Uncaught Error: Call to a member function get_thumbnail_by_type() on null in /var/www/html/wp-content/plugins/ss-pay-author-per-post/vendor/htmlburger/carbon-fields/core/REST_API/Router.php:323`. Of course, your directory will be different.

## Comments
I've already read the other issues that are related to Association fields, but none of them fixes my problem.
I've also had the same issue in a fresh WP installation with no plugins installed.
Please, help.

**Comment by filipecsweb** [comment]
Anybody? 😢

**Comment by davidvina** [comment]
Same problem.

No idea how to resolve. Please help

`Fatal error: Uncaught Error: Call to a member function get_thumbnail_by_type() on null in /DATOS/CLIENTS/galfer/galfer.devel/theme/vendor/htmlburger/carbon-fields/core/REST_API/Router.php:323 Stack trace: #0 /DATOS/CLIENTS/galfer/galfer.devel/wordpress/wp-includes/rest-api/class-wp-rest-server.php(946): Carbon_Fields\REST_API\Router->get_association_data(Object(WP_REST_Request)) #1 /DATOS/CLIENTS/galfer/galfer.devel/wordpress/wp-includes/rest-api/class-wp-rest-server.php(329): WP_REST_Server->dispatch(Object(WP_REST_Request)) #2 /DATOS/CLIENTS/galfer/galfer.devel/wordpress/wp-includes/rest-api.php(309): WP_REST_Server->serve_request('/carbon-fields/...') #3 /DATOS/CLIENTS/galfer/galfer.devel/wordpress/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP)) #4 /DATOS/CLIENTS/galfer/galfer.devel/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #5 /DATOS/CLIENTS/galfer/galfer.devel/wordpress/wp-includes/plugin.php(531): WP_Hook->do_action(Array) #6 /DATOS/CLIENTS/galfer/galfer.devel/wor in /DATOS/CLIENTS/galfer/galfer.devel/theme/vendor/htmlburger/carbon-fields/core/REST_API/Router.php on line 323`

**Comment by lstoyanoff** [comment]
Hi, this issues was already resolved. Please update to the latest Carbon Fields version.

**Comment by bilalmalkoc** [comment]
Same issue in 3.1.20

**Comment by TheJema** [comment]
v3.2.1 same problem

**Comment by jorostoyanov** [comment]
The issue should be fixed in the latest release.

If you happen to experience it again, please open a new one with more details.

Thanks!

**Comment by filipac** [comment]
@jorostoyanov it happens with WPML when you switch to a secondary language, not the main one.

**Comment by filipac** [comment]
@jorostoyanov not really a code issue, but we had in the PHP file this:
```Container::make('theme_options', __('Homepage'))``` and that translated Homepage to Pagina de inicio and had another container id. That confused Carbon Fields.

**Comment by TheJema** [comment]
> The issue should be fixed in the latest release.
> 
> If you happen to experience it again, please open a new one with more details.
> 
> Thanks!


Hello

This problem is relevant when using associative fields in custom post types.


`Fatal error: Uncaught Error: Call to a member function get_thumbnail_by_type() on null in wp-content/themes/jbetting_v4/includes/libs/carbon-fields/vendor/htmlburger/carbon-fields/core/REST_API/Router.php:330
`

**Comment by devi-vahid** [comment]
When creating a container make sure you put the containers label in 3rd method and 2nd method which is container name is not translated. 
so your container should look like this: 

`Container::make( 'term_meta', 'container_name', __( 'Container Label', 'parssteel-core' ) )`

If you wanna know why look at `factory` method in Field class(arguments are passed to that method eventually): 
```
	/**
	 * Create a new field of type $raw_type and name $name and label $label.
	 *
	 * @param string $raw_type
	 * @param string $name lower case and underscore-delimited
	 * @param string $label (optional) Automatically generated from $name if not present
	 * @return Field
	 */
	public static function factory( $raw_type, $name, $label = null ) {
		$type = Helper::normalize_type( $raw_type );

		// stop hidden symbol support when the end user is creating fields ][
		// @see Field::set_name()
		if ( ! Helper::is_valid_entity_id( $name ) ) {
			Incorrect_Syntax_Exception::raise( 'Field names can only contain lowercase alphanumeric characters, dashes and underscores ("' . $name . '" passed).' );
			return null;
		}

		if ( Carbon_Fields::has( $type, 'fields' ) ) {
			return Carbon_Fields::resolve_with_arguments( $type, array(
				'type' => $type,
				'name' => $name,
				'label' => $label,
			), 'fields' );
		}
```
