### ISSUE TITLE
How to use carbon-fields last version with qtranslate?

### ISSUE THREAD

**Issue by seriiserii825** [htmlburger/carbon-fields#747]
## Version

  - Carbon Fields:
  - WordPress:
  - PHP:

## Expected Behavior
_Please enter the expected behavior here_

## Actual Behavior
_Please enter the actual, unexpected behavior here_

## Container definition
```php
// Please add your entire container defintion here so issues
// are easy to reproduce
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Comments
_Please add any other comments here_

**Comment by jorostoyanov** [comment]
No information provided
