### ISSUE TITLE
Problem with Transparency Color

### ISSUE THREAD

**Issue by EMembrillas** [htmlburger/carbon-fields#748]
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 5.2.2
  - PHP: 7.3.5

## Expected Behavior
When you choose a color with transparency 0 and "set_alpha enabled = TRUE", must return the RGBA values with Alpha 0

## Actual Behavior
Right now, always return this array
array (4) {["red"] => int (0) ["green"] => int (0) ["blue"] => int (0) ["alpha"] => float (1)}

**Comment by lstoyanoff** [comment]
Hi, this issue has been resolved in https://github.com/htmlburger/carbon-fields/releases/tag/v3.1.13 , please update
