### ISSUE TITLE
Is Carbon Fields 3 backwards compatible with 2's code?

### ISSUE THREAD

**Issue by RachelRVasquez** [htmlburger/carbon-fields#752]
## Version

  - Carbon Fields: 2
  - WordPress: 5.1.1
  - PHP: 7.1.15

I just want to know if I have a WordPress theme that's full of Carbon Fields V2 code, can I update to V3 and it will all work or will things break?

My WordPress site is already using Gutenberg, however it's disabled using the Classic Editor plugin for now. Reason why I'm asking is because I'm fine using the fields without them necessarily being "blocks" but I want the fix that was applied to the association field performance from this thread: https://github.com/htmlburger/carbon-fields/issues/318

Seems like the performance fix is only on V3, but I don't want to upgrade if it will break all of my V2 code. Thanks!

**Comment by RachelRVasquez** [comment]
Umm... anyone? *crickets* 😅

**Comment by macronomicus** [comment]
Interesting question, my guess is no, but the best way to check is just try it on a clone of the site and see what happens, I cant remember where but I saw a post about upgrading to the new version somewhere.  Sorry thats not more helpful lol.  Did you try it out yet?

**Comment by RachelRVasquez** [comment]
@macronomicus I haven't tried it yet but I intend to. I'm still figuring out how to set up Composer locally so I can give it a go. I doubt it's backwards compatible too but worth a try. Will update here once I have a more solid answer.

**Comment by iamntz** [comment]
In terms of container/fields definition and saved data, yes, it's compatible. I've upgraded a bunch of sites with no issues whatsoever.

If you have any custom/3rd party field (i.e. that is NOT bundled with the plugin) then it will NOT work, as the API is not backward compatible.

**Comment by RachelRVasquez** [comment]
Thanks for letting me know. I did upgrade but since I didn't have composer
locally, I just replaced the carbon fields folder that existed with the
newest release. So far it looks like it works. I haven't thoroughly tested
but just by viewing the front end and admin pages, no errors so far.
