### ISSUE TITLE
Update WordPress JS/Gutenberg Dependencies

### ISSUE THREAD

**Issue by gaambo** [htmlburger/carbon-fields#762]
## Version

  - Carbon Fields: 3.1.3
  - WordPress: 5.2.3
  - PHP: 7.3
  - Gutenberg: 6.6.0 (via plugin)

## Expected Behavior
No deprecation notices about deprecated packages of if SCRIPT_DEBUG is enabled.

## Actual Behavior
Deprecation notices about some deprecated packages of WordPress JS packages - most of them are components which were moved to another package.
## Steps to Reproduce the Problem

  1. Install Gutenberg plugin (6.6.0, might happen with earlier versions as well - depends on the messages)
  2. Enable SCRIPT_DEBUG constant
  3. Open editor in backend and see notices in browser console.

## Comments

Most of the components/imports were moved to another package/namespace - so it's just a matter of changing the import paths. Also bugs with the latest react version used by gutenberg plugin might have to be checked/tested.

**Comment by gaambo** [comment]
I can update the imports in a PR (I'm used to working with the latest gutenberg / wordpress js packages and know them quite well) - but I'd need some help about testing, versioning & backwards compatibility and (preparing for) merging since this would be my first contribution.

**Comment by jorostoyanov** [comment]
The dependencies have been updated in v3.4.0-beta.1 :)
