### ISSUE TITLE
Set Preview Mode as default

### ISSUE THREAD

**Issue by chrishufnagel** [htmlburger/carbon-fields#777]
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 5.2.4
  - PHP: 7.3

## Expected Behavior
Gutenberg blocks don't save preview mode as the state. 

In an ideal world, it would be possible to set the blocks to preview mode as default or at least save the state they are in so that when you go back to that page the blocks are in preview mode.

We are switching over from ACF and this is one thing that we can not find a solution for.

**Comment by ChrisButterworth** [comment]
Is this still something being looked at in v3? I'd find this really handy too.

**Comment by jl-a** [comment]
When the mode is `both` the default is `edit`. i.e. when the block is rendered in the editor it will always be in edit mode first.

To change it so the default mode is `preview` (which I believe is the original intent of this issue) you need to manually write into the block's settings array.

```
$block = Block::make( $title );
$block->settings[ 'mode' ] = 'preview';
```
