### ISSUE TITLE
Gutenberg blocks not working on WP 5.3

### ISSUE THREAD

**Issue by rafaucau** [htmlburger/carbon-fields#779]
## Version

  - Carbon Fields: 3.1.6
  - WordPress: 5.3
  - PHP: 7.3

## Actual Behavior
Custom blocks do not appear in the editor on WP 5.3. No errors in PHP and console.

## Container definition
```php
use Carbon_Fields\Block;

Block::make( __( 'My Shiny Gutenberg Block' ) )
    ->add_fields( array(
        Field::make( 'text', 'heading', __( 'Block Heading' ) ),
        Field::make( 'image', 'image', __( 'Block Image' ) ),
        Field::make( 'rich_text', 'content', __( 'Block Content' ) ),
    ) )
    ->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {
        ?>

        <div class="block">
            <div class="block__heading">
                <h1><?php echo esc_html( $fields['heading'] ); ?></h1>
            </div><!-- /.block__heading -->

            <div class="block__image">
                <?php echo wp_get_attachment_image( $fields['image'], 'full' ); ?>
            </div><!-- /.block__image -->

            <div class="block__content">
                <?php echo apply_filters( 'the_content', $fields['content'] ); ?>
            </div><!-- /.block__content -->
        </div><!-- /.block -->

        <?php
    } );

```

## Steps to Reproduce the Problem

  1. Install WP 5.3 Beta
  1. Try adding custom block
  1. The block don't appear in the editor

## Comments
I know that WordPress 5.3 is still a beta version, but I am reporting earlier so that there will be no problems after the official update

**Comment by jorostoyanov** [comment]
Hi @rafaucau 

Can you try setting the icon for your block via `->set_icon( 'book-alt' )`. This should resolve the issue.

**Comment by drzraf** [comment]
Same annoying issue here. (no log, no error, no trace of why block does not seem registered).
Why was this issue closed?

**Comment by rafaucau** [comment]
@drzraf 
> Why was this issue closed?
It's already fixed. Maybe you have an old version of Carbon Fields.
run `composer update` command and check again

**Comment by drzraf** [comment]
I'm using the latest CBF 3.1.8 + WP 5.3.2

**Comment by rafaucau** [comment]
@drzraf 
Have you checked on the minimum WP installation? With all plugins disabled.

Eg. Google Site Kit plugin breaks Carbon Fields:
https://wordpress.org/support/topic/site-kit-breaks-carbon-fields-gallery-field/

**Comment by drzraf** [comment]
#786 ? I'm indeed seeing `TypeError: cf.core is undefined`.

**Comment by alimoshen** [comment]
> @drzraf
> 
> > Why was this issue closed?
> 
> It's already fixed. Maybe you have an old version of Carbon Fields.
> Run `composer update` command and check again

Thanks @drzraf, the composer update did the trick for me! Was about to give up and revert back to ACF 👍
