### ISSUE TITLE
How save data from fields to custom mysql tables?

### ISSUE THREAD

**Issue by viterzbayraku** [htmlburger/carbon-fields#781]
Thank you for awesome framework. I have a question.
Do you have any way to save data from post fields as set to custom mysql table?
I have for example 40-50 positions of custom data for any post and want: 1) save in as one easy compact data set to different database table and after 2) use it on site as custom request directly from mysql.

**Comment by emohamed** [comment]
You can use custom datastore in order to achieve that. Here is an example that saves a complex field to a serialized array:
https://carbonfields.net/docs/guides-serialized-datastore/

Please give it a shot and let me know if you face any issues.

**Comment by viterzbayraku** [comment]
> You can use custom datastore in order to achieve that. Here is an example that saves a complex field to a serialized array:
> https://carbonfields.net/docs/guides-serialized-datastore/
> 
> Please give it a shot and let me know if you face any issues.

Thank you for answer. It is actual for version 3.0?

**Comment by emohamed** [comment]
Custom datastores will work just fine on v3. Give it a try and let me know if you face any incompatibilities. 

> And second question: using of $post->ID in post_meta requests is possible with custom datastores like this? Thank you.

I don't think that this would work. You can still use `WP_Query`, and hook to the `JOIN` clauses. Here are some examples for this: https://wordpress.stackexchange.com/questions/50305/how-to-extend-wp-query-to-include-custom-table-in-query

**Comment by viterzbayraku** [comment]
When i'm trying to include custom code in functions.php, I have error:

'Carbon_Fields\Datastore\Datastore' not found

**Comment by jorostoyanov** [comment]
Hi @viterzbayraku 

You should register the `Serialized_Theme_Options_Datastore` after Carbon Fields are loaded:

```
add_action( 'carbon_fields_register_fields', 'crb_register_custom_datastore', 5 );
function crb_register_custom_datastore() {
    include("inc/save_carbon.php");
}
```

Give it a try and let me know how this goes.

**Comment by viterzbayraku** [comment]
Thank you! Working fine :)

**Comment by viterzbayraku** [comment]
Guys, thank you for your help.
Additional question. Can I save data of some field without serialization?
Simple data instead of string like this: `a:1:{i:0;a:1:{s:5:"value";s:4:"4444";}}`?

**Comment by kostikovmu** [comment]
> Hi @viterzbayraku
> 
> You should register the `Serialized_Theme_Options_Datastore` after Carbon Fields are loaded:
> 
> ```
> add_action( 'carbon_fields_register_fields', 'crb_register_custom_datastore', 5 );
> function crb_register_custom_datastore() {
>     include("inc/save_carbon.php");
> }
> ```
> 
> Give it a try and let me know how this goes.

Why is this not have in the documentation example? https://docs.carbonfields.net/learn/advanced-topics/serialized-datastore.html
