### ISSUE TITLE
post_parent_id filter bug

### ISSUE THREAD

**Issue by determin1st** [htmlburger/carbon-fields#782]
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 5.2
  - PHP: 7.2

## Expected Behavior
shows UI

## Actual Behavior
doesnt show UI

## Container definition
```php
// any container def with post_parent_id = <integer> filter
```

## Comments
I suppose, it's the gutenberg, upon opening of any page has this delay/lag of showing page parent attribute which happens after carbon init and the UI doesnt show. Here is some workaround fix:
```livescript
	if n = document.querySelector '#editor'
		n = n.querySelector '.components-panel > div:last-child'
		o = new MutationObserver (list, observer) !->
			observer.disconnect!
			wp.hooks.doAction('carbon-fields.init');
		o.observe n, {childList: true}
```

**Comment by jorostoyanov** [comment]
Hi @determin1st 

Apologies for the late reply.

Using v3.2 the containers are showing as expected.

Feel free to re-open if the issue persists on your side :-)
