### ISSUE TITLE
Order multiselect items

### ISSUE THREAD

**Issue by liciniofs** [htmlburger/carbon-fields#784]
## Version

  - Carbon Fields: 3.1
  - WordPress: 5.2.4
  - PHP: 7.3

## Expected Behavior
Manualy order multiselect items.

## Actual Behavior
Can't order manually. Reverses order.

**Comment by atwellpub** [comment]
Does anyone have a workaround for this? I'm trying to update the hidden input manually for a postmeta multiselect field but it does not seem to take. Interested in workarounds.
