### ISSUE TITLE
Gutenberg Blocks issue on WordPress 5.3

### ISSUE THREAD

**Issue by Probewise** [htmlburger/carbon-fields#785]
## Version

  - Carbon Fields: 3.1.2
  - WordPress: 5.3
  - PHP: 7.3

## Expected Behavior
Add Gutenberg Blocks on posts or pages.

## Actual Behavior
No Gutenberg Blocks are showing on posts or pages after updating to WordPress 5.3.

**Comment by rinseringma** [comment]
Yep, same here. Already noticed it when using the Gutenberg plugin.
<img width="618" alt="Schermafbeelding 2019-11-13 om 09 38 45" src="https://user-images.githubusercontent.com/2634987/68746720-7bc93180-05f9-11ea-95ad-e23f9f8978b1.png">

The blocks also missing from the dropdown selector.

**Comment by emohamed** [comment]
Hi guys,

we're looking into this ... will have an update in the next few days.

**Comment by rinseringma** [comment]
> Hi guys,
> 
> we're looking into this ... will have an update in the next few days.

Noticed an console error when editing a page:
<img width="1347" alt="Schermafbeelding 2019-11-13 om 10 27 19" src="https://user-images.githubusercontent.com/2634987/68750523-4aa02f80-0600-11ea-8237-485fb6c396d7.png">

**Comment by webdevid** [comment]
yups same here...  Already noticed when upgrade to wp 5.3
the layout in frontend looks ok.. 

but in gutenberg editor  show warning:

Your site doesn’t include support for the "carbon-fields/block-partner-selected" block. You can leave this block intact or remove it entirely.

and all block has gone from dropdown block selector

**Comment by vvasilev-** [comment]
@Probewise, @webdevid, @rinseringma,

The fix for this issue is released in v3.1.7. :)

**Comment by webdevid** [comment]
Great thanks @vvasilev-  and @emohamed   for update..

**Comment by devnostic** [comment]
Looks like this is happening in 5.4 as well. I am on 3.1.15
