### ISSUE TITLE
Conflict with Site Kit by Google (theme option)

### ISSUE THREAD

**Issue by SYip** [htmlburger/carbon-fields#786]
## Version

  - Carbon Fields: 3.1.7
  - WordPress: WordPress 5.3
  - PHP: 7.1

## Expected Behavior
Theme option fields should be shown in theme option page.
Should not display errors in console.

## Actual Behavior
Theme option fields are not displayed.
Error in console:
```
TypeError: u is undefined core.min.js:10:19659
TypeError: a is undefined metaboxes.min.js:1:6563
TypeError: d is undefined blocks.min.js:11:5870
TypeError: cf.core is undefined admin.php:1819:10
```

## Steps to Reproduce the Problem

  1. Require carbon fields with composer in theme and set theme option
  1. Install site kit by google
  1. Go to theme option page

## Comments
_Please add any other comments here_

**Comment by drzraf** [comment]
I'm getting `TypeError: cf.core is undefined` too, but without "Site Kit by Google"  being installed.

**Comment by jorostoyanov** [comment]
Cannot reproduce. Closing
