### ISSUE TITLE
Taxonomy Field

### ISSUE THREAD

**Issue by mjmc-jporter** [htmlburger/carbon-fields#791]
Does CF have a field comparable to Metabox.io Taxonomy field? https://docs.metabox.io/fields/taxonomy/

Where it actually adds post terms and not saving it as post meta?   I see something like the association field, but that field stores it as post meta

**Comment by Jakob-Maudience** [comment]
Yes for this you would use the association field - https://docs.carbonfields.net/#/fields/association?id=association

```php
Field::make( 'association', 'crb_association', __( 'Association' ) )
    ->set_types( array(
        array(
            'type'     => 'term',
            'taxonomy' => 'category',
        )
    ) )
```

**Comment by mihdan** [comment]
@Jakob-Maudience This example adds post terms and saving it as post meta, how to save value in term_relationship table?

**Comment by jorostoyanov** [comment]
@mihdan 

The `term_relationship` table is not meant to store additional meta data.

There are `postmeta` and `termmeta` tables which should be used for that.

Carbon Fields provides `Post Meta Container` and `Term Meta Container` which do exactly that :-)

**Comment by mihdan** [comment]
https://github.com/leurdo/carbon-taxonomy-field
