### ISSUE TITLE
Can't succesfully run quickstart guide: fields isn't build inside container

### ISSUE THREAD

**Issue by userlond** [htmlburger/carbon-fields#792]
## Version

  - Carbon Fields: "htmlburger/carbon-fields": "^3.1", installed via composer
  - WordPress: 5.3
  - PHP: 5.6

## Expected Behavior
I follow this guide https://docs.carbonfields.net/#/quickstart

I expect it to be working.

## Actual Behavior
Container is created, but Carbon Fields is not visible, they aren't actually generated.
![image](https://user-images.githubusercontent.com/7788670/69477258-8dd77b00-0e16-11ea-9768-579aba722281.png)

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;
// my functions.php theme file
add_action('after_setup_theme', function() {
    \Carbon_Fields\Carbon_Fields::boot();
});
add_action('carbon_fields_register_fields', function() {
    Container::make('theme_options', __('Theme Options'))
        ->add_fields(array(
            Field::make('text', 'crb_text', 'Text Field'),
        ));
});
```

**Comment by jorostoyanov** [comment]
Hi @userlond,

Please make sure that your composer autoload is included as well.

Modify the snippet to look like this:

```
use Carbon_Fields\Container;
use Carbon_Fields\Field;

require_once __DIR__ . '/vendor/autoload.php';

// my functions.php theme file
add_action('after_setup_theme', function() {
    \Carbon_Fields\Carbon_Fields::boot();
});
add_action('carbon_fields_register_fields', function() {
    Container::make('theme_options', __('Theme Options'))
        ->add_fields(array(
            Field::make('text', 'crb_text', 'Text Field'),
        ));
});
```

**Comment by drzraf** [comment]
Same problem.

**Comment by fabienlege** [comment]
Same problem, Basic theme_options page not working (no fields in the DOM), many JS errors

**Comment by justlevine** [comment]
Anyone find a fix to this? Same issue, no fields displayed...

**Comment by jorostoyanov** [comment]
Guys, I am not able to reproduce this issue..

It should be somehow specific to your setup.

Feel free to re-open the issue if the problem persists and we will find a way to debug this.

**Comment by chigozieorunta** [comment]
Same here. I noticed when you revert back to the 3.1 version, the problem disappears.

```
"require": {
    "htmlburger/carbon-fields": "~3.1"
  },
```
