### ISSUE TITLE
Complex fields set_header_template

### ISSUE THREAD

**Issue by KotovAndrey** [htmlburger/carbon-fields#793]
## Version

  - Carbon Fields: v3.1.8
  - WordPress: 5.3
  - PHP: 7.2

Guys, I use the construct:
$partner = get_posts([
        'numberposts' => -1,
        'orderby' => 'ABC',
        'post_type' => 'partner'
    ]);
    $partner_list[0] = 'None';

    if ($partner) {
        foreach ($partner as $post) {
            $partner_list[$post->ID] = $post->post_title;
        }
    }

Field::make('complex', 'slider')
                ->set_layout('tabbed-horizontal')
                ->add_fields([
                    Field::make('select', 'select_post')
                        ->set_options($partner_list)
                ])
Pls, tell me, how I can use set_header_template for showing post name on the tab?

**Comment by matepaiva** [comment]
@KotovAndrey i dont know if you figured it out, but the only change you have to make is to `set_layout` after `add_fields`.

**Comment by lstoyanoff** [comment]
@KotovAndrey You can `json_encode` the $partner_list and use it in the `set_header_template` method

```
$partner_list_json = json_encode( $partner_list );

Field::make('complex', 'slider')
  ->set_layout('tabbed-horizontal')
  ->add_fields([
    Field::make('select', 'select_post')
      ->set_options($partner_list)
  ])
  ->set_header_template( '<%-' . $partner_list_json . '[select_post] %> )
```
