### ISSUE TITLE
Problem using carbon_get_post_meta() with multiple field definition for different post levels

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#794]
## Version

  - Carbon Fields: 3.1.8 / 2.2.0
  - WordPress: 5.3
  - PHP: 7.3

## Expected Behavior

I want get post field value (2nd level of hierarchical post type) using `carbon_get_post_meta()` function.

## Actual Behavior

I get wrong value from first container definition (for 1st level). But i can get right value using `get_post_meta()` function.

## Container definition

```php
Container::make( 'post_meta', 'Fields' )
	->where( 'post_type', '=', 'myposttype' )
	->where( 'post_level', '=', 1 )
	->add_fields( [
		Field::make( 'select', 'keyname', 'Key Name' )
			->set_required( true )
			->add_options( [
				'value1' => 'Value 1',
			] ),
	] );

Container::make( 'post_meta', 'Fields' )
	->where( 'post_type', '=', 'myposttype' )
	->where( 'post_level', '=', 2 )
	->add_fields( [
		Field::make( 'select', 'keyname', 'Key Name' )
			->set_required( true )
			->add_options( [
				'value2' => 'Value 2',
				'value3' => 'Value 3',
			] ),
	] );
```

## Steps to Reproduce the Problem

1. Add custom hierarchical post type `myposttype`.
2. Add fields like above.
3. Add 2 level post and save post (default value will be `value2`).
4. Get this post field value:
```php
echo carbon_get_post_meta( $post_id, 'keyname' );
```
it return `value1`.

**Comment by lstoyanoff** [comment]
Hi, could you please provide a real example and describe what are you exactly trying to achieve?

**Comment by coder618** [comment]
I am facing the same issu, for select and multiselect, Cant able to get data for this kind of field using carbon_get_post_meta.
But on the backend(WP data saved successfully).

single-example_postypetype.php
`var_dump(carbon_get_post_meta($post->ID, 'selected_post_ids'));`

functions.php
```
Container::make( 'post_meta', 'Select Related post
    ->where( 'post_type', '=', 'expertise' )
    ->add_fields( array(
        Field::make( 'multiselect', 'selected_post_ids', 'Select Expertise Post' )
        ->add_options(get_post_arr('expertise')),
    ));
```
my-custom-function.php 
```

function get_post_arr($pType){
    $output =[];
    
    if(is_admin()){
        $c_posts = get_posts( ['post_type'=>$pType, 'posts_per_page'=>-1, ] );
        foreach($c_posts as $c_post){
            $output[$c_post->ID] = $c_post->post_title ."($c_post->ID)" ;
        }
    }
    return $output;
}
```

I am just trying to get list of ids

**Comment by EMembrillas** [comment]
Same problem with multiselect :(

**Comment by cyhuauin** [comment]
ON  2022  Year i had same issue

**Comment by Bratslavskij** [comment]
And me.

**Comment by Bratslavskij** [comment]
Maybe, post field value need print like this:
`
print_r(carbon_get_post_meta( $post_id, 'keyname' ));
`

**Comment by HTMLBurger-NG** [comment]
Hi @zevilz ,

Please note that the `post_level` check is just a visual check. The field would be shown/hidden by the time you change the dropdown for "Parent page". So this means that you are trying to define two fields with the same name. If you disable the where clause you would notice that both fields would be shown on the back end but only the first would be able to be used on the front end.

Please consider changing the key name and making some extra checks in the front end for the post level in order to get the correct field for the exact level.
