### ISSUE TITLE
Create types getter in Association_Field 

### ISSUE THREAD

**Issue by matepaiva** [htmlburger/carbon-fields#809]
## Version

  - Carbon Fields: 3.1

## Expected Behavior
I am doing a wrapper to integrate Carbon Fields and WpGraphQL, to register container fields to GraphQL. To map the association and relate it to other objects, I need to know the association types.

I can't map the Association Field relationship, because currently the 

## Actual Behavior
Currently, it is not possible to get the association types, as the `Carbon_Fields\Field\Association_Field` class has only a setter method (`set_types`) to the private property `types`, but no getter. I would like to add a getter method to that class, so the integration could be done easily.

I believe this change would have a very low impact, as it is only a getter and it exposes a information added by the consumer of the package. 

## Container definition
```php
$field = Field::make('association', 'crb_association', __('Association'))
  ->set_types([
    ['type' => 'post', 'post_type' => 'company'],
    ['type' => 'post', 'post_type' => 'post'],
    ['type' => 'term', 'taxonomy' => 'category'],
    ['type' => 'user'],
    ['type' => 'comment'],
]);

$types = $field->get_types(); // Error, because this getter doesn't exist.
```

## Comments
Suggested code for this change:

```php
/**
 * Get the types.
 *
 * @return  array $types types
 */
public function get_types() {
  return $this->types;
}
```

The experimental package that needs this change, integrating WpGraphQL and Carbon Fields: https://github.com/matepaiva/wp-graphql-crb

Thanks.

**Comment by jorostoyanov** [comment]
Hi @matepaiva 

I have added the getter -- https://github.com/htmlburger/carbon-fields/commit/1f43ca547f762b3d883ccfa12623aaa75e020741

The commit will be included in the next release.

Thank you for your contribution!

**Comment by matepaiva** [comment]
Glad to know that! Do you have a defined date for the next release? Thank you!

**Comment by jorostoyanov** [comment]
@matepaiva 

The method is now available in the latest v.3.1.11 release :)
