### ISSUE TITLE
Reusing Relationship Field inside Nested Section

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#81]
I am using a sections layout to make a modular theme. I have my sections displaying on the default page template, but I also wish to embed the sections inside of other sections using multiple complex types.
![image](https://cloud.githubusercontent.com/assets/10775656/17983048/44b197ae-6ad0-11e6-828b-0bb30983a5e2.png)

However the problem is that even though it displays the section in the backend and I can interract with it, when I update the post, the value doesn't get saved.
![image](https://cloud.githubusercontent.com/assets/10775656/17983070/5634be2a-6ad0-11e6-9448-0807cd6a4031.png)

**Comment by m1r0** [comment]
Hey @Santana1053,

This is a known bug. If you need to reuse a field, you have to make a new instance of it. I suggest making a function that will return a new instance of the field or making some sort of field generator for more complex stuff.

Quick example:
```
function crb_get_section_selector_field() {
	return Field::make...
}
```
