### ISSUE TITLE
Exotic bootstrapping process & assets URLs

### ISSUE THREAD

**Issue by drzraf** [htmlburger/carbon-fields#813]
## Version
  - Carbon Fields: v3.1.8
  - WordPress: 5.3
  - PHP: 7.4

## Expected Behavior
Should work out of the box on any WP installation

## Actual Behavior
Needs to customize  path/URL/symlink/composer in order to make it work. Eg: Bedrock, use of symlinks, ...

## Comments
I think that quite many bug reports are related to the installation. Bootstrap, assets access, path & class loading, ...
#457, #730, #779,  #792, #805
(#786, maybe ?)

1. One part is related to autoloader customization needed (because of the exotic bootstrapping process).

2. Another is related to assets.
One possible solution would be to provide static assets as a standalone build which is included in the plugin bundle. Then `plugin_url()` is usable and assets are always part of a publicly accessible directory.

The border between the WP plugin and the library could be reshaped a bit to improve installation process and initial usage.

## Note
Timber (the Twig implementation for WP) is another project trying to both fit as a library and a WP package (but they don't rely upon assets).

**Comment by lstoyanoff** [comment]
Hi, could you please provide more information for the setup you are using? Which version of the carbon-fields you are using the `carbon-fields-plugin` or the other? Additionally if possible please describe the installation process step by step.

**Comment by drzraf** [comment]
In my specific case, the source of the problem is the use of Bedrock. Composer dependencies live in `/vendor/` directory, distinct from the `/web` directory where WP and plugins lives. `/vendor` is outside webserver root.

**Comment by lstoyanoff** [comment]
Hi, sorry for the late response, I agree with your point and currently it is not possible to install it from the root bedrock composer. You could either install it as a theme dependency or use the CF plugin zip package -- https://docs.carbonfields.net/#/plugin-quickstart?id=without-composer

**Comment by ju1ius** [comment]
@drzraf see [my comment](https://github.com/htmlburger/carbon-fields/issues/805#issuecomment-683131100) on #805 for a workaround.
