### ISSUE TITLE
Metabox not visible on post-new.php screen

### ISSUE THREAD

**Issue by adamiscoding** [htmlburger/carbon-fields#815]
## Version

  - Carbon Fields: 3.1.1
  - WordPress: 5.2.3
  - PHP: 7.3.13

## Expected Behavior
Metabox should show when adding new post (or CPT) and when editing existing post (CPT)

## Actual Behavior
Metabox shows only on existing posts

## Container definition
```php
    Container::make('post_meta', 'hg_post_meta_side', 'HG Meta')
      ->where('post_type', 'IN', $postTypes)
      ->set_context('side')
      ->add_fields(
        [
          Field::make(
            'image',
            'mobile_featured_image',
            'Mobile featured image'
          ),
          Field::make(
            'text',
            'short_title',
            'Short title'
          ),
          Field::make(
            'date',
            'last_updated_date',
            'Last updated date'
          ),
        ]
      );
```

## Steps to Reproduce the Problem

  1. Go to Post and add new.
  2. No metabox is HG meta metabox is visible

**Comment by jorostoyanov** [comment]
Hi @adamiscoding 

Can you post the entire file that contains this container definition? I would like to see how you define `$postTypes`

**Comment by jorostoyanov** [comment]
Based on the issue description, it appears that you are registering post meta container before your post types are being registered.

Feel free to re-open the issue, so we can further debug.

**Comment by adamiscoding** [comment]
I'm still experiencing this today. Is it impossible to make it work on post-new screen? I have tried everything and it even doesn't work with built in post types. 

It works only after post is published and you reload the page. 
Metabox is only visible when I remove `->where()` condition.

**Comment by jorostoyanov** [comment]
Hi @adamiscoding 

Please send me the code that registers the custom post types and the fields, so I can debug
