### ISSUE TITLE
Groupping data of all fields in add_tab as a single array. It's possible?

### ISSUE THREAD

**Issue by viterzbayraku** [htmlburger/carbon-fields#816]
Complex fields - good solution. After using this type of fields I have serialized array of some group of data. But it is very inconvenient that the tabs need to be opened individually through a click in tabbed-horizontal layout. And I do not want array like:

```
array (
    0 => array (
        '_type' => 'photograph',
        'caption' => 'Lorem Ipsum',
        'image' => 'http://example.com/wp-content/uploads/2012/12/Jellyfish.jpg',
    ),
    1 => array (
        '_type' => 'movie',
        'length' => '1:56',
        'title' => 'Dolor sit amet',
        'video' => 'http://example.com/wp-content/uploads/2012/12/video_new.mp4',
    ),
    2 => array (
        '_type' => 'photograph',
        'caption' => 'Consectetur adipiscing elit',
        'image' => 'http://example.com/wp-content/uploads/2012/12/Koala.jpg',
    ),
)
```
And instead want have an array like:

```
array (
    'photograph' => array (
        'caption' => 'Lorem Ipsum',
        'image' => 'http://example.com/wp-content/uploads/2012/12/Jellyfish.jpg',
    ),
    'movie' => array (
        'length' => '1:56',
        'title' => 'Dolor sit amet',
        'video' => 'http://example.com/wp-content/uploads/2012/12/video_new.mp4',
    )
)
```

 How I can use add_tab() or any other grouping solution instead and save data of all fields inside as an array like in complex fields? Thank you.

**Comment by jorostoyanov** [comment]
Hi @viterzbayraku 

> But it is very inconvenient that the tabs need to be opened individually through a click in tabbed-horizontal layout. 

That's how tabs are supposed to work. Alternatively, you can skip the tabs and show the fields in a single complex group.

> How I can use add_tab() or any other grouping solution instead and save data of all fields inside as an array like in complex fields? Thank you.

You can create a helper function that will accept the data returned for the complex field and return it in the format you've described. The function will look like this:

```
function app_format_complex_data( $items ) {
	$formatted_items = [];

	foreach ($items as $item) {
		$item_type = $item['_type'];
		unset($item['_type']);

		$formatted_items[ $item_type ] = $item;
	}

	return $formatted_items;
}
```

**Comment by viterzbayraku** [comment]
@jorostoyanov thank you for your answer.
I will try explain my problem more detailed.
Complex fields - cool solution. I like possibility to make an array of fields inside it.
I'm using ->set_duplicate_groups_allowed( false ), because do not want any duplications.
But I want open all tabs at once without clicking to Add button on the bottom of this complex field. Like in add_tabs() function. This is possible?

**Comment by viterzbayraku** [comment]
@jorostoyanov for me is very important have way to combine group of fields to one array and use ->set_datastore( new Serialized_Post_Meta_Datastore() ) for it. That's way working only with complex fields. But this complex fields creates unnecessary feature with opening tab after clicking of "Add" button instead of opening them at once.

**Comment by jorostoyanov** [comment]
Based on your description, you want to use the tabs as simple groups of fields and return them as such.

This is not currently possible, but is worth exploring in future.

**Comment by viterzbayraku** [comment]
@jorostoyanov can I make some custom code to make it possible as extension of carbon fields?

**Comment by viterzbayraku** [comment]
@jorostoyanov tabs in Complex Fields opening only after clicking to Add button. Is there any way to open all these tabs immediately without having to click a button?

**Comment by lstoyanoff** [comment]
@viterzbayraku You can try adding predefined complex groups -- https://docs.carbonfields.net/#/fields/complex?id=adding-predefined-complex-groups

**Comment by viterzbayraku** [comment]
> @viterzbayraku You can try adding predefined complex groups -- https://docs.carbonfields.net/#/fields/complex?id=adding-predefined-complex-groups

Thank you. My own solution is:

```
    public function load( Field $field ) {
		global $post;
        $key = $this->get_key_for_field( $field );
        $value = get_post_meta( $post->ID, $key, true );
        
        // predefined fields groups list
        $passport_el = array("name", "desc", "from", "type", "internal", "saved", "renew", "content", "fund", "more");
        $toremove = array();
        if($value && is_array($value)){
            foreach($value as $el){
                $toremove[] = $el['value'];
            }
            $passport_el = array_merge(array_diff($passport_el, $toremove));
        }else{
            $value = array();
        }
        foreach($passport_el as $el){
            array_push($value, array('value'=>$el));
        }
       
        return $value;
    }
```
