### ISSUE TITLE
Can't see the taxonomy custom CPT in gutenberg mode

### ISSUE THREAD

**Issue by madebyaris** [htmlburger/carbon-fields#832]
## Version

  - Carbon Fields: 3.1.12
  - WordPress: 5.3.2
  - PHP: 7.2.19

## Expected Behavior
The taxonomy should be visible on tab document

## Actual Behavior
The taxonomy didn't show on the document.

## Container definition
```php
`        $newshub = new CPT(
            array(
                'post_type_name' => 'newshub',
                'singular' => 'Newshub',
                'plural' => 'Newshub',
                'slug' => 'newshub',
            ),
            array(
                'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'page-attributes' ),
                'menu_position' => 4,
                'public' => true,
                'has_archive' => 'newshub',
                'show_in_rest' => true,
                'capability_type' => 'post',
            )
        );

        $newshub->menu_icon( 'dashicons-format-aside' );

        // Register the taxonomy (this will be the city).
        $newshub->register_taxonomy(
            array(
                'taxonomy_name' => 'nhcategory',
                'singular' => 'category',
                'plural' => 'categories',
                'slug' => 'newshub-category',
            )
        );`
```

## Steps to Reproduce the Problem
- Click add new CPT

## Comments
There's no error, checked via WP_DEBUG_LOG & Query monitor

**Comment by jorostoyanov** [comment]
Hi @madebyaris 

Apologies for the late reply.

This doesn't seem to be an issue with Carbon Fields, but rather with the way you are setting up new taxonomies.

I see you are using a `CPT` class wrapper, which might be the reason why the taxonomy is not visible.

Try using the native `register_taxonomy` :-)
