### ISSUE TITLE
carbon_get_post_meta and PHP warning from IDE

### ISSUE THREAD

**Issue by klocus** [htmlburger/carbon-fields#834]
## Version

  - Carbon Fields: ^3.1
  - WordPress: 5.3.2
  - PHP: 7.3

## Expected Behavior
No warning about `carbon_get_post_meta`.

## Actual Behavior
On Visual Studio Code and phpStorm I see warnings about `carbon_get_post_meta` if I use it with `echo`. 

```
Argument '1' passed to echo() is expected to be of type string, void given
```

Screenshot: https://snipboard.io/xcJD3g.jpg

**Comment by lstoyanoff** [comment]
Hi, I've tested on VSCode with both PHP Intelephense and PHP IntelliSense Extensions and I can't reproduce the issue. Can you please provide more details about the environment you're using?

**Comment by klocus** [comment]
Hey! I'm using "PHP Tools for Visual Studio Code". https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode - maybe that's the reason.

**Comment by lstoyanoff** [comment]
Hey, I've tested the extension you're using and CF doesn't currently support such strict type hinting which is required in order for the extension to properly validate the code. I guess in future type hinting will be added both for function parameters and return values.
