### ISSUE TITLE
BUG! Comments meta ID always 0

### ISSUE THREAD

**Issue by 4selin** [htmlburger/carbon-fields#846]
## Version

  - Carbon Fields: 3.1.13
  - WordPress: 5.3.2
  - PHP: 7.2.24

## Expected Behavior
Unique ID for every comment_meta entry

## Actual Behavior
wp_commentmeta.meta_id = 0 for every comment_meta field
Screenshot https://yadi.sk/i/okzwWF1wNX_vOA

## Container definition
```php
Container::make( 'comment_meta', __( 'Comment Information' ) )
         ->add_fields( array(
	         Field::make( 'text', 'crb_comment_title', __( 'Заголовок отзыва' ) ),
	         Field::make( 'text', 'crb_comment_disease', __( 'Заболевание' ) ),
	         Field::make( 'text', 'crb_comment_treatment_duration', __( 'Длительность применения' ) ),
	         Field::make( 'text', 'crb_comment_side_effects', __( 'Побочные действия' ) ),
	         Field::make( 'media_gallery', 'crb_comment_gallery', __( 'Фотографии' ) )
         ) );
```

## Steps to Reproduce the Problem

Save comment fields using container from definition

**Comment by lstoyanoff** [comment]
Hi, I've tested your `comment_meta` definition and it works fine for me: 
![image](https://user-images.githubusercontent.com/35492381/73919106-8f6bf780-48cb-11ea-87a1-1dc05f54c9e5.png)

Internally, Carbon Fields is using [add_metadata()](https://developer.wordpress.org/reference/functions/add_metadata/) to save the values in the database. Please make sure that there aren't any modifications to the wp hooks in the `add_metadata()` function in the theme that you're using.

Alternatively, you can test it out on a clean WP installation with twentynineteen or twentytwenty theme.
