### ISSUE TITLE
Useless mysql queries

### ISSUE THREAD

**Issue by nasyrov** [htmlburger/carbon-fields#85]
Hi guys,

Thanks for a nice plugin!
I was wondering why these 3 db queries (see the attachment) fire on every admin page, is there any way to prevent them and execute only when it's needed?

![screen shot 2016-09-03 at 10 55 43 am](https://cloud.githubusercontent.com/assets/1330477/18224177/33bf89f0-71c5-11e6-9046-855e6be3dd1d.png)

Thanks,
E

**Comment by emohamed** [comment]
Hi @nasyrov 

I did a quick fix for the problem in bbb99b5b45bfc604e04fbd21f7db543cf9b23105

I'll have the change reviewed and merged to master today. 

Thanks!

**Comment by m1r0** [comment]
The problem with the field initialization should be fixed in https://github.com/htmlburger/carbon-fields/pull/88/commits/785e613b06e94c95767998251999c5b51842410d.
