### ISSUE TITLE
Why does the site https://wordpress.org/plugins/carbon-fields/ that the plugin is closed? Will it affect anything?

### ISSUE THREAD

**Issue by Ercogx** [htmlburger/carbon-fields#853]

**Comment by emohamed** [comment]
Here is a blog post we wrote about this: https://carbonfields.net/2017/07/31/carbon-fields-distribution-woes/

This is also important: https://make.wordpress.org/plugins/2016/03/01/please-do-not-submit-frameworks/

You can still get Carbon Fields as a plugin from here: https://carbonfields.net/release-archive/

TLDR: Carbon Fields doesn't do anything on it's own, so it shouldn't be distributed as a plugin. You should use Composer to get it. 

> Will it affect anything?

You should be fine, however you can't upgrade the plugin from the WordPress dashboard. At some point WordPress core upgrade might be incompatible with your Carbon Fields version. At that point, you'd need to either disable Carbon Fields, use our plugin packages, or switch to using Composer package.
