### ISSUE TITLE
[Feature] Association Field - Search on title OR meta

### ISSUE THREAD

**Issue by TheYaXxE** [htmlburger/carbon-fields#859]
## Version

  - Carbon Fields: 3.1.14
  
## Expected Behavior
Be able to modify the search query on the Association Field to search on the defaults `s` OR meta-data. Useful when searching on custom post-types or WooCommerce product (sku).

## Actual Behavior
By default results are found by searching title, content or excerpt.
The `carbon_fields_association_field_options_{name}_{type}_{subtype}` filter allows you do modify the query arguments but the relation between the defaults `s` and the `meta_query` will always be 'AND' when it really should be using 'OR'.

## Comments
I've tried to achieve this in many ways, by using filters like `carbon_fields_association_field_options`, `pre_get_posts` etc, with no luck. By using `pre_get_posts` I successfully got it to search on title OR meta, but I was receiving a lot of duplicate posts, resulting in over 40.000 results with only 2020 actual posts.

**Comment by jorostoyanov** [comment]
Hi @TheYaXxE 

Apologies for the late reply!

The request you are asking for has nothing to do with Carbon Fields, but rather with the way WordPress query works.

By default, WordPress uses AND join when using `s` and `meta_query` arguments.

However, after a quick search I came up with the following StackOverflow answer, which seems to solve the issue -- https://wordpress.stackexchange.com/a/208939

Hope this helps!
