### ISSUE TITLE
How to correctly add fields to a record type attachments - image

### ISSUE THREAD

**Issue by sergeyterr** [htmlburger/carbon-fields#865]
## Version

  - Carbon Fields: 3.0
  - WordPress: 5.3.2
  - PHP: 7.3

## Expected Behavior
When adding fields to an attachment record type, the fields appear on the record type editing page

## Actual Behavior
Only the container appears on the edit page

## Container definition
```php
// Please add your entire container defintion here so issues
// are easy to reproduce
add_action( 'carbon_fields_register_fields', 'register_fields');
function register_fields() {
  Container::make( 'post_meta', __( 'Image Options' ) )
    ->where( 'post_type', '=', 'attachment' )
    ->add_fields( [
      Field::make( 'textarea', 'crb_text', 'Text Field' )
    ] );
}
```

## Steps to Reproduce the Problem

  1. I do not see the field being created on the record type edit page.

**Comment by jorostoyanov** [comment]
Hi @sergeyterr 

I have just tested this and the fields are being shown on the "Edit more Details" page.

Feel free to re-open the issue if the problem persists :-)

**Comment by hay** [comment]
Can confirm this works. It's a bit of a nuisance that the fields are hidden under 'Edit more details', but i'm very glad that there's an option to add custom fields to attachments.

Maybe one other small point: it might be useful to also include the fact that it's possible to add custom fields to attachments in the documentation, i couldn't find it.
