### ISSUE TITLE
Does unique Container's title support translation?

### ISSUE THREAD

**Issue by daviedR** [htmlburger/carbon-fields#87]
Hi guys, in your documentation you mentioned that container's `$title` parameter is "Unique title of the container." Does it support translation? I meant I want to have a meta box with "Page Options" title, but I want it possible to be translated into other languages too.

**Comment by m1r0** [comment]
Hi @daviedR,

You can pass the title string through a build in WordPress translation function, for example:

```
Container::make( 'post_meta', __('Page Options', 'your-domain') )
```

For more info, checkout [I18n for WordPress Developers](https://codex.wordpress.org/I18n_for_WordPress_Developers).
