### ISSUE TITLE
JS BUILD ERROR - Error: Your Refract aperture didn't return an observable entity in WithDispatch(WithDispatch(o)) (component).

### ISSUE THREAD

**Issue by sweetappleuk** [htmlburger/carbon-fields#870]
## Version

  - Carbon Fields: 3.1.15
  - WordPress: 5.3.2
  - PHP: 7.2

## Expected Behavior
Running npm run build or npm run start should create valid JS with no errors.

## Actual Behavior
On running the npm task multiple console errors are seen in JS Console error from /wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0

For example on the Theme Options page I see
TypeError: Object(z.fromEvent) is not a function. (In 'Object(z.fromEvent)(window,"scroll")', 'Object(z.fromEvent)' is an instance of Object

On a post add/edit page with fields defined in teh JS Console I see

Error: Your Refract aperture didn't return an observable entity in WithDispatch(WithDispatch(o)) (component).

## Container definition
use Carbon_Fields\Container;
use Carbon_Fields\Field;

function makegroup_carbon_fields_load()
{
  require_once( 'carbon-fields/vendor/autoload.php' );
    Carbon_Fields\Carbon_Fields::boot();
}
add_action( 'after_setup_theme', 'makegroup_carbon_fields_load' );

function makegroup_carbon_fields_attach_theme_options()
{
    Container::make( 'theme_options', __( 'Theme Options', 'crb' ) )
             ->add_fields( array(
                 Field::make( 'text', 'crb_text', 'Text Field' ),
             ) );
}
add_action( 'carbon_fields_register_fields', 'makegroup_carbon_fields_attach_theme_options' );

## Steps to Reproduce the Problem
Follow instructions from CONTRIBUTING.md. No errors are seen during install or npm run start

Installing the Library "normally" works as expected with no JS errors in the console.

## Comments
_Please add any other comments here_

**Comment by MDSilviu** [comment]
@sweetappleuk I have the same issues, where you able to fix them?

**Comment by sweetappleuk** [comment]
I didn't have this issue with the latest version of the plugin. Not sure if that's because of changes in my local environment or fixes in this repo.

However I did have a different issue when trying to run npm run build; please see https://github.com/htmlburger/carbon-fields/pull/898

**Comment by dhalucario** [comment]
I can mostly fix errors like these when running `npm install` and using a node version >=10

**Comment by jorostoyanov** [comment]
As @dhalucario suggested -- this can be fixed by using an older version of Node (=10)

Supporting new versions of NodeJS is on our roadmap :-)

**Comment by kennydude** [comment]
I've been trying to resolve this myself, and it seems setting `refract-callbag` to `4.0.0` clears it, although with a lot of warnings so somethings changed with how those are put together.

**Comment by kennydude** [comment]
In fact on top of doing that, and using Node version 10.0.0 doesn't seem to clear these issues anymore :( I know nothing much about React itself to even untangle how Carbon Fields is put together to fix it,
