### ISSUE TITLE
Gutenberg Blocks issue on WordPress 5.4

### ISSUE THREAD

**Issue by devnostic** [htmlburger/carbon-fields#871]
## Version

  - Carbon Fields: 3.1.15
  - WordPress: 5.4
  - PHP: 7.3.11

## Expected Behavior
Gutenberg blocks would show in admin page editor

## Actual Behavior
Getting an error stating 
Your site doesn’t include support for the "carbon-fields/{block}" block. You can leave this block intact or remove it entirely.

## Container definition
```php
// Please add your entire container defintion here so issues
// are easy to reproduce
```

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Comments
_Please add any other comments here_

**Comment by devnostic** [comment]
I found a quick hack fix for now, but I had to comment out these lines in wp-includes/js/dist/blocks.js

// if (!isValidIcon(settings.icon.src)) {
// console.error(‘The icon passed is invalid. ’ + ‘The icon should be a string, an element, a function, or an object following the specifications documented in https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#icon-optional’);
// return;
// }

Looks like the icon is not getting set correctly for blocks.

**Comment by jorostoyanov** [comment]
@devnostic 

This error appears when you have a misconfiguration with your theme / plugin and specifically with the block registration.

Apart from that, there is a new WordPress version - 5.5.3

Feel free to re-open the issue if the problem persists :-)
