### ISSUE TITLE
Rich Text Fields Media Upload Button

### ISSUE THREAD

**Issue by ulziibat-n** [htmlburger/carbon-fields#873]
## Version

  - Carbon Fields: v3.1.15
  - WordPress: 5.4
  - PHP: 73

## Expected Behavior

Hello. I'm new customer from ACF. I need to disable upload media button of Rich Text field. How can i disable it. I didn't found any solution from you documentation and from github. 

Thanks.

**Comment by lstoyanoff** [comment]
Hey @ulziibat-n,
From [v3.1.15](https://github.com/htmlburger/carbon-fields/releases/tag/v3.1.15) you can now use `set_settings` method on the Rich Text field which accepts the same arguments as the [WP Editor Settings](https://developer.wordpress.org/reference/classes/_wp_editors/parse_settings/). For example:

```php
```
