### ISSUE TITLE
carbon_set_{container_type}( [$id,] $field_name, $value ) for associate fields

### ISSUE THREAD

**Issue by winston0410** [htmlburger/carbon-fields#878]
## Version

  - Carbon Fields: 3.x
  - WordPress: 5.4
  - PHP: 7.4

## Expected Behavior
I expect carbon_set_{container_type}( [$id,] $field_name, $value ) can help me set value for an associate field.

## Actual Behavior
carbon_set_{container_type}( [$id,] $field_name, $value ) does not set value for an associate field. I have inputted parameter according to doc, and I have double checked that my association field is not inside a complex field.

I have tried this function on text field and they are working perfectly fine.

## Container definition
```php
add_action( 'carbon_fields_register_fields', 'lesson_details' );

function lesson_details (){
    Container::make( 'post_meta', __('Lesson memo', 'smartgo') )
        ->where( 'post_type', '=', 'lesson' )
        ->add_fields( array(
            Field::make( 'text', 'lesson_memo', __( 'What has been taught in this lesson' ) ),
            
            Field::make( 'association', 'attendance', __('Attendance: students who attended', 'smartgo') )
            ->set_width( 50 )
            ->set_required( true )
            ->set_types( array(
        array(
            'type'      => 'user',
        )
        ) )
        ->set_min( 1 ),
        
            Field::make( 'association', 'leave', __('Leave: students who applied leave', 'smartgo') )
            ->set_width( 50 )
            ->set_types( array(
        array(
            'type'      => 'user',
        )
        ) )
            
        ) );
}

```

## Steps to Reproduce the Problem
 The post id is 41; the value I want to set is '5'
  1.  carbon_set_post_meta( 41, 'leave', 5 );
Nothing is changed in my database with this function

## Comments
_Please add any other comments here_

**Comment by lstoyanoff** [comment]
Hey @winston0410,
The association field value format is an array of arrays -- (https://docs.carbonfields.net/#/fields/association?id=value-format)  -- and you should provide the same value format when you're updating the field value. In your case:
```php
$new_value = array(
    array(
        'value' => 'user:user:5',
        'type' => 'user',
        'subtype' => 'user',
        'id' => '5'
    ),
);
carbon_set_post_meta( 41, 'leave', $new_value );
```
