### ISSUE TITLE
set_context(‘side’) not working with Gutenberg in default Post Type

### ISSUE THREAD

**Issue by weogrim** [htmlburger/carbon-fields#880]
## Version

  - Carbon Fields: 3.1
  - WordPress: 5.4
  - PHP: 7.4

## Expected Behavior
When I use `->set_context('side')` on default Post the meta box should appear on the right... 

## Actual Behavior
... but it appear below Gutenberg editor. 

## Container definition
`function.php` in custom theme. 
```php
<?php
require_once( __DIR__ . '/vendor/autoload.php' );
use Carbon_Fields\Container;
use Carbon_Fields\Field;

//Configure Carbon Fields
\Carbon_Fields\Carbon_Fields::boot();

//Custom Data - Carbon
Container::make( 'post_meta', 'Custom Data' )
->set_context( 'side' )
->where( 'post_type', '=', 'post')
->add_fields([
    Field::make( 'text', 'crb_phone_number', __( 'Phone Number' ) ),
]);

//Film Meta - Manual
add_action( 'add_meta_boxes', 'cd_meta_box_add' );
function cd_meta_box_add(){
    add_meta_box( 'film_metabox', 'Film Meta', 'cd_meta_box_cb', 'post', 'side', );
}
function cd_meta_box_cb()  {  
  echo 'What you put here, show\'s up in the meta box';     
}  

```

## Steps to Reproduce the Problem

  1. Install fresh Wordpress
  1. Install Carbon from Composer in custom theme (theme is clean, just some scss and templates, CPT declaration)
  1. Declare CPT
  1. Add code above to functions.php
  1. When you go to Posts, Container will be below, when go to CPT will be on side. 

## Comments
All working fine, when I change post_type for Custom Post Type. 

When I declare metabox manually by `add_action`, `add_meta_boxes` and `add_meta_box` works all well in both default posts and custom post type.

Below links to two screens. One from Default Post, one from Anime CPT. Custom data is Carbon Fields and Film Meta is manual method. In both screens I use the same code, just change post_type slug. 

Screen 1: https://imgur.com/a/jdHO8w9
Screen 2: https://imgur.com/a/MpZRM3b

Thanks for help!

**Comment by lstoyanoff** [comment]
Hey @weogrim,
You haven't declared the Carbon Fields Containers at the right  WP Hook and this might cause issues. As shown in the docs -- https://docs.carbonfields.net/#/quickstart -- container declarations should be done in the `carbon_fields_register_fields` WordPress Action Hook. Could you please try changing your code to match this pattern and then write back if the issue persist.
