### ISSUE TITLE
File field not show file after save/update

### ISSUE THREAD

**Issue by AdsonCicilioti** [htmlburger/carbon-fields#883]
## Version

  - Carbon Fields: 3.1.18
  - WordPress: 5.4
  - PHP: 7.3.16

## Expected Behavior
That the file appears in the file field after saving / updating as it appears when we put it in the field before saving / updating.

## Actual Behavior
The thumbnail / Name / Link of the file disappears from the field after saving / updating the post.

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

require_once __DIR__ . '/vendor/autoload.php';
	\Carbon_Fields\Carbon_Fields::boot();

Container::make( 'post_meta', 'Custom Data' )
	->where( 'post_type', '=', 'ca_cert' )
	->add_fields(
		array(
			Field::make( 'date', 'crb_emission', __( 'Emission', 'ca_cert' ) )
			->set_required( true ),

			Field::make( 'date', 'crb_validity', __( 'Validity', 'ca_cert' ) )
			->set_required( true ),

			Field::make( 'text', 'crb_equipment', __( 'Equipment', 'ca_cert' ) )
			->set_required( true ),

			Field::make( 'text', 'crb_locate', __( 'Locatization', 'ca_cert' ) )
			->set_required( true ),

			Field::make( 'association', 'crb_customer', __( 'Customer', 'ca_cert' ) )
			->set_required( true )
			->set_types(
				array(
					array(
						'type'      => 'post',
						'post_type' => 'post',
					),
				)
			)
			->set_min( 1 )
			->set_max( 1 ),

			Field::make( 'file', 'crb_file', __( 'File', 'ca_cert' ) )
			->set_type( array( 'doc', 'pdf' ) )
			->set_value_type( 'url' )
			->set_required( true ),

		)
	);
```

## Steps to Reproduce the Problem

1. Choose and send a media to the field.
2. See that the thumbnail and description are present 
![image](https://user-images.githubusercontent.com/6278398/79982699-1d905c80-847d-11ea-8fbd-b45f7dc0c3bb.png)

3. Save the Post Type
4. and See that the file (thumbnail, description and link) does not appear anywhere. Field is Empty 
![image](https://user-images.githubusercontent.com/6278398/79982784-37ca3a80-847d-11ea-8c40-d9d3a4fa0093.png)

## Comments
Nothing for the moment

**Comment by AdsonCicilioti** [comment]
@yuliyan, u can see this?

Sorry for inconvinience.

**Comment by yuliyan** [comment]
@AdsonCicilioti unfortunately, I'm not very experienced with CarbonFields and I can't help with your problem here. Also, I'm no longer part of htmlBurger team and I can't either redirect your query to someone else.

The team is most likely slowed down due to the quarantine, but I'm sure you'll get back from them soon.

**Comment by jorostoyanov** [comment]
Fixed here -- https://github.com/htmlburger/carbon-fields/commit/4aac21d3c3cc537e2c02c5f3a8c094a6567d3dac

You will be able to use in the next release!

**Comment by AdsonCicilioti** [comment]
Nice work @jorostoyanov !

**Comment by dark37rus** [comment]
I have the same problem on version 3.2.2
Version wordpress 5.6.2
