### ISSUE TITLE
cf.core is undefined when upgrade to WP 5.4.1

### ISSUE THREAD

**Issue by cmtinz** [htmlburger/carbon-fields#888]
## Version

  - Carbon Fields: 3.1.18
  - WordPress: 5.4.1
  - PHP: 7.2

## Expected Behavior
CF fields and blocks controls available in admin page. No error messages shown in browser console.

## Actual Behavior
The declared blocks with Carbon Fields are not visible in the available blocks list. The fields controls do not exist. "can't access property "initialize", cf.core is undefined" appears in the browser console.

### Fields code
```php
Container::make( 'post_meta', __('Opciones de Home', 'icon'))
    ->where( 'post_id', 'IN', array_values( pll_get_post_translations( get_option('page_on_front') ) ) )
    ->add_fields( array(
        Field::make( 'complex', 'post_slider', 'Agrega un slide' )
        ->add_fields( array(
            Field::make( 'select', 'starred_post' )
                ->add_options( 'get_post_list' ),
            Field::make( 'image', 'starred_image', __('Imagen del slider', 'icon') )
                ->set_help_text( __('Dimensiones requeridas: 850x360.', 'icon') )
                ->set_value_type( 'id' )
        )),
        Field::make( 'association', 'starred_news', __( 'Novedades destacadas' ) )
                ->set_max(3)
                ->set_types( array(
                    array(
                        'type' => 'post',
                        'post_type' => 'post',
                    )
                ))
        ));
```
### Blocks code
```php
Block::make( __( 'Hero' ) )
    ->set_inner_blocks( true )
    ->set_inner_blocks_template( array(
        array( 'core/heading' ),
        array( 'icon/image' )
    ) )
    ->set_inner_blocks_template_lock( 'all' )
    ->set_render_callback( function ( $fields, $attributes, $inner_blocks ) {

    } );
```

## Steps to Reproduce the Problem

  1. Install Carbon Fields to the theme using Composer.
  2. Upgrade Wordpress from 5.3 to 5.4.1.

## Comments
The JS error comes from this line in posts.php or edit.php. It does no matter whether or not you have blocks or fields declared. Downgrade Wordpress solves the problem.

```html
<script>
    if ( typeof cf.core.initialize === 'function' ) {
        cf.core.initialize();
    }
</script>
```

**Comment by jorostoyanov** [comment]
Hi @cmtinz 

I have tried to reproduce the bug on a fresh install with, however, it didn't throw any errors.

I see you are using the "polylang" plugin. Can you try to disable it and check if the bug persists?

**Comment by cmtinz** [comment]
Finally, I realized that the problem came from the fact that the theme directory was symbolic link. It confused, the Wordpress’  content_url() function and caused some scripts were not loaded.

So, it was my setup. Sorry.
