### ISSUE TITLE
Does post_template argument not work with page templates?

### ISSUE THREAD

**Issue by luisaureliocasoni** [htmlburger/carbon-fields#891]
## Version

  - Carbon Fields: 3.1.20 (installed with component of a theme - not a plugin)
  - WordPress: 5.4.1
  - PHP: 7.3
  - Classic Editor plugin installed

## Expected Behavior
The container appears on the page editor on a page with a slug named `o-curso`, using a template called `page-o-curso.php`, where the template works as assigned. 

## Actual Behavior
The page fields shows quiclkly on page load, but the container dissapears, and I not edit the page.

## Container definition
```php
Container::make('post_meta', 'O Curso - Textos')
        ->where( 'post_type', '=', 'page' )
        ->where( 'post_template', '=', 'page-o-curso.php' )
        ->add_tab( __( 'Profile' ), array(
            Field::make( 'text', 'crb_first_name', __( 'First Name' ) ),
            Field::make( 'text', 'crb_last_name', __( 'Last Name' ) ),
            Field::make( 'text', 'crb_position', __( 'Position' ) ),
        ) )
        ->add_tab( __( 'Notification' ), array(
            Field::make( 'text', 'crb_email', __( 'Notification Email' ) ),
            Field::make( 'text', 'crb_phone', __( 'Phone Number' ) ),
) );
```

## Steps to Reproduce the Problem

  1. Install Carbon Fields;
  2. Intialize the Carbon Fields using the documentation instructions;
  3. Put this container definition inside a function for a register fields;
  4. Access the editor for a page with a slug `o-curso`.

## Comments
The `post_template` argument works only for a posts?

**Comment by lstoyanoff** [comment]
Hey @luisaureliocasoni,
I'm afraid that in your case the page template is the default page template. You can use the following approach to implement a condition display by page slug.

```php
Container::make( 'post_meta', 'O Curso - Textos' )
    ->where( 'post_type', '=', 'page' )
    ->where( 'post_id', 'CUSTOM', function( $post_id ) {
        $slug = get_post_field( 'post_name', $post_id );
        return $slug === 'o-curso';
    } )
    ->add_fields( array(
        // your fields
    ) );
```

**Comment by luisaureliocasoni** [comment]
> 
> 
> Hey @luisaureliocasoni,
> I'm afraid that in your case the page template is the default page template. You can use the following approach to implement a conditional display by page slug.
> 
> ```
> Container::make( 'post_meta', 'O Curso - Textos' )
>     ->where( 'post_type', '=', 'page' )
>     ->where( 'post_id', 'CUSTOM', function( $post_id ) {
>         $slug = get_post_field( 'post_name', $post_id );
>         return $slug === 'o-curso';
>     } )
>     ->add_fields( array(
>         // your fields
>     ) );
> ```

This solution works and is pretty! Thanks @lstoyanoff.
