### ISSUE TITLE
Is it possible two have multiple "theme_options" containers in the same page?

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [htmlburger/carbon-fields#894]
Hello,

Is it possible to have two or more `theme_options` containers in the same page to get something like this or at least do something that could be similar to this result?
![2-theme-options](https://user-images.githubusercontent.com/8193404/83362298-9204c800-a366-11ea-82a0-98053809b523.png)

I've already tried the `separator` field but it's not what I want because it's displayed in the same container. I want something that looks like it's a whole new section disconnected from the first

**Comment by jorostoyanov** [comment]
Hi @pablo-sg-pacheco 

No, that's not currently possible.

However, you can achieve similar effect by using tabs - https://docs.carbonfields.net/#/containers/tabs
