### ISSUE TITLE
Option to markup fields with the Gutenberg "Rich text" options for inline text

### ISSUE THREAD

**Issue by peroyomas** [htmlburger/carbon-fields#895]
## Version

  - Carbon Fields: 3.1.20
  - WordPress: 5.4.1
  - PHP: 7.3.11

## Comments
I'm not sure if this is currently possible in some way, yet I'm not sure of another place I can ask, so I ask here: I would like that in the plugin Fields, either on an existing one or a new one, we can have the option to style it with "Rich text", but not with the TinyMCE UI as it currently works for the Richtext field, but with the Gutenberg tools of the same name (the one that lets you markup inline stuff like `<strong>` and `<em>` and any extension by the user) Mainly because I think TinyMCE is too much for some cases, but the Gutenberg Rich Text tools is othewise perfect.

**Comment by lstoyanoff** [comment]
Hey @peroyomas,
From v3.1.15 you can use `set_settings` method on the Rich Text field which accepts the same settings argument as the [WP Editor Settings](https://developer.wordpress.org/reference/classes/_wp_editors/parse_settings/) and directly modify the TinyMCE toolbars. For example you can remove the media buttons and show only bold and italic buttons:

```php
<?php
Container::make('theme_options', 'Theme Options')
  ->add_fields([
    Field::make('rich_text', 'text', 'Text)
      ->set_settings([
        'media_buttons' => false,
        'tinymce' => [
          'toolbar1' => 'bold,italic',
        ],
        'quicktags' => false,
      ]),
  ])


```
