### ISSUE TITLE
How to show Carbon Fields in Tickbox modal

### ISSUE THREAD

**Issue by mihdan** [htmlburger/carbon-fields#908]
## Version

  - Carbon Fields: 3.1.20
  - WordPress: 5.4.2
  - PHP: 5.6

## Comments
For example:

![](https://cloud.githubusercontent.com/assets/7590968/18725041/fdd02a7e-803e-11e6-825a-9cbc4f2e0db1.png)

**Comment by jorostoyanov** [comment]
Hi @mihdan 

This is currently labeled under "Feature" enhancements. There is an active issue here -- https://github.com/htmlburger/carbon-fields/issues/133

However, it is not on the roadmap for now.
