### ISSUE TITLE
Saving theme options defaults on activation

### ISSUE THREAD

**Issue by halvardos** [htmlburger/carbon-fields#91]
**How it works:**
Human interaction is needed to press save on the theme options page to make default values available to `carbon_get_theme_option()`

**How i would like it to work:**
Default values should be available to the developer even with no human interaction on the admin panel.

**Use case:**
A value set in theme options is needed for specific functionality in the theme to work.
The developer wants to run the theme through Continuos Integration.
CI tests break because options value is not available without a save to the theme options page. 

There are a lot of other use cases regarding dev env. staging servers etc. But i think this illustrates the point well.

I could create a PR if someone pointed me in the right direction for this.
I _think_ this only makes sense to try and achieve on theme options?

**Comment by Jeger** [comment]
Seeing as the `carbon_get_theme_option()` returns false and not null 
you cant use the new _null coalescing_ operator either.

`<?= carbon_get_theme_option('unset_option_field') ?? 'default_value' ?>`

**Comment by m1r0** [comment]
Hey @Jeger,

Good suggestion, we will look for a solution for this in a future version.
Maybe the best approach will to make the Field instances public so the getter functions can pull the default value. Suggestions are welcomed.

**Comment by Jeger** [comment]
I will look into how it works later next week. Maybe there is a way to do this for all fields optionally when getting the value. But i really have not looked at how / when you store the default values.

I really think that this improvement would fit very nicely with the developer focus of this plugin :)

**Comment by nasyrov** [comment]
Maybe it's better to implement it inside the actual function, so it will look like:
`
carbon_get_theme_option($option_name, $default = false)
`

And in Jeger case it will look like:
`
<?= carbon_get_theme_option('unset_option_field', 'default_value') ?>
`

Thoughts?

**Comment by Jeger** [comment]
Well, two things strike me about that solution.
The first is, what if i want to use the default more than one place? A theme option would be a good example of something that you would often want to use multiple places. So then you would have to create global variables.

The second is that this functionality kinda exists in php if you just return undefined instead of false.
`<?= carbon_get_theme_option('unset_option_field`) ?? 'default_value' ?>`

**Comment by nasyrov** [comment]
Following my way, you write less and it looks more readable. As well a lot of frameworks use this approach, so you avoid writing constructions like yours (... ? ... : ... / ... ?? ...):
```php
$session->get($key, $default = false)
```

PS:
I would as well introduce namespaces, so it will look like:
```php
carbon\get_theme_option($option, $default = false)
```
Then in your theme you can shorten the syntax and do something like:
```php
use carbon\get_theme_option as option;

<h1><?= option('heading') ?></h1>
<p><?= option('description') ?></p>
```
Beatiful, isn't it?

**Comment by atanas-angelov-dev** [comment]
2.0.0 has been released which updates getter methods to return default values if no value is saved in the database.
