### ISSUE TITLE
How to separate front-end code

### ISSUE THREAD

**Issue by KevinChenYF** [htmlburger/carbon-fields#916]
## Version

  - Carbon Fields:2.+
  - PHP:7.3

## Expected Behavior
Is there a library to store separate front-end js source code, or how can I use the front-end code alone to generate forms for integration in other PHP frameworks, such as lavarel slim or custom frameworks

**Comment by jorostoyanov** [comment]
Hi @KevinChenYF 

Apologies for the late reply.

Carbon Fields isn't meant to be used on the front-end as a standalone application outside WordPress. You will need to consider other tools or develop your own solution.
