### ISSUE TITLE
Store set of fields (no-repeatable) into one row in database

### ISSUE THREAD

**Issue by Vojtechremis** [htmlburger/carbon-fields#922]
Plugin Carbon fields saves one row per field into database.

Can I save for example these two fields into one row (array serialize)?

`Field::make('text', 'field1', 'Field1')->set_width(50),
Field::make('text', 'field2', 'Field 2')->set_width(50)`

**Comment by jorostoyanov** [comment]
Hi @Vojtechremis 

Apologies for the late reply.

Yes, you can implement your own datastore, which handles the data save in the database.

Here is an example -- https://carbonfields.net/docs/guides-serialized-datastore-2/?crb_version=2-2-0

This example is under the 2.2.0 version, however, it still completely valid for the v3 as well.

Hope this helps!
