### ISSUE TITLE
Is carbon-fields Dead or Alive?

### ISSUE THREAD

**Issue by eddiewp** [htmlburger/carbon-fields#925]
There are no updates for many months.

**Comment by Panchev** [comment]
Carbon Fields is not abandoned. We(at htmlBurger) are actively using it for new and ongoing projects.

There aren’t too many new features recently – nevertheless, the project is being maintained for new WordPress core versions.

**Comment by ChipRyan** [comment]
Would be great if at least issue #800 would be addressed ...

**Comment by ChipRyan** [comment]
Also found out a new one in #927 related to container visibility in the latest WP 5.5 when using specific condition types

**Comment by dhalucario** [comment]
Could we add something like a community branch/repo where we merge all approved community fixes?
If you guys lack manpower a lot of people seem to be happy to help out, including me. Some people are actually depending on this it seems.

**Comment by jorostoyanov** [comment]
@ChipRyan

Issue #800 has been fixed in development and will be available in the next release.

Issue #927 is on the current roadmap and will be fixed as well.

@dhalucario I have started approving pull requests. Feel free to open a new one, so I can review :-)

**Comment by mrdarrengriffin** [comment]
Just want to check in on this. Is the project still active as there have been issues open since July and prior that I would love to see fixed.

For instance #1042 which is something I have major issues with and have to use alternative methods as a workaround.
