### ISSUE TITLE
Changes you made may not be saved. 

### ISSUE THREAD

**Issue by TheJema** [htmlburger/carbon-fields#926]
## Version
  - Carbon Fields: 3.1.20
  - WordPress: 5.5
  - PHP: 7.4

I use carbon fields to create a new widget.
Code: 
```
use Carbon_Fields\Widget;
use Carbon_Fields\Field;

class ThemeWidgetExample extends Widget {
	// Register widget function. Must have the same name as the class
	function __construct() {
		$this->setup( 'theme_widget_example', 'Theme Widget - Example', 'Displays a block with title/text', array(
			Field::make( 'text', 'title', 'Title' )->set_default_value( 'Hello World!') ,
			Field::make( 'textarea', 'content', 'Content' )->set_default_value( 'Lorem Ipsum dolor sit amet' )
		) );
	}

	// Called when rendering the widget in the front-end
	function front_end( $args, $instance ) {
		echo $args['before_title'] . $instance['title'] . $args['after_title'];
		echo '<p>' . $instance['content'] . '</p>';
	}
}

function load_widgets() {
	register_widget( 'ThemeWidgetExample' );
}

add_action( 'widgets_init', 'load_widgets' );
```

when I change some fields from the widget in the admin area and try to leave the page, this notification is always displayed. (https://prnt.sc/v12d5n) How to fix it?

**Comment by jorostoyanov** [comment]
Hi @TheJema 

I have pushed a fix in v.3.2.2. Please test it and let me know if the issue persists :-)

**Comment by TheJema** [comment]
> Hi @TheJema
> 
> I have pushed a fix in v.3.2.2. Please test it and let me know if the issue persists :-)
The problem has not disappeared, everything is as it was

**Comment by jorostoyanov** [comment]
@TheJema Are you using the plugin or the composer package?

**Comment by TheJema** [comment]
@jorostoyanov plugin

**Comment by jorostoyanov** [comment]
The plugin was also updated to v3.2.2 -- Please update :-)

**Comment by TheJema** [comment]
@jorostoyanov
great, now everything works!
Thanks you! :-)
