### ISSUE TITLE
Container visibility issues in WP 5.5

### ISSUE THREAD

**Issue by ChipRyan** [htmlburger/carbon-fields#927]
## Version

  - Carbon Fields: 3.1.20
  - WordPress: 5.5.1
  - PHP: 7.4

## Expected Behavior
Show container if the post has the the 'cat-1' term assigned to it

## Actual Behavior
Container never shows.

## Container definition
```php
Container::make('post_meta', 'Additional Details')
    ->where('post_type', '=', 'price')
    ->where('post_term', '=', array(
        'field' => 'slug',
        'value' => 'cat-1',
        'taxonomy' => 'price_cat',
    ))
    ->add_fields(array(
        Field::make('rich_text', 'test', "Test")
    ));
```

## Comments
I tested on a previous site that hasn't been updated to WP 5.5 and the container definitions work OK so I'm guessing the 5.5 container updates are breaking the CF ones.

**Comment by Panchev** [comment]
Thank you for reporting that. We reproduced the issue and started working on a solution for it.

**Comment by jorostoyanov** [comment]
@ChipRyan 

Can you try updating Carbon Fields to v3.2 and let me know if the issue persists?

**Comment by ChipRyan** [comment]
Hey @jorostoyanov ,

Still not working in the latest v3.2.1

**Comment by jorostoyanov** [comment]
Hi @ChipRyan 

Can you double-check whether the container isn't hidden from the Screen Options?

**Comment by JuhaniGeniem** [comment]
I'm using v3.2.1 and WP 4.9.8 and the most basic code:

```
Container::make( 'theme_options', __( 'Theme Options' ) )
        ->add_fields( array(
            Field::make( 'text', 'crb_text', 'Text Field' ),
        ) );
```

Displays an empty page, with a save button.

**Comment by yunusga** [comment]
@JuhaniGeniem `debug` is on?

**Comment by JuhaniGeniem** [comment]
@yunusga 

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
Container::make( 'theme_options', __( 'Theme Options' ) )
    ->add_fields( array(
        Field::make( 'text', 'crb_text', 'Text Field' ),
 ) );
```

Gives:
<img width="1219" alt="Screenshot 2020-11-10 at 22 06 15" src="https://user-images.githubusercontent.com/22659221/98727712-0aa19300-23a1-11eb-86d8-9682ffe16361.png">

PS. "Teeman asetukset" is finnish for "Theme options".

**Comment by JuhaniGeniem** [comment]
@yunusga I edited my answer above, let me know if there's any more info I can provide you with.

**Comment by yunusga** [comment]
@JuhaniGeniem @jorostoyanov сonfirmed on Wordpress `4.9.8`, PHP `7.1`

Error log:
```
PHP Fatal error:

Uncaught Error: Call to undefined method WP_Screen::is_block_editor() in ...\wp-carbonfields.local\wp-content\themes\twentytwenty\vendor\htmlburger\carbon-fields\core\Loader\Loader.php:143

Stack trace:

#0 ...\wp-carbonfields.local\wp-content\themes\twentytwenty\vendor\htmlburger\carbon-fields\core\Loader\Loader.php(164): Carbon_Fields\Loader\Loader->get_assets_context()
#1 ...\wp-carbonfields.local\wp-content\themes\twentytwenty\vendor\htmlburger\carbon-fields\core\Loader\Loader.php(201): Carbon_Fields\Loader\Loader->enqueue_style('core')
#2 ...\wp-carbonfields.local\wp-includes\class-wp-hook.php(286): Carbon_Fields\Loader\Loader->enqueue_assets('')
#3 ...\wp-carbonfields.local\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 ...\wp-carbonfields.local\wp in ...\wp-carbonfields.local\wp-content\themes\twentytwenty\vendor\htmlburger\carbon-fields\core\Loader\Loader.php on line 143
```

and Wordpress `4.9.8` not work with PHP `7.4` in debug mode, work with PHP `7.1`, check you server configuration

**Comment by JuhaniGeniem** [comment]
@yunusga Can you share any info why it doesn't work on 7.4 so I can fix it for myself?

**Comment by jorostoyanov** [comment]
Guys, Carbon Fields v3+ supports WordPress above v5.0.

There are dependencies from WordPress 5 that are used in Carbon Fields.

Please make sure to update to a more recent version of WordPress or switch back to Carbon Fields v2.

---

Apologies for the confusion. Just noticed that the minimum supported WordPress version is not stated anywhere. I will make sure to add this information.

**Comment by ChipRyan** [comment]
@jorostoyanov I double-checked and the container isn't hidden from the screen options. The issues reported by @JuhaniGeniem have nothing to do with my original post and I'm testing on the latest WP. Please re-open.

I made a few more tests. It seems to be working fine (both in Gutenberg and Classic Editor modes) if I define the following container for a default post:

```
Container::make( 'post_meta', 'Custom Data' )
    ->where( 'post_type', '=', 'post' )
    ->where( 'post_term', '=', array(
        'field' => 'slug',
        'value' => 'uncategorized',
        'taxonomy' => 'category',
    ) )
    ->add_fields( array(
        Field::make( 'text', 'heading', __( 'Heading' ) )
    ));
```

The problem appears when defining the container for a custom post type/taxonomy like the following:

```
Container::make( 'post_meta', 'Custom Data' )
    ->where( 'post_type', '=', 'price' )
    ->where( 'post_term', '=', array(
        'field' => 'slug',
        'value' => 'price-cat-test',
        'taxonomy' => 'price_category',
    ) )
    ->add_fields( array(
        Field::make( 'text', 'heading', __( 'Heading' ) )
    ));
```
