### ISSUE TITLE
Container Nav Menu not working?

### ISSUE THREAD

**Issue by daviedR** [htmlburger/carbon-fields#93]
Hi guys, I tried creating custom fields for my menu items. I used the example on your documentation:

```
Container::make('nav_menu', 'Menu Settings')
    ->add_fields(array(
        Field::make('color', 'crb_color'),
    ));
```

But there is no additional option in the menu item settings. Is it not working?

**Comment by pkostadinov-2create** [comment]
I have just tested the container with the latest Carbon Fields version, and it appears to be working.

Here are few steps to debug your issue:

1. Get the latest plugin version by `zip`/`composer`/`git`

2. Enable `WP_Debug`, and make sure there are no errors, like missing namespace declaration:
	```
	<?php

	use Carbon_Fields\Container\Container;
	use Carbon_Fields\Field\Field;

	Container::make('nav_menu', 'Menu Settings')
	    ->add_fields(array(
	        Field::make('color', 'crb_color'),
	    ));
	```

3. Check the `Appearance - Menus` for the declared field:

![menu-field](https://cloud.githubusercontent.com/assets/6572699/18383382/fb2462d2-768d-11e6-8613-3ee225e5a433.jpg)

**Comment by daviedR** [comment]
Hi, yes it was my own mistake. Sorry for the troubles. Great plugin!
