### ISSUE TITLE
Complex field header using data from association field

### ISSUE THREAD

**Issue by wpt00ls** [htmlburger/carbon-fields#939]
## Version

  - Carbon Fields: 3.1.20
  - WordPress: 5.5.3
  - PHP: 7.4

## Expected Behavior
I am looking to use the title from an associated field as the header of a complex field. The associated field data contains ID, post type information only.  I looked over at the documentation but couldn't find anything related to it. 

Can you please advice.

Thank you for such a wonderful library :-)

**Comment by emohamed** [comment]
Hi @wpt00ls 

Unfortunately this is not supported. I'd suggest tweaking the setup of your page so it's not relying on the association field for the title of the tab.

Alternatively, you can try hacking something together from the JS API, but it might be tricky and fragile with updates.
