### ISSUE TITLE
Question: Association Filter

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#94]
I am using a grouped complex 'sections' post type
![image](https://cloud.githubusercontent.com/assets/10775656/18475727/2db520d6-798d-11e6-98f7-7a8333f94bd6.png)

I would like to be able to have the section type be visible in the association/relationship table selector
![image](https://cloud.githubusercontent.com/assets/10775656/18475785/698f8132-798d-11e6-956b-8cc6879e594f.png)

**Comment by emohamed** [comment]
Hi @Santana1053!

Currently this is not supported.

However, please take a look at the `set_layout()` method: https://carbonfields.net/docs/complex-field-setup-methods/

It allows you to structure the complex field in cleaner UI.

**Comment by dackr** [comment]
Hello  @Santana1053!
You managed to do what you were wanting, and if you did you could share the code please.

**Comment by Santana1053** [comment]
@dackr Oh gosh, that was a while ago. I did not at the time but given the experience I've gained in the past year I might be able to figure out a way to do it now. Are you using version 1.x or 2.x?
