### ISSUE TITLE
Deprecation notice with Composer

### ISSUE THREAD

**Issue by peterhebert** [htmlburger/carbon-fields#941]
## Version

  - Carbon Fields: 3.1.20
  - WordPress: 5.5.3
  - PHP:7.3.23

Getting the following deprecation notice when installing via Composer (1.x):
`Deprecation Notice: Class Carbon_Fields\Field\OEmbed_Field located in ./vendor/htmlburger/carbon-fields/core/Field/Oembed_Field.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /app/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Generating jetpack autoloader (/app/vendor/jetpack-autoloader/)
  Generated: ../autoload_packages.php`

Seems like there may be some work to fully support PSR-4 autoloading to ensure Composer 2.0 compatibility

**Comment by jorostoyanov** [comment]
Hi @peterhebert 

This has already been reported and fixed via this PR -- https://github.com/htmlburger/carbon-fields/pull/915

The change will be available in the next release, which will be released shortly!

**Comment by peterhebert** [comment]
Good to hear, thanks!
