### ISSUE TITLE
Cant load fields values and lots of 508 errors in admin

### ISSUE THREAD

**Issue by brnteka** [htmlburger/carbon-fields#942]
Hi, I'm unable to load saved values in the admin dashboard, and the reason it seems is 508 error, I have a lot of "###/wp-json/carbon-fields/v1/attachment/?type=id&value=20678 508" in the console, is it because of the weak setup of shared hosting and nothing can be done to fix this? I'm using the 3.1.11 version installed as a plugin.

**Comment by jorostoyanov** [comment]
Hi @brnteka 

There were changes made regarding the attachment endpoint in v3.2.0

Please update and let me know if the problem persists :-)

**Comment by brnteka** [comment]
ok i have deactivated and uninstalled the plugin and then installed the latest version through composer but the errors are still there

![Screenshot 2020-11-05 133454](https://user-images.githubusercontent.com/24354148/98238008-708bb600-1f6e-11eb-9996-482774a8badb.png)

i should say that the theme options page I have problems with has around 175 fields on it (complex fields mostly)

**Comment by jorostoyanov** [comment]
I see..

508 error means "Resource Limit Is Reached", so you are probably maxing out the hardware resources your hosting provides you.

Contact your hosting provider to give you more information about the limits and how can you increase them :-)
