### ISSUE TITLE
Deprecate Support PHP Versions < PHP 5.6

### ISSUE THREAD

**Issue by dhalucario** [htmlburger/carbon-fields#944]
PHP 5 and some PHP 7 versions are marked as EOL by the PHP maintainers:
https://www.php.net/supported-versions.php

Wordpress minimally supported PHP Version is 5.6.20 based on the data found here:
https://displaywp.com/wordpress-minimum-php-version/

We should think about removing leftover tests and old code that still targets PHP versions below 5.6.

**Comment by jorostoyanov** [comment]
@dhalucario

Thank you for pointing this out.

This is something we have been discussing internally and will soon update in the repo :-)

**Comment by jorostoyanov** [comment]
The minimum PHP version is now bumped to 5.6.20. The same as WordPress minimum requirement

https://github.com/htmlburger/carbon-fields/commit/7874adfac0c61bf98b90a5d7cdf95275d710d0e7
