### ISSUE TITLE
Version 3.2.1 Plugin for wordpress?

### ISSUE THREAD

**Issue by EMembrillas** [htmlburger/carbon-fields#945]
First of all, thank you very much for this plugin, I have created a theme combined with bulma.io that is wonderful.

When do you plan to put the new version as a wordpress plugin? Thank you!

**Comment by jorostoyanov** [comment]
Hi @EMembrillas 

The new version has been released as a plugin as well. You can download it from here - https://carbonfields.net/release-archive/

Cheers! 🍾

**Comment by madeinnordeste** [comment]
Hi!

i try download of the plugin from site,  but don't work. the links redirect to home page when try download.

have another way to download the plugin?

thanks
