### ISSUE TITLE
carbon-fields not render blocks on front

### ISSUE THREAD

**Issue by vbghtu** [htmlburger/carbon-fields#948]
ihave the same issue on

Carbon Fields: 3.1.2
WordPress: 5.5.3
PHP: 7.4

_Originally posted by @vbghtu in https://github.com/htmlburger/carbon-fields/issues/756#issuecomment-727921169_

**Comment by jorostoyanov** [comment]
Hi @vbghtu 

Please re-open the issue with more details if you didn't find another solution.

Thanks!
