### ISSUE TITLE
Image field skipping multibyte characters in name and URL of the image file

### ISSUE THREAD

**Issue by thomas-figved** [htmlburger/carbon-fields#949]
## Version

  - Carbon Fields: 3.2.1
  - WordPress:  5.5.3
  - PHP: 7.2.19-0ubuntu0.18.04.2

## Expected Behavior
When using an "image" carbon field there are issues appearing on the admin panel interface when the image file name contains multibyte characters. This is even more troublesome when the type of the image field is "url".

If you have two image fields and set them both to a different image with multibyte characters in the filename, it should show each image in the correct field and with the correct name.

## Actual Behavior
If you have two image fields and set them both to a different image with multibyte characters in the filename, it ignores the multibyte characters and can show you the wrong image with the wrong title.

For example these are my media files:
![image](https://user-images.githubusercontent.com/28971514/99477356-b34d8500-2995-11eb-8493-859539ae9b40.png)
(desert pic filename : ①_image.jpg
mona lisa filename : ②_image.jpg)

Value of the fields before saving:
![image](https://user-images.githubusercontent.com/28971514/99477444-db3ce880-2995-11eb-941c-8e105c432196.png)

After saving:
![image](https://user-images.githubusercontent.com/28971514/99477475-e859d780-2995-11eb-81a4-17f259fbad42.png)

## Container definition
```php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

add_action( 'carbon_fields_register_fields', 'crb_attach_theme_options' );
function crb_attach_theme_options() {
    Container::make( 'theme_options', __( 'Theme Options', 'crb' ) )
        ->add_fields( array(
          Field::make( 'image', 'crb_image', __( 'Image' ) )
            ->set_value_type( 'url' ),
          Field::make( 'image', 'crb_image2', __( 'Image 2' ) )
            ->set_value_type( 'url' ),
        ) );
}
```

## Steps to Reproduce the Problem

  1. Upload images with multibyte characters in the media library
  2. Set up one field with one of the image, the second field with the other image
  3. Press the save button
  4. Name of the file is now skipping multibyte characters, and depending on the name of the files it can also display the wrong image.

## Comments
As far as I know this is only affecting the admin interface as the data in the database looks fine. It is also more impactful with the "URL" type of image field as it will display both a wrong name and potentially a wrong image. If the type is set to "ID", it only impacts the display of the file name.

**Comment by jorostoyanov** [comment]
Fixed in https://github.com/htmlburger/carbon-fields/pull/950
