### ISSUE TITLE
Upgrading Carbon Fields

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#95]
I have an old theme built using Carbon Fields 0.4.2. I am trying to update the code to be compatible with the latest version of Carbon Fields, but even though no errors are being displayed on the website, no carbon fields are showing in the dashboard.

The steps I have taken to upgrade the code is as followed:
Replace `Carbon_Container::factory` with `Container::make`
Replace `Carbon_Field::factory` with `Field::make`
Replace `theme_options` type with `post_meta`
Replace `Carbon_Widget` with `Widget`

As far as I can tell, the rest of the syntax for modern Carbon Fields is the same.

**Comment by 2c-gstoqnov** [comment]
@Santana1053 

Can you confirm that you have imported the Carbon_Fields namespace by using:

_for post_meta and theme_options_

```php
<?php

use Carbon_Fields\Container;
use Carbon_Fields\Field;
```

_and for widgets_

```php
<?php

use Carbon_Fields\Widget;
```

Also, you shouldn't replace `theme_options` with `post_meta`, since these are two different containers.

**Comment by Santana1053** [comment]
Sorry my mistake, I mean't to say that I have replaced `custom_fields` with `post_meta`, and yes I have also imported the namespaces

**Comment by 2c-gstoqnov** [comment]
Can you please enable WP_DEBUG in `wp-config.php` and check for errors? If there are any, please paste them here.

In addition, can you paste the code, that you are using to register Carbon Fields, in a Github Gist, so I can have a look and check for errors?

**Comment by Santana1053** [comment]
It would seem that the issue is with https://wordpress.org/plugins/wp-db-driver/
After removing the db.php file from my wp-contents folder, the carbon fields were working.

**Comment by Santana1053** [comment]
Lastly, is there anything I need to do to the database to make the new version compatible, or is changing the PHP structure enough?
