### ISSUE TITLE
Greedy auto-focus when editing Rich Text fields

### ISSUE THREAD

**Issue by ericestes** [htmlburger/carbon-fields#963]
## Version
  - Carbon Fields: 3.2.1
  - WordPress: 5.6, Classic Editor
  - PHP: 7.2

## Expected Behavior
Edit pages with multiple Rich Text fields open uneventfully.

## Actual Behavior
The TinyMCE editor in Rich Text fields auto-focuses, which causes the page to scroll jump and focus the cursor

## Comments
I've isolated the cause to this: https://github.com/htmlburger/carbon-fields/blob/c7961c7d95d8fc0edaafca6c0183f419dbf34ae6/packages/core/fields/rich-text/index.js#L45

Modifying this line to `this.editor.execCommand( 'wpAutoResize', undefined, undefined, { skip_focus: true });` fixes my particular issue, but may have side effects. I've also not looked at the Gutenberg side of things.

**Comment by jorostoyanov** [comment]
Hi @ericestes 

This is now fixed in v3.3.0!

Thanks! :-)
