### ISSUE TITLE
Add is attribut support 

### ISSUE THREAD

**Issue by dimitriBouteille** [htmlburger/carbon-fields#982]
Please add `is` attribute support : :heart: 

```php
Field::make('text', $fieldName, $label)
    ->set_attribute('type', 'tel')
    ->set_attribute('is', 'input-phone')
    ->set_required($required);
```

![Capture d’écran du 2021-03-31 22-05-54](https://user-images.githubusercontent.com/34821762/113204202-4fa16580-926d-11eb-8b1e-834163bed3fb.png)

carbon-fields/core/Field/Text_Field.php :

```php
protected $allowed_attributes = array( 'is', 'list', 'max', 'maxLength', 'min', 'pattern', 'placeholder', 'readOnly', 'step', 'type' );
```

**Comment by jorostoyanov** [comment]
Hi @dimitriBouteille 

Can you showcase an example of usage?

**Comment by dimitriBouteille** [comment]
Hey @jorostoyanov ,

Here is a simple case: format a phone number. I add the attribute `is` to the field:

```php
 Field::make('text', 'my_phone', 'Customer phone')
	->set_attribute('type', 'tel')
	->set_classes('input-type-phone')
	->set_attribute('is', 'app-field-phone');
```

Then, in a web component, I format the phone number with `cleave.js` library:

```js
import Cleave from 'cleave.js/dist/cleave-esm.min';
import 'cleave.js/dist/addons/cleave-phone.fr'

export default class Phone extends HTMLInputElement {

    connectedCallback() {

        this.cleave = new Cleave(this, {
            phone: true,
            phoneRegionCode: 'FR',
        });
    }
}

global.customElements.get('app-field-phone') || global.customElements.define('app-field-phone', Phone, {extends: 'input'})
```

This solution makes it very easy to create custom fields without necessarily having to extend [carbon-field](https://docs.carbonfields.net/learn/extending/extending.html) knowing that it is sometimes difficult to extend carbon-field (https://github.com/htmlburger/carbon-fields/issues/899).

This is a very simple example, but it is possible to imagine more complex cases.

**Comment by jorostoyanov** [comment]
`set_attribute` is meant to be used only for the allowed attributes for the input DOM element.

Custom attributes are not supported.

I think you should be able to achieve the same result by using a CSS class.

**Comment by dimitriBouteille** [comment]
I just watched at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is) and the attribute `is` is supported by all elements (input, select, textarea, ... and more)

![Capture d’écran 2021-04-02 à 11 33 28](https://user-images.githubusercontent.com/34821762/113403962-ba56bc00-93a7-11eb-8d50-66e97d6e4728.png)

**Comment by jorostoyanov** [comment]
Hmm, fair point.

I will add it shortly :-)

**Comment by dimitriBouteille** [comment]
Perfect ! Can you let me know when this feature is deployed?

**Comment by dimitriBouteille** [comment]
@jorostoyanov  no news ?

**Comment by jorostoyanov** [comment]
The attribute is allowed for text and select fields in v3.3.1
