### ISSUE TITLE
Bug: cannot delete tabs in complex layout

### ISSUE THREAD

**Issue by duncanarrow** [htmlburger/carbon-fields#987]
## Version

  - Carbon Fields: 3.3.0
  - WordPress: 5.6.2
  - PHP: 7.2

## Expected Behavior
When creating a `complex` field using the `tabbed-horizontal` layout, I'd expect to be able to delete a tab if I no longer needed it (as I can do by clicking the trashcan icon in normal grid mode).

## Actual Behavior
There is physically no way to delete a tab once created?

## Container definition
```php
		                Field::make( 'complex', 'image_grid', 'Image grid' )
							->set_layout('tabbed-horizontal')
		                    ->add_fields( array(
		                        Field::make( 'image', 'image' )
		                )),
```

## Steps to Reproduce the Problem

Create a `complex` field type as above with the layout set to either `tabbed-horizontal` or `tabbed-vertical`. Then try and delete a tab.

**Comment by jorostoyanov** [comment]
Hi @duncanarrow 

Do you see any errors in DevTools once you click the Delete button?

**Comment by duncanarrow** [comment]
@jorostoyanov There's literally no delete button! Only a + (plus) button to create a new tab. But how do you delete a tab?

**Comment by duncanarrow** [comment]
Any ideas how this can be resolved? @jorostoyanov

**Comment by jorostoyanov** [comment]
I am attaching a screenshot which shows where the delete button is located.

![complex-field-delete-button](https://user-images.githubusercontent.com/6777091/128308303-78b95764-189b-484f-8cbf-108a21de6265.png)

**Comment by duncanarrow** [comment]
@jorostoyanov ha ha, yes you're quite right, sorry about that! I've done a fairly significant amount of styling to the backend interface and realised that those icons had been turned off-white (#fbfbfc) so I couldn't see them!

Anyway I've corrected my CSS and all is good. Thanks!
