### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by andrewostrin** [htmlburger/carbon-fields#99]
Hi, guys! I did a Russian translation for Carbon Fields.

Here are the po/mo files. Please, feel free to include them, if you deem them useful:
[crb_russian.zip](https://github.com/htmlburger/carbon-fields/files/487868/crb_russian.zip)

**Comment by fitodac** [comment]
Hi.
I did a spanish translation too... regards.
[carbon-fields-es_ES.zip](https://github.com/htmlburger/carbon-fields/files/540575/carbon-fields-es_ES.zip)

**Comment by m1r0** [comment]
Thanks a ton guys! We will add the translations in the next release.
