### ISSUE TITLE
Reusing a master set of fields

### ISSUE THREAD

**Issue by duncanarrow** [htmlburger/carbon-fields#990]
## Version

  - Carbon Fields: 3.3.0
  - WordPress: 5.7
  - PHP: 7.3

## Expected Behavior
I'm trying to find an efficient way of maintaining a set of master fields which can be reused in multiple places. If I need to add to this master set of fields, I can then just do it in one place and it immediately reflects in each field group where it's called. 

## Actual Behavior
I've tried the following, as well as with a variable which stores the master fields and also a simple include file. I'm unable to get it to work as it keeps on coming back with a white screen.

## Container definition
```php
	add_action( 'carbon_fields_register_fields', 'page_builder' );
	function page_builder() {
	
		Container::make( 'post_meta', 'Page builder' )
		        ->where( 'post_type', '=', 'page' )
		        ->add_fields( array(
					Field::make( 'complex', 'crb_media_item' )
					    ->add_fields( 'photograph', array(
						/* INCLUDE MASTER FIELDS FROM master_reusable_fields() HERE */
					        master_reusable_fields();
					        Field::make( 'image', 'image' ),
					        Field::make( 'text', 'caption' ),
					    ) )
					    ->add_fields( 'movie', array(
						/* INCLUDE MASTER FIELDS FROM master_reusable_fields() HERE */
					        master_reusable_fields();
					        Field::make( 'file', 'video' ),
					        Field::make( 'text', 'title' ),
					        Field::make( 'text', 'length' ),
					    ) )
					    ->add_fields( 'book', array(
						/* INCLUDE MASTER FIELDS FROM master_reusable_fields() HERE */
					        master_reusable_fields();
					        Field::make( 'text', 'video' ),
					        Field::make( 'rich_text', 'title' ),
					    ) )
	        ));
	}
	
	function master_reusable_fields() {
		$text_fields[] = Field::make( 'checkbox', 'container_options', 'Container options' ) ->set_option_value( 'yes' );
                /* PLUS ANY OTHER FIELDS ADDED TO THIS MASTER ARRAY */
	        ...
		return $text_fields;
	}

```

## Steps to Reproduce the Problem

As above.

## Comments
I've taken a look at https://github.com/htmlburger/carbon-fields/issues/576 and https://github.com/htmlburger/carbon-fields/issues/578 but I'm assuming I'm just not using the right syntax?

**Comment by jorostoyanov** [comment]
Hi @duncanarrow 

You should be using `array_merge` in order to combine to sets of fields.

Example:

```
->add_fields( 'book', array_merge(
/* INCLUDE MASTER FIELDS FROM master_reusable_fields() HERE */
    master_reusable_fields(),
    array(
        Field::make( 'text', 'video' ),
        Field::make( 'rich_text', 'title' ),
    )
) )
```

**Comment by duncanarrow** [comment]
@jorostoyanov Perfect thanks! As you say, `array_merge()` was critical and also wrapping the existing fields (video, title fields) in their own `array()` Anyway, this now makes my code so much more efficient and reusable.

Thank you :-)
